Repository sojourn-13/sojourn-station, pull requests merged in 2020-10, with the labels that each got.

#447 more borg armor
  code/datums/craft/recipes/guild.dm
  code/game/jobs/job/engineering.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/research/designs/robot_parts.dm
  code/modules/research/nodes/robotics.dm
Labels: enhancement

#461 More queueing and parts
  code/game/machinery/autolathe/autolathe.dm
  code/game/objects/items/weapons/circuitboards/machinery/research.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/engineering.dm
Labels: enhancement

#462 Cleans up dispener code
  code/game/machinery/Sleeper.dm
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: enhancement

#459 Fixes a runtime in tools.dm
  code/game/objects/items/weapons/tools/_tools.dm
Labels: runtime

#460 Disk tooning
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Labels: enhancement

#464 Tweaks stuttering to be more comprehensible and fixes special charact…
  code/modules/mob/mob_helpers.dm
Labels: enhancement

#469 Roach buffs
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: enhancement

#465 Borg love
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/modules/mob/living/silicon/robot/robot_dogborgs.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/research/designs/robot_parts.dm
  code/modules/research/nodes/robotics.dm
Labels: DO NOT MERGE, enhancement

#473 New perks, perk rebalances, and adjustments.
  code/__DEFINES/chemistry.dm
  code/__DEFINES/perks.dm
  code/datums/craft/recipes/clothing.dm
  code/datums/perks/job.dm
  code/datums/perks/racial.dm
  code/datums/setup_option/backgrounds/origin.dm
  code/game/jobs/job/prospector.dm
  code/game/machinery/excelsior/ex_turret.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/stacks/ichor.dm
  code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/random/mob/misc.dm
  code/game/objects/random/mob/roach.dm
  code/game/objects/structures/burrows.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/dungeons/procedural/deepmaint.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/research/xenoarchaeology/tools/tools_anoscanner.dm
  code/modules/sanity/sanity_mob.dm
  icons/obj/machines/excelsior/turret.dmi
  sojourn-station.dme
Labels: enhancement

#479 Artificer Firebrand
  code/datums/craft/recipes/guild.dm
  code/game/jobs/job/engineering.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: enhancement
