Repository sojourn-13/sojourn-station, pull requests merged in 2022-11, with the labels that each got.

#4068 stat runtime fix: negative robust stat should not make you a god in grabs
  code/__HELPERS/unsorted.dm
  code/modules/mob/living/carbon/resist.dm
  code/modules/mob/mob_grab.dm
Labels: Bug-Fix

#4069 Autodoc runtime and behavior fix
  code/game/machinery/autodoc.dm
  code/modules/surgery/autodoc.dm
Labels: Bug-Fix

#4070 fix runtimes in nanogate prk removal
  code/datums/perks/nanogate.dm
Labels: Bug-Fix

#4072 Xenoarch weapons pass
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_eguns.dm
Labels: Balance

#4071 Xenoarch Expiditions
  code/controllers/subsystems/xenoarch.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
Labels: Enhancement, Balance

#4053 Plushie vendor, Eyepatch HUDs, and more fixes
  code/datums/outfits/jobs/medical.dm
  code/game/gamemodes/events/infestation.dm
  code/game/machinery/vendor/cloathing.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/random/cloth.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/lists/factionartificer.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/suits.dm
  code/modules/genetics/creatures/wasonce.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/projectiles/guns/energy/cog.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/revolver/capgun.dm
  code/modules/research/designs/greyson.dm
  code/modules/research/designs/medical.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/guns/projectile/heavysniper.dmi
  icons/obj/toy.dmi
  icons/obj/vending.dmi
  icons/obj/weapons.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Bug-Fix, Sprite Work

#4075 Archeology loot list rebalance
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
Labels: Balance

#4074 Xenobio grade bodybags
  code/game/objects/items/bodybag.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  icons/obj/bodybag.dmi
Labels: Balance, Sprite Work

#4077 Marshal Bowman Headsets Unique
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/glasses/misc.dm
Labels: Balance

#4078 Re-Loudens the STS
  sound/weapons/guns/fire/NM_PARA.ogg
Labels: Question

#4081 Pet slime bug fix pass
  code/modules/mob/living/simple_animal/friendly/slime.dm
Labels: Bug-Fix

#4031 Hunter Content: Big monster drops Pt.1 the big boys
  code/game/objects/items/animal_parts.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  icons/obj/animal_parts.dmi
Labels: Enhancement, New Content, Content, Sprite Work

#4082 Hotfixes and Lodge improvement
  code/datums/perks/job.dm
  code/game/jobs/job/offcolony.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/genetics/mutations/cat_eyes.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/power/port_gen.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/tips_and_tricks/jobs.dm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance

#4083 Event arc stuff part 1
  modular_sojourn/stalker_annomlies.dm
  modular_sojourn/stalker_annomlies.dmi
  sojourn-station.dme
Labels: New Content, Content

#4084 deploynt suits verb
  code/modules/clothing/spacesuits/rig/rig_verbs.dm
Labels: Balance

#4085 Cargo tweaks and scav buffs?
  code/datums/outfits/jobs/guild.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/random/pouches.dm
  code/game/objects/random/powercells.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  icons/obj/grenade.dmi
Labels: Bug-Fix, Balance

#4087 Fixes spelling errors in #4085
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Labels: Documentation

#4088 sci locker - folded bodybags
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
Labels: Bug-Fix

#4089 Blob changes, fixes and tips and tricks
  code/game/gamemodes/events/blob.dm
  code/game/gamemodes/events/hivemind_controller.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/tips_and_tricks/gameplay.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/submaps/deepmaint_rooms/core/overrun.dmm
  modular_sojourn/stalker_annomlies.dm
Labels: Bug-Fix, Balance

#4086 Matrix character scaling
  code/__DEFINES/misc.dm
  code/__HELPERS/matrices.dm
  code/datums/transformation_types/types.dm
  code/game/core/atom/Transform.dm
  code/game/core/image/Transform.dm
  code/game/core/matrix/Transform.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/client/preferences.dm
  code/modules/genetics/mutations/dwarfism.dm
  code/modules/genetics/mutations/gigantism.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/resize.dm
  code/modules/mob/mob_defines.dm
  sojourn-station.dme
Labels: Enhancement, Help Wanted

#4090 By Pink-Chink
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/reagents/holder.dm
  code/modules/reagents/metabolism.dm
  code/modules/sanity/sanity_mob.dm
Labels: Bug-Fix

#4095 gear tweaks and firedelay fix
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/cog.dm
Labels: Bug-Fix, Balance

#4096 changes fire_delays down
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/sonic_emitter.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/projectile/automatic/dp.dm
  code/modules/projectiles/guns/projectile/automatic/mac.dm
Labels: Bug-Fix, Balance

#4097 Archeology Manuals Update
  code/modules/research/xenoarchaeology/manuals.dm
  code/modules/research/xenoarchaeology/misc.dm
Labels: Documentation

#4098 misc fixes
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/storage.dm
  code/modules/tips_and_tricks/jobs.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#4100 Wrist computer
  code/datums/autolathe/computer_parts.dm
  code/datums/craft/recipes/machinery.dm
  code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/modular_computers/computers/subtypes/dev_wristbound.dm
  code/modules/modular_computers/computers/subtypes/preset_wristbound.dm
  icons/inventory/hands/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/modular_wristbound.dmi
  sojourn-station.dme
Labels: Enhancement, New Content, Content

#4101 Mycus are normal creatures with normal limbs (mushroom head still works normally) and people who has tail can finally use shirt or anything really without having the middle bits appearing from nowhere
  icons/mob/human_races/r_mycus.dmi
  icons/mob/sprite_accessory/tails.dmi
Labels: Sprite Work

#4103 brand new ears
  code/modules/sprite_accessories/_accessory_ears.dm
  icons/mob/sprite_accessory/ears.dmi
Labels: Sprite Work

#4102 Genetics update
  code/__DEFINES/genetics.dm
  code/modules/genetics/creatures/bioshock.dm
  code/modules/genetics/genetics.dm
  code/modules/genetics/machinery/genetics_items.dm
  code/modules/genetics/mutations/bomb_resist.dm
  code/modules/genetics/mutations/friend_bug.dm
  code/modules/genetics/mutations/gold_roach.dm
  code/modules/genetics/mutations/poison_gas.dm
  code/modules/genetics/mutations/wurm_cry.dm
  code/modules/genetics/recipes/abilities.dm
  code/modules/genetics/recipes/cloning_recipes.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/simple_animal/friendly/possum.dm
  sojourn-station.dme
Labels: New Content, Bug-Fix, Balance

#4079 Rebalances Loadout points and new items.
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/lists/belt.dm
  code/modules/client/preference_setup/loadout/lists/clothing.dm
  code/modules/client/preference_setup/loadout/lists/cosmetics.dm
  code/modules/client/preference_setup/loadout/lists/earwear.dm
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
  code/modules/client/preference_setup/loadout/lists/factionartificer.dm
  code/modules/client/preference_setup/loadout/lists/factioncommand.dm
  code/modules/client/preference_setup/loadout/lists/factionlonestar.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/factionservice.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/tools.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  icons/obj/weapons.dmi
  sojourn-station.dme
Labels: DO NOT MERGE, Balance, Discussion Needed

#4108 Update r_mycus.dmi FINALLY fixed
  icons/mob/human_races/r_mycus.dmi
Labels: Bug-Fix

#4109 fix heirloom dagger icon
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
Labels: Balance

#4110 Readjust some prices and essentially fixed all the belts issues
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/lists/belt.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
Labels: Balance

#4112 Cat dead chat fix
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Bug-Fix

#4113 xenoarch guns fix
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_eguns.dm
Labels: Balance

#4115 Nanobot fluid, Kyphotorin fix, and more
  code/__DEFINES/projectile_defines.dm
  code/datums/autolathe/ammo.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/cryo.dm
  code/game/objects/items/devices/scanners/health.dm
  code/game/objects/items/weapons/literature/manuals.dm
  code/game/objects/items/weapons/manuals.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/random/cloth.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/boltgun/anti_materiel_sniper.dm
  code/modules/projectiles/guns/projectile/boltgun/armstrong.dm
  code/modules/projectiles/guns/projectile/boltgun/baroque.dm
  code/modules/projectiles/guns/projectile/boltgun/mares_leg.dm
  code/modules/projectiles/guns/projectile/pistol/handmade.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/alchemy.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/nanites.dm
  code/modules/reagents/reagents/race.dm
  code/modules/reagents/reagents/stims.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  icons/inventory/feet/mob.dmi
  news_articles/Sniper_Assault.html
Labels: Enhancement, Bug-Fix, Content, Balance

#4118 New Shotgun Scrap-Ammo, Guild Better Scrapping, & Forge Lock
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/autolathe/matterforge.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/bullettypes.dm
  icons/obj/ammo.dmi
Labels: Bug-Fix, Balance

#4111 Genetics genes expansion
  code/__DEFINES/genetics.dm
  code/modules/genetics/creatures/bioshock.dm
  code/modules/genetics/machinery/genetics_extractor.dm
  code/modules/genetics/machinery/genetics_items.dm
  code/modules/genetics/mutations/flame_retardant.dm
  code/modules/genetics/mutations/item_makers.dm
  code/modules/genetics/mutations/spark_breath.dm
  code/modules/genetics/recipes/abilities.dm
  code/modules/genetics/recipes/organ_recipes.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/organs/internal/slime.dm
  code/modules/surgery/old_surgery.dm
  code/modules/surgery/surgery.dm
  sojourn-station.dme
Labels: New Content, Content, Balance

#4119 Fixes Explosive Makeshift AK
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
Labels: Bug-Fix

#4120 first gun pass
  code/__DEFINES/weapons.dm
  code/datums/contract.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/projectiles/gun_firemode.dm
  code/modules/projectiles/guns/energy/carpediem.dm
  code/modules/projectiles/guns/energy/cassad.dm
  code/modules/projectiles/guns/energy/cog.dm
  code/modules/projectiles/guns/energy/disco_vazer.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/sst.dm
  code/modules/projectiles/guns/minigun.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/armsmg.dm
  code/modules/projectiles/guns/projectile/automatic/bastard.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/buckler.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/chaingun.dm
  code/modules/projectiles/guns/projectile/automatic/dp.dm
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
  code/modules/projectiles/guns/projectile/automatic/mac.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/nail_gun.dm
  code/modules/projectiles/guns/projectile/automatic/ostwind.dm
  code/modules/projectiles/guns/projectile/automatic/ppsh.dm
  code/modules/projectiles/guns/projectile/automatic/scaffold.dm
  code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
  code/modules/projectiles/guns/projectile/automatic/specop.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/automatic/texan.dm
  code/modules/projectiles/guns/projectile/automatic/tommygun.dm
  code/modules/projectiles/guns/projectile/automatic/triage.dm
  code/modules/projectiles/guns/projectile/automatic/vector.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/shotgun/pug.dm
  code/modules/projectiles/guns/projectile/shotgun/sbaw.dm
Labels: Documentation, Bug-Fix, Balance

#4117 Death
  code/__DEFINES/projectile_defines.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/greyson.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/equipment/weapons/ranged/bullet_weapons.dm
  code/game/mecha/equipment/weapons/ranged/explosive_weapons.dm
  code/game/mecha/equipment/weapons/ranged/mech_ammunition.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/random/mecha.dm
  code/modules/research/designs/mecha_equipment.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
  icons/mecha/mecha_equipment.dmi
  sojourn-station.dme
  sound/mecha/weapons/autocannon.ogg
  sound/mecha/weapons/hmg.ogg
  sound/mecha/weapons/lbx.ogg
  sound/mecha/weapons/ultracannon.ogg
Labels: Bug-Fix, Balance

#4123 more annomlies
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/modular_computers/file_system/news_article.dm
  icons/mob/mobs-monster.dmi
  modular_sojourn/cardgame_2/corrupted_beings.dm
  modular_sojourn/stalker_annomlies.dm
  modular_sojourn/stalker_annomlies.dmi
  news_articles/FIRE_IN_THE_JUNGLE.html
  sojourn-station.dme
Labels: Documentation, New Content

#4125 Sheet Snatchers Offers!! Wow!!
  code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
Labels: Balance

#4126 Quick fix
  modular_sojourn/stalker_annomlies.dm
Labels: Bug-Fix

#4129 Removes bone modding (bug fix)
  code/modules/organs/internal/bones.dm
Labels: Bug-Fix

#4130 Pink-Chink
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/projectile.dm
  icons/mob/hud.dmi
  icons/obj/machines/disgorger.dmi
  icons/obj/organ_mods.dmi
Labels: Bug-Fix, Balance, Sprite Work

#4128 More beacon fiddling, part TWO!! WOW! !EGHGHG!!!
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm
Labels: Bug-Fix, Balance

#4132 Aberrant organ updates
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/aberrants/organs/holders.dm
  code/modules/aberrants/organs/internal/simple.dm
  code/modules/aberrants/organs/internal/teratoma.dm
  code/modules/aberrants/organs/mods/0_mods.dm
  code/modules/aberrants/organs/mods/1_input.dm
  code/modules/aberrants/organs/mods/component/_component.dm
  code/modules/aberrants/organs/mods/component/input.dm
  code/modules/aberrants/organs/mods/component/output.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/internal/bones.dm
Labels: Bug-Fix, Balance

#4131 GP and autolathen balance
  code/_onclick/item_attack.dm
  code/datums/autolathe/tools.dm
  code/game/machinery/autolathe/autolathe.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/multitool.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
Labels: Balance

#4133 AIs now can use a specific type of fabricator that allows them to use cyborgs as shells and a few mapping tweaks
  code/modules/mob/living/silicon/Cyborg_AI/borg_fabricator.dm
  code/modules/mob/living/silicon/Cyborg_AI/custom_cyborg.dm
  code/modules/mob/living/silicon/Cyborg_AI/remote_control.dm
  code/modules/mob/living/silicon/ai/icons.dm
  icons/mob/AI.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: New Content, Content, Balance, Sprite Work, Map

#4135 Fixes the Luty
  icons/obj/guns/projectile/luty.dmi
Labels: Bug-Fix, Sprite Work

#4137 Mining Profits Nerf, replacing problematic Offers
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
Labels: Bug-Fix, Balance

#4136 few descs and icon changes
  code/game/objects/random/oddities.dm
  code/game/objects/random/psi_loot.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/psionics/greater_powers.dm
  code/modules/psionics/psionic_items/psi_weptools.dm
  icons/obj/guns/projectile/clarissa_black.dmi
  icons/obj/guns/projectile/luty.dmi
  icons/obj/guns/projectile/makarov.dmi
Labels: Bug-Fix, Balance

#4138 Basic Chemist Offers, Combination Driver Slash. Famine.
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
Labels: Balance

#4139 annomlie fixes
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  modular_sojourn/stalker_annomlies.dm
  modular_sojourn/stalker_annomlies.dmi
Labels: Bug-Fix, Balance

#4140 Tenacity
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/datums/perks/racial.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/reagents/race.dm
Labels: Balance

#4145 water and bots
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/silicon/Cyborg_AI/remote_control.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/silicon.dm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance

#4146 Rebalances over rebalances
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/guns.dm
  code/datums/perks/job.dm
  code/datums/uplink/highly visible and dangerous weapons.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/kitchen/petrel_maker.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/game/objects/items/weapons/implant/implants/carrion/mindboil_spider.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/random/guns.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/sst.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/revolver/breakaction.dm
  code/modules/projectiles/guns/projectile/revolver/judge.dm
  code/modules/projectiles/guns/projectile/shotgun/riot.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/race.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/research/research.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/research/xenoarchaeology/manuals.dm
  code/modules/stashes/stash_types/ninja.dm
  code/modules/tips_and_tricks/gameplay.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  icons/obj/discs.dmi
  icons/obj/guns/projectile/baroque.dmi
  icons/obj/guns/projectile/bluecross.dmi
  icons/obj/guns/projectile/cr20.dmi
  icons/obj/guns/projectile/dp.dmi
  icons/obj/guns/projectile/zatvor.dmi
  maps/SpaceFortress/map/spacefortress.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  modular_sojourn/stalker_annomlies.dm
Labels: Bug-Fix, Content, Balance, Sprite Work

#4147 More Mining Balancing
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
Labels: Balance

#4148 birbs and ameridian
  code/game/gamemodes/events/migration_ameridian.dm
  code/game/gamemodes/events/migration_carp.dm
  code/game/gamemodes/events/migration_vox.dm
  code/game/objects/random/ameridian.dm
  code/modules/ameridian/ameridian_spire.dm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Bug-Fix, Balance

#4149 horns
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Bug-Fix

#4150 New sounds
  code/game/objects/items/weapons/material/bats.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/genetics/genetics.dm
  code/modules/mob/mob_grab_specials.dm
  code/modules/organs/internal/bones.dm
  code/modules/projectiles/guns/energy/sst.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/boltgun/mares_leg.dm
  code/modules/projectiles/guns/projectile/little_comet.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/glock.dm
  code/modules/projectiles/guns/projectile/pistol/judiciary.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/revolver/breakaction.dm
  code/modules/projectiles/guns/projectile/revolver/detective.dm
  code/modules/projectiles/guns/projectile/revolver/hornet.dm
  code/modules/projectiles/guns/projectile/revolver/lemant.dm
  code/modules/projectiles/guns/projectile/revolver/longboi.dm
  code/modules/projectiles/guns/projectile/revolver/sixshot.dm
  code/modules/projectiles/guns/projectile/revolver/tacticool_revolver.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/combatsg.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/riot.dm
  code/modules/projectiles/guns/projectile/shotgun/swat.dm
  code/modules/projectiles/projectile/bullettypes.dm
  sound/weapons/blunthit.ogg
  sound/weapons/guns/fire/12mm_revolver.ogg
  sound/weapons/guns/fire/9mm_pistol.ogg
  sound/weapons/guns/fire/9mm_revolver.ogg
  sound/weapons/guns/fire/shotgun.ogg
  sound/weapons/guns/fire/silenced_rifle.ogg
  sound/weapons/guns/fire/system_cost.ogg
  sound/weapons/heavyslash.ogg
  sound/weapons/jointORbonebreak.ogg
  sound/weapons/pinground.ogg
  sound/weapons/sharphit.ogg
Labels: Bug-Fix, Balance, Sound Addition

#4151 Fixes AP on the Luty/homemade Kalash
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
Labels: Bug-Fix

#4152 drill fixes and miner buffs
  code/modules/mining/drilling/drill.dm
  code/modules/mining/mine_point_vendor.dm
Labels: Bug-Fix, Balance

#4155 SPROCKET GEAR SOLID: REVENGEANCE
  code/datums/craft/recipes/clothing.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/projectiles/guns/energy/laser/cog.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/research/designs/greyson.dm
  code/modules/research/nodes/greyson.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/obj/guns/energy/sprocket.dmi
Labels: Enhancement, Balance, Sprite Work

#4157 Uhh yeah uhhhhhhhhhhh
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/projectiles/guns/oddity_items.dm
Labels: Bug-Fix, Balance

#4159 No More Infinite Perks from Oddities
  code/modules/sanity/sanity_mob.dm
Labels: Balance

#4162 Annomlies inhand
  code/game/turfs/simulated/wall_types.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/scrap/scrap_pileripper.dm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/submaps/map_clearers/coras_map.dmm
  maps/submaps/map_clearers/map_clearers.dm
  maps/submaps/map_clearers/mapclear_10x10.dmm
  maps/submaps/map_clearers/mapclear_20x20.dmm
  maps/submaps/map_clearers/mapclear_30x30.dmm
  maps/submaps/map_clearers/mapclear_40x40.dmm
  modular_sojourn/annomlies/equipable_annomlies.dm
  modular_sojourn/annomlies/stalker_annomlies.dm
  modular_sojourn/annomlies/stalker_annomlies.dmi
  modular_sojourn/lamp.dm
  modular_sojourn/lamps.dmi
  modular_sojourn/stalker_annomlies.dmi
  sojourn-station.dme
Labels: Bug-Fix, Balance, Map

#4160 Adds missing button for the trade logs
  nano/templates/trade.tmpl
Labels: Bug-Fix

#4161 firestack hallos buff
  code/modules/mob/living/carbon/human/life.dm
Labels: Balance

#4163 Heavy armor
  code/New_Hud_Manual_ru.dm
  code/modules/psionics/conquest_powers.dm
  code/modules/psionics/psionic_items/psi_Harmor.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
  config/example/admins.txt
  icons/obj/psionic/occHicon.dmi
  icons/obj/psionic/occHmob.dmi
  sojourn-station.dme
Labels: Content, Balance, Sprite Work

#4164 helm fix
  icons/obj/psionic/occHmob.dmi
Labels: Bug-Fix

#4165 fixes bastion shields even more
  icons/obj/guns/projectile/makarov.dmi
  modular_sojourn/shields.dm
  sojourn-station.dme
Labels: Bug-Fix

#4166 This will affect the trout population
  code/game/objects/random/scrap.dm
  code/modules/scrap/scrap.dm
Labels: Balance

#4158 Nanogate Balancing
  code/modules/organs/internal/nanogate.dm
  code/modules/organs/organ.dm
Labels: Balance

#4169 Shields, sounds, holsters and more
  code/datums/autolathe/biomatter.dm
  code/datums/craft/recipes/weapon.dm
  code/datums/repositories/crew/binary.dm
  code/game/machinery/deployable.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/mob/misc.dm
  code/game/objects/random/pouches.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/low_wall.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/projectiles/guns/energy/laser/laser_cannon.dm
  code/modules/projectiles/guns/energy/projectile/stun.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/plasma.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagents/food-Drinks.dm
  icons/inventory/accessory/mob.dmi
  icons/inventory/belt/mob.dmi
  icons/inventory/pockets/icon.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_Prepper_Bunker.dmm
  sound/effects/creatures/cat_hiss.ogg
  sound/effects/mob_effects/f_sigh.ogg
  sound/effects/mob_effects/m_sigh.ogg
  sound/misc/roach.ogg
  sound/misc/weasel.ogg
  sound/misc/whistle_attention.ogg
  sound/misc/zartan.ogg
  sound/voice/f_warcry.ogg
  sound/voice/femalewarcry.ogg
  sound/weapons/shield/shieldblock.ogg
  sound/weapons/shield/shielddissipate.ogg
  sound/weapons/shield/shieldmelee.ogg
  sound/weapons/shield/shieldpen.ogg
Labels: Bug-Fix, Balance, Sprite Work, Sound Addition

#4170 gunbox buff
  code/datums/autolathe/security.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/clothing/clothing.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance

#4175 loadout clearing and balance
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/client/preference_setup/loadout/lists/general.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
Labels: Balance, Removal

#4174 New alert voiceovers (pt2)
  sound/AI/outbreak5.ogg
  sound/AI/outbreak7.ogg
  sound/AI/poweroff.ogg
  sound/AI/poweron.ogg
  sound/AI/vermin.ogg
Labels: Sound Addition

#4176 Smartlink balance
  code/game/objects/items/devices/hardware_imprinter.dm
  code/modules/mob/living/carbon/human/human_recoil.dm
  code/modules/mob/living/living_recoil.dm
Labels: Balance

#4181 Gives the Guild Master their own gun
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/projectile/slab.dm
  icons/obj/guns/energy/slab.dmi
  sojourn-station.dme
Labels: Balance, Sprite Work

#4185 rewards for cooking
  code/game/machinery/smelter.dm
  code/game/objects/items/weapons/vacuum.dm
  code/modules/scrap/scrap_beacon.dm
  maps/_DeepForest/map/_River_To_Swamp.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance

#4188 Guild Fixes & Minor Additions
  code/game/machinery/crafting_station.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
  code/modules/nanogate/nanogate_items.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance

#4186 event map space fort and more
  code/game/objects/effects/step_triggers.dm
  code/game/objects/items/weapons/candle.dm
  code/modules/hydroponics/grown.dm
  maps/SpaceFortress/map/blackstone_temple.dmm
  maps/SpaceFortress/map/exc_fort.dmm
  maps/SpaceFortress/map/spacefortress.dmm
  maps/SpaceFortress/spacefortress.dm
  maps/submaps/map_clearers/coras_map.dmm
Labels: Content, Map

#4187 Syrettes(request PR)
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/obj/syringe.dmi
Labels: Balance

#4189 adds machete scabbards to the loadout
  code/modules/client/preference_setup/loadout/lists/armament.dm
Labels: Balance

#4191 Light armor catalisator for deepmaint psions!
  code/modules/psionics/conquest_powers.dm
  code/modules/psionics/psionic_items/psi_Harmor.dm
  code/modules/psionics/psionic_items/psi_Larmor.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
  icons/obj/psionic/occLicon.dmi
  icons/obj/psionic/occLmob.dmi
  sojourn-station.dme
Labels: Content, Balance, Sprite Work
