Repository sojourn-13/sojourn-station, pull requests merged in 2022-05, with the labels that each got.

#3220 More eris stuff
  code/__DEFINES/mobs.dm
  code/__HELPERS/turfs.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/perks/oddity.dm
  code/game/gamemodes/roleset/faction/excelsior.dm
  code/game/gamemodes/roleset/faction/mercenary.dm
  code/game/gamemodes/roleset/faction/roleset_faction.dm
  code/game/gamemodes/roleset/roleset.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/deployable.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/admin/player_panel.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/resist.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/simple_animal/spider_core.dm
  code/modules/mob/mob_grab.dm
  code/modules/projectiles/ammunition/bullets.dmplayer_panel.dm
  icons/mob/grab_icons.dmi
  icons/mob/screen1.dmi
Labels: Bug-Fix, Balance, Sprite Work

#3223 Antibodies Fix
  code/modules/mob/living/carbon/viruses.dm
Labels: Bug-Fix

#3225 stack autostacking, haul on controlclicking tiles
  code/game/objects/items/stacks/stack.dm
  code/game/turfs/turf.dm
  code/modules/mob/mob.dm
Labels: Enhancement, Good Issue Report, Good-To-Merge

#3224 New Drip
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/under/casual.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/security.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Enhancement, Sprite Work

#3207 Ranger Vouchers & Guns
  code/datums/autolathe/guns.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/items/weapons/vouchers.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/energy/egun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/projectile/boltgun/armstrong.dm
  code/modules/projectiles/guns/projectile/revolver/judge.dm
  icons/obj/guns/energy/peacekeeper.dmi
  icons/obj/guns/energy/zwang.dmi
  icons/obj/guns/projectile/judge.dmi
  sojourn-station.dme
Labels: Enhancement, Balance, Sprite Work

#3218 Church boogaloo
  code/datums/autolathe/biomatter.dm
  code/game/machinery/bioprinter_nt.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/candle.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/church_kits.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/core_implant/cruciform/machinery/armaments.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/projectiles/guns/energy/carpediem.dm
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/obj/storage.dmi
  sojourn-station.dme
Labels: Enhancement, Balance, Sprite Work

#3097 guild laser smg / guild crafting changes
  code/datums/craft/recipes/guild.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/tetra.dm
  code/modules/projectiles/projectile/beams.dm
  icons/obj/guns/energy/tetra.dmi
  sojourn-station.dme
  sound/weapons/quietlaser2.ogg
Labels: New Content, Balance, Sprite Work

#3221 Nagant buff??
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/boltgun/novakovic.dm
  icons/obj/guns/mods.dmi
Labels: Balance, Sprite Work, Skill-Issue | Salt PR

#3230 Readds the cargo shuttle
  code/game/machinery/computer/supply.dm
  code/game/objects/items/weapons/circuitboards/computer/supply.dm
  code/modules/cargo/packs_security.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/engineering.dm
  code/modules/trade/machinery/trade_beacon.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/uniform/mob.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, Balance

#3072 Map in an ameridian crystal field
  code/game/machinery/suit_storage_unit.dm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
Labels: Map

#3234 boards
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3233 Sonic node
  code/modules/research/designs/circuits.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  nano/css/shared.css
  nano/images/science.png
Labels: Content, Balance

#3236 Update noticeboard.dm
  code/game/objects/structures/noticeboard.dm
Labels: Bug-Fix

#3235 fixes item mod blacklists
  code/__HELPERS/_lists.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/projectiles/guns/energy/railgun.dm
Labels: Bug-Fix

#3237 Fixes the thing
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/structures/noticeboard.dm
  icons/obj/guns/energy/peacekeeper.dmi
  icons/obj/guns/energy/zwang.dmi
Labels: Bug-Fix, Sprite Work

#3240 50% reduction in beacon entropy
  code/modules/trade/machinery/trade_beacon.dm
Labels: Balance

#3246 small fix
  html/changelog.html
Labels: Bug-Fix

#3242 Adds "Bulk Glass Crate"
  code/modules/cargo/packs_engineering.dm
Labels: Balance, Good-To-Merge

#3229 ROUND 2 - Railrifle & Abdicator Balancing
  code/modules/projectiles/guns/energy/abdicator.dm
  code/modules/projectiles/guns/energy/railgun.dm
Labels: Balance

#3244 Cell charger rebalance
  code/game/objects/items/weapons/power_cells.dm
Labels: Balance

#3245 ore stacking!
  code/controllers/subsystems/trade.dm
  code/datums/craft/recipes/lodge.dm
  code/game/gamemodes/events/meteors.dm
  code/game/machinery/smelter.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/random/junk.dm
  code/game/objects/random/materials.dm
  code/game/objects/structures/flora/flora.dm
  code/modules/integrated_electronics/subtpes/mining.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/ore.dm
  code/modules/mining/ore_datum.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  code/modules/research/xenoarchaeology/tools/tools_coresampler.dm
  code/modules/scrap/oldificator.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  maps/_DeepForest/map/_Prepper_Bunker.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/Surface_Old.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Surface.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Underground.dmm
Labels: Enhancement, Good Issue Report, Bug-Fix

#3241 Fixes RIG suit drill
  code/game/objects/items/weapons/tools/pickaxe.dm
Labels: Bug-Fix

#3243 More Ameridian stuff
  code/_onclick/ghost.dm
  code/datums/craft/recipes/misc.dm
  code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm
  code/modules/admin/holder2.dm
  code/modules/ameridian/ameridian_analyzer.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_crystal_blue.dm
  code/modules/ameridian/ameridian_crystal_red.dm
  code/modules/ameridian/ameridian_refinery.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/ameridian/liquid_ameridian_processor.dm
  code/modules/ameridian/sonic_fence.dm
  icons/obj/ameridian.dmi
  sojourn-station.dme
Labels: New Content, Content, Balance, Sprite Work

#3250 Bnny Rbbt
  code/modules/sprite_accessories/_accessory_ears.dm
  icons/mob/sprite_accessory/ears.dmi
Labels: Content, Sprite Work

#3249 Replace Hydrogen Knight Rig with Ameridian Knight Rig
  code/datums/craft/recipes/robot.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/clothing/spacesuits/rig/rig_verbs.dm
  code/modules/clothing/spacesuits/rig/suits/ameridian_knight.dm
  code/modules/research/designs/robot_parts.dm
  code/modules/research/nodes/combat.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
  sojourn-station.dme
Labels: Balance, Sprite Work

#3248 Church Knight rigsuit cost nerf
  code/datums/autolathe/biomatter.dm
Labels: Balance

#3252 mapping is bad
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3253 balance and fixes
  code/controllers/subsystems/trade.dm
  code/modules/mining/ore.dm
  code/modules/research/designs/rigmodules.dm
  code/modules/research/designs/robot_parts.dm
  code/modules/research/nodes/combat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
Labels: Bug-Fix, Balance

#3257 fixes a notice board
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#3256 More Ameridian stuff
  code/game/mecha/equipment/weapons/ranged/laser_weapons.dm
  code/modules/ameridian/ameridian_analyzer.dm
  code/modules/ameridian/ameridian_crystal_red.dm
  code/modules/ameridian/liquid_ameridian_processor.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/research/designs/mecha_equipment.dm
  code/modules/research/nodes/combat.dm
Labels: Content, Balance

#3260 Update duty
  code/modules/projectiles/guns/projectile/automatic/duty.dm
Labels: Balance

#3261 psionic omnitools can no longer be artifier perfection cubed
  code/game/objects/items/oddities_faction.dm
Labels: Bug-Fix

#3258 Drummy nerf ):
  code/modules/projectiles/ammunition/magazines.dm
  icons/obj/guns/projectile/AK_wood.dmi
  icons/obj/guns/projectile/ak.dmi
  icons/obj/guns/projectile/ak_tact.dmi
  icons/obj/guns/projectile/basstet.dmi
  icons/obj/guns/projectile/bren.dmi
  icons/obj/guns/projectile/bulldog.dmi
  icons/obj/guns/projectile/bulldog_rds.dmi
  icons/obj/guns/projectile/duty.dmi
  icons/obj/guns/projectile/nordwind.dmi
  icons/obj/guns/projectile/ostwind.dmi
  icons/obj/guns/projectile/sawnoff/ak.dmi
  icons/obj/guns/projectile/sawnoff/strelki.dmi
  icons/obj/guns/projectile/sawnoff/sts25.dmi
  icons/obj/guns/projectile/sawnoff/sts30.dmi
  icons/obj/guns/projectile/solmarine.dmi
  icons/obj/guns/projectile/strelki.dmi
  icons/obj/guns/projectile/sts25.dmi
  icons/obj/guns/projectile/sts30.dmi
  icons/obj/guns/projectile/sts35.dmi
  icons/obj/guns/projectile/vintorez.dmi
  icons/obj/guns/projectile/watchtower.dmi
Labels: Balance, Sprite Work

#3255 SST balancing
  code/modules/projectiles/guns/energy/sst.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/trade/machinery/trade_beacon.dm
Labels: Balance

#3262 Updates mind.dm
  code/datums/mind.dm
Labels: Bug-Fix

#3263 beacon balance pass part 1
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
Labels: Bug-Fix, Balance

#3269 access tweaks
  code/datums/mind.dm
  code/game/machinery/computer/prisoner.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
Labels: Bug-Fix, Balance

#3266 It's time to get RIIIIIIIIIIIIIIIIIIIPPPPPPPPPPPPPED!
  code/datums/autolathe/security.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/landmarks/costume.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/admin/verbs/debug.dm
  code/modules/cargo/packs_clothing.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/clothing/suits/storage.dm
  code/modules/sprite_accessories/_accessory_marking.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/mob/human_races/markings.dmi
Labels: Bug-Fix, Balance, Sprite Work

#3267 mining update part 2 (point vendor + ore stacking fixes)
  code/controllers/subsystems/processing/fastprocess.dm
  code/game/machinery/Sleeper.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/circuitboards/machinery/mining_vendor.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/mine_point_items.dm
  code/modules/mining/mine_point_vendor.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/ore.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/power/cable.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  sojourn-station.dme
Labels: Enhancement, New Content, Bug-Fix, Balance, Good-To-Merge

#3264 LITERALLY 1984: 2, cyberpunk boogaloo
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance, Map

#3272 all the hotfixes
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3273 Mapcdbbad
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Skill-Issue | Salt PR, Map

#3278 fixes ore stacking and minor material processor things
  code/game/objects/items/stacks/stack.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/mine_point_vendor.dm
  code/modules/mining/satchel_ore_boxdm.dm
Labels: Bug-Fix

#3275 7.5 & LMG Rebalance
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/dp.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/boltgun/zatvor_ak.dm
Labels: Balance

#3274 Mild Buffs to 7.5 (Oversights??)
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#3277 Removes Some Redundant / Purposeless Firearms
  code/datums/autolathe/guns.dm
  code/datums/contract.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/cargo/packs_security.dm
  sojourn-station.dme
Labels: Question, Balance

#3276 Map and plant
  code/game/objects/random/furniture.dm
  code/game/objects/structures/flora/flora_potted.dm
  icons/obj/plants.dmi
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
Labels: Content, Map

#3268 P9 EEEVIIILE
  code/modules/projectiles/guns/oddity_items.dm
  icons/obj/guns/energy/p9evil.dmi
Labels: Balance, Sprite Work

#3280 area code vender and chemaster
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance

#3285 Jackal markings + tail
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/sprite_accessories/_accessory_marking.dm
  code/modules/sprite_accessories/_accessory_tail.dm
  icons/mob/human_races/markings.dmi
  icons/mob/sprite_accessory/tails.dmi
Labels: Content, Sprite Work

#3270 Add the Ameridian Tender
  code/modules/ameridian/ameridian_core.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_crystal_blue.dm
  code/modules/ameridian/liquid_ameridian_processor.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/simple_animal/friendly/ameridian_tender.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/research/designs/rigmodules.dm
  sojourn-station.dme
Labels: Enhancement, New Content, Bug-Fix, Balance

#3281 Better bookcase code
  code/modules/library/lib_items.dm
  code/modules/library/lib_machines.dm
Labels: Enhancement

#3282 Erisupdates
  code/datums/autolathe/parts.dm
  code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm
  code/modules/mob/mob_grab.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/subtypes/robotic_types.dm
  icons/mob/human_races/cyberlimbs/advanced_ghetto.dmi
  icons/mob/human_races/cyberlimbs/asters.dmi
  icons/mob/human_races/cyberlimbs/excelsior.dmi
  icons/mob/human_races/cyberlimbs/moebius.dmi
  icons/mob/human_races/cyberlimbs/serbian.dmi
  icons/mob/human_races/cyberlimbs/technomancer.dmi
Labels: New Content, Bug-Fix, Sprite Work

#3287 Fix the ameridian plant pot
  code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm
  code/game/objects/structures/flora/flora_potted.dm
Labels: Enhancement

#3293 fixes some now missing sprites
  icons/mob/human_races/cyberlimbs/advanced_ghetto.dmi
  icons/mob/human_races/cyberlimbs/moebius.dmi
Labels: Bug-Fix

#3292 LMG "rebalance" aka fixes
  code/__DEFINES/projectile_defines.dm
  code/__DEFINES/weapons.dm
  code/datums/autolathe/ammo.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/bastard.dm
  code/modules/projectiles/guns/projectile/automatic/chaingun.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  icons/obj/ammo.dmi
  icons/obj/ammo_mags.dmi
  icons/obj/guns/projectile/chaingun.dmi
Labels: Bug-Fix, Balance, Sprite Work

#3294 [Quickfix] Makes Helltaker waistcoat obtainable again
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
Labels: Content

#3290 Add an Ameridian lab to Soteria
  code/game/objects/structures/flora/flora_potted.dm
  code/game/objects/structures/noticeboard.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3291 ports a bunch of pins and stuff
  code/modules/client/preference_setup/loadout/lists/cosmetics.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/head/misc.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Content, Sprite Work

#3288 Update steward playtime requirements
  code/game/jobs/job/captain.dm
Labels: Balance

#3295 warrening players
  code/modules/client/preference_setup/background/03_records.dm
  code/modules/mob/new_player/new_player.dm
Labels: Wont fix, Bug-Fix, Skill-Issue | Salt PR

#3284 Total not skill issue PR
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/modules/projectiles/guns/projectile/automatic/blackguard.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance

#3297 Tender Hotfix
  code/modules/mob/living/simple_animal/friendly/ameridian_tender.dm
Labels: Bug-Fix

#3298 Make the nanite chem power display the name of the nanites
  code/modules/nanogate/powers/user.dm
Labels: Enhancement

#3296 So long Stomper
  code/game/mecha/combat/gygax.dm
  code/game/mecha/equipment/weapons/melee.dm
  code/game/mecha/mecha_wreckage.dm
  icons/mecha/mecha.dmi
  icons/mecha/mecha_equipment.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Content, Balance

#3299 Kavs drinks
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  icons/obj/drinks.dmi
Labels: Content, Sprite Work

#3303 chestfixes
  icons/mob/human_races/cyberlimbs/advanced_ghetto.dmi
  icons/mob/human_races/cyberlimbs/asters.dmi
  icons/mob/human_races/cyberlimbs/excelsior.dmi
  icons/mob/human_races/cyberlimbs/serbian.dmi
  icons/mob/human_races/cyberlimbs/technomancer.dmi
Labels: Sprite Work

#3304 Real time O:
  code/__HELPERS/time.dm
  code/controllers/subsystems/ticker.dm
Labels: Enhancement, Nuclear Option

#3306 prob ruins everything
  code/controllers/subsystems/ticker.dm
Labels: Game Breaking

#3308 Realtime
  code/controllers/subsystems/ticker.dm
Labels: Bug-Fix

#3309 Fixes Marshal Negotiator Disk
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Labels: Bug-Fix

#3318 adds 60 units as an option to chem dispensers
  nano/templates/chem_dispenser.tmpl
Labels: Enhancement, Balance

#3317 Give the Ameridian Tender a sprite
  code/modules/mob/living/simple_animal/friendly/ameridian_tender.dm
  icons/obj/ameridian.dmi
Labels: Sprite Work

#3314 Give a place for admin faxes to end up
  code/modules/paperwork/faxmachine.dm
  maps/Centcom/map/centcom.dmm
Labels: Bug-Fix

#3310 Adds the ACOG to the sec disk
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Labels: Balance

#3315 Adds an ATM to the Blackshield department at player request.
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3325 The ameridian nodes
  code/__DEFINES/research.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/designs/computer_parts.dm
  code/modules/research/nodes/engineering.dm
  icons/obj/ameridian.dmi
  nano/css/shared.css
  nano/images/science.png
Labels: Balance, Sprite Work

#3333 Marshal Turtleneck update
  code/modules/clothing/under/jobs/security.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work

#3321 hollowpoint rework, post-penetration damage
  code/game/objects/items.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/special.dm
Labels: Balance

#3330 Misc Ameridian Changes
  code/__DEFINES/maths.dm
  code/modules/ameridian/ameridian_core.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_crystal_blue.dm
  code/modules/ameridian/ameridian_crystal_red.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/ameridian/liquid_ameridian_processor.dm
  code/modules/mob/observer/ghost/ghost.dm
  icons/obj/ameridian.dmi
Labels: Bug-Fix, Balance, Merge Conflict

#3329 Bond buffs, rework, caseless ammo now works in boltguns
  code/__DEFINES/weapons.dm
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/guns.dm
  code/game/machinery/vendor/tool_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/random/guns.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/bastard.dm
  code/modules/projectiles/guns/projectile/automatic/chaingun.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/survivalrifle.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/boltgun/bond.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  icons/obj/ammo_mags.dmi
  icons/obj/guns/projectile/survivalrifle.dmi
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance

#3326 cow and mapping tweaks
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance, Map

#3334 Character head accessories (bodyparts)
  code/modules/sprite_accessories/_accessory_ears.dm
  icons/mob/sprite_accessory/ears.dmi
Labels: Enhancement, Sprite Work

#3331 Removal of Trade Beacon bluespace entropy
  code/modules/trade/machinery/trade_beacon.dm
Labels: Balance

#3339 SI buff
  code/game/objects/effects/decals/crayon.dm
  code/modules/telesci/teleporter_blocker.dm
Labels: Balance

#3340 Buffs Radiation and expedition suits
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/utility.dm
  code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
Labels: Balance, Good-To-Merge

#3336 Tetra Rebalance
  code/modules/projectiles/guns/energy/tetra.dm
Labels: Balance

#3350 fixes some marshal boxes
  code/game/objects/items/weapons/storage/marshal_kits.dm
Labels: Bug-Fix

#3349 stashes shrinkings
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/_DeepForest/map/_River_Forest_old.dmm
Labels: Map

#3348 runtime fix
  code/modules/projectiles/ammunition.dm
Labels: Bug-Fix

#3347 Makes disposals deadly again.
  code/modules/recycling/disposal.dm
Labels: Balance

#3332 Mech Melee Un-Fucking and More
  code/datums/craft/step.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/weapons/melee.dm
  code/game/mecha/mecha.dm
  code/game/objects/structures/low_wall.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/mob/animations.dm
Labels: Enhancement, Good Issue Report, Bug-Fix, Balance

#3353 Adds the Marshal BDU to the Marshal outfit lockers.
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
Labels: Content

#3351 Fix examine not showing as unknown when wearing mask
  code/game/machinery/suit_storage_unit.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/friendly/ameridian_tender.dm
Labels: Bug-Fix

#3354 Sonic weapon fix
  code/modules/projectiles/projectile/special.dm
Labels: Balance

#3343 tetra re-rebalance (and fixes)
  code/modules/projectiles/guns/energy/tetra.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Balance

#3352 Mask Voice Transmitters
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
Labels: Enhancement

#3357 fixes stacks deleting randomly
  code/game/objects/items/stacks/stack.dm
Labels: Bug-Fix

#3358 Minor math improvements.
  code/__DEFINES/maths.dm
  code/modules/ameridian/ameridian_crystal.dm
Labels: Enhancement

#3359 Newshuttle
  code/game/turfs/simulated/wall_types.dm
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
  maps/CEVEris/prospector_shuttle.dmm
  maps/Centcom/map/centcom.dmm
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, New Content, Balance, Map

#3361 of cams and pipes
  code/__DEFINES/machinery.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3364 cube improvements and better blood
  code/game/objects/random/food.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/reagents/reagent_containers/food/cubes.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
Labels: Enhancement, Bug-Fix

#3366 Fixes yet another harddel, this time on atom/movable and /mob.
  code/game/atoms_movable.dm
  code/modules/mob/mob.dm
Labels: Bug-Fix

#3365 Makes the ninja suit usable, part of a PR I'm making.
  code/modules/clothing/spacesuits/rig/modules/ninja.dm
Labels: Bug-Fix

#3363 Buffs Soteria medical gauze
  code/game/objects/items/stacks/medical.dm
Labels: Bug-Fix, Balance

#3370 Attempted bugfix for a mapping error in the Junk Field submaps.
  maps/submaps/junk_field/j25_25/neutral/neutral1.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral3.dmm
Labels: Bug-Fix

#3369 Fixes even MORE hard-dels.
  code/ATMOSPHERICS/datum_pipeline.dm
  code/ATMOSPHERICS/pipes.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/ventcrawl/ventcrawl_atmospherics.dm
Labels: Bug-Fix

#3371 ACTUALLY MAKES PROGRESS ON GETTING RID OF THE PIPE HARDDELS OH GOD
  code/ATMOSPHERICS/datum_pipeline.dm
  code/ATMOSPHERICS/pipes.dm
  code/game/machinery/atmoalter/meter.dm
Labels: Bug-Fix

#3372 Quick hotfix for a possible runtime
  code/game/machinery/atmoalter/meter.dm
Labels: Bug-Fix

#3373 Fixes ANOTHER runtime.
  code/game/machinery/atmoalter/meter.dm
Labels: Bug-Fix

#3368 Integrated circuits tweaks and fixes
  code/modules/integrated_electronics/subtpes/input.dm
  code/modules/integrated_electronics/subtpes/manipulation.dm
  code/modules/integrated_electronics/subtpes/mining.dm
  code/modules/integrated_electronics/subtpes/output.dm
  code/modules/integrated_electronics/subtpes/reagents.dm
Labels: Enhancement, Bug-Fix

#3374 untested getflaticon optimizations
  code/__HELPERS/icons.dm
  icons/blanks/32x32.dmi
Labels: Bug-Fix

#3378 Removes duplicate pipes in the colony and Preppers
  maps/_DeepForest/map/_Prepper_Bunker.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Good-To-Merge, Map

#3383 Eris ports
  code/datums/wires/recycle_vendor.dm
  code/game/machinery/crafting_station.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/vending.dm
  code/game/machinery/vendor/recycle_vendor.dm
  code/modules/materials/material_sheets.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/magazines.dm
  icons/obj/machines/crafting_station.dmi
  icons/obj/vending.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  nano/templates/recycle_vendor.tmpl
  sojourn-station.dme
Labels: Enhancement, New Content, Balance

#3362 Blackshield drip buff
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/mob/living/carbon/human/say.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/mob.dmi
Labels: Sprite Work

#3382 handmade crank charger
  code/datums/craft/recipes/tools.dm
  code/game/objects/items/weapons/power_cells.dm
Labels: Content

#3380 Terrafed
  code/datums/setup_option/backgrounds/origin_akula.dm
  code/datums/setup_option/backgrounds/origin_career.dm
  code/datums/setup_option/backgrounds/origin_homeworld.dm
  code/datums/setup_option/backgrounds/origin_human.dm
  code/datums/setup_option/backgrounds/origin_kriosan.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Bug-Fix

#3384 Fixes some missing impassable rock around the spider gauntlet in southern maintenance
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3387 Blast door loading optimisations
  code/game/machinery/doors/blast_door.dm
Labels: Good Issue Report, Good-To-Merge

#3386 Trauma Team buff, return of the RIG supremacy.
  code/modules/clothing/spacesuits/rig/modules/storage.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  icons/inventory/on_suit/mob.dmi
  icons/mob/rig_back.dmi
Labels: Enhancement, Balance

#3300 Mar'Qua stuff.
  code/__DEFINES/chemistry.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/organs/internal/eyes.dm
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/mob/human_face.dmi
  icons/mob/human_races/r_marqua.dmi
  icons/mob/human_races/r_marqua_vr.dmi
  icons/mob/human_races/species/human/hair.dmi
  icons/obj/guns/energy/thalkor.dmi
  icons/obj/guns/energy/thilkor.dmi
Labels: New Content, Content, Balance, Sprite Work

#3392 gen tweaks and ghost fix
  code/datums/components/fabric.dm
  code/modules/dungeons/crawler/dungeon_gen.dm
  code/modules/dungeons/procedural/deepmaint.dm
Labels: Enhancement, Bug-Fix

#3393 Revert "Fixes more runtimes and harddels wohooooo"
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/controllers/communications.dm
  code/controllers/subsystems/tickets/tickets.dm
  code/datums/mixed.dm
  code/datums/outfits/jobs/job.dm
  code/datums/perks/perk.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/offcolony.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/hydrogen_fuel_cell.dm
  code/game/objects/structures/burrows.dm
  code/modules/assembly/signaler.dm
  code/modules/integrated_electronics/subtpes/input.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/new_player/login.dm
  code/modules/organs/blood.dm
  code/modules/xgm/xgm_gas_mixture.dm
Labels: Invalid

#3394 Fixes a duplicated pipe that was missed.
  maps/_DeepForest/map/_Prepper_Bunker.dmm
Labels: Bug-Fix

#3395 Fixes runtimes and harddels but in a way that really shouldn't break anything.
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/controllers/subsystems/tickets/tickets.dm
  code/datums/mixed.dm
  code/datums/outfits/jobs/job.dm
  code/datums/perks/perk.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/offcolony.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/hydrogen_fuel_cell.dm
  code/game/objects/structures/burrows.dm
  code/modules/assembly/signaler.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/new_player/login.dm
  code/modules/organs/blood.dm
  code/modules/xgm/xgm_gas_mixture.dm
Labels: Bug-Fix

#3396 more fucking pipes
  maps/_DeepForest/map/_Prepper_Bunker.dmm
Labels: Bug-Fix

#3385 Fix some ameridian-related harddels
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
Labels: Bug-Fix

#3398 Burrow hammer
  code/game/objects/structures/burrows.dm
Labels: Bug-Fix

#3397 rocket engine is now a real attachment
  code/datums/craft/craft_items.dm
  code/datums/craft/recipes/guild.dm
  code/datums/craft/recipes/robot.dm
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/research/designs/stock_parts.dm
  sojourn-station.dme
Labels: Balance, Good-To-Merge

#3403 Marshal Gun Overhaul, Some Drip & Minor Armory Rework
  code/datums/autolathe/guns.dm
  code/datums/outfits/jobs/ghostroles.dm
  code/datums/outfits/jobs/security.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/guns/projectile/automatic/freedom.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/specop.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/shotgun/riot.dm
  code/modules/random_map/drop/drop_types.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/obj/guns/projectile/amnesty.dmi
  icons/obj/guns/projectile/copperhead.dmi
  icons/obj/guns/projectile/freedom.dmi
  icons/obj/guns/projectile/liberty.dmi
  icons/obj/guns/projectile/mamba.dmi
  icons/obj/guns/projectile/operator.dmi
  icons/obj/guns/projectile/python.dmi
  icons/obj/guns/projectile/specop.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, New Content, Bug-Fix, Content, Balance, Sprite Work

#3402 Dear god I really hope this version works
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/controllers/subsystems/tickets/tickets.dm
  code/datums/mixed.dm
  code/datums/outfits/jobs/job.dm
  code/datums/perks/perk.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/offcolony.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/hydrogen_fuel_cell.dm
  code/game/objects/structures/burrows.dm
  code/modules/assembly/signaler.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/organs/blood.dm
  code/modules/xgm/xgm_gas_mixture.dm
Labels: Bug-Fix

#3406 Spriters wishes
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/storage/church_kits.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  sojourn-station.dme
Labels: Sprite Work

#3405 Marshool
  code/datums/outfits/jobs/security.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/obj/guns/projectile/copperhead.dmi
  icons/obj/guns/projectile/mamba.dmi
Labels: Bug-Fix, Sprite Work

#3407 Fixes Marshal Gun Sprites & Miswording
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/projectile/automatic/freedom.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/specop.dm
  code/modules/projectiles/guns/projectile/shotgun/riot.dm
  icons/obj/guns/projectile/amnesty.dmi
  icons/obj/guns/projectile/copperhead.dmi
  icons/obj/guns/projectile/freedom.dmi
  icons/obj/guns/projectile/liberty.dmi
  icons/obj/guns/projectile/mamba.dmi
  icons/obj/guns/projectile/operator.dmi
  icons/obj/guns/projectile/python.dmi
  icons/obj/guns/projectile/specop.dmi
Labels: Bug-Fix, Sprite Work

#3408 Spec-Op Sprite Fix
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  icons/obj/guns/projectile/mamba.dmi
  icons/obj/guns/projectile/specop.dmi
Labels: Bug-Fix, Sprite Work

#3411 burrow welding
  code/game/objects/structures/burrows.dm
Labels: Bug-Fix

#3360 Dylo OD + Mech Refining
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/mecha.dm
  code/modules/mob/animations.dm
  code/modules/reagents/reagents/medicine.dm
Labels: Bug-Fix, Balance

#3412 Fixes even more harddels and runtimes.
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/mind.dm
  code/datums/outfits/jobs/job.dm
  code/datums/perks/perk.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/objects/effects/portals.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/devices/scanners/price.dm
  code/game/objects/structures/burrows.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/dungeons/junk_tractor_beam.dm
  code/modules/materials/material_sheets.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/projectile.dm
Labels: Bug-Fix

#3414 Better logged news
  code/modules/modular_computers/file_system/news_article.dm
  code/modules/modular_computers/file_system/programs/generic/news_browser.dm
  news_articles/Agent_Captured.html
  news_articles/Call_to_Action.html
  news_articles/CardCarp.html
  news_articles/Catastrophic_Outbreak.html
  news_articles/Deep_Maint_Psychosis.html
  news_articles/Didnt_think_to_ask_if_they_should.html
  news_articles/Gatehouse_Clusterfuck.html
  news_articles/Listening_Post_Destroyed.html
  news_articles/Morning_Star.html
  news_articles/Official_Marshal_communique.html
  news_articles/Progress.html
  news_articles/Psionic_Ascension.html
  news_articles/Psionic_Medicine.html
  news_articles/Scrap_Haven.html
  news_articles/Sniper_Assault.html
  news_articles/Whoever_fights_monsters.html
Labels: Documentation

#3423 Allows more shotguns to use tubes
  code/modules/projectiles/guns/projectile/shotgun/handmade.dm
  code/modules/projectiles/guns/projectile/shotgun/riot.dm
Labels: Balance

#3427 Makes termites accully attack the drill
  code/modules/mining/drilling/drill.dm
  code/modules/mining/drilling/termite_wave.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/simple_animal/soul.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance

#3400 Better names
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Enhancement, Skill-Issue | Salt PR

#3424 fixes typos in the bluespace inhibitor
  code/modules/telesci/teleporter_blocker.dm
Labels: Documentation

#3430 Various sprite fixes
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/admin/bluespacetech.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/masks/gasmask.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/obj/card.dmi
  icons/obj/guns/energy/cog.dmi
  icons/obj/storage.dmi
  icons/obj/terminals.dmi
Labels: Bug-Fix, Sprite Work

#3433 Increases mob reaction time by approximately 300%.
  code/game/objects/effects/mines.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Nuclear Option

#3439 mob fire delays, they just work
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/living_defines.dm
Labels: Bug-Fix, Balance

#3436 Optimizes my last PR a bit.
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug-Fix

#3435 fixes rig armor stacking
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
Labels: Bug-Fix

#2494 better names and a slight deckerd lore tweak
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
Labels: Documentation

#3441 Makes ranged mobs have a delay on both attack and targetting, to make it a bit more fair to players.
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
Labels: Balance
