Repository sojourn-13/sojourn-station, pull requests merged in 2022-04, with the labels that each got.

#2914 Add the Hydrogen Knight Rigsuit
  code/datums/craft/recipes/robot.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/clothing/spacesuits/rig/rig_verbs.dm
  code/modules/clothing/spacesuits/rig/suits/hydrogen_knight.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/research/designs/robot_parts.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/mob/rig_back.dmi
  icons/obj/power_cells.dmi
  icons/obj/rig_modules.dmi
  icons/obj/robot_component.dmi
  sojourn-station.dme
Labels: New Content, Sprite Work

#3007 Duty update and gun balance
  code/modules/projectiles/gun.dm
  icons/obj/guns/projectile/buckler.dmi
  icons/obj/guns/projectile/duty.dmi
Labels: Bug-Fix, Sprite Work

#3008 hotfixes
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
Labels: Bug-Fix

#3014 commits out wurms in drilling
  code/modules/mining/drilling/drill.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/random_map/noise/ore.dm
  sojourn-station.dme
Labels: Skill-Issue | Salt PR

#3012 Makes shock stage not stack infinitely
  code/modules/mob/living/carbon/human/life.dm
Labels: Balance

#3011 Accessory Galore
  code/game/machinery/vendor/weapon_vendors.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/suit/mob.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Sprite Work, Good-To-Merge, Map

#3019 GC update to even more TG like
  code/__DEFINES/qdel.dm
  code/__HELPERS/logging.dm
  code/controllers/subsystems/garbage.dm
  code/modules/admin/view_variables/reference_tracking.dm
  sojourn-station.dme
Labels: Documentation, dependencies

#3017 Lonestar Organ Market
  code/game/machinery/computer/supply.dm
Labels: Balance

#3013 [REVERT] Reverts trilby's nerf to funny man viro
  code/modules/virus2/effect.dm
Labels: Invalid, Balance, Skill-Issue | Salt PR

#3020 Fix Unknown speech
  code/modules/mob/living/carbon/human/say.dm
Labels: Bug-Fix

#3022 Misc issue fixes
  code/datums/mind.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/core_implant/cruciform/machinery/armaments.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/mob/living/silicon/robot/drone/_drone.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/projectiles/guns/projectile.dm
Labels: Bug-Fix, Balance

#3023 Nanogate nerds take more cloneloss
  code/modules/genetics/creatures/wasonce.dm
  code/modules/genetics/genetics.dm
Labels: Bug-Fix, Balance

#3018 Cloak Refactor
  code/datums/craft/recipes/clothing.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/factionartificer.dm
  code/modules/client/preference_setup/loadout/lists/factioncommand.dm
  code/modules/client/preference_setup/loadout/lists/factionlonestar.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/factionservice.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/cloak/jobs.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  sojourn-station.dme
Labels: Enhancement

#3024 Goldilocks Gilded void suit
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/modules/cargo/packs_clothing.dm
  code/modules/clothing/spacesuits/void/station.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Content, Sprite Work

#3027 armor plating/rig armor plating changes/tweaks/fixes
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/hydrogen_knight.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/spacesuits/void/void.dm
Labels: DO NOT MERGE, Bug-Fix, Balance, Good-To-Merge

#3029 Carp changes
  code/modules/mob/living/simple_animal/hostile/carp.dm
Labels: Balance

#3030 Fix the suit's armor value
  code/modules/clothing/spacesuits/rig/suits/hydrogen_knight.dm
Labels: Bug-Fix

#3031 Gives scavenger armor and hand made gear more downsides
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
Labels: Bug-Fix, Balance

#3034 Fixes a bug with integrated circuits' debugger tool costing 1000 steel, 500 plastic, 500 glass
  code/modules/integrated_electronics/core/debugger.dm
Labels: Bug-Fix, Good-To-Merge

#3035 borg port
  code/__DEFINES/cyborg_traits.dm
  code/datums/mind.dm
  code/datums/wires/robot.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_interdiction.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/flasher.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/modules/admin/admin.dm
  code/modules/mob/living/silicon/robot/admin_only_modules.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/drone/_drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/drone/drone_remote_control.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/living/silicon/robot/robot_dogborgs.dm
  code/modules/mob/living/silicon/robot/robot_hud.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/modular_computers/file_system/programs/research/cyborg_remote.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/research/designs/robot_parts.dm
  sojourn-station.dme
Labels: Documentation, Enhancement, Bug-Fix

#3033 Adjusts laser ammunition production costs
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
Labels: Enhancement, Bug-Fix, Balance, Good-To-Merge

#3036 Some onmob sprite fixes and additions
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/guns/energy/antebellum.dmi
  icons/obj/guns/energy/cog.dmi
  icons/obj/guns/energy/lascannon.dmi
  icons/obj/guns/energy/laser.dmi
  icons/obj/guns/energy/si_lascannon.dmi
  icons/obj/guns/energy/sniper.dmi
Labels: Bug-Fix, Sprite Work

#3037 Prosthetic energy sword fix
  code/game/objects/items/weapons/melee/energy.dm
Labels: Bug-Fix

#3038 unloader removal
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
Labels: Good-To-Merge, Skill-Issue | Salt PR, Map

#3009 Dream Logic - Merge Me!
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/weapons/candle.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/sanity/breakdowns.dm
Labels: New Content, Good-To-Merge

#2902 Add a psionic effect to the artifacts
  code/__DEFINES/misc.dm
  code/modules/research/xenoarchaeology/_psi-xenoarch_defines.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/research/xenoarchaeology/machinery/psionic_harvester.dm
  sojourn-station.dme
Labels: Enhancement, New Content

#3046 second try
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/militia.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/mob/light_overlays.dmi
Labels: Bug-Fix, Balance, Sprite Work, Good-To-Merge

#3040 Fix the bitflags
  code/__DEFINES/cyborg_traits.dm
Labels: Documentation

#3041 Energy sword implant icon fix
  code/game/objects/items/weapons/melee/energy.dm
Labels: Bug-Fix

#3042 Opifex gas mask fix
  code/modules/clothing/masks/gasmask.dm
Labels: Bug-Fix

#3043 Fixes a bug where implants could not be installed via surgery
  code/modules/surgery/internal.dm
Labels: Bug-Fix

#3045 Buffs Goldilocks
  code/modules/clothing/spacesuits/void/station.dm
Labels: Balance, Good-To-Merge

#3047 10% more laser and no slowdown
  code/datums/autolathe/clothing.dm
  code/datums/craft/recipes/clothing.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Balance

#3048 Cultured psionic organ implant fix
  code/datums/setup_option/core_implants.dm
Labels: Bug-Fix

#3049 Fixes many church spells not having a cooldown
  code/modules/core_implant/cruciform/rituals/path.dm
Labels: Bug-Fix

#3050 Hotfixes a couple issues with my .223 update
  code/modules/projectiles/ammunition/boxes.dm
  icons/obj/ammo.dmi
Labels: Bug-Fix

#3025 Triage gun thing
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/guns.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/vouchers.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/projectiles/guns/projectile/automatic/tommygun.dm
  code/modules/projectiles/guns/projectile/automatic/triage.dm
  icons/obj/guns/projectile/triage.dmi
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#3021 Everyone's (un)favorite QoL patch number...
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/mining/mine_items.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  code/modules/sprite_accessories/_accessory_ears.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/mob/mobs-domestic.dmi
  icons/mob/sprite_accessory/ears.dmi
  icons/obj/drinks.dmi
  icons/obj/guns/energy/abnegate.dmi
  icons/obj/guns/energy/format_bound.dmi
  icons/obj/guns/energy/humility.dmi
  icons/obj/guns/energy/system_cost.dmi
Labels: Enhancement, New Content, Bug-Fix, Balance, Sprite Work

#3051 Raise the maximum chicken limit by 10, to 20
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Balance

#3053 Harpoon Corrections
  code/game/objects/items/weapons/space_harpoon.dm
Labels: Bug-Fix, Balance

#3055 Fixes for bluespace snare.
  code/modules/bs_snare/machinery.dm
Labels: Bug-Fix

#3060 The sytle!
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/weapons/storage/costume.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/clothing/head/costume.dm
  code/modules/clothing/suits/costume.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Enhancement, Sprite Work

#3059 Make the ameridian shards stack to 360
  code/modules/materials/material_sheets.dm
  code/modules/reagents/machinery/grinder.dm
  code/modules/reagents/reagents/other.dm
Labels: Good Issue Report, Good-To-Merge

#3061 Buffs artest
  code/game/jobs/job/civilian.dm
Labels: Balance

#3062 Upgrades xenobio
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/reagents/recipes/recipes_slime.dm
Labels: Enhancement, Bug-Fix, Balance, Good-To-Merge

#3063 beaker and fixes
  code/datums/craft/recipes/medical.dm
  code/datums/craft/recipes/misc.dm
  code/datums/craft/recipes/storage.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Bug-Fix, Sprite Work

#3075 Shuttle fix and wish soup
  code/datums/objective/merc_mission.dm
  code/modules/reagents/reagent_containers/food/snacks/soup.dm
  maps/__Nadezhda/data/shuttles-eris.dm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#3054 Prospectors oddity price change
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/storage/vendor_loot_boxes.dm
Labels: Balance

#3056 Gauss Rifle, Axe Shotgun, Drum Mags & More
  code/__DEFINES/materials.dm
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/guns.dm
  code/datums/craft/recipes/guild.dm
  code/datums/craft/recipes/guns.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/materials/materials.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/egun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/railgun.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/projectile/plasma.dm
  code/modules/scrap/scrap_refine.dm
  icons/obj/ammo_mags.dmi
  icons/obj/guns/energy/gauss.dmi
  icons/obj/guns/energy/pdw.dmi
  icons/obj/guns/energy/sunrise.dmi
  icons/obj/guns/projectile/AK_wood.dmi
  icons/obj/guns/projectile/ak.dmi
  icons/obj/guns/projectile/ak_tact.dmi
  icons/obj/guns/projectile/basstet.dmi
  icons/obj/guns/projectile/blackguard.dmi
  icons/obj/guns/projectile/bren.dmi
  icons/obj/guns/projectile/bulldog.dmi
  icons/obj/guns/projectile/bulldog_rds.dmi
  icons/obj/guns/projectile/chaingun.dmi
  icons/obj/guns/projectile/dshotgun.dmi
  icons/obj/guns/projectile/duty.dmi
  icons/obj/guns/projectile/ostwind.dmi
  icons/obj/guns/projectile/pitbull.dmi
  icons/obj/guns/projectile/sawnoff/ak.dmi
  icons/obj/guns/projectile/sawnoff/strelki.dmi
  icons/obj/guns/projectile/sawnoff/sts25.dmi
  icons/obj/guns/projectile/sawnoff/sts30.dmi
  icons/obj/guns/projectile/sawnoff/sts40.dmi
  icons/obj/guns/projectile/strelki.dmi
  icons/obj/guns/projectile/sts25.dmi
  icons/obj/guns/projectile/sts30.dmi
  icons/obj/guns/projectile/sts35.dmi
  icons/obj/guns/projectile/vintorez.dmi
  icons/obj/guns/projectile/watchtower.dmi
  sojourn-station.dme
  sound/weapons/guns/fire/gaussrifle.ogg
  sound/weapons/guns/fire/sunrise_fire.ogg
  sound/weapons/guns/interact/gauss_vent.ogg
Labels: New Content, Bug-Fix, Balance, Sprite Work, Good-To-Merge

#3064 more bottle and bottle fix
  code/datums/craft/recipes/medical.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Bug-Fix, Sprite Work

#3066 Xenobio update
  code/game/machinery/kitchen/slime_gibber.dm
  code/game/machinery/xenobio.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mob/living/carbon/slime/items.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/reagents/recipes/recipes_slime.dm
  icons/obj/xenobio.dmi
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance

#3067 Exsperimental GC changes
  code/__DEFINES/qdel.dm
Labels: Wont fix

#3069 Recettear: An Item Shop's Tale
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Skill-Issue | Salt PR

#3077 A shield nerf, gasp
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal/_personal.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/helmet.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/triage.dm
  code/modules/projectiles/guns/projectile/pistol/glock.dm
  code/modules/projectiles/projectile/bullettypes.dm
  icons/inventory/belt/icon.dmi
Labels: Enhancement, New Content, Bug-Fix, Balance, Good-To-Merge

#3079 Blackshield Adjustments
  code/datums/contract.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/psionics/conquest_powers.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Content, Balance

#3080 New maid outfit and flannels
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/dress.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work

#3081 Delete loadout.txt
  loadout.txt
Labels: Documentation

#3082 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation

#3083 [Port from skyrat] Adds a few frills, horns, tails, mainly for lizards. Changes the short spines to use the correct sprite.
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/sprite_accessories/_accessory_ears.dm
  code/modules/sprite_accessories/_accessory_hair.dm
  code/modules/sprite_accessories/_accessory_tail.dm
  icons/mob/human_races/species/human/hair.dmi
  icons/mob/sprite_accessory/ears.dmi
  icons/mob/sprite_accessory/tails.dmi
  icons/mob/sprite_accessory/wings.dmi
Labels: Sprite Work, Good-To-Merge

#3084 Small linter fix
  maps/submaps/deepmaint_rooms/core/xenostudy.dmm
Labels: Bug-Fix

#3086 CDB is dumb femboy *GASP*
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
Labels: Good Issue Report, Bug-Fix, Good-To-Merge, Skill-Issue | Salt PR

#3089 Finer Toons GC exerpimental changes
  code/__DEFINES/qdel.dm
Labels: Bug-Fix

#3092 Makes the trade beacon a lot more balanced
  code/modules/modular_computers/file_system/programs/generic/trade.dm
Labels: Balance

#3093 Fixes Drums & AK 'Buff'
  code/datums/autolathe/ammo.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  icons/obj/guns/projectile/Boar.dmi
  icons/obj/guns/projectile/Warthog.dmi
  icons/obj/guns/projectile/nordwind.dmi
  icons/obj/guns/projectile/omnirifle.dmi
  icons/obj/guns/projectile/sts40.dmi
Labels: Bug-Fix, Balance

#3094 Timelocks and a new toy
  code/datums/autolathe/security.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/tools/stunbatons.dm
  icons/inventory/on_suit/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: Enhancement, New Content, Good-To-Merge

#3095 Fixes some bottles and para kit
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/modules/reagents/machinery/grinder.dm
Labels: Bug-Fix

#3028 Marshool
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/modules/projectiles/guns/energy/cog.dm
  code/modules/projectiles/guns/projectile/automatic/ppsh.dm
  icons/obj/guns/projectile/ppv.dmi
  icons/obj/tools.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance, Good-To-Merge

#3076 webs are now flammable, can be burnt down and ignite people
  code/game/objects/effects/spiders.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/projectiles/projectile/special.dm
  icons/effects/effects.dmi
Labels: Good Issue Report, Bug-Fix, Good-To-Merge

#3078 crank charger buffs + fixes crank charger
  code/datums/autolathe/tools.dm
  code/game/objects/items/weapons/autolathe_disk/lonestar_disks.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/research/nodes/power.dm
Labels: Bug-Fix, Balance

#3090 Fixes some Gauss rifle issues
  code/modules/projectiles/guns/energy/railgun.dm
Labels: Bug-Fix, Balance

#3099 Rework the Ameridian-Material Conversion Process
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm
  code/modules/ameridian/ameridian_core.dm
  code/modules/ameridian/ameridian_processor.dm
  code/modules/ameridian/ameridian_refinery.dm
  code/modules/ameridian/liquid_ameridian_processor.dm
  code/modules/materials/material_sheets.dm
  code/modules/reagents/machinery/grinder.dm
  sojourn-station.dme
Labels: Enhancement

#3068 Quality of Life-changing and drink-mixing Patch: "Bartender, Shake that drink!" edition
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/xenobio.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/structures/burrows.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/genetics/machinery/genetics_extractor.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiMega.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiTrash.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/obj/drinks.dmi
  icons/obj/guns/energy/abnegate.dmi
  icons/obj/guns/energy/format_bound.dmi
  icons/obj/guns/energy/humility.dmi
  icons/obj/guns/energy/system_cost.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sound/effects/shakeshake.ogg
Labels: Bug-Fix, Sprite Work, Good-To-Merge

#3098 HOPEFULLY Last Drum Fix
  icons/obj/guns/projectile/Boar.dmi
  icons/obj/guns/projectile/Warthog.dmi
  icons/obj/guns/projectile/bulldog.dmi
  icons/obj/guns/projectile/bulldog_rds.dmi
  icons/obj/guns/projectile/omnirifle.dmi
  icons/obj/guns/projectile/sawnoff/sts25.dmi
Labels: Bug-Fix, Sprite Work

#3101 Tweaks artest and fixes corpsmen vourchers
  code/game/jobs/job/civilian.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
Labels: Bug-Fix, Balance

#3096 Bar Remodeling/Lounge and VIP Addition
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Good-To-Merge, Map

#3102 Change Ameridian Refinery Sprite
  code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_crystal_blue.dm
  code/modules/ameridian/ameridian_refinery.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_runtling.dm
  icons/obj/machines/ameridian_refinery.dmi
  sojourn-station.dme
Labels: Sprite Work

#3105 Fix duplication glitch
  code/game/mecha/mecha_wreckage.dm
Labels: Enhancement, Bug-Fix

#3106 Fixes ablistics always being on
  code/modules/core_implant/cruciform/machinery/obelisk.dm
Labels: Bug-Fix

#3107 Minor addition to cargo packs
  code/modules/cargo/packs_security.dm
Labels: Balance, Good-To-Merge

#3108 fixes crank chargers for real
  code/game/objects/items/weapons/power_cells.dm
Labels: Bug-Fix

#3109 Adds in an Wooly/Furred neck fluff plus sheep ears into the game.
  code/modules/sprite_accessories/_accessory_ears.dm
  code/modules/sprite_accessories/_accessory_facial.dm
  icons/mob/human_races/species/human/facial.dmi
  icons/mob/sprite_accessory/ears.dmi
Labels: Sprite Work

#3112 Adds Bees to the Church garden, slight rework!
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3111 Add the base for ameridian weaponry
  code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/guns/ameridian.dm
  code/modules/projectiles/guns/energy/sonic_emitter.dm
  code/modules/projectiles/projectile/ameridian.dm
  icons/obj/guns/ameridian/ameridian_cog.dmi
  sojourn-station.dme
Labels: Enhancement, New Content, Balance

#3113 temperature tolerance changes
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/reagents/food-Drinks.dm
Labels: Bug-Fix, Balance

#3115 Totally not a church buff
  code/datums/outfits/jobs/ghostroles.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/client/preference_setup/loadout/lists/clothing.dm
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Documentation, Enhancement, Sprite Work

#3116 Pilgrim Hero and Reductor Nerf
  code/datums/craft/recipes/guns.dm
  code/modules/projectiles/guns/energy/railgun.dm
  code/modules/projectiles/guns/projectile/revolver/lemant.dm
  icons/obj/guns/projectile/lemant.dmi
  icons/obj/guns/projectile/lemant_hero.dmi
Labels: Balance, Sprite Work

#3117 Fixes and tweaks the new Nadezhda areas
  icons/obj/holosign.dmi
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3118 GetFlatIcon() optimizations from 2018 that we dont have yet
  code/__HELPERS/icons.dm
Labels: Documentation, Enhancement, Good Issue Report, Good-To-Merge

#3121 The service lounge is now service only
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#3122 Really really dirty reference tracker fix
  code/__HELPERS/logging.dm
  code/_compile_options.dm
  code/game/atoms_movable.dm
Labels: Bug-Fix

#3123 The hairpulling out mewinging
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/projectiles/guns/energy/railgun.dm
  icons/obj/guns/energy/gauss.dmi
Labels: Wont fix, Bug-Fix, Balance

#3124 Smol UI Change
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/types/aether.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/power/hydrogen_generator.dm
  nano/templates/ameridian_processor.tmpl
Labels: Enhancement

#3125 The long work
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Bug-Fix, Balance

#3126 The omni port pr (didnt even get all the prs into this as I wanted
  code/__DEFINES/movement.dm
  code/datums/craft/recipes/tools.dm
  code/datums/outfits/equipment/backpacks.dm
  code/game/machinery/vending.dm
  code/game/machinery/vendor/food_vendors.dm
  code/game/machinery/vendor/medical_vendors.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/devices/organ_module/active/multitool/improvised.dm
  code/game/objects/items/devices/organ_module/active/multitool/makeshift_multy.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/structures/catwalk.dm
  code/modules/economy/economy_misc.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/plasmaroach.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/multiz/movement.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/reagent_containers/food/cubes.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  icons/mob/mobs-roach.dmi
  icons/obj/roach_cubes.dmi
  icons/obj/storage/backpack.dmi
  sojourn-station.dme
Labels: Enhancement, New Content, Bug-Fix, Content, Balance, Sprite Work

#3127 Gives Cargo access to service coms
  code/game/objects/items/devices/radio/encryptionkey.dm
Labels: Balance

#3128 Totally a church nerf
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/modules/core_implant/cruciform/rituals/path.dm
Labels: Nuclear Option

#3130 Area code fix
  maps/submaps/deepmaint_rooms/core/Lab2.dmm
Labels: Bug-Fix

#3140 Elf mapping gone wrong
  maps/_DeepForest/map/_River_Forest.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3149 Revert "Elf mapping gone wrong"
  maps/_DeepForest/map/_River_Forest.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3119 Steal his look: Demon Harem Maker Starter Pack + fixes alt maid uniform issue
  code/game/machinery/vendor/food_vendors.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/dress.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Enhancement, Bug-Fix, Sprite Work

#3131 Give the nanobot a UI
  code/modules/mob/living/carbon/superior_animal/nanobot/ai.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
  code/modules/nanogate/powers/nanobot.dm
  code/modules/power/hydrogen_generator.dm
Labels: Enhancement

#3133 Rework blue crystals
  code/modules/ameridian/_defines.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_crystal_blue.dm
  code/modules/ameridian/ameridian_spire.dm
  sojourn-station.dme
Labels: Enhancement, New Content, Balance

#3134 Removes the forced harddel on mobs
  code/modules/mob/mob.dm
Labels: Enhancement, Good Issue Report, Good-To-Merge

#3135 Readds fire door open list
  code/game/machinery/doors/firedoor.dm
Labels: Bug-Fix

#3141 Allow the Pilgrim to directly reload from boxes
  code/modules/projectiles/guns/projectile/revolver/lemant.dm
Labels: Balance

#3143 Bat'ko Balance & Hotfix
  code/modules/projectiles/guns/energy/railgun.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Bug-Fix, Balance, Good-To-Merge

#3148 Allows research borgs to unlock other borgs again
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Bug-Fix

#3150 SMG balance stuff
  code/__DEFINES/weapons.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
  code/modules/projectiles/guns/projectile/automatic/luger.dm
  code/modules/projectiles/guns/projectile/automatic/mac.dm
  code/modules/projectiles/guns/projectile/automatic/ppsh.dm
  code/modules/projectiles/guns/projectile/automatic/texan.dm
  code/modules/projectiles/guns/projectile/automatic/tommygun.dm
  code/modules/projectiles/guns/projectile/automatic/triage.dm
  code/modules/projectiles/guns/projectile/automatic/vector.dm
  code/modules/projectiles/guns/projectile/automatic/wirbelwind.dm
Labels: Balance, Good-To-Merge

#3151 lower level
  maps/_DeepForest/map/_River_Forest.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3154 SMG hotbalance
  code/modules/projectiles/guns/projectile/automatic/armsmg.dm
  code/modules/projectiles/guns/projectile/automatic/buckler.dm
Labels: Balance

#3157 Adds in-hands for materials
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
Labels: Sprite Work

#3147 Omni-platform changes, Sprites
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/blackguard.dm
  code/modules/projectiles/guns/projectile/automatic/ostwind.dm
  code/modules/projectiles/guns/projectile/shotgun/swat.dm
  icons/obj/ammo_mags.dmi
  icons/obj/guns/projectile/bulldog.dmi
Labels: Enhancement, Balance, Good-To-Merge

#3155 more testing
  code/modules/mining/abandonedcrates.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3136 Kills a bunch of harddels as well as GC failures. Big PR.
  code/__DEFINES/components.dm
  code/__HELPERS/icons.dm
  code/controllers/subsystems/garbage.dm
  code/datums/craft/menu.dm
  code/game/atoms_movable.dm
  code/game/mecha/mecha.dm
  code/game/mecha/medical/odysseus.dm
  code/game/objects/structures/burrows.dm
  code/modules/assembly/assembly.dm
  code/modules/assembly/holder.dm
  code/modules/hivemind/mobs.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/living/carbon/alien/alien_attacks.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/drone/types/hammer.dm
  code/modules/mob/living/carbon/superior_animal/drone/types/mantis.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach_spits.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoMega.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/commanded/commanded.dm
  code/modules/mob/living/simple_animal/hostile/commanded/nanomachines.dm
  code/modules/mob/living/simple_animal/hostile/excelsior.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm
  code/modules/mob/living/simple_animal/hostile/misc.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/stranger.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/guns/plasma/variant.dm
  code/modules/projectiles/guns/plasma/welder.dm
Labels: Documentation, Enhancement, Bug-Fix

#3160 Add the victorian coats from skyrat
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/storage.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Sprite Work

#3162 Xenobio Dye Vat -Admin Testing Only For Now-
  code/game/machinery/xenobio.dm
Labels: Enhancement

#3161 so many small things
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/neotheology.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/guns/projectile/boltgun/star_striker.dm
  code/modules/reagents/machinery/grinder.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/obj/guns/projectile/ppsh.dmi
  icons/obj/guns/projectile/ppv.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map, Merge Conflict

#3166 pile ripper fix(?)/rework
  code/modules/scrap/scrap_pileripper.dm
Labels: Enhancement, Bug-Fix

#3167 Fixes cloner bypass
  code/modules/genetics/machinery/genetics_cloner.dm
Labels: Bug-Fix

#3169 silencer rebalance
  code/modules/projectiles/guns/mods/mods.dm
Labels: Balance, Good-To-Merge

#3170 Make absolutist garments unrestricted by role again :)
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
Labels: Good Issue Report, Good-To-Merge

#3165 Add Radiation Subsystem
  code/controllers/subsystems/radiation.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items/devices/geiger.dm
  code/game/objects/structures/simple_doors.dm
  code/game/turfs/simulated/walls.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/power/gravitygenerator.dm
  code/modules/power/port_gen.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_radiate.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  icons/obj/device.dmi
  sojourn-station.dme
Labels: Enhancement

#3174 The actual church buff PR (ft. Bath salts)
  code/game/machinery/doors/holy_door.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/candle.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/energy/carpediem.dm
  code/modules/projectiles/guns/matter/launcher/books.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/psionics/psionic_items/psi_misc.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagents/medicine.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/candle.dmi
  icons/obj/chemical.dmi
  icons/obj/lighting.dmi
  icons/obj/oddities.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sound/weapons/lasmusket_fire.ogg
  sound/weapons/magical.ogg
Labels: Enhancement, New Content, Balance, Sprite Work, Good-To-Merge, Map

#3175 Fix an exploit with the throwing knives
  code/game/objects/items/stacks/throwing.dm
Labels: Bug-Fix

#3172 Factorio: Industrial Autolathes can now automatically load sheets
  code/game/machinery/autolathe/autolathe.dm
  code/modules/projectiles/guns/breacher.dm
Labels: Good Issue Report, New Content, Good-To-Merge

#3178 Couple surface changes
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance, Map

#3168 new utility hardsuit modules
  code/modules/clothing/spacesuits/rig/modules/modules.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/guns/energy/misc.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/research/designs/rigmodules.dm
  code/modules/research/nodes/engineering.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  icons/effects/projectiles.dmi
  icons/obj/projectiles.dmi
  icons/obj/rig_modules.dmi
  sojourn-station.dme
Labels: Enhancement, New Content

#3177 geiger counters crate
  code/modules/cargo/packs_engineering.dm
Labels: Content

#3180 TEERRRRMIIITES!!!!
  code/modules/mining/drilling/drill.dm
  code/modules/mining/drilling/termite_burrow.dm
  code/modules/mining/drilling/termite_controller.dm
  code/modules/mining/drilling/termite_wave.dm
  code/modules/mining/drilling/wurm_controller.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  icons/mob/40x40.dmi
  icons/mob/mobs-termite.dmi
  sojourn-station.dme
Labels: New Content, Good-To-Merge

#3182 Stunslug Affective Range
  code/modules/projectiles/projectile/energy.dm
Labels: Balance

#3185 Wire Fixes, and Emote Icon Additions
  icons/mob/emote.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3186 Sec Ham Radio Fix
  code/game/objects/items/devices/radio/radio.dm
Labels: Good Issue Report, Bug-Fix, Good-To-Merge, Skill-Issue | Salt PR, Nuclear Option

#3187 powered crossbow/rxd rework
  code/datums/craft/recipes/guns.dm
  code/datums/craft/recipes/weapon.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/energy/charge.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/projectiles/projectile/bullettypes.dm
  maps/Centcom/map/centcom.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/__Nadezhda/map/Surface_Old.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Surface.dmm
Labels: Enhancement, Balance

#3189 Xenobio Dye Vat Finishing Touches
  code/game/machinery/xenobio.dm
  icons/obj/xenobio.dmi
Labels: Content, Balance

#3188 Drip megapack 100% real not fake 1 commit church buff speedmerge
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/pants.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/mob/rig_back.dmi
  icons/obj/closet.dmi
  icons/obj/rig_modules.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: New Content, Content, Balance, Sprite Work

#3192 unused var hotfix
  code/modules/projectiles/guns/launcher/crossbow.dm
Labels: Bug-Fix

#3195 Omnbugfixs - Critical bug fixes
  code/game/machinery/autolathe/artist_bench.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/uniform/icon.dmi
  icons/obj/ammo_mags.dmi
  icons/obj/electronic_assemblies.dmi
  icons/obj/furniture.dmi
  icons/obj/tables.dmi
  icons/obj/tool_upgrades.dmi
  maps/JunkTractorBeam/junk_tractor_beam.dm
Labels: Bug-Fix

#3198 Omnbugfixs MK II
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/modules/projectiles/guns/alien.dm
  code/modules/projectiles/guns/energy/crossbow.dm
  code/modules/projectiles/guns/energy/disco_vazer.dm
  code/modules/projectiles/guns/energy/floragun.dm
  code/modules/projectiles/guns/energy/makeshift_carbine.dm
  code/modules/projectiles/guns/energy/mindflayer.dm
  code/modules/projectiles/guns/energy/railgun.dm
  code/modules/projectiles/guns/energy/tesla_gun.dm
  code/modules/projectiles/guns/energy/xray.dm
  code/modules/projectiles/guns/matter/launcher/books.dm
  code/modules/projectiles/guns/plasma/variant.dm
  code/modules/projectiles/guns/projectile/automatic/armsmg.dm
  code/modules/projectiles/guns/projectile/automatic/bren.dm
  code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
  code/modules/projectiles/guns/projectile/automatic/pulse_rifle.dm
  code/modules/projectiles/guns/projectile/boltgun/handmade.dm
  code/modules/projectiles/guns/projectile/pistol/handmade.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
Labels: Bug-Fix

#3200 Updates target_mob documentation to hopefully avoid future AI failures
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Documentation

#3205 de-hardcodes hydr trays needing a multy tool
  code/game/machinery/washing_machine.dm
  code/game/objects/items/stacks/leather.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/recycling/disposal.dm
  code/modules/surgery/autodoc.dm
  icons/obj/machines/washing_machine.dmi
  sojourn-station.dme
Labels: Bug-Fix, Sprite Work

#3204 let me inject my people
  code/modules/clothing/spacesuits/rig/modules/utility.dm
Labels: Balance

#3197 Fixes makeshift grinders
  code/modules/reagents/machinery/grinder.dm
Labels: Bug-Fix

#3209 Fix genetics cloner logs
  code/modules/genetics/machinery/genetics_cloner.dm
Labels: Bug-Fix

#3210 Anti Stain fix
  code/game/objects/effects/decals/Cleanable/humans.dm
Labels: Bug-Fix

#3208 Hopefully reduce some lag
  code/modules/mob/living/living_defines.dm
Labels: Bug-Fix

#3196 adds a turtleneck w/ skirt
  code/modules/clothing/under/casual.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Content

#3214 Makes the ablative helmet look better
  icons/inventory/head/mob.dmi
Labels: Sprite Work

#3211 BS Teleporter - +Blackguard, -Strelki, +Duty, Adds .408 Drum
  code/game/machinery/excelsior/blackshield_teleporter.dm
Labels: Balance, Good-To-Merge

#3206 Small tweaks
  code/game/jobs/job/church.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/genetics/machinery/genetics_analyzer.dm
  code/modules/genetics/machinery/genetics_cloner.dm
  code/modules/genetics/machinery/genetics_extractor.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
Labels: Bug-Fix, Balance

#3202 New bluecross icons and rework to thunderlord
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/_projectile.dm
  code/modules/projectiles/guns/oddity_items.dm
  icons/obj/guns/energy/ntpistol_bluecross.dmi
  icons/obj/guns/energy/pdw.dmi
  icons/obj/guns/energy/sniper_saint.dmi
  icons/obj/guns/projectile/hm_bluecross.dmi
  icons/obj/guns/projectile/sawnoff/bluecross_shotgun.dmi
  icons/obj/guns/projectile/shotgun_king.dmi
  sojourn-station.dme
Labels: Enhancement, Balance, Sprite Work
