Repository sojourn-13/sojourn-station, pull requests merged in 2022-03, with the labels that each got.

#2814 Erisports
  code/game/objects/items.dm
  code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/organs/internal/carrion.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/boltgun/anti_materiel_sniper.dm
  code/modules/projectiles/projectile/bullettypes.dm
  nano/templates/carrion_spiders.tmpl
Labels: Enhancement, Bug-Fix, Balance, Skill-Issue | Salt PR

#2813 Hydrogen Plasma Sword Sprite Update
  code/game/objects/items/weapons/hydrogen_melee.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/guns/plasma/hydrogen.dmi
Labels: Documentation, Sprite Work

#2828 Massive Church Update (check wiki too)
  code/game/machinery/vendor/food_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/lunchbox.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/general.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/core_implant/cruciform/machinery/altar.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/omni.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/race.dm
  icons/obj/guns/mods.dmi
  icons/obj/storage.dmi
  icons/obj/tool_upgrades.dmi
Labels: Enhancement, New Content, Bug-Fix, Content, Balance

#2837 Colony game rewards
  code/game/objects/items/weapons/storage/firstaid.dm
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Wont fix, Skill-Issue | Salt PR

#2818 Marshal loadout changes, some fixes - Its a omni pr
  code/game/jobs/job/security.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/vouchers.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Enhancement, Bug-Fix, Balance

#2819 RCDs
  code/game/objects/items/weapons/RCD.dm
  code/modules/cargo/packs_engineering.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tools.dmi
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Content, Balance, Sprite Work, Good-To-Merge

#2820 Occulus fruit port
  code/game/machinery/vendor/food_vendors.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
  code/modules/reagents/reagents/food-Drinks.dm
  icons/obj/hydroponics_growing.dmi
  icons/obj/hydroponics_products.dmi
  icons/obj/seeds.dmi
Labels: Enhancement, Content, Sprite Work

#2822 medical misc fixes
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Bug-Fix

#2823 Small tweaks
  maps/DeepForest/map/_Deep_Forest.dmm
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#2825 Erisports2
  code/game/objects/random/mob/greyson.dm
  code/modules/dungeons/junk_tractor_beam.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/turrets.dm
  code/modules/projectiles/ammunition/magazines.dm
  icons/mob/battle_roomba.dmi
  nano/templates/jtb_console.tmpl
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#2826 hardcase buff
  code/game/objects/items/weapons/storage/hardcases.dm
Labels: Skill-Issue | Salt PR

#2830 Wayfarer revolver
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/projectiles/guns/projectile/revolver/wayfarer.dm
  icons/obj/guns/projectile/wayfarer.dmi
  sojourn-station.dme
Labels: Content, Sprite Work

#2832 Make the FBP revive less worse
  code/modules/organs/internal/machine.dm
Labels: Bug-Fix

#2833 Viro no cure self fix
  code/modules/virus2/disease2.dm
  code/modules/virus2/dishincubator.dm
  code/modules/virus2/isolator.dm
Labels: Enhancement

#2834 new cards and fixes - CCC
  modular_sojourn/cardgame_2/cardgame_2.dm
  modular_sojourn/cardgame_2/cardpacks_and_spawner.dm
Labels: Enhancement, Balance

#2835 Hides Crafting Menus of Unknown Categories
  code/datums/craft/menu.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/guild.dm
  code/datums/craft/recipes/lodge.dm
  code/datums/craft/recipes/robot.dm
Labels: Bug-Fix

#2821 Crack Addicts and their Crack
  code/__DEFINES/perks.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Balance

#2829 funny
  code/game/objects/items/oddities.dm
  code/game/objects/random/oddities.dm
  icons/obj/oddities.dmi
  sound/weapons/redbrick.ogg
Labels: Content, Balance, Sprite Work

#2824 Removes the hand-holder rail mod.
  code/datums/contract.dm
  code/game/objects/random/guns.dm
  code/modules/projectiles/guns/mods/mods.dm
Labels: Balance, Good-To-Merge

#2841 whoops! All hotfixes!
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Bug-Fix, Good-To-Merge

#2836 Linguist Trait & 2 Languages
  code/__DEFINES/species_languages.dm
  code/datums/perks/job.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/modules/mob/language/esperanto.dm
  code/modules/mob/language/yassari.dm
  code/stylesheet.dm
  sojourn-station.dme
Labels: New Content, Good-To-Merge

#2843 Makes genetics accully locked and give correct messages
  code/modules/genetics/machinery/genetics_analyzer.dm
  code/modules/genetics/machinery/genetics_cloner.dm
  code/modules/genetics/machinery/genetics_extractor.dm
Labels: Bug-Fix

#2840 ID cards get a title toggle verb.
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Enhancement, Good Issue Report, Good-To-Merge

#2847 Misc Fixes
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/build_a_drone.dm
  code/modules/nanogate/nanogate_items.dm
  code/modules/power/antimatter/control.dm
Labels: Bug-Fix

#2853 moves the debugger by LetterN
  code/__DEFINES/spaceman_dmm.dm
  code/__HELPERS/debugger.dm
  code/_debugger.dm
  code/controllers/master.dm
  code/game/world.dm
  sojourn-station.dme
Labels: dependencies

#2852 Tesla_Links & Reinforced Glass Hotfix
  code/modules/materials/materials.dm
  code/modules/modular_computers/computers/subtypes/preset_tablet.dm
Labels: Good Issue Report, Bug-Fix, Balance

#2851 Title Toggle HOTFIXED version~
  code/modules/mob/living/carbon/human/human.dm
Labels: Enhancement, Good Issue Report, Bug-Fix, Balance

#2861 I HATE TRILBY
  code/__DEFINES/misc.dm
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/global/01_ui.dm
Labels: Bug-Fix

#2858 Adds in New Soteria Crafting
  code/__DEFINES/perks.dm
  code/datums/craft/recipes/soteria.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/modules/materials/material_sheets.dm
  code/modules/reagents/recipes/recipes.dm
  icons/obj/stack/items.dmi
  sojourn-station.dme
Labels: Enhancement, Content, Sprite Work, Good-To-Merge, Skill-Issue | Salt PR

#2859 Fratellis
  code/__DEFINES/genetics.dm
  code/modules/genetics/creatures/fratellis.dm
  code/modules/genetics/genetics.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_grab_specials.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/internal/nerves.dm
  code/modules/ventcrawl/ventcrawl.dm
  icons/mob/genetics/fratellis.dmi
  maps/Centcom/map/centcom.dmm
  sojourn-station.dme
Labels: Documentation, Enhancement, Content, Balance

#2860 Drill + Dice + venDor
  code/game/machinery/vendor/labtop_vendor.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/machinery/vendor/technologies.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/research/designs/medical.dm
  sojourn-station.dme
Labels: Documentation, Bug-Fix, Balance

#2863 Massive food/snack improvements
  code/game/machinery/vendor/food_vendors.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/random/food.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/economy/price_list.dm
  code/modules/reagents/reagent_containers/food/sandwich.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm
  code/modules/reagents/reagent_containers/food/snacks/bread_loafs.dm
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
  code/modules/reagents/reagent_containers/food/snacks/cakes_pies.dm
  code/modules/reagents/reagent_containers/food/snacks/donut.dm
  code/modules/reagents/reagent_containers/food/snacks/pizza.dm
  code/modules/reagents/reagent_containers/food/snacks/sandwich.dm
  code/modules/reagents/reagent_containers/food/snacks/soup.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
  code/modules/scrap/oldificator.dm
  icons/obj/food.dmi
  icons/obj/trash.dmi
  maps/DeepForest/map/_Deep_Forest.dmm
  maps/DeepForest/map/_Prepper_Bunker.dmm
  sojourn-station.dme
Labels: Documentation, Enhancement, Bug-Fix, Balance, Sprite Work

#2865 Boost the custom drone's health and damage
  code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/build_a_drone.dm
Labels: Balance

#2866 Fixing Defibs
  code/game/objects/items/devices/defib.dm
Labels: Bug-Fix

#2867 Typo Fix
  code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/build_a_drone.dm
Labels: Bug-Fix

#2868 icon fix
  code/game/objects/random/food.dm
  code/modules/economy/price_list.dm
  code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
  maps/DeepForest/map/_Greyson_Field_Office.dmm
  maps/DeepForest/map/_River_Forest.dmm
Labels: Bug-Fix

#2869 Linguist trait fix
  code/datums/perks/job.dm
Labels: Bug-Fix

#2871 Fixed New Chem Reaction
  code/modules/reagents/recipes/recipes.dm
Labels: Bug-Fix

#2872 Smol Update to RnD's point miner
  code/modules/modular_computers/file_system/programs/research/passive_pointes.dm
Labels: Enhancement, Good-To-Merge

#2857 Cleans up back-end of hand-crafting
  code/controllers/subsystems/jobs.dm
  code/datums/craft/menu.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/airlocks.dm
  code/datums/craft/recipes/guild.dm
  code/datums/craft/recipes/lodge.dm
  code/datums/craft/recipes/robot.dm
  code/datums/craft/recipes/storage.dm
  code/datums/mind.dm
  code/datums/mob_modifications/modification_types.dm
  code/datums/perks/job.dm
  code/game/jobs/job/job.dm
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Documentation, Good-To-Merge

#2864 Remove the Antag Tax program
  code/modules/modular_computers/computers/subtypes/preset_pda.dm
  code/modules/modular_computers/file_system/programs/antagonist/uplink.dm
  code/modules/modular_computers/file_system/programs/generic/taxes.dm
Labels: Documentation, Good Issue Report

#2874 Pilgrim Devout
  code/datums/craft/recipes/guild.dm
  code/datums/perks/job.dm
  code/modules/projectiles/guns/projectile/revolver/lemant.dm
  icons/obj/guns/projectile/lemant_way.dmi
Labels: Content, Sprite Work

#2873 Add two robot animals
  code/datums/craft/recipes/robot.dm
  code/game/objects/items/weapons/circuitboards/other.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  icons/mob/mobs-domestic.dmi
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: New Content, Content, Sprite Work

#2875 chemmaster fixes and syrette
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/machinery/electrolyzer.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/obj/syringe.dmi
Labels: Bug-Fix, Content, Sprite Work

#2876 painful
  code/game/objects/items/oddities.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
Labels: Balance

#2877 Spray bottles and Robot genes
  code/__DEFINES/is_helpers.dm
  code/game/objects/effects/chem/water.dm
  code/modules/genetics/genetics.dm
  code/modules/genetics/machinery/genetics_items.dm
Labels: Documentation, Enhancement, Good Issue Report

#2878 Latin Linguist Fix - Sterilizer Fix
  code/datums/perks/job.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Bug-Fix

#2880 Ghost doggo
  code/datums/outfits/jobs/ghostroles.dm
  code/game/objects/effects/spawners/ghostroles.dm
Labels: Bug-Fix

#2881 Wurms, Teddy Pipes & Spec Access
  code/datums/craft/recipes/furniture.dm
  code/datums/craft/recipes/storage.dm
  code/datums/craft/recipes/weapon.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/random/mob/misc.dm
  code/game/turfs/simulated.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/drilling/wurm_burrow.dm
  code/modules/mining/drilling/wurm_controller.dm
  code/modules/mining/drilling/wurm_wave.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/wurm.dm
  code/modules/random_map/noise/ore.dm
  icons/obj/grenade.dmi
  maps/DeepForest/map/_Deep_Forest.dmm
  maps/DeepForest/map/_River_Forest.dmm
  maps/DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  sojourn-station.dme
Labels: Enhancement, Good Issue Report, New Content, Bug-Fix, Balance

#2879 title Toggle fix
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug-Fix

#2882 Fix a runtime
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Bug-Fix

#2883 Alliostra
  code/__DEFINES/weapons.dm
  code/datums/mind.dm
  code/datums/uplink/stealth and camouflage items.dm
  code/game/objects/items/devices/lighting/toggleable/flashlight.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/random/cloth.dm
  code/game/objects/random/contraband.dm
  code/modules/client/preference_setup/global/preferences.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/masks/voice.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/login.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/pistol/silenced.dm
  nano/templates/chameleon.tmpl
Labels: New Content, Bug-Fix, Balance

#2886 Using the mining drill is no longer suicide
  code/modules/mining/drilling/wurm_wave.dm
Labels: Balance

#2887 quick fix for my wurm spawn increas
  code/modules/mining/drilling/wurm_wave.dm
Labels: Balance

#2885 Psionic Powers : Heck Around And Find Out Edition.
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
  code/modules/psionics/psionic_items/psi_misc.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
  code/modules/psionics/psionic_items/psi_weptools.dm
  code/modules/psionics/researched_powers.dm
  code/modules/psionics/standard_powers.dm
Labels: New Content, Content

#2892 Radio Frequency patch fix with error logging
  code/game/objects/items/devices/radio/radio.dm
  code/modules/genetics/genetics.dm
Labels: Bug-Fix

#2893 New bag and sprites form Hound
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/hydroponics_machines.dmi
Labels: Content, Sprite Work

#2894 The longest qol projects that failed
  code/modules/modular_computers/computers/subtypes/preset_tablet.dm
  code/modules/modular_computers/file_system/catalog.dm
  code/modules/modular_computers/file_system/programs/medical/debug_catalog.dm
  code/modules/reagents/recipes.dm
  code/modules/reagents/recipes/recipes.dm
  nano/templates/catalog_entry_reagent.tmpl
  nano/templates/catalog_list_general.tmpl
  sojourn-station.dme
Labels: Enhancement, Wont fix, Bug-Fix, Skill-Issue | Salt PR

#2895 Bugfix for clucker eggs
  code/modules/mob/living/carbon/superior_animal/lodge/types/clucker.dm
Labels: Bug-Fix

#2898 better cluck sanity
  code/modules/mob/living/carbon/superior_animal/lodge/types/clucker.dm
Labels: Balance

#2899 Fixes suncleaver for real
  code/game/objects/items/weapons/tools/simple_weapons.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
Labels: Bug-Fix, Sprite Work

#2897 New bots
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/church.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm
  icons/mob/mobs-humanoid.dmi
  sojourn-station.dme
Labels: Enhancement, Content, Sprite Work

#2900 Move the Church Golem to their own section.
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/church/church.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/bishop.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/pawn.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/rook.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/church.dm
  sojourn-station.dme
Labels: Documentation, Enhancement, Balance

#2901 hunters quest + fix
  maps/DeepForest/map/_Prepper_Bunker.dmm
  maps/HunterLodge/map/_Hunting_Lodge.dmm
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#2903 produce bag/smartfridge can hold raw poultry
  code/game/machinery/kitchen/smartfridge.dm
  code/game/objects/items/weapons/storage/bags.dm
Labels: Bug-Fix

#2905 Lodge recipe tweaks
  code/datums/craft/recipes/lodge.dm
Labels: Balance

#2906 Turn the overheat explosion into an overheat heatwave
  code/modules/projectiles/guns/plasma/hydrogen.dm
Labels: Balance

#2909 Complex Wurms
  code/game/objects/random/mob/misc.dm
  code/modules/mining/drilling/wurm_controller.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  maps/DeepForest/map/_Deep_Forest.dmm
  maps/DeepForest/map/_River_Forest.dmm
  maps/DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement

#2908 Added Soteria to Geneticist title
  code/game/jobs/job/science.dm
Labels: Good Issue Report, Good-To-Merge

#2910 Z-level cleaning
  code/modules/genetics/creatures/ambusher.dm
  maps/_DeepForest/deepforest.dm
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
  maps/_DeepForest/map/_Prepper_Bunker.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/_DeepForest/map/_River_To_Swamp.dmm
  maps/_HunterLodge/lodge.dm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__DeepTunnels/deeptunnels.dm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/Map_Nadezhda.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/data/_Nadezhda_Turbolifts.dm
  maps/__Nadezhda/data/_Nadezhda_factions.dm
  maps/__Nadezhda/data/overmap-eris.dm
  maps/__Nadezhda/data/reports.dm
  maps/__Nadezhda/data/shuttles-eris.dm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
  maps/__Nadezhda/map/Surface_Old.dmm
  maps/__Nadezhda/map/Underground_Old.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Surface.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Transition.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Underground.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_labercamp.dmm
  maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
  maps/__Nadezhda/nadezhda.dm
  maps/_dungeons/crawler/crawler-1.dmm
  maps/_dungeons/crawler/crawler.dm
  maps/_dungeons/deepmaint/deepmaint-1.dmm
  maps/_dungeons/deepmaint/deepmaint-2.dmm
  maps/_dungeons/deepmaint/deepmaint-3.dmm
  maps/_dungeons/deepmaint/deepmaint.dm
  sojourn-station.dme
Labels: Bug-Fix

#2904 Add Knight Golem
  code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/knight.dm
  icons/mob/mobs-humanoid.dmi
  sojourn-station.dme
Labels: Enhancement, New Content

#2911 tg sprites are shockingly good
  code/game/objects/items/weapons/dice.dm
  code/modules/clothing/masks/costume.dm
  code/modules/power/port_gen.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/obj/chemical.dmi
  icons/obj/defibrillator.dmi
  icons/obj/device.dmi
  icons/obj/dice.dmi
  icons/obj/flora/pumpkins.dmi
  icons/obj/food.dmi
  icons/obj/items.dmi
  icons/obj/janitor.dmi
  icons/obj/library.dmi
  icons/obj/oddities.dmi
  icons/obj/power.dmi
  icons/obj/singularity.dmi
  icons/obj/stack/material.dmi
  icons/obj/storage.dmi
  icons/obj/storage/boxes.dmi
  icons/obj/vending.dmi
  icons/obj/wizard.dmi
Labels: Bug-Fix, Sprite Work

#2912 Landminebad
  maps/_DeepForest/map/_River_Forest.dmm
Labels: Balance

#2913 Drinkable drug
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/recipes/recipes.dm
  icons/obj/drinks.dmi
Labels: Content, Sprite Work

#2915 Artest fix and chameleon
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/modules/clothing/chameleon.dm
  code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
Labels: Bug-Fix

#2918 Fix a typo
  code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/pawn.dm
Labels: Bug-Fix

#2920 Headsets fixed forever (Potentially)
  code/controllers/communications.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Bug-Fix

#2922 Lean
  code/modules/reagents/recipes/recipes.dm
Labels: Balance

#2923 mew
  code/modules/clothing/masks/costume.dm
  code/modules/clothing/under/costume.dm
Labels: Sprite Work

#2925 drip
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/casual.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work, Good-To-Merge

#2927 Couple
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/dungeons/junk_tractor_beam.dm
Labels: Bug-Fix

#2928 ports annomlie fixes
  code/controllers/subsystems/xenoarch.dm
  code/modules/research/xenoarchaeology/anomaly_container.dm
  code/modules/research/xenoarchaeology/machinery/artifact_harvester.dm
  code/modules/research/xenoarchaeology/readme.dm
  code/modules/research/xenoarchaeology/tools/ano_device_battery.dm
  icons/obj/xenoarchaeology.dmi
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#2926 Alliostra is a coder byond my understanding
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/items/oddities.dm
  code/game/objects/random/oddities.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/sanity/inspiration_component.dm
Labels: New Content, Bug-Fix, Balance, Good-To-Merge

#2924 Viro rebalance
  code/modules/virus2/dishincubator.dm
Labels: Balance

#2933 Allow the antimatter console to have custom explosion strength
  code/modules/power/antimatter/control.dm
Labels: Enhancement

#2936 Runtime fix?
  code/modules/virus2/effect.dm
Labels: Bug-Fix

#2934 fixes oddity desc and deepmaints point
  code/modules/sanity/inspiration_component.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#2932 Some untested and unfinished event stuff
  code/game/area/asteroid_areas.dm
  code/game/machinery/excelsior/ex_turret.dm
  code/game/mecha/combat/marauder.dm
  maps/SpaceFortress/map/spacefortress.dmm
  maps/SpaceFortress/spacefortress.dm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
  sojourn-station.dme
Labels: Map

#2919 Ports stats trainning
  code/controllers/subsystems/jobs.dm
  code/modules/client/preference_setup/general/07_stats.dm
  sojourn-station.dme
Labels: New Content, Balance, Good-To-Merge

#2929 A clip in 2 saves 4
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/oddities_faction.dm
Labels: Nuclear Option

#2930 The rebalance
  code/game/objects/items/oddities.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/weapons/secdocs.dm
  code/modules/reagents/reagent_containers/food/snacks/donut.dm
Labels: Documentation, Balance

#2935 Plasma roaches!
  code/modules/mob/living/carbon/superior_animal/roach/types/plasmaroach.dm
  icons/mob/mobs-roach.dmi
Labels: New Content, Sprite Work, Good-To-Merge

#2941 This was accully really hard to even think to fix
  code/__HELPERS/global_lists.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/drilling/wurm_controller.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
Labels: Bug-Fix

#2942 EMP Rockets & New Caseless Sprite
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/special.dm
  icons/obj/ammo.dmi
Labels: Content, Balance, Sprite Work, Good-To-Merge

#2943 FPB fixes and rebalancing
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/organs/external/subtypes/robotic.dm
  code/modules/organs/external/subtypes/robotic_types.dm
Labels: Bug-Fix, Balance

#2944 Adds New blood chems, Fixes Sanguinum OD
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Bug-Fix, Balance, Good-To-Merge

#2945 Hounds BS sprites
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  icons/obj/stack/items.dmi
Labels: Sprite Work, Good-To-Merge

#2931 2 new perks for oddites
  code/datums/perks/oddity.dm
Labels: Content

#2949 New toys! Bug fixes!
  code/datums/autolathe/ammo.dm
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/modular_computers/computers/subtypes/preset_pda.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/projectile/bullettypes.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Enhancement, Bug-Fix, Balance, Good-To-Merge

#2953 adds the missing kriosin fax
  maps/__Nadezhda/data/_Nadezhda_factions.dm
Labels: Bug-Fix

#2954 Coat capes
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/storage.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Sprite Work

#2955 Typo Fix: Soteria Doctor's Uniform
  code/modules/clothing/under/jobs/medsci.dm
Labels: Enhancement, Good Issue Report, Bug-Fix, Good-To-Merge

#2952 Water Overlays can't be cleaned away.
  code/game/machinery/shower.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/items/weapons/vacuum.dm
  code/game/objects/structures/watercloset.dm
  code/game/turfs/simulated/cleaning.dm
  code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/reagents/other.dm
Labels: Good Issue Report, Bug-Fix, Good-To-Merge

#2959 fixes cell names and toast
  code/datums/autolathe/cells.dm
  code/modules/reagents/reagent_containers/food/snacks/bread_loafs.dm
  code/modules/reagents/reagent_containers/food/snacks/sandwich.dm
Labels: Bug-Fix

#2960 Fixes Runtimes from Items being thrown into/at disposal units.
  code/modules/recycling/disposal.dm
Labels: Good Issue Report, Bug-Fix

#2961 nerfs some op healing
  code/datums/perks/nanogate.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/projectiles/guns/matter/launcher/books.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/virus2/effect.dm
Labels: Balance, Skill-Issue | Salt PR, Nuclear Option

#2962 Throwingthegame
  code/__DEFINES/machinery.dm
  code/__HELPERS/mobs.dm
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/biomatter.dm
  code/datums/craft/recipes/weapon.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/throwing.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/modules/core_implant/cruciform/machinery/armaments.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/core_implant/cruciform/rituals/group.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/core_implant/cruciform/upgrades.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/stack/items.dmi
  nano/templates/eotp.tmpl
  sojourn-station.dme
Labels: Documentation, New Content, Bug-Fix, Balance, Sprite Work, Game Breaking, Skill-Issue | Salt PR

#2963 vode-code
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/__DEFINES/MC.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystems/processing/processing.dm
  code/controllers/subsystems/trade.dm
  code/datums/components/_component.dm
  code/datums/lobbyscreen.dm
  code/datums/mob_stats.dm
  code/datums/repositories/decls.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/smelter.dm
  code/game/objects/items/oddities_faction.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/reagents/metabolism.dm
  code/modules/trade/datums/_trade_station.dm
Labels: Documentation, Bug-Fix

#2966 church hotfixes
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  icons/obj/eotp.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  nano/templates/eopt.tmpl
Labels: Bug-Fix, Balance

#2968 Tree Nests Spider Edition
  code/game/objects/structures/flora/flora_tree.dm
Labels: New Content, Balance

#2967 Torch Ignition Bug Fix
  code/game/objects/items/devices/lighting/flare.dm
Labels: Good Issue Report, Bug-Fix

#2950 Add Ameridian Crystals
  code/__DEFINES/genetics.dm
  code/__DEFINES/materials.dm
  code/datums/craft/recipes/misc.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/items/weapons/circuitboards/machinery/ameridian_processor.dm
  code/modules/ameridian/_defines.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_processor.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/genetics/mutations/rad_protection.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  icons/mob/golems.dmi
  icons/obj/ameridian.dmi
  icons/obj/machines/grinder.dmi
  icons/turf/areas.dmi
  nano/templates/ameridian_processor.tmpl
  sojourn-station.dme
Labels: New Content, Content, Sprite Work

#2970 I forgot the name of the sprites
  icons/obj/ameridian.dmi
Labels: Bug-Fix

#2937 BS armerments
  code/datums/autolathe/guns.dm
  code/datums/craft/recipes/repairs.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/projectiles/guns/projectile/automatic/buckler.dm
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/shotgun/rushing_bull.dm
  icons/obj/guns/projectile/buckler.dmi
  icons/obj/guns/projectile/rushingbull.dmi
  icons/obj/guns/projectile/rushingbull_sawn.dmi
  icons/obj/guns/projectile/watchtower.dmi
  sojourn-station.dme
  sound/weapons/guns/fire/rushingbull.ogg
Labels: Content, Sprite Work

#2972 Few fixes and wurm correction
  code/__HELPERS/global_lists.dm
  code/game/area/Space Station 13 areas.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
Labels: Bug-Fix

#2971 icon hotfixes
  code/modules/clothing/accessories/accessory.dm
  code/modules/projectiles/guns/projectile/automatic/buckler.dm
  icons/obj/guns/projectile/buckler.dmi
Labels: Bug-Fix, Sprite Work

#2973 [TESTED] Buffs ERP
  code/modules/mob/say.dm
Labels: Bug-Fix, Good-To-Merge

#2976 Nordwind ammo fix
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
Labels: Bug-Fix

#2977 Did you know we overrid the emotes for humans?
  code/modules/mob/living/carbon/human/say.dm
Labels: Bug-Fix

#2978 more misc fixes
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/projectile/automatic/buckler.dm
  code/modules/projectiles/guns/projectile/automatic/vector.dm
  code/modules/projectiles/guns/projectile/shotgun/swat.dm
Labels: Bug-Fix

#2980 Prevent the spire from being mined by ripleys
  code/modules/ameridian/ameridian_spire.dm
  code/modules/materials/material_sheets.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  icons/obj/ameridian.dmi
Labels: Bug-Fix

#2981 CI flows work darn you
  dependencies.sh
  tools/bootstrap/python36._pth
  tools/bootstrap/python_.ps1
  tools/requirements.txt
Labels: dependencies

#2986 the dark testu
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Bug-Fix

#2987 Tester PR
  code/hub.dm
  code/modules/unit_tests/map_tests.dm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
Labels: DO NOT MERGE

#2982 Port - Unrecognizable voice when wearing Gas Masks
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/carbon/human/say.dm
Labels: Enhancement, Balance, Good-To-Merge

#2983 Actual fix for corpsman cape + brown greatcoat
  code/modules/projectiles/guns/projectile/shotgun/rushing_bull.dm
  icons/inventory/accessory/mob.dmi
  icons/inventory/suit/mob.dmi
Labels: Bug-Fix, Sprite Work

#2985 BST-anti-Psionics-Beret
  code/modules/admin/bluespacetech.dm
Labels: Enhancement, Good Issue Report, Bug-Fix, Good-To-Merge

#2988 More goofy stuff
  code/game/machinery/vendor/food_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/obj/food.dmi
  icons/obj/trash.dmi
Labels: Enhancement, New Content, Bug-Fix, Balance, Sprite Work, Good-To-Merge

#2989 Old Ammunition Box Slug Fix
  code/modules/projectiles/ammunition/boxes.dm
Labels: Good Issue Report, Bug-Fix, Good-To-Merge

#2991 Fix a dumb error
  code/game/mecha/mecha_wreckage.dm
Labels: Bug-Fix

#2993 Round End Timer
  code/__HELPERS/time.dm
  code/controllers/subsystems/ticker.dm
  code/modules/mob/mob.dm
Labels: Good Issue Report, New Content, Good-To-Merge

#2994 Eerisports
  code/datums/contract.dm
  code/datums/movement/mob.dm
  code/datums/uplink/hardsuit_modules.dm
  code/game/objects/items/stacks/throwing.dm
  code/game/objects/random/rig.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_movement.dm
  code/modules/reagents/recipes.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  code/modules/research/designs/rigmodules.dm
  code/modules/stashes/stash_types/ninja.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
Labels: Documentation, New Content, Bug-Fix, Balance

#2992 Ameridium Updates
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/ameridian/ameridian_tree.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_behemoth.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_runner.dm
  icons/obj/ameridian.dmi
  sojourn-station.dme
Labels: New Content, Balance

#2995 wait this is a church nerf?
  code/game/objects/items/oddities.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
Labels: Balance

#2999 Fixes
  code/datums/craft/recipes/robot.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/nanogate/powers/nanobot.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
  icons/obj/food.dmi
Labels: Bug-Fix, Balance

#3000 Blackshield content!(and some marshal stuff too, ig.)
  code/datums/craft/recipes/clothing.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/mob/living/carbon/human/emote.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/mob/light_overlays.dmi
  icons/obj/guns/projectile/colt.dmi
  icons/obj/light_overlays.dmi
  sound/voice/bleat.ogg
Labels: New Content, Bug-Fix, Balance, Sprite Work

#3002 Fixes hear-say issue
  code/modules/mob/hear_say.dm
Labels: Bug-Fix

#3003 Anti-ameridian weaponry
  code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm
  code/game/objects/items/weapons/circuitboards/machinery/ameridian_processor.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_processor.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/ameridian/sonic_fence.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  code/modules/projectiles/guns/energy/sonic_emitter.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/shieldgen/sheldwallgen.dm
  icons/obj/guns/energy/sonic_emitter.dmi
  sojourn-station.dme
Labels: Enhancement, New Content

#3004 "CDB always nerfs the blackshield"
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/vouchers.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/sprite_accessories/_accessory_ears.dm
  code/modules/sprite_accessories/_accessory_marking.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/mob/human_races/markings.dmi
  icons/mob/light_overlays.dmi
  icons/mob/sprite_accessory/ears.dmi
  icons/obj/light_overlays.dmi
Labels: Enhancement, New Content, Bug-Fix, Balance, Sprite Work, Good-To-Merge

#2996 WotP Revamp
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/modules/core_implant/cruciform/machinery/armaments.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  icons/obj/eotp.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Invalid, New Content, Sprite Work
