Repository sojourn-13/sojourn-station, pull requests merged in 2022-09, with the labels that each got.

#3930 speed loader fix
  code/modules/projectiles/ammunition/magazines.dm
  icons/obj/ammo_speed.dmi
Labels: Bug-Fix

#3927 Toolbox Maul revolution, AKA, Wilson's re-endeavor to coding
  code/game/objects/items/weapons/melee/misc.dm
  icons/mob/items/lefthand.dmi
Labels: Bug-Fix

#3920 Makes the Akula tail fit non-Akula bodies.
  code/datums/setup_option/backgrounds/origin_akula.dm
  icons/mob/sprite_accessory/tails.dmi
Labels: Sprite Work

#3923 Aberrant organs update
  code/datums/autolathe/organ.dm
  code/modules/aberrants/organs/_defines.dm
  code/modules/aberrants/organs/design_disks/designs.dm
  code/modules/aberrants/organs/design_disks/disks.dm
  code/modules/aberrants/organs/holders.dm
  code/modules/aberrants/organs/internal/simple.dm
  code/modules/aberrants/organs/internal/teratoma.dm
  code/modules/aberrants/organs/machinery/medi-sarcophagus.dm
  code/modules/aberrants/organs/machinery/organ_fabricator.dm
  code/modules/aberrants/organs/machinery/organfridge.dm
  code/modules/aberrants/organs/mods/0_mods.dm
  code/modules/aberrants/organs/mods/1_input.dm
  code/modules/aberrants/organs/mods/2_process.dm
  code/modules/aberrants/organs/mods/3_output.dm
  code/modules/aberrants/organs/mods/4_special.dm
  code/modules/aberrants/organs/mods/component/input.dm
  code/modules/aberrants/organs/mods/component/output.dm
  code/modules/aberrants/organs/mods/component/special.dm
  code/modules/aberrants/organs/projectiles/teratoma.dm
  code/modules/aberrants/organs/reagents/hormones.dm
  code/modules/aberrants/organs/spawners.dm
  code/modules/research/research.dm
  sojourn-station.dme
Labels: Bug-Fix, Content, Balance

#3924 Synthetic Church Healing - No More Self-Synth Healing
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Bug-Fix, Balance

#3926 deepmaints and lighting
  code/game/area/Space Station 13 areas.dm
  code/modules/dungeons/procedural/deepmaint.dm
  code/modules/dungeons/procedural/jp_dungeon_gen.dm
  code/modules/power/lighting.dm
  icons/obj/lighting.dmi
Labels: Sprite Work

#3928 Stops slime speed up being stackable to -0.2
  code/modules/mob/living/carbon/slime/items.dm
Labels: Balance

#3929 Moo Moo revolution
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Content

#3931 deepmaints: respawning and fixes
  code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/life.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiMega.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiTrash.dm
Labels: Enhancement, Bug-Fix, Balance

#3933 A small change and new gene
  code/__DEFINES/genetics.dm
  code/modules/genetics/creatures/bioshock.dm
  code/modules/genetics/mutations/blood_bank.dm
  code/modules/genetics/mutations/cat_eyes.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/tomato.dm
  code/modules/organs/internal/internal_organ_processes.dm
  sojourn-station.dme
Labels: Bug-Fix, Content, Balance

#3864 Nanogate Removed from FBPS (EXCEPT Guild FBP Models)
  code/datums/setup_option/core_implants.dm
Labels: Balance

#3935 stranger fix and buff
  code/__HELPERS/bluespace_entropy.dm
  code/game/objects/items/oddities.dm
  code/modules/mob/living/carbon/superior_animal/human/stranger.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance

#3936 fixes synths doing genetics
  code/modules/genetics/genetics.dm
  code/modules/genetics/machinery/genetics_items.dm
Labels: Bug-Fix

#3938 Turns off sprite gen logging in character setup
  code/modules/admin/verbs/appearance_testing.dm
Labels: Bug-Fix

#3937 Aberrant Organs - surgery buttons and RNG reduction
  code/modules/aberrants/organs/design_disks/designs.dm
  code/modules/aberrants/organs/design_disks/disks.dm
  code/modules/aberrants/organs/internal/teratoma.dm
  code/modules/organs/internal/bones.dm
  code/modules/organs/surgery_helpers.dm
  code/modules/surgery/mods.dm
  nano/templates/surgery_organ.tmpl
  sojourn-station.dme
Labels: Enhancement

#3934 RE-removes cargo shuttle
  code/game/machinery/status_display.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/engineering.dm
  code/modules/shuttles/shuttle.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/unit_tests/map_tests.dm
  maps/Centcom/map/centcom.dmm
  maps/__Nadezhda/data/shuttles-eris.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Map, Removal

#3939 Readds a trade request console to cargo
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#3942 FBPs cannot use genetics injector
  code/modules/genetics/genetics.dm
  code/modules/genetics/machinery/genetics_items.dm
Labels: Bug-Fix

#3941 Creates Hunter Fangs necklace
  code/datums/craft/recipes/lodge.dm
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
Labels: Content, Sprite Work

#3945 Revert "Makes the Akula tail fit non-Akula bodies." because Sojourn doesn't have a functioning layer system.
  code/datums/setup_option/backgrounds/origin_akula.dm
  icons/mob/sprite_accessory/tails.dmi
Labels: Bug-Fix

#3947 Adds a snoutless version of the shark sprite.
  code/__DEFINES/mob_species_forms.dm
  code/modules/mob/living/carbon/human/species/forms/station.dm
  icons/mob/human_races/r_def_sudak.dmi
  icons/mob/human_races/r_sudak.dmi
Labels: Enhancement, Sprite Work

#3944 Fixes gaining of ana stat
  code/modules/aberrants/organs/internal/teratoma.dm
Labels: Balance

#3943 To you, the word "QoL patch" and "Seb" are one and the same.
  code/game/machinery/vendor/cloathing.dm
  code/game/objects/items/devices/lighting/flare.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/secdocs.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/costume.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/costume.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/masks/balaclava.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/suits.dm
  code/modules/organs/internal/stomach.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/assemblies.dmi
  icons/obj/drinks.dmi
  icons/obj/oddities.dmi
  icons/obj/surgery.dmi
  icons/obj/toy.dmi
Labels: Content, Balance, Sprite Work

#3949 Allerisports
  code/__DEFINES/components.dm
  code/__DEFINES/mobs.dm
  code/_onclick/click.dm
  code/datums/components/ai_like_control.dm
  code/game/gamemodes/events/carp_migration.dm
  code/game/objects/items/weapons/explosives.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_grab_specials.dm
  code/modules/multiz/turf.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/stump.dm
  code/modules/organs/external/subtypes/robotic.dm
  code/modules/organs/external/subtypes/slime.dm
  code/modules/organs/external/subtypes/unbreakable.dm
  code/modules/organs/organ_description.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/effects/projectiles.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/mob.dmi
  sojourn-station.dme
Labels: New Content, Bug-Fix, Balance, Sprite Work

#3946 huntermap redone
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/_HunterLodge/map/_Hunting_Lodge_old.dmm
  maps/__Nadezhda/nadezhda.dm
Labels: Balance, Map

#3953 Adds in two clothing items by ErisMeleeEnjoyer
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/casual.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work

#3954 fixes smoke and metaball
  code/ATMOSPHERICS/pipes.dm
  code/game/objects/effects/chem/chemsmoke.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: Bug-Fix

#3952 Aberrant Organs - tweaks and a little bit of content
  code/datums/autolathe/organ.dm
  code/modules/aberrants/organs/_defines.dm
  code/modules/aberrants/organs/design_disks/designs.dm
  code/modules/aberrants/organs/holders.dm
  code/modules/aberrants/organs/internal/teratoma.dm
  code/modules/aberrants/organs/mods/5_upgrades.dm
  code/modules/aberrants/organs/mods/component/_component.dm
  code/modules/aberrants/organs/mods/component/special.dm
  code/modules/aberrants/organs/reagents/hormones.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/organs/organ.dm
Labels: Enhancement, Bug-Fix, Balance

#3959 chef perk no alog
  code/datums/perks/job.dm
Labels: Bug-Fix

#3958 fixes being able to see smallivisable lights
  code/game/objects/structures/omnius.dm
Labels: Bug-Fix

#3957 Makes coolant cool
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Balance

#3961 beaker and bag fixes
  code/modules/reagents/machinery/centrifuge.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_heater.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/machinery/electrolyzer.dm
  code/modules/recycling/disposal.dm
Labels: Bug-Fix

#3962 removes a bad obelisk and misc
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3965 fixes venders power changing
  code/game/machinery/vending.dm
Labels: Bug-Fix

#3964 fix typos in the centurion
  code/modules/projectiles/guns/energy/centurio_auretian.dm
Labels: Bug-Fix

#3966 Fixes fireman carry
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/mob_grab_specials.dm
Labels: Bug-Fix

#3960 Unmaker Buff
  code/modules/projectiles/guns/mods/mods.dm
Labels: Balance

#3967 recoil and new gunmod
  code/__DEFINES/weapons.dm
  code/datums/uplink/stealth and camouflage items.dm
  code/datums/uplink/stealthy and inconspicuous weapons.dm
  code/game/objects/items/weapons/tools/mods/_defines.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/random/guns.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_hud_actions.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  nano/templates/weapon_stats.tmpl
Labels: Bug-Fix, Content, Balance

#3968 New masks for big guys
  code/__DEFINES/jobs.dm
  code/game/machinery/vendor/cloathing.dm
  code/modules/client/preference_setup/loadout/lists/clothing.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
Labels: Enhancement, Bug-Fix, Sprite Work

#3970 RnD Anti-cheating
  code/modules/modular_computers/file_system/binary/research.dm
  code/modules/modular_computers/file_system/programs/research/passive_pointes.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
Labels: Bug-Fix, Balance

#3972 icon fixes for speed loaders
  code/modules/projectiles/ammunition/magazines.dm
  icons/obj/ammo_speed.dmi
Labels: Bug-Fix, Sprite Work

#3971 slightly improves code-speak
  code/modules/mob/hear_say.dm
  code/modules/mob/language/codespeak.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Bug-Fix

#3974 Massively buffs undark glowsticks
  code/game/objects/items/devices/lighting/glowstick.dm
Labels: Balance, Skill-Issue | Salt PR

#3975 death fix+ gc fixes + icon fix
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/ammunition/bullets.dm
Labels: Bug-Fix

#3978 speedloader relinement
  icons/obj/ammo_speed.dmi
Labels: Bug-Fix

#3977 Trade - adds new offer type (modded items) and merge trade logs into main app
  code/__DEFINES/trade.dm
  code/controllers/subsystems/trade.dm
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/modular_computers/file_system/programs/generic/trade_log.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  nano/templates/trade_log.tmpl
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance

#3976 misc bug fixes. AKA, minor bug fixes
  code/modules/clothing/accessories/accessory.dm
  code/modules/mob/living/simple_animal/borer/borer_powers.dm
Labels: Bug-Fix
