Repository sojourn-13/sojourn-station, pull requests merged in 2022-08, with the labels that each got.

#3742 gun fixes
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/ppsh.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  maps/_DeepForest/map/_Beast_Cave.dmm
Labels: Bug-Fix

#3743 Adds firing offsets to mobs.
  code/__DEFINES/components.dm
  code/__DEFINES/maths.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/projectiles/projectile.dm
Labels: Enhancement

#3744 The best chem
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/stims.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Content

#3746 Trauma team Fix
  code/modules/clothing/spacesuits/rig/suits/station.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Bug-Fix

#3750 readds missing maska things
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Bug-Fix

#3749 various EMT fixes
  code/modules/clothing/spacesuits/rig/suits/station.dm
  icons/inventory/eyes/mob.dmi
  icons/inventory/suit/mob.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
Labels: Bug-Fix

#3751 New Rigback for Response Team
  code/modules/clothing/spacesuits/rig/suits/station.dm
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
Labels: Sprite Work

#3752 termite sanity
  code/modules/mining/drilling/drill.dm
Labels: Bug-Fix

#3747 New PDA Sprites
  icons/obj/modular_pda.dmi
Labels: Sprite Work

#3755 Fixed Bowman Headset
  code/game/objects/items/devices/radio/headset.dm
  icons/inventory/ears/mob.dmi
Labels: Sprite Work

#3754 pat
  code/modules/mob/living/carbon/superior_animal/lodge/lodge.dm
Labels: Enhancement

#3759 RPD port
  code/__DEFINES/construction.dm
  code/datums/autolathe/tools.dm
  code/game/machinery/pipe/construction.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/items/weapons/autolathe_disk/guild_disks.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  icons/obj/tools.dmi
  sojourn-station.dme
Labels: Enhancement, Content

#3760 sound fix
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/genetics/mutations/emp_blast.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/emp.dm
  code/modules/mob/living/simple_animal/hostile/stranger.dm
  code/modules/projectiles/gun.dm
  sound/weapons/guns/unknown_spacegun_burn.ogg
  sound/weapons/guns/unknown_spacegun_incinerate.ogg
  sound/weapons/guns/unknown_spacegun_melt.ogg
  sound/weapons/guns/unknown_spacegun_vaporize.ogg
Labels: Bug-Fix

#3758 Add a new tail
  code/modules/sprite_accessories/_accessory_tail.dm
  icons/mob/sprite_accessory/tails.dmi
Labels: Sprite Work

#3762 Occult port
  code/modules/reagents/reagents/nanites.dm
Labels: Bug-Fix, Balance

#3763 makes it so psions as intented cant be implanted
  code/game/objects/items/weapons/implant/implant.dm
  code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
  code/modules/psionics/psion.dm
Labels: Bug-Fix

#3769 Better infestions
  code/game/gamemodes/events/infestation.dm
Labels: Bug-Fix, Balance

#3770 fixes freedom tags
  code/modules/projectiles/guns/projectile/automatic/freedom.dm
  code/modules/projectiles/guns/projectile/automatic/nail_gun.dm
Labels: Bug-Fix

#3768 Guild and genetic spawners
  code/__DEFINES/perks.dm
  code/datums/outfits/jobs/ghostroles.dm
  code/datums/perks/job.dm
  code/datums/perks/racial.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/storage/belt.dm
Labels: Content

#3772 blackshield bowmens and binoclard buff
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  code/modules/clothing/glasses/misc.dm
  icons/inventory/ears/mob.dmi
  icons/inventory/ears/mob_fat.dmi
  icons/inventory/ears/mob_slim.dmi
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/obj/radio.dmi
Labels: Balance, Sprite Work

#3773 Blackshield Balancing
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
Labels: Balance, Good-To-Merge

#3785 chem and eblade fixes
  code/game/objects/items/weapons/melee/energy.dm
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Bug-Fix

#3784 fixes inflatable walls + cleaner code
  code/game/objects/structures/inflatable.dm
Labels: Bug-Fix

#3783 fixes the faction medical items
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
Labels: Bug-Fix

#3782 Adds multicolored pen to the loadout menu
  code/modules/client/preference_setup/loadout/lists/utility.dm
Labels: Enhancement

#3781 Should hopefully make wings less awful if you use demon wings. Will do the rest soonTM
  code/modules/sprite_accessories/_accessory_wings.dm
  icons/mob/sprite_accessory/wings.dmi
Labels: Sprite Work, Good-To-Merge

#3778 Steward hard suit changes
  code/modules/clothing/spacesuits/rig/suits/station.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Sprite Work

#3792 Tesla turret fix and ameridian balance
  code/game/machinery/portable_turret.dm
  code/game/machinery/tesla_turret.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_behemoth.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_runtling.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_shooter.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/projectile/ameridian.dm
  icons/obj/tesla_turret.dmi
Labels: Bug-Fix, Balance, Skill-Issue | Salt PR

#3790 untested roach fic
  code/game/objects/effects/spiders.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
Labels: Bug-Fix

#3788 matterforge no longer takes ammo
  code/game/machinery/autolathe/matterforge.dm
Labels: Bug-Fix

#3793 Ameridian weak to explosions
  code/modules/ameridian/ameridian_crystal.dm
Labels: Enhancement, Balance, Good-To-Merge, Skill-Issue | Salt PR

#3786 Bay Port - Mutual Language Understanding
  code/modules/mob/language/ancient_latin.dm
  code/modules/mob/language/esperanto.dm
  code/modules/mob/language/german.dm
  code/modules/mob/language/jana.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/monkey.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/serbian.dm
  code/modules/mob/language/station.dm
  code/modules/mob/language/yassari.dm
Labels: Enhancement, New Content

#3795 better wall obelisk optimization
  code/modules/core_implant/cruciform/machinery/wall_obelisk.dm
Labels: Enhancement

#3798 Removes some cursed code that was breaking grenades.
  code/game/objects/items/weapons/grenades/grenade.dm
Labels: Bug-Fix

#3797 A bunch of micro-optimizations (and maybe one significant one)
  code/__HELPERS/game.dm
  code/controllers/subsystems/processing/mobs.dm
  code/game/atoms.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/say.dm
  code/modules/mob/observer/ghost/ghost.dm
Labels: Enhancement

#3803 Potentially fixes a bug with saycode
  code/modules/mob/living/say.dm
Labels: Bug-Fix

#3801 new lighter
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  icons/obj/items.dmi
Labels: Sprite Work

#3806 THIS IS THE WORST FUCKING CODE I HAVE SEEN. FIXES. A GODDAMN. SAYCODE ISSUE. AMONG OTHERS.
  code/datums/observation/moved.dm
  code/game/atoms_movable.dm
Labels: Bug-Fix

#3800 Oh My Guts! - Aberrant Organs
  code/__DEFINES/components.dm
  code/controllers/subsystems/_spawner.dm
  code/datums/autolathe/biomatter.dm
  code/datums/autolathe/organ.dm
  code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
  code/game/objects/random/packs.dm
  code/modules/aberrants/_modification.dm
  code/modules/aberrants/organs/_defines.dm
  code/modules/aberrants/organs/design_disks/designs.dm
  code/modules/aberrants/organs/design_disks/disks.dm
  code/modules/aberrants/organs/holders.dm
  code/modules/aberrants/organs/internal/dependent.dm
  code/modules/aberrants/organs/internal/simple.dm
  code/modules/aberrants/organs/internal/teratoma.dm
  code/modules/aberrants/organs/machinery/medi-sarcophagus.dm
  code/modules/aberrants/organs/machinery/medical_bioprinter.dm
  code/modules/aberrants/organs/machinery/organfridge.dm
  code/modules/aberrants/organs/mods/0_mods.dm
  code/modules/aberrants/organs/mods/1_input.dm
  code/modules/aberrants/organs/mods/2_process.dm
  code/modules/aberrants/organs/mods/3_output.dm
  code/modules/aberrants/organs/mods/4_special.dm
  code/modules/aberrants/organs/mods/5_upgrades.dm
  code/modules/aberrants/organs/mods/component/_component.dm
  code/modules/aberrants/organs/mods/component/input.dm
  code/modules/aberrants/organs/mods/component/output.dm
  code/modules/aberrants/organs/mods/component/process.dm
  code/modules/aberrants/organs/mods/component/special.dm
  code/modules/aberrants/organs/mods/component/stromal.dm
  code/modules/aberrants/organs/projectiles/teratoma.dm
  code/modules/aberrants/organs/spawners.dm
  code/modules/dungeons/procedural/deepmaint.dm
  code/modules/hivemind/mobs.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/organ.dm
  icons/obj/aberrant_organs.dmi
  icons/obj/discs.dmi
  icons/obj/machines/autolathe.dmi
  icons/obj/medisarcophagus.dmi
  icons/obj/organ_mods.dmi
  icons/obj/vending.dmi
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, New Content, Good-To-Merge

#3777 Marshal Bullet Fab, Prospector Scrap Crafting & Misc Changes
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/game/jobs/job/security.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/objects/structures/noticeboard.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance, Map

#3809 ANother attempted fix for saycode
  code/__HELPERS/game.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/say.dm
Labels: Bug-Fix

#3811 Shield gen Rewire plus Soteria map fixes
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance

#3817 Causes mobs to update their zlevel if they actually change zlevel through forceMove
  code/modules/multiz/shadow.dm
Labels: Bug-Fix

#3821 Balls!
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/toys.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/toy.dmi
  sojourn-station.dme
Labels: Content, Sprite Work

#3820 Aberrant organ bug fixes
  code/modules/aberrants/organs/design_disks/disks.dm
  code/modules/aberrants/organs/internal/dependent.dm
  code/modules/aberrants/organs/machinery/medi-sarcophagus.dm
  code/modules/aberrants/organs/machinery/organfridge.dm
Labels: Bug-Fix, Balance

#3826 Better bacon sprite
  icons/obj/food_ingredients.dmi
Labels: Sprite Work

#3825 Fixes a harddel associated with z movement
  code/game/atoms_movable.dm
  code/modules/multiz/shadow.dm
Labels: Bug-Fix

#3824 Maybe fixes bills to pay
  code/datums/objective/individual_objective/common.dm
Labels: Bug-Fix

#3814 Remove corporation checking from examining objects
  code/game/objects/objs.dm
Labels: Enhancement

#3823 dorms nerf
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
Labels: Bug-Fix, Balance, Map

#3830 Restructure Genetics Lab
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance, Map

#3829 lighting and better surgery
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance, Map

#3833 Map fixes
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3834 Makes it so you know what account to pay
  code/datums/objective/individual_objective/common.dm
Labels: Bug-Fix

#3835 Turns dusters into accessories
  code/game/machinery/vendor/misc_vendors.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/suits/storage.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
Labels: Balance, Sprite Work

#3841 Fixes a dumb mistake I did in saycode
  code/modules/mob/living/say.dm
Labels: Bug-Fix

#3838 Aberrant Organs - Organ fab update, RNG reduction, balance pass
  code/datums/autolathe/organ.dm
  code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
  code/modules/aberrants/_modification.dm
  code/modules/aberrants/organs/_defines.dm
  code/modules/aberrants/organs/design_disks/designs.dm
  code/modules/aberrants/organs/design_disks/disks.dm
  code/modules/aberrants/organs/holders.dm
  code/modules/aberrants/organs/internal/simple.dm
  code/modules/aberrants/organs/internal/teratoma.dm
  code/modules/aberrants/organs/machinery/medi-sarcophagus.dm
  code/modules/aberrants/organs/machinery/medical_bioprinter.dm
  code/modules/aberrants/organs/machinery/organ_fabricator.dm
  code/modules/aberrants/organs/machinery/organfridge.dm
  code/modules/aberrants/organs/mods/0_mods.dm
  code/modules/aberrants/organs/mods/3_output.dm
  code/modules/aberrants/organs/mods/4_special.dm
  code/modules/aberrants/organs/mods/component/input.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance

#3845 Eris fix ports
  code/game/machinery/camera/camera.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/toxins.dm
Labels: Bug-Fix, Balance

#3843 linked box nerf
  code/modules/projectiles/ammunition/magazines.dm
Labels: Bug-Fix, Good-To-Merge

#3846 Kriosan mobs for the upcoming event
  code/modules/mob/living/carbon/superior_animal/human/subtype/kriosan/kriosan.dm
  icons/mob/mobs-humanoid.dmi
  sojourn-station.dme
Labels: Sprite Work

#3850 syndacat trade beacon buffs
  code/modules/organs/internal/heart.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/organs/internal/liver.dm
  code/modules/organs/internal/lungs.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
Labels: Balance

#3856 small explote fix
  code/modules/economy/Accounts.dm
Labels: Bug-Fix

#3857 Fixes Language Intelligibility & Adds Written Languages
  code/modules/mob/language/ancient_latin.dm
  code/modules/mob/language/esperanto.dm
  code/modules/mob/language/generic.dm
  code/modules/mob/language/german.dm
  code/modules/mob/language/jana.dm
  code/modules/mob/language/jive.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/monkey.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/serbian.dm
  code/modules/mob/language/station.dm
  code/modules/mob/language/synthetic.dm
  code/modules/mob/language/yassari.dm
  code/modules/mob/living/say.dm
  code/modules/modular_computers/file_system/programs/generic/configurator.dm
  code/modules/modular_computers/hardware/printer.dm
  code/modules/paperwork/carbonpaper.dm
  code/modules/paperwork/paper.dm
Labels: Enhancement, Bug-Fix, Balance

#3849 Klutz balance pass
  code/game/objects/items/weapons/material/kitchen.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/tools/stunbatons.dm
  code/modules/projectiles/gun.dm
Labels: Bug-Fix, Balance

#3859 more MLGTASTIC fixes for sanitization
  code/modules/economy/Accounts.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/cash_register.dm
  code/modules/ghosttrap/trap.dm
  code/modules/mob/living/living.dm
  code/modules/modular_computers/file_system/programs/generic/taxes.dm
Labels: Bug-Fix

#3860 bond fix and automatic again
  code/datums/autolathe/guns.dm
  code/game/objects/random/guns.dm
  code/modules/projectiles/guns/projectile/automatic/bond.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  icons/obj/guns/projectile/survivalrifle.dmi
  sojourn-station.dme
Labels: Bug-Fix, Skill-Issue | Salt PR

#3827 fpb-phobic
  code/game/jobs/job/captain.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Wont fix, Balance

#3866 removal of more dorms and condecing
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance, Map, Removal

#3868 Medfixes and ports
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/organs/external/_external.dm
  code/modules/surgery/autodoc.dm
  code/modules/surgery/robotic_damage.dm
  code/modules/surgery/surgery.dm
Labels: Enhancement, Bug-Fix, Balance

#3867 Allows More Jobs for FBPs
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Balance

#3870 more medical stuff
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/wound.dm
Labels: Enhancement

#3872 fixes exploits
  code/modules/ameridian/liquid_ameridian_processor.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/modular_computers/file_system/programs/generic/taxes.dm
Labels: Bug-Fix

#3877 fixe ore drop doups
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
Labels: Bug-Fix

#3874 massively lowers darksight and fixes it
  code/modules/clothing/glasses/powered.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/living_defines.dm
Labels: Bug-Fix, Balance

#3875 Another big batch of goodies!
  code/__DEFINES/is_helpers.dm
  code/datums/craft/recipes/clothing.dm
  code/game/objects/structures/dogbed.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/obj/chemical.dmi
  icons/obj/crafts.dmi
  icons/obj/furniture.dmi
  icons/obj/janitor.dmi
  icons/obj/reagentfillings.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Balance, Sprite Work, Map

#3878 more dence xenoflora and teleporter room
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3865 Removes Dogborgs (As requested)
  code/modules/mob/living/silicon/robot/robot_dogborgs.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots_wide.dmi
  icons/mob/screen1_robot_vr.dmi
  sojourn-station.dme
Labels: Balance, Removal

#3881 Fixes bio check
  code/modules/surgery/surgery.dm
Labels: Bug-Fix

#3880 Trade Program Update
  code/controllers/subsystems/trade.dm
  code/datums/autolathe/circuits.dm
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/modular_computers/file_system/programs/generic/trade_catalog.dm
  code/modules/modular_computers/file_system/programs/generic/trade_log.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/machinery/circuits/trade_beacon.dm
  code/modules/trade/machinery/trade_beacon.dm
  nano/templates/trade.tmpl
  nano/templates/trade_cart.tmpl
  nano/templates/trade_goods.tmpl
  nano/templates/trade_log.tmpl
  nano/templates/trade_offers.tmpl
  nano/templates/trade_orders.tmpl
  nano/templates/trade_saved.tmpl
Labels: Enhancement, New Content, Balance

#3879 New church maping
  maps/_DeepForest/map/_River_Forest.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3885 Trade bug fix
  code/controllers/subsystems/trade.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
Labels: Bug-Fix

#3887 mis rnd and gun fixes
  code/modules/genetics/machinery/genetics_analyzer.dm
  code/modules/projectiles/gun.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_eguns.dm
Labels: Bug-Fix

#3883 Emotes now use gender, not sex
  code/modules/mob/living/carbon/human/emote.dm
Labels: Bug-Fix

#3889 Adds PDA ordering app to default
  code/controllers/subsystems/trade.dm
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/computers/subtypes/preset_pda.dm
  code/modules/modular_computers/file_system/programs/generic/trade_log.dm
  code/modules/modular_computers/file_system/programs/generic/trade_orders.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Bug-Fix, Balance

#3891 fixes faxes
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#3893 Nv coverted guild goggles
  code/datums/craft/recipes/guild.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
Labels: Balance, Good-To-Merge

#3894 Many ports and ideas from Occulists
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/clothing.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/head/fishing.dm
  code/modules/clothing/head/jobs.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/sprite_accessories/_accessory_ears.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/mob/sprite_accessory/ears.dmi
  icons/obj/chemical.dmi
  sojourn-station.dme
Labels: Balance, Sprite Work

#3892 Emp tweaks
  code/modules/organs/external/_external.dm
  code/modules/organs/organ.dm
Labels: Balance, Discussion Needed

#3898 Fixes endocrinal organoid adjustment
  code/modules/aberrants/organs/mods/3_output.dm
Labels: Bug-Fix

#3900 makes it so whitelists are a bit more needed
  code/game/verbs/ooc.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/mob/observer/ghost/say.dm
Labels: Skill-Issue | Salt PR, Removal

#3899 Henryk and Two-Face iconic suits
  code/modules/clothing/under/suits.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work, Good-To-Merge

#3910 Measons +1 view
  code/modules/clothing/glasses/powered.dm
Labels: Balance

#3909 Relics
  code/game/machinery/doors/holy_door.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/candle.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/psionics/psionic_items/psi_misc.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Documentation

#3904 Ripley buff
  code/datums/craft/recipes/guild.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/structures/burrows.dm
Labels: Balance

#3911 Church Gun Lore :tm:
  code/modules/projectiles/guns/energy/antebellum.dm
  code/modules/projectiles/guns/energy/carpediem.dm
  code/modules/projectiles/guns/energy/concilium.dm
  code/modules/projectiles/guns/energy/crossbow.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/guns/energy/sniperrifle.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/matter/launcher/books.dm
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
  code/modules/projectiles/guns/projectile/other/protector.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
Labels: Documentation

#3890 misc random changes
  code/datums/craft/recipes/wall.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/circuitboards/computer/research.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/random/circuitboards.dm
  code/game/objects/structures/turf_spawner.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/inventory/slots.dm
  code/modules/organs/internal/nanogate.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/rdconsole.dm
  icons/obj/structures.dmi
  icons/turf/flooring/plating.dmi
  sojourn-station.dme
Labels: Bug-Fix, Balance, Good-To-Merge

#3906 Blackshield HARD Nerf!!!! (Prospector gang rise up kill em' all 1984)
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3901 New optimized NV goggles sprites and more
  code/datums/craft/recipes/guild.dm
  code/game/objects/items/contraband.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/clothing/suits/storage.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/walllocker.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance, Sprite Work, Map

#3912 New rune glubs
  code/game/machinery/vendor/cloathing.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/modules/client/preference_setup/loadout/lists/gloves.dm
  code/modules/clothing/gloves/miscellaneous.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  sojourn-station.dme
Labels: Sprite Work

#3917 Eris ports
  code/__DEFINES/storyteller_defines.dm
  code/__HELPERS/bluespace_entropy.dm
  code/controllers/subsystems/voting/poll_types.dm
  code/datums/datum_hud.dm
  code/game/atoms.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/gamemodes/storyteller.dm
  code/game/gamemodes/storyteller_print.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/flasher.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/lighting/toggleable/flashlight.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  code/modules/client/preference_setup/global/preferences.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/dungeons/teleporter.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/multiz/structures.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/reagents/recipes/recipes_slime.dm
  code/modules/surgery/hardsuit.dm
  code/modules/surgery/robotic_damage.dm
  icons/obj/ammo_speed.dmi
Labels: New Content, Bug-Fix, Balance, Sprite Work

#3916 adds last of the missing packs to trade beacons
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
Labels: Balance

#3915 craftable soil
  code/datums/craft/recipes/furniture.dm
Labels: Content

#3913 prepper bunker resizing
  maps/_DeepForest/map/_Prepper_Bunker.dmm
Labels: Balance, Map

#3918 Mindswapping out
  code/game/machinery/mindswapper.dm
  code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/illegal.dm
  sojourn-station.dme
Labels: Removal

#3919 You can teleport out of the wasonce
  code/modules/genetics/creatures/wasonce.dm
Labels: Bug-Fix

#3908 bullet balance 2.0
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance, Discussion Needed

#3882 Removes outsider GP Field Office spawn
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
Labels: Balance, Discussion Needed

#3921 i hate grid checks
  code/game/gamemodes/events/grid_check.dm
Labels: Skill-Issue | Salt PR

#3896 Ameridain redo
  code/datums/craft/recipes/misc.dm
  code/game/area/asteroid_areas.dm
  code/game/objects/random/mob/golems.dm
  code/game/turfs/initialization/mines.dm
  code/modules/ameridian/ameridian_core.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_crystal_blue.dm
  code/modules/ameridian/ameridian_crystal_red.dm
  code/modules/ameridian/ameridian_field.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/ameridian/liquid_ameridian_processor.dm
  code/modules/mining/drilling/ore_sonar.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  code/modules/mob/living/simple_animal/friendly/ameridian_tender.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/reagents/reagents/other.dm
  code/modules/research/designs/circuits.dm
  code/modules/unit_tests/map_tests.dm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, Help Wanted, Balance, Removal, Discussion Needed
