Repository sojourn-13/sojourn-station, pull requests merged in 2022-12, with the labels that each got.

#4198 Add microwave recipe for hawaiian pizza
  code/modules/food/recipes_microwave.dm
Labels: Content

#4202 Fix point deductions for Church for dirty areas
  code/game/gamemodes/scores.dm
Labels: Bug-Fix

#4203 a cool sword (and minor refactors)
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/tools/_tools.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/nt_melee.dmi
Labels: Balance, Sprite Work

#4204 fixes reject icon
  code/modules/genetics/machinery/genetics_items.dm
Labels: Bug-Fix

#4208 New prospector cape + All jumpsuits are now tracking sensors by default
  code/datums/outfits/jobs/prospector.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/casual.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
Labels: Bug-Fix, Sprite Work

#4209 Lonestar: The Drip or Drown Edition
  code/datums/outfits/jobs/guild.dm
  code/modules/client/preference_setup/loadout/lists/factionlonestar.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Sprite Work

#4206 buffs the heck out of the lever guns
  code/modules/projectiles/guns/projectile/boltgun.dm
Labels: Bug-Fix, Balance

#4211 Partial Factorial rework/cruciform stat tweaks
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/projectiles/guns/mods/mods.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tool_upgrades.dmi
  icons/obj/tools.dmi
Labels: Content, Balance, Sprite Work

#4212 fixes a silly error in the tool refactor
  code/game/objects/items/weapons/tools/_tools.dm
Labels: Bug-Fix

#4213 Restorting psionics
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/conquest_powers.dm
  code/modules/psionics/greater_powers.dm
  code/modules/psionics/psion.dm
  code/modules/psionics/psion_powers/_powers.dm
  code/modules/psionics/psion_powers/armour_powers.dm
  code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
  code/modules/psionics/psion_powers/faction_powers.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/locator_powers.dm
  code/modules/psionics/psion_powers/mob_affecting_powers.dm
  code/modules/psionics/psion_powers/oddity_powers.dm
  code/modules/psionics/psion_powers/oldification_powers.dm
  code/modules/psionics/psion_powers/psion_starter_powers.dm
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
  code/modules/psionics/psion_powers/telekinetsis_powers.dm
  code/modules/psionics/psion_powers/teleporation_powers.dm
  code/modules/psionics/researched_powers.dm
  code/modules/psionics/standard_powers.dm
  sojourn-station.dme
Labels: Documentation, Bug-Fix, Balance

#4215 stuff for the event
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/stunbatons.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/projectiles/guns/energy/plasma/cassad.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/obj/guns/plasma/marqua.dmi
  icons/obj/tools.dmi
Labels: Balance, Sprite Work

#4217 Removes 5.56, fixes Homemade sprite
  code/datums/perks/nanogate.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  maps/_DeepForest/map/_River_To_Swamp.dmm
Labels: Bug-Fix, Removal

#4218 Jackboot icons and changes
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/clothing/shoes/jobs.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
Labels: Balance, Sprite Work

#4219 Wetfloor Visual Fix for the blind and speedy
  icons/effects/water.dmi
Labels: Balance

#4220 fixes doble point costs
  code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
  code/modules/psionics/psion_powers/mob_affecting_powers.dm
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
  code/modules/psionics/psion_powers/telekinetsis_powers.dm
  code/modules/psionics/psion_powers/teleporation_powers.dm
Labels: Bug-Fix

#4216 Language Vote Implimenation
  code/__DEFINES/species_languages.dm
  code/datums/perks/job.dm
  code/datums/perks/racial.dm
  code/game/antagonist/outer/mercenary/mercenary.dm
  code/modules/admin/bluespacetech.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/mob/language/ancient_latin.dm
  code/modules/mob/language/euro.dm
  code/modules/mob/language/illyrian.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/romana.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/admin_only_modules.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/paperwork/paper.dm
  code/stylesheet.dm
  sojourn-station.dme
Labels: Documentation

#4222 some map error fixes
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#4223 scrap refine exploit fix
  code/modules/scrap/scrap_refine.dm
Labels: Balance

#4221 More Church cosmetics
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/cloak/hooded.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Balance, Sprite Work

#4224 Better Marshal mapping
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#4225 Language and anomaly exploit fixes
  code/datums/perks/oddity.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/mob/language/euro.dm
  code/modules/mob/language/illyrian.dm
  code/modules/mob/language/jana.dm
  code/modules/mob/language/station.dm
  code/modules/mob/language/yassari.dm
Labels: Bug-Fix, Balance

#4226 xenorebalance
  code/datums/stat_modifiers/modifiers/mob/superior/xeno_modifers.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoImpressive.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoMega.dm
  sojourn-station.dme
Labels: Balance

#4227 shield properly block and break
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/shields.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
Labels: Bug-Fix, Balance

#4229 buffs tazntz mobs for event
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tazntz.dm
  code/modules/psionics/psionic_items/psi_weptools.dm
  icons/mob/mobs-daskvey.dmi
Labels: Balance, Sprite Work

#4228 New zippo sounds
  code/game/objects/items/weapons/cigs_lighters.dm
  sound/items/zippo_close.ogg
  sound/items/zippo_open.ogg
Labels: Sound Addition

#4234 fixes church alt sprites
  icons/inventory/suit/mob_fem.dmi
Labels: Bug-Fix

#4232 Webs QOL sprite change
  icons/effects/effects.dmi
Labels: Balance, Sprite Work

#4237 some mob fixes and sprite corrections
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  icons/mob/sprite_accessory/ears.dmi
  icons/obj/guns/energy/toxgun.dmi
Labels: Bug-Fix, Sprite Work

#4238 iconfix
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  icons/mob/mobs-daskvey.dmi
Labels: Sprite Work

#4240 The omni spritening and more
  code/datums/craft/recipes/guns.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/autodoc_excelsior.dm
  code/game/machinery/vendor/cloathing.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/effects/spawners/ghostspawner.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/game/objects/items/weapons/implant/implants/adrenalin.dm
  code/game/objects/items/weapons/implant/implants/compressed.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/random/cloth.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/mining/drilling/ore_sonar.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/power/smes_construction.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/research/xenoarchaeology/tools/tools_anoscanner.dm
  code/modules/research/xenoarchaeology/tools/tools_depthscanner.dm
  code/modules/telesci/teleporter_blocker.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/Cryogenic2.dmi
  icons/obj/adms.dmi
  icons/obj/adms_old.dmi
  icons/obj/ammo.dmi
  icons/obj/items.dmi
  icons/obj/stock_parts.dmi
  icons/obj/tools.dmi
  icons/obj/xenoarchaeology.dmi
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/submaps/deepmaint_rooms/normal/cryo.dmm
  maps/testmap/test_map.dmm
  sound/items/chainsaw_off.ogg
  sound/items/chainsaw_on.ogg
Labels: Bug-Fix, Balance, Sprite Work

#4245 Catwalk and underplating categorization fix
  code/datums/craft/recipes/floor.dm
  code/datums/craft/recipes/wall.dm
Labels: Bug-Fix

#4247 Eris coding
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/perks.dm
  code/datums/autolathe/guns.dm
  code/datums/outfits/equipment/backpacks.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/perks/oddity.dm
  code/game/atoms.dm
  code/game/jobs/department.dm
  code/game/machinery/os_portable_turret.dm
  code/game/machinery/vending.dm
  code/game/machinery/vendor/one_star_vending.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/spawners/corpsespawner.dm
  code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/random/ammo.dm
  code/game/objects/random/lathe_disks/onestar.dm
  code/game/objects/random/structures.dm
  code/game/objects/structures/salvageable.dm
  code/game/turfs/simulated/walls.dm
  code/modules/economy/os_cash.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/species/station/skeleton.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/living.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/subtypes/skeleton.dm
  code/modules/organs/organ_description.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/pistol/rebar.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/fragment.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
  icons/obj/chemical.dmi
  icons/obj/grenade.dmi
  icons/obj/guns/projectile/nail_gun.dmi
  icons/obj/guns/projectile/rebar.dmi
  icons/obj/machines/one_star/machines.dmi
  icons/obj/machines/one_star/vending.dmi
  icons/obj/os_cash.dmi
  icons/obj/projectiles_64x64.dmi
  icons/obj/salvageable.dmi
  icons/obj/storage/boxes.dmi
  sojourn-station.dme
Labels: Enhancement, New Content, Bug-Fix, Content, Balance, Sprite Work

#4248 book buff
  code/game/objects/items/oddities.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
Labels: Enhancement, Balance

#4246 Bugfixes and a drink
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/autolathe/guns.dm
  code/datums/contract.dm
  code/datums/craft/recipes/guns.dm
  code/datums/craft/recipes/repairs.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/random/guns.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/biotech.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/mob/rig_back.dmi
  icons/obj/adms.dmi
  icons/obj/drinks.dmi
  icons/obj/rig_modules.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Documentation, Bug-Fix, Balance, Sprite Work

#4249 fixes a edge case in bondfires and AI langs
  code/game/objects/structures/firepits.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
Labels: Bug-Fix

#4250 Duplicate Table fix
  maps/_DeepForest/map/_River_Forest.dmm
Labels: Bug-Fix

#4251 Cigarettes in scrap piles
  code/game/objects/random/cigarettes.dm
  code/modules/scrap/scrap.dm
  sojourn-station.dme
Labels: Balance

#4252 Makes the Gazer Eyestalks colourable
  code/modules/sprite_accessories/_accessory_wings.dm
  icons/mob/sprite_accessory/wings.dmi
Labels: Sprite Work

#4253 fix: Fix links to Wiki-books
  code/game/objects/items/weapons/manuals.dm
  code/modules/library/lib_items.dm
Labels: Bug-Fix

#4260 grey ponchos
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/head/misc.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#4259 lmg small fix
  icons/obj/guns/projectile/lmg.dmi
Labels: Bug-Fix

#4257 Small batch of QoL changes and requests
  code/datums/autolathe/tools.dm
  code/game/objects/items/weapons/tools/multitool.dm
  code/game/objects/random/tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/projectiles/guns/projectile/boltgun/scout.dm
  code/modules/research/designs/greyson.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
Labels: Enhancement, Balance
