Repository sojourn-13/sojourn-station, pull requests merged in 2022-07, with the labels that each got.

#3624 news
  code/modules/modular_computers/file_system/news_article.dm
  news_articles/kros_news.html
Labels: dependencies

#3625 Trade fix: re-adds direct sales, some error messages
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  nano/templates/trade.tmpl
Labels: Bug-Fix, Balance

#3621 Simple mobs now also clear their target on death
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug-Fix

#3630 Martin fixes
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  icons/obj/guns/projectile/martian.dmi
Labels: Bug-Fix

#3628 BDU Fix
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/uniform/mob.dmi
Labels: Bug-Fix

#3632 SirRichardFrancis runtimefixes
  code/ZAS/Fire.dm
  code/__DEFINES/movement.dm
  code/datums/perks/perk.dm
  code/game/gamemodes/events/money_lotto.dm
  code/modules/clothing/spacesuits/rig/modules/computer.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/organ.dm
  icons/obj/guns/projectile/martian.dmi
Labels: Bug-Fix

#3636 fixes numerical and cardigan icons
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/storage.dm
Labels: Bug-Fix

#3634 Emp landmine counter
  code/game/objects/items/weapons/emp_mine.dm
Labels: Balance

#3633 hivemind event spawning fixes
  code/game/gamemodes/events/hivemind_invasion.dm
Labels: Bug-Fix

#3622 Fixes a few weird mob bugs, such as them sprinting to you if they lose LOS. Enhances certain areas of visible messages, certain parts of mob code, etc.
  code/game/objects/items/weapons/power_cells.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/life.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/turrets.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/mob.dm
Labels: Bug-Fix, Balance

#3641 Fix for the Liverless
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Bug-Fix

#3640 Fixes SI synth heads
  icons/mob/human_races/cyberlimbs/moebius.dmi
Labels: Sprite Work

#3635 Loadout Coat & Hats
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/head/costume.dm
  code/modules/clothing/suits/greatcoat.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Content

#3644 Improves mob AI even more.
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
Labels: Enhancement

#3643 even more mertain icon changes
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  icons/obj/guns/projectile/martian.dmi
Labels: Bug-Fix, Sprite Work

#3629 Adds a funky new tool for mappers and events: Entity spawners, objects that endlessly churn out any given entity, to a limit
  code/game/machinery/machinery.dm
  code/game/objects/explosion_recursive.dm
  code/game/objects/objs.dm
  code/game/objects/random/entity_spawners/entity_spawner.dm
  code/game/objects/random/entity_spawners/greyson_spawners/greyson_spawners.dm
  code/game/objects/random/entity_spawners/greyson_spawners/roomba_spawners.dm
  code/modules/mob/death.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  sojourn-station.dme
Labels: Documentation, New Content, Balance

#3638 duck and cover
  code/game/machinery/deployable.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/low_wall.dm
Labels: Bug-Fix, Balance

#3637 Adds a few admin-only greyson mobs, some with custom sprites.
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/mechs.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/turrets.dm
  icons/mob/mobs-humanoid.dmi
  icons/obj/chemical.dmi
  sojourn-station.dme
Labels: Documentation, Enhancement, New Content, Balance, Sprite Work, Merge Conflict

#3646 Small pepper spider buff, increases the speed of their spray
  code/game/objects/effects/chem/water.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/pepper.dm
Labels: Balance

#3655 Makes entity spawners test projectile compatible.
  code/game/objects/random/entity_spawners/entity_spawner.dm
Labels: Bug-Fix

#3647 Adds a new buildmode mode, path mode, that allows admins to force mobs to walk towards things and stuff.
  code/__DEFINES/admin.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/structures/burrows.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/hivemind/mobs.dm
  code/modules/mob/living/bot/drillbot.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/friendly/ameridian_tender.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/hostile/commanded/commanded.dm
  code/modules/mob/living/simple_animal/hostile/commanded/nanomachines.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_helpers.dm
  icons/misc/buildmode.dmi
  sojourn-station.dme
Labels: Enhancement

#3656 a few more !testing checks
  code/game/objects/items/weapons/emp_mine.dm
  code/modules/tables/interactions.dm
  modular_sojourn/shields.dm
Labels: Bug-Fix

#3659 Fixes buildmode deleting its own icons
  code/modules/admin/verbs/buildmode.dm
Labels: Bug-Fix

#3660 Fixing GoatMed Again
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Bug-Fix

#3661 actually fixes this fucking runtime
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Bug-Fix

#3657 Gun Size Rebalance, New Lever-Shotgun & Plasma AOE
  code/datums/craft/recipes/guns.dm
  code/modules/projectiles/guns/energy/cog.dm
  code/modules/projectiles/guns/energy/ionrifle.dm
  code/modules/projectiles/guns/energy/lasertag.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/guns/energy/railgun.dm
  code/modules/projectiles/guns/projectile/automatic/bren.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/boltgun/armstrong.dm
  code/modules/projectiles/guns/projectile/revolver/longboi.dm
  icons/obj/guns/projectile/mares.dmi
Labels: Bug-Fix, Balance, Sprite Work

#3662 Mobs now avoid friendly fire, and also work better with burrows
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/projectiles/projectile.dm
Labels: Balance

#3666 Bagless Buff
  code/__DEFINES/mobs.dm
  code/_onclick/click.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/modules/mob/mob_defines.dm
Labels: Balance

#3648 blackshield buff
  code/datums/outfits/jobs/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/clothing/gloves/miscellaneous.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
Labels: Balance, Sprite Work

#3668 Map fixes
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#3649 the space leakening
  code/__HELPERS/bluespace_entropy.dm
  code/modules/reagents/reagents/other.dm
  modular_sojourn/spaceleak.dm
  modular_sojourn/spaceleak.dmi
  sojourn-station.dme
Labels: New Content, Balance

#3669 Fixes some mob AI stuff I broke
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug-Fix, Balance

#3667 Oddites and Deepmtains
  code/__DEFINES/perks.dm
  code/game/objects/items/oddities.dm
  code/game/objects/random/psi_loot.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiMega.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiTrash.dm
  code/modules/psionics/psionic_items/psi_weptools.dm
  sojourn-station.dme
Labels: Enhancement, Balance

#3664 Datumizes prefixes for more modularity and ease of use, fixes king termite ranged attack, adds a few extra prefixes that wont be used for now
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/_lists.dm
  code/datums/stat_modifiers/mob/mob_modifiers.dm
  code/datums/stat_modifiers/mob/ranged/ranged_modifiers.dm
  code/datums/stat_modifiers/mob/roach_modifiers.dm
  code/datums/stat_modifiers/mob/robot_modifiers.dm
  code/datums/stat_modifiers/mob/special/special_modifiers.dm
  code/datums/stat_modifiers/mob/spider_modifiers.dm
  code/datums/stat_modifiers/mob/superior_modifiers.dm
  code/datums/stat_modifiers/stat_modifier.dm
  code/game/atoms.dm
  code/game/objects/items.dm
  code/modules/dungeons/junk_tractor_beam.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/spider_armor.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach_armor.dm
  code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/build_a_drone.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/turrets.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/special.dm
  sojourn-station.dme
Labels: Enhancement, Bug-Fix

#3673 newsardical
  code/modules/modular_computers/file_system/news_article.dm
  news_articles/kros_news_ii.html
Labels: Documentation

#3665 Adds the prefixes to mobs
  code/__DEFINES/maths.dm
  code/__DEFINES/misc.dm
  code/datums/stat_modifiers/mob_modifiers.dm
  code/datums/stat_modifiers/modifiers/health.dm
  code/datums/stat_modifiers/modifiers/mob/damage.dm
  code/datums/stat_modifiers/modifiers/mob/speed.dm
  code/datums/stat_modifiers/modifiers/mob/superior/armor.dm
  code/datums/stat_modifiers/modifiers/mob/superior/ranged/ranged_modifiers.dm
  code/datums/stat_modifiers/modifiers/mob/superior/roach_modifiers.dm
  code/datums/stat_modifiers/modifiers/mob/superior/robot_modifiers.dm
  code/datums/stat_modifiers/modifiers/mob/superior/special/special_modifiers.dm
  code/datums/stat_modifiers/modifiers/mob/superior/spider_modifiers.dm
  code/datums/stat_modifiers/modifiers/mob/superior/superior_modifiers.dm
  code/datums/stat_modifiers/stat_modifier.dm
  code/datums/stat_modifiers/superior_modifier_defines.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/superior_animal/drone/parts/parts.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/robots/build_a_drone/build_a_drone.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/greyson.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/custodian.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/mechs.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/roomba.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/turrets.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  sojourn-station.dme
Labels: New Content

#3676 Blobbuff
  code/game/gamemodes/events/blob.dm
  code/modules/reagents/reagents/dispenser.dm
Labels: Enhancement, Bug-Fix, Balance

#3675 Siezed Access
  code/game/objects/items/weapons/secdocs.dm
  icons/obj/oddities.dmi
Labels: Nuclear Option

#3680 Fixes a prefix
  code/datums/stat_modifiers/modifiers/mob/superior/ranged/ranged_modifiers.dm
Labels: Bug-Fix

#3677 Various fixes.
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/materials/material_sheets.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
Labels: Bug-Fix

#3682 Bounty and balance
  code/datums/autolathe/guns.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/boltgun/armstrong.dm
  code/modules/projectiles/guns/projectile/boltgun/mares_leg.dm
  icons/obj/guns/projectile/bounty.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#3683 Fixes mobs attacking mechs.
  code/modules/mob/living/carbon/superior_animal/ai.dm
Labels: Bug-Fix

#3684 bounty icon fix
  icons/obj/guns/projectile/bounty.dmi
Labels: Bug-Fix, Sprite Work

#3670 Medical Perk-Checking
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagents/stims.dm
  code/modules/surgery/organic_damage.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/surgery_ui.dm
Labels: Enhancement, Balance

#3685 major fix
  code/controllers/subsystems/trade.dm
Labels: Bug-Fix

#3689 More TT adjustments
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
Labels: Balance

#3686 progress
  code/__DEFINES/mob_species_forms.dm
  code/datums/perks/racial.dm
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/akila.dm
  code/modules/mob/living/carbon/human/species/station/chtmant.dm
  code/modules/mob/living/carbon/human/species/station/cindarite.dm
  code/modules/mob/living/carbon/human/species/station/folken.dm
  code/modules/mob/living/carbon/human/species/station/fpbs.dm
  code/modules/mob/living/carbon/human/species/station/human.dm
  code/modules/mob/living/carbon/human/species/station/kriosan.dm
  code/modules/mob/living/carbon/human/species/station/marqua.dm
  code/modules/mob/living/carbon/human/species/station/mycus.dm
  code/modules/mob/living/carbon/human/species/station/naramad.dm
  code/modules/mob/living/carbon/human/species/station/opifex.dm
  code/modules/mob/living/carbon/human/species/station/sablekyne.dm
  code/modules/mob/living/carbon/human/species/station/slime.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/organ_icon.dm
  code/modules/organs/internal/slime.dm
  code/modules/sprite_accessories/_accessory_hair.dm
  sojourn-station.dme
Labels: Skill-Issue | Salt PR

#3693 Tesla turret.
  code/game/machinery/tesla_turret.dm
Labels: Skill-Issue | Salt PR

#3690 Ports bits of aurora atmos to vastly optimize c_airblock.
  code/ATMOSPHERICS/_atmos_setup.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/ATMOSPHERICS/datum_pipeline.dm
  code/ZAS/Airflow.dm
  code/ZAS/Atom.dm
  code/ZAS/ConnectionGroup.dm
  code/ZAS/ConnectionManager.dm
  code/ZAS/Controller.dm
  code/ZAS/Debug.dm
  code/ZAS/Diagnostic.dm
  code/ZAS/Fire.dm
  code/ZAS/Plasma.dm
  code/ZAS/Turf.dm
  code/ZAS/Variable Settings.dm
  code/ZAS/Zone.dm
  code/__DEFINES/ZAS.dm
  code/__DEFINES/_macros.dm
  code/__DEFINES/atmos.dm
  code/__DEFINES/colors.dm
  code/__DEFINES/machinery.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/logging.dm
  code/__HELPERS/sorting/cmp.dm
  code/__HELPERS/type2type.dm
  code/_macros.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/processing/airflow.dm
  code/game/gamemodes/events/blob.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/machinery.dm
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/window.dm
  code/game/shuttle_engines.dm
  code/game/sound.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/turf.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/maps/tg/map_template.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/power/powernet.dm
  code/modules/shieldgen/emergency_shield.dm
  code/modules/shieldgen/energy_field.dm
  code/modules/xgm/xgm_gas_data.dm
  code/modules/xgm/xgm_gas_mixture.dm
  sojourn-station.dme
Labels: Enhancement

#3679 SIGNIFICANTLY buffs c20r and akl reavers (see inside for reasoning)
  code/game/objects/items.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/random/guns.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/projectile/beams.dm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_River_To_Swamp.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian1.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian2.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian3.dmm
Labels: Balance

#3699 Fixes reagent check in trade program
  code/controllers/subsystems/trade.dm
Labels: Bug-Fix

#3700 Fixes a bad flare inbalance
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
Labels: Balance

#3698 red suit and welder mask
  code/game/machinery/vendor/misc_vendors.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/inventory/head/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work

#3695 Heroism is accessible. Happiness is more difficult.
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  icons/obj/guns/projectile/heroic.dmi
  icons/obj/guns/projectile/tk.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sound/weapons/guns/fire/NM_PARA.ogg
  sound/weapons/guns/fire/heroic_fire.ogg
  sound/weapons/guns/fire/silenced_mg.ogg
  sound/weapons/guns/misc/trigger_fail.ogg
Labels: Balance, Sprite Work

#3696 Makes voidwolf reavers flash immune
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
Labels: Balance

#3487 Add a ranged ameridian golem
  code/game/objects/items/weapons/material/shards.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/sonic_fence.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_shooter.dm
  code/modules/projectiles/guns/ameridian.dm
  code/modules/projectiles/projectile/ameridian.dm
  sojourn-station.dme
Labels: New Content

#3702 Robotic Self Surgery Adjustment
  code/modules/surgery/surgery.dm
Labels: Balance

#3674 The Armor_Overpentration Revolution & Its Consequences
  code/modules/mob/living/living_defense.dm
Labels: Balance

#3704 I hate balance
  code/game/objects/items/weapons/tools/mods/_defines.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/objs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/ameridian.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/hydrogen.dm
  code/modules/projectiles/projectile/plasma.dm
  code/modules/projectiles/projectile/plasma_aoe.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  nano/templates/weapon_stats.tmpl
Labels: Enhancement, Bug-Fix, Balance

#3705 Some trade and ammo fixes
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/modules/clothing/masks/breath.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
Labels: Bug-Fix, Balance

#3708 Reduces stockparts and stuff
  code/controllers/subsystems/trade.dm
  code/game/objects/items/weapons/stock_parts.dm
Labels: Balance

#3710 bounty icon fix
  icons/obj/guns/projectile/bounty.dmi
Labels: Sprite Work

#3709 I hate icon code!I hate icon code!I hate icon code!
  code/game/objects/items/weapons/storage.dm
  code/game/objects/items/weapons/storage/judgement_sheath.dm
  code/modules/clothing/clothing.dm
  icons/inventory/belt/mob.dmi
  icons/inventory/on_suit/mob.dmi
  icons/obj/sheath.dmi
Labels: Bug-Fix, Balance, Sprite Work

#3713 Fixes handmade stripper clip crafting datum bad pathing
  code/datums/craft/recipes/guns.dm
Labels: Bug-Fix

#3714 I HATE LIVERMED, I HATE LIVERMED, I HATE LIVERMED!!!
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Balance

#3718 Bullet balance
  code/modules/mob/living/living_defense.dm
Labels: Balance

#3720 Fixes pve multyplier and gun mod descs
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
Labels: Bug-Fix

#3719 knight -> hussar
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Sprite Work

#3722 New vending machine wire hacking minigame
  code/datums/wires/vending.dm
Labels: Enhancement, New Content

#3721 Adds psy damage handling to human mobs
  code/__DEFINES/damage_organs.dm
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Enhancement

#3723 Adds 2 alt titles for Trauma Team
  code/game/jobs/job/medical.dm
Labels: Enhancement

#3724 fixes some rig hats
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Bug-Fix

#3728 adds the artemis dart gun to SI
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/illegal.dm
  icons/obj/guns/projectile/dartgun.dmi
  nano/css/shared.css
  nano/images/science.png
Labels: Content

#3726 more bullet sprites
  code/modules/projectiles/projectile/bullettypes.dm
  icons/obj/projectiles.dmi
Labels: Sprite Work

#3729 Cog draining bad
  code/modules/psionics/psionic_items/psi_armor.dm
Labels: Bug-Fix

#3730 removes hivelord species form
  code/__DEFINES/mob_species_forms.dm
  sojourn-station.dme
Labels: Bug-Fix

#3731 Splashing Darts
  code/game/objects/effects/effect_system.dm
  code/modules/projectiles/guns/projectile/dartgun.dm
Labels: Enhancement

#3732 NSA lower threshold balance
  code/modules/reagents/metabolism.dm
Labels: Balance

#3733 blackshield maska
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/modules/clothing/head/helmet.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/obj/rig_modules.dmi
Labels: Bug-Fix, Balance, Sprite Work

#3736 Marshal Alternative Headset
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/chameleon.dm
  icons/inventory/ears/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/obj/radio.dmi
Labels: Sprite Work

#3737 maska and tree of dog
  code/game/machinery/atmoalter/scrubber.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Content

#3735 Renames & Overhauls Trauma Team Looks
  code/__DEFINES/jobs.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/setup_option/core_implants.dm
  code/game/jobs/department.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/jobs.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/multiz/map_data.dm
  code/modules/tips_and_tricks/jobs.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Balance, Sprite Work
