Repository sojourn-13/sojourn-station, pull requests merged in 2022-02, with the labels that each got.

#2687 Ai law 2
  code/datums/ai/ai_law_sets.dm
  code/game/objects/items/weapons/AI_modules.dm
Labels: Enhancement, Help Wanted

#2690 chemdispender cleaning and and stat requirements
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
Labels: Bug-Fix, Balance

#2691 Gives Opifex two new mask
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/masks/gasmask.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
Labels: Enhancement, Content, Sprite Work

#2692 gives spear an new sprite
  icons/inventory/back/mob.dmi
  icons/inventory/on_suit/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: Sprite Work, Good-To-Merge

#2693 Moretradeports
  code/__DEFINES/trade.dm
  code/controllers/subsystems/trade.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advtechno.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/cybernetics.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
  code/modules/trade/datums/trade_stations_presets/_example.dm
  nano/templates/trade.tmpl
  sojourn-station.dme
Labels: Documentation, Enhancement, Bug-Fix, Content, Balance, Good-To-Merge

#2696 Marshal buffs
  code/datums/autolathe/circuits.dm
  code/game/machinery/autolathe/nanite_reconstitution_apparatus.dm
  code/modules/scrap/oldificator.dm
  icons/obj/machines/nanite_reconstitution_apparatus.dmi
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  nano/templates/nanite_reconstitution_apparatus.tmpl
  nano/templates/nanite_reconstitution_apparatus_materials.tmpl
  nano/templates/nanite_reconstitution_apparatus_reagents.tmpl
  sojourn-station.dme
Labels: Enhancement, New Content, Balance, Sprite Work, Good-To-Merge

#2698 Fel is best
  code/modules/telesci/relay.dm
  code/modules/telesci/telepads.dm
  code/modules/telesci/teleporter_blocker.dm
  code/modules/telesci/telesci_computer.dm
  icons/obj/telescience.dmi
  sound/effects/telesci_inhibitor_alarm.ogg
  sound/effects/telesci_ping.ogg
  sound/effects/telesci_process.ogg
  sound/effects/telesci_sparkles.ogg
Labels: Bug-Fix, Content, Sprite Work, Sound Addition

#2700 fixes master
  code/modules/clothing/masks/gasmask.dm
Labels: Bug-Fix, Good-To-Merge

#2702 Siegs fix
  code/game/machinery/autolathe/nanite_reconstitution_apparatus.dm
Labels: Bug-Fix, Balance

#2704 Fix opifix mask not appearing on xenowear
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
Labels: Bug-Fix, Good-To-Merge

#2705 Lowers drone costs
  code/datums/craft/recipes/robot.dm
Labels: Balance

#2706 new church guns :D
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/projectiles/guns/energy/antebellum.dm
  code/modules/projectiles/guns/energy/carpediem.dm
  code/modules/projectiles/guns/energy/cog.dm
  code/modules/projectiles/guns/energy/concilium.dm
  code/modules/projectiles/guns/energy/egun.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  icons/obj/guns/energy/antebellum.dmi
  icons/obj/guns/energy/carpediem.dmi
  icons/obj/guns/energy/concilium.dmi
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Content, Balance, Sprite Work

#2701 mico-optimation - Trade ships
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
Labels: Enhancement

#2707 Makes master work
  code/game/machinery/autolathe/nanite_reconstitution_apparatus.dm
Labels: Bug-Fix, Good-To-Merge

#2708 fixes broken icon
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/cassad.dm
  code/modules/projectiles/guns/energy/cog.dm
  code/modules/projectiles/guns/energy/concilium.dm
  code/modules/projectiles/guns/energy/ionrifle.dm
  icons/obj/guns/energy/cassad.dmi
  icons/obj/guns/energy/cog.dmi
  icons/obj/guns/energy/cog_alt.dmi
  icons/obj/guns/energy/iongun.dmi
Labels: Bug-Fix, Sprite Work, Good-To-Merge, Skill-Issue | Salt PR

#2709 Nanogate Overhaul
  code/__DEFINES/misc.dm
  code/controllers/subsystems/ticker.dm
  code/datums/perks/nanogate.dm
  code/modules/genetics/creatures/wasonce.dm
  code/modules/genetics/genetics.dm
  code/modules/genetics/mutations/barotrauma.dm
  code/modules/genetics/mutations/bottomless_belly.dm
  code/modules/genetics/mutations/cat_eyes.dm
  code/modules/genetics/mutations/echolocation.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/modular_computers/NTNet/emails/email_account.dm
  code/modules/nanogate/nanogate.dm
  code/modules/nanogate/nanogate_powers.dm
  code/modules/nanogate/powers/nanobot.dm
  code/modules/nanogate/powers/user.dm
  code/modules/organs/internal/nanogate.dm
  code/modules/organs/organ.dm
  code/modules/psionics/psion.dm
Labels: Documentation, Enhancement, New Content, Bug-Fix, Content, Balance

#2711 Fix nanite ammo
  code/datums/perks/nanogate.dm
Labels: Bug-Fix

#2712 [VANITY] Gives more tribal clothing to xeno-wear
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work

#2718 maybe fixes human tags
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/projectiles/guns/energy/carpediem.dm
  icons/obj/guns/energy/carpediem.dmi
  maps/dungeons/crawler/crawler.dm
Labels: Bug-Fix, Balance

#2721 Card Carp Update
  code/game/machinery/vendor/misc_vendors.dm
  modular_sojourn/cardgame_2.dm
  modular_sojourn/cardgame_sprites.dmi
Labels: Enhancement, Content, Balance, Sprite Work, Good-To-Merge, Game Breaking

#2720 Fixes viewing chemicals + Dependency update
  code/game/atoms.dm
  dependencies.sh
Labels: Bug-Fix, Good-To-Merge

#2722 slight fix but not a complete correct
  code/__HELPERS/game.dm
  code/modules/mob/mob.dm
Labels: Help Wanted, Wont fix, Bug-Fix, Good-To-Merge, Skill-Issue | Salt PR

#2723 Fix visible_message function
  code/__DEFINES/lighting.dm
  code/__HELPERS/game.dm
  code/__HELPERS/unsorted.dm
  code/datums/perks/oddity.dm
  code/game/atoms.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/power.dm
  code/modules/modular_computers/file_system/program_events.dm
Labels: Bug-Fix, Good-To-Merge

#2725 Fixes MC
  code/controllers/subsystem.dm
Labels: Enhancement, Bug-Fix, Good-To-Merge

#2726 Bundled fixes and new content (Card carp, mods, and mechs!)
  code/game/machinery/vendor/misc_vendors.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/mob/living/carbon/superior_animal/human/human.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/greyson.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoMega.dm
  code/modules/projectiles/guns/mods/mods.dm
  icons/obj/storage/cases.dmi
  modular_sojourn/cardgame_2.dm
  modular_sojourn/cardgame_sprites.dmi
Labels: Enhancement, Bug-Fix, Balance

#2717 New Alt-Titles[Need Feedback]
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Help Wanted

#2695 new BDU suits.
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Enhancement, New Content, Content, Sprite Work, Good-To-Merge

#2727 whoops!
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/chitter1.ogg
  sound/voice/croak.ogg
  sound/voice/croon1.ogg
  sound/voice/croon2.ogg
  sound/voice/lowwarble.ogg
  sound/voice/moo1.ogg
  sound/voice/warble.ogg
Labels: Content

#2731 more grayson tweaks
  maps/submaps/dungeon_rooms/rooms/corner_energy_SE.dmm
  maps/submaps/dungeon_rooms/rooms/droppod.dmm
  maps/submaps/dungeon_rooms/rooms/room_templates.dm
  maps/submaps/dungeon_rooms/rooms/shootingrange.dmm
  maps/submaps/dungeon_rooms/rooms/surgery.dmm
Labels: Enhancement, Bug-Fix, Balance

#2728 Bullet balance changes.
  code/modules/clothing/under/miscellaneous.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#2736 Attempt to fix reader.dm CI fails
  code/modules/maps/tg/reader.dm
Labels: Bug-Fix

#2735 New point miner program
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/file_system/programs/research/passive_pointes.dm
  code/modules/research/designs/computer_parts.dm
  code/modules/research/nodes/biotech.dm
  code/modules/research/nodes/engineering.dm
  icons/obj/modular_pda.dmi
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  nano/templates/mpc_point_miner.tmpl
  sojourn-station.dme
Labels: Enhancement, Content, Balance

#2737 im a dumb
  code/modules/modular_computers/file_system/programs/research/passive_pointes.dm
Labels: Content, Skill-Issue | Salt PR

#2741 List of Fixes
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/nanogate/nanogate_powers.dm
Labels: Bug-Fix, Good-To-Merge

#2739 trade station fixes and balance
  code/controllers/subsystems/trade.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
Labels: Enhancement, Bug-Fix, Balance

#2743 New cargo trade beacon, and better balace
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, Balance

#2747 Plastic flaps crafting and destuction
  code/datums/craft/recipes/misc.dm
  code/game/supplyshuttle.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Content, Balance

#2734 Frog Helmet 2.0 and Bandages
  code/datums/underwear/top.dm
  code/datums/underwear/undershirt.dm
  code/modules/clothing/head/helmet.dm
  code/modules/sprite_accessories/_accessory_marking.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/underwear/mob.dmi
  icons/mob/human_races/markings.dmi
Labels: Content, Sprite Work

#2748 Nade and AoE plasma
  code/datums/autolathe/biomatter.dm
  code/datums/autolathe/guns.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/empulse.dm
  code/game/objects/heatwave.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/items/weapons/grenades/heatwave.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/projectile/plasma_aoe.dm
  icons/obj/grenade.dmi
  sojourn-station.dme
Labels: Enhancement, Content, Balance, Sprite Work

#2752 More eris ports and misc fixes
  code/game/machinery/vendor/misc_vendors.dm
  code/modules/clothing/spacesuits/rig/rig_wiring.dm
  code/modules/games/cardemon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_grab_specials.dm
  code/modules/projectiles/gun.dm
Labels: Bug-Fix, Balance

#2761 name fixes and armor to its own mods
  code/game/objects/items/weapons/tools/mods/armor_mods.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/projectiles/guns/mods/mods.dm
  sojourn-station.dme
Labels: Bug-Fix

#2763 Tesla turret overhaul
  code/game/machinery/tesla_turret.dm
  code/game/objects/items/weapons/circuitboards/machinery/tesla_turret.dm
  icons/obj/tesla_turret.dmi
  nano/templates/tesla_turret_control.tmpl
Labels: Enhancement, DO NOT MERGE, Bug-Fix, Content, Balance, Sprite Work

#2764 Prefixes
  code/modules/mob/living/carbon/human/human.dm
Labels: Question, Content

#2768 remoal of blackshield medical gear
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance

#2772 Medical hcases for medcal and hotfix for church kit
  code/datums/outfits/jobs/medical.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/hardcases.dm
Labels: Bug-Fix, Balance

#2773 Makes radio command colour on darkmode less same as admin message
  code/modules/goonchat/browserassets/css/browserOutput.css
Labels: Skill-Issue | Salt PR

#2771 Small house in the woods
  maps/DeepForest/map/_Deep_Forest.dmm
Labels: Enhancement

#2774 new trade ships and some better trades
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/economy/price_list.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advtechno.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Content, Balance

#2776 Tesla turret rework part 2
  code/game/machinery/tesla_turret.dm
  nano/templates/tesla_turret_control.tmpl
Labels: Bug-Fix, Good-To-Merge

#2777 masterfix remoes obsessive and hardcase fix
  code/datums/objective/individual_objective/common.dm
  code/game/machinery/tesla_turret.dm
  code/game/objects/items/weapons/circuitboards/machinery/tesla_turret.dm
  code/game/objects/items/weapons/storage/hardcases.dm
Labels: Bug-Fix, Good-To-Merge

#2775 GM disk
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#2778 Eris porst mark IIV
  code/datums/autolathe/guns.dm
  code/datums/wires/wires.dm
  code/game/machinery/doors/firedoor.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/tools/mods/_defines.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/random/guns.dm
  code/game/objects/structures/low_wall.dm
  code/modules/mob/living/recoil.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/chaingun.dm
  code/modules/projectiles/guns/projectile/automatic/dp.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/ppsh.dm
  code/modules/projectiles/guns/projectile/boltgun/anti_materiel_sniper.dm
  code/modules/projectiles/guns/projectile/boltgun/scout.dm
  code/modules/tables/interactions.dm
  code/modules/tips_and_tricks/gameplay.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  icons/obj/guns/mods.dmi
Labels: Enhancement, Bug-Fix, Content, Balance, Sprite Work

#2713 Map in the Antimatter Engine
  code/modules/cargo/packs_engineering.dm
  code/modules/power/antimatter/control.dm
  code/modules/power/antimatter/shielding.dm
  icons/obj/machines/antimatter.dmi
  maps/Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Content

#2785 Fixes and rebalances
  code/controllers/subsystems/trade.dm
  code/datums/setup_option/backgrounds/origin_homeworld.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/game/objects/items/weapons/tools/wrenches.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/reagents/food-Drinks.dm
Labels: Enhancement, Bug-Fix, Balance

#2784 fixes some easy linter errors
  code/controllers/subsystems/chat.dm
  code/datums/perks/job.dm
  code/game/dna/genes/powers.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/modules/maps/swapmaps.dm
  sojourn-station.dme
Labels: Bug-Fix

#2783 better sorting, new side decks and betterness
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  modular_sojourn/cardgame_2/cardgame_2.dm
  modular_sojourn/cardgame_2/cardgame_sprites.dmi
  modular_sojourn/cardgame_2/cardholder.dm
  modular_sojourn/cardgame_2/cardpacks_and_spawner.dm
  modular_sojourn/cardgame_2/items.dm
  modular_sojourn/cardgame_sprites.dmi
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance, Sprite Work

#2782 Prevent testing Engines from announcing their startup and shutdown.
  code/modules/power/antimatter/control.dm
Labels: Bug-Fix

#2781 Condences!
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/command.dm
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/storage.dm
Labels: Enhancement, Bug-Fix, Balance

#2780 Marshal buffs
  code/datums/autolathe/ammo.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Enhancement, Content, Balance

#2779 New ship and missing drinks
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
  sojourn-station.dme
Labels: Enhancement, Content

#2787 Killer Tomatoes
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/trays/tray.dm
Labels: Enhancement, Bug-Fix

#2789 Fixes some trade ship marketing
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
Labels: Bug-Fix, Balance

#2791 some more bracing
  code/game/machinery/deployable.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/low_wall.dm
  modular_sojourn/shields.dm
Labels: Bug-Fix, Balance

#2790 talking/controle spider fix and bomb spider fix
  code/game/objects/items/weapons/implant/implants/carrion/control_spider.dm
  code/game/objects/items/weapons/implant/implants/carrion/explosive_spider.dm
  code/game/objects/items/weapons/implant/implants/carrion/talking_spider.dm
Labels: Bug-Fix, Balance

#2798 Plant Tweaking
  code/controllers/subsystems/migration.dm
  code/game/objects/effects/spawners/maintshroom.dm
  code/game/objects/random/flora.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/core_implant/cruciform/machinery/wall_obelisk.dm
  code/modules/core_implant/cruciform/upgrades.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/spreading/spacevines.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/hydroponics/trays/tray.dm
Labels: Bug-Fix, Balance

#2799 Rise of the Most Unpopular PR of All Time 2: Revengeance Rising Revel…
  code/datums/perks/job.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/vendor_loot_boxes.dm
  code/game/objects/items/weapons/tools/mods/_defines.dm
  code/game/objects/random/medicine.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/random_map/drop/drop_types.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/surgery/surgery.dm
Labels: Wont fix

#2800 Make robots superior mobs immune to heat & cold
  code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
Labels: Bug-Fix

#2807 Add bulk ointment & gauze
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Enhancement

#2808 docs and wine
  code/game/machinery/autodoc.dm
  code/game/objects/items/weapons/circuitboards/machinery/medical.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/biotech.dm
Labels: Bug-Fix

#2806 Medical fixes and tweaks
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/surgery/organic.dm
  code/modules/surgery/surgery_ui.dm
Labels: Bug-Fix, Balance

#2811 More ATK/Surgery fixes
  code/game/objects/items/stacks/medical.dm
  code/modules/surgery/robotic.dm
  code/modules/surgery/surgery.dm
Labels: Bug-Fix

#2810 Hopefully the last ATK PR...
  code/modules/surgery/surgery.dm
Labels: Balance

#2809 Move the Ossisine OD effect to its OD proc.
  code/modules/reagents/reagents/medicine.dm
Labels: Documentation, Good Issue Report
