Repository sojourn-13/sojourn-station, pull requests merged in 2022-10, with the labels that each got.

#3979 New energy spear and eblades crafting
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/melee/energy.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: Balance, Sprite Work

#3982 genetor fix and turret fix
  code/game/machinery/os_portable_turret.dm
  code/modules/power/os_port_gen.dm
  nano/templates/os_generator.tmpl
Labels: Bug-Fix

#3984 SI can make SI gunmods
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
Labels: Balance

#3983 coras want for mobs
  code/modules/genetics/creatures/wasonce.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tazntz.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/toxins.dm
  icons/mob/mobs-roach.dmi
  icons/mob/mobs-voxy.dmi
  modular_sojourn/random_robot.dmi
  sojourn-station.dme
Labels: Enhancement, Bug-Fix

#3988 some ploge tweaks
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm
Labels: Balance

#3989 turns on solgov mobs
  sojourn-station.dme
Labels: Skill-Issue | Salt PR

#3991 Job Alternative Names Updates
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Enhancement, Content

#3993 "Marshal Civil Servant"
  code/game/jobs/job/security.dm
Labels: Skill-Issue | Salt PR

#3994 Removes
  code/datums/perks/nanogate.dm
  code/game/objects/random/guns.dm
  code/modules/nanogate/powers/user.dm
  code/modules/projectiles/guns/mods/mods.dm
Labels: Balance

#3995 Sol marines
  code/modules/mob/living/carbon/superior_animal/human/subtype/solgov/marines.dm
  code/modules/projectiles/ammunition/bullets.dm
Labels: Bug-Fix, Balance

#3998 Excubitor Halberd Cannon
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/modules/projectiles/guns/energy/excubitor.dm
  icons/obj/guns/energy/excubitor.dmi
Labels: Help Wanted, New Content, Content, Sprite Work

#4000 master fix
  sojourn-station.dme
Labels: Bug-Fix

#3997 Organlab improvement
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3996 wire and flyers
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3999 Lodge Redo
  maps/_DeepForest/map/_River_Forest.dmm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/_HunterLodge/map/_Hunting_Lodge_guidesu.dmm
  maps/__Nadezhda/nadezhda.dm
Labels: Content, Map

#4004 Lodge Spawn Fixes
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Bug-Fix

#4005 i hate maps
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Bug-Fix

#4007 more lighting tweaks
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#4010 Excubitor Sprite Fixes
  icons/obj/guns/energy/excubitor.dmi
Labels: Sprite Work

#4008 Borers now 'talk' outside of hosts
  code/modules/mob/living/captive_brain.dm
  code/modules/mob/living/simple_animal/borer/say.dm
  sojourn-station.dme
Labels: Enhancement

#4011 miner ammo fix
  code/modules/projectiles/guns/_projectile.dm
Labels: Bug-Fix

#4012 shadow runtime fix
  code/modules/multiz/shadow.dm
Labels: Bug-Fix

#4014 Lodge wiring and soap
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Bug-Fix

#4015 Underwear Clothing: Bored at work edition
  code/datums/underwear/bottom.dm
  code/datums/underwear/socks.dm
  code/datums/underwear/undershirt.dm
  icons/mob/human_races/underwear.dmi
Labels: Sprite Work

#4016 STS rebalances and fixes
  code/datums/craft/recipes/guns.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  icons/obj/guns/projectile/sawnoff/sts35.dmi
Labels: Bug-Fix, Balance, Sprite Work

#4017 TT fix
  code/game/jobs/job/medical.dm
Labels: Bug-Fix

#4019 more lifeline fixes and shirts
  code/__DEFINES/jobs.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  icons/inventory/underwear/mob.dmi
Labels: Bug-Fix

#4022 small crafting icon fix
  icons/obj/guns/projectile/sawnoff/sts35.dmi
Labels: Bug-Fix

#4021 Adjustments to borer
  code/game/gamemodes/roleset/simple.dm
  code/modules/ghosttrap/trap.dm
  code/modules/mob/holder.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/living/carbon/human/death.dm
  modular_sojourn/Borers/__ADMIN SHIT/antagonist.dm
  modular_sojourn/Borers/__ADMIN SHIT/ghost_trap.dm
  modular_sojourn/Borers/__ADMIN SHIT/holder.dm
  modular_sojourn/Borers/__ADMIN SHIT/language.dm
  modular_sojourn/Borers/__ADMIN SHIT/objective.dm
  modular_sojourn/Borers/__ADMIN SHIT/organs.dm
  modular_sojourn/Borers/__ADMIN SHIT/roleset.dm
  modular_sojourn/Borers/borer.dm
  modular_sojourn/Borers/borer_powers.dm
  modular_sojourn/Borers/carbon_powers.dm
  modular_sojourn/Borers/say.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance

#4024 cryo fixes
  code/game/machinery/cryopod.dm
  code/modules/mob/mob_helpers.dm
Labels: Bug-Fix

#4025 Cryotweaks
  code/modules/mob/mob_helpers.dm
Labels: Bug-Fix

#4026 guns and robo fixes
  code/datums/outfits/jobs/off_colony.dm
  code/datums/setup_option/core_implants.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/random/guns.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
Labels: Bug-Fix, Balance

#4027 Kitchen Freezer Area Fix
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#4028 Alldaheris
  code/datums/contract.dm
  code/datums/craft/recipes/clothing.dm
  code/datums/craft/recipes/weapon.dm
  code/datums/datum_click_handlers.dm
  code/datums/objective/objective.dm
  code/datums/objective/rev.dm
  code/defines/procs/announce.dm
  code/game/antagonist/station/revolutionary/excel_faction.dm
  code/game/machinery/doors/holy_door.dm
  code/game/objects/heatwave.dm
  code/game/objects/items/weapons/implant/implanter.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/clothing/gloves/knuckledusters.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/resist.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
  icons/inventory/back/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/on_suit/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance, Sprite Work

#4030 two fixes
  code/game/objects/structures/burrows.dm
  code/modules/clothing/gloves/knuckledusters.dm
Labels: Bug-Fix

#4034 death to subtle
  code/modules/mob/say.dm
Labels: Wont fix, Skill-Issue | Salt PR, Removal

#4033 New Language Basics (Akula, Folken / Mycus, Marqua)
  code/__DEFINES/chemistry.dm
  code/__DEFINES/species_languages.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/mob/language/outsider.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/stylesheet.dm
Labels: New Content, Content

#4009 slowdown!
  code/game/objects/items/devices/organ_module/passive/muscle.dm
  code/modules/aberrants/organs/reagents/hormones.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/organs/external/_external.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/race.dm
  code/modules/reagents/reagents/stims.dm
Labels: DO NOT MERGE, Balance, Discussion Needed

#4035 humans get 3 langs and code cleaning
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/datums/perks/racial.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Documentation, Balance

#4018 Staircase-Church remap
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#4036 small map tweaks
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#4037 doble var trouble
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Bug-Fix

#4038 buffs church nullifer and nerfs organ sizes
  code/modules/core_implant/cruciform/machinery/onlooker.dm
  code/modules/organs/internal/muscles.dm
  code/modules/organs/internal/nerves.dm
  code/modules/organs/organ_description.dm
  icons/obj/machines/church_looker.dmi
Labels: Balance, Sprite Work

#4039 Makes Huntmaster have the perks of hunter and herbalist.
  code/game/jobs/job/offcolony.dm
Labels: Bug-Fix

#4041 Fixing new church biogen
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#4040 Alchemy burner touchups
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  icons/obj/tools.dmi
Labels: Bug-Fix

#4042 THE DRIPPENING: More than just drip, less than a flood
  code/datums/outfits/jobs/medical.dm
  code/game/machinery/vendor/cloathing.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/balaclava.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/casual.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/suits.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/inventory/accessory/mob.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/vending.dmi
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Sprite Work, Map

#4032 Lodge Solar Array Revamp
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Map

#3969 Proto23
  code/datums/objective/individual_objective/individual_objective.dm
  code/game/machinery/vending.dm
  code/game/machinery/vendor/integrated_electronics.dm
  code/game/machinery/vendor/medical_vendors.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/machinery/vendor/technologies.dm
  code/game/machinery/vendor/tool_vendors.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/structures/flora/flora.dm
  code/modules/genetics/mutations/bottomless_belly.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/reagents/reagents/stims.dm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/human_helper.dm
  modular_sojourn/task_master/task_helpers.dm
  modular_sojourn/task_master/tasks.dm
  sojourn-station.dme
Labels: New Content, Content

#4044 Drip PR HOTFIX: No more commando colonists
  code/game/machinery/vendor/cloathing.dm
  code/game/objects/random/cloth.dm
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/casual.dm
  code/modules/clothing/under/suits.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/inventory/ears/mob.dmi
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Bug-Fix, Sprite Work

#4047 More tentacle hairs
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/mob/human_races/species/human/hair.dmi
Labels: Sprite Work

#4046 Hey! Taxi!
  code/datums/perks/job.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/game/machinery/vendor/cloathing.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/storage/costume.dm
  code/game/objects/random/cloth.dm
  code/game/objects/random/toys.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/clothing/head/costume.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/pants.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/toy.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sound/sanity/nyah.ogg
Labels: Bug-Fix, Balance, Sprite Work

#4048 Ticket changes and fax stuff
  code/controllers/subsystems/tickets/tickets.dm
  code/game/verbs/who.dm
  code/modules/paperwork/faxmachine.dm
Labels: Wont fix, Bug-Fix, Skill-Issue | Salt PR

#4050 Replaces poncho sprites
  icons/inventory/accessory/mob.dmi
Labels: Sprite Work

#4051 Miko dress and fix for pentatails
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/sprite_accessory/tails.dmi
Labels: Sprite Work

#4052 faxes and maybe messages
  code/controllers/subsystems/tickets/tickets.dm
  code/modules/admin/admin.dm
  code/modules/paperwork/faxmachine.dm
Labels: Bug-Fix

#4056 misc. bugfixes to get them off the error list
  code/ATMOSPHERICS/components/valve.dm
  code/ATMOSPHERICS/mainspipe.dm
  code/ATMOSPHERICS/pipes.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/type2type.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/effects/decals/contraband.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/flufftext/TextFilters.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  code/modules/organs/body_modifications.dm
  code/modules/power/singularity/singularity.dm
  code/modules/shuttles/shuttle.dm
  sojourn-station.dme
Labels: Enhancement, Bug-Fix

#4057 Miko dress fix
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#4058 Adds UI and verb for tasks
  code/modules/mob/living/living.dm
  nano/templates/tasks.tmpl
Labels: Enhancement

#4060 Task UI fix
  nano/templates/tasks.tmpl
Labels: Bug-Fix

#4061 Ranger Loadout & Fixes
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
Labels: Bug-Fix, Balance

#4063 egregious Church buffs
  code/modules/clothing/head/misc.dm
Labels: Balance

#4064 Fixes flying deleted bullets
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/_projectile.dm
Labels: Bug-Fix

#4065 Updates Ship Colors
  icons/turf/shuttlescience.dmi
Labels: Sprite Work

#4066 Step 1. Redefining the defines
  code/__DEFINES/_compile_helpers.dm
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/dna.dm
  code/__DEFINES/gamemode.dm
  code/__DEFINES/mobs.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/organ_module/active.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  code/game/objects/items/weapons/implant/implants/carrion/infection_spider.dm
  code/game/objects/items/weapons/implant/implants/excelsior.dm
  code/game/objects/items/weapons/implant/implants/explosive.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/admin/bluespacetech.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/glasses/welding.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/spacesuits/rig/suits/ameridian_knight.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/void/neotheology.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/external/dismemberment.dm
  code/modules/organs/external/subtypes/slime.dm
  code/modules/organs/surgery_helpers.dm
  code/modules/organs/wound.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/reagents/recipes/recipes_slime.dm
  code/modules/surgery/old_mmi.dm
  code/modules/surgery/organic.dm
  code/modules/surgery/robotic.dm
  code/modules/virus2/effect.dm
  sojourn-station.dme
Labels: Documentation
