Repository sojourn-13/sojourn-station, pull requests merged in 2022-06, with the labels that each got.

#3463 quick fix and ameridian cell
  code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
  code/modules/research/designs/cell.dm
  code/modules/research/nodes/power.dm
Labels: Bug-Fix, Balance

#3465 Optimizes mobcode by removing two calls of findtarget() on every life tick.
  code/datums/perks/racial.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/ai.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Enhancement, Balance

#3467 mobs now respect being weakend
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug-Fix

#3466 Some more Chemical things
  code/modules/reagents/machinery/alchemy.dm
  code/modules/reagents/reagents/alchemy.dm
  code/modules/reagents/recipes.dm
  code/modules/reagents/recipes/alchemy.dm
  icons/obj/chemical.dmi
  sojourn-station.dme
Labels: New Content

#3440 More Mech Weapons: The Draft Edition
  code/game/mecha/equipment/weapons/melee.dm
  code/game/mecha/equipment/weapons/ranged/bullet_weapons.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/research/designs/mecha_equipment.dm
  code/modules/research/nodes/robotics.dm
  icons/mecha/mecha_equipment.dmi
Labels: Balance, Good-To-Merge

#3475 Makes mobs properly stop following if you tell them to stop
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug-Fix

#3476 more names for damage
  code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Balance

#3478 Loot rotation and missing disks
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/game/objects/random/lathe_disks/guns.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance

#3477 Spider difficulty tweak.
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/reagents/reagents/toxins.dm
Labels: Balance

#3484 AAAAAAAAAAAAA
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug-Fix

#3482 Fixes Sanctify group
  code/modules/core_implant/cruciform/rituals/group.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Bug-Fix

#3481 simple targeting tweaks
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/lodge/lodge.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/church/types/rook.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Enhancement

#3483 Adds a new admin tool, var copies, that allow admins to copypaste var editted atoms.
  code/__DEFINES/admin.dm
  code/__DEFINES/topic.dm
  code/modules/admin/admin.dm
  code/modules/admin/view_variables/helpers.dm
  code/modules/admin/view_variables/topic.dm
Labels: Documentation, Enhancement

#3488 Adds locs to the var blacklist
  code/__DEFINES/admin.dm
Labels: Bug-Fix

#3485 More spider tweaks
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/reagents/reagents/toxins.dm
Labels: Balance

#3490 Fix an Icon of an glove
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Bug-Fix

#3492 Makes it so mobs actually use comfy_range for their targetting.
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Balance

#3494 misc fixes
  code/game/objects/items/weapons/mop.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagents/alchemy.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/scrap/oldificator.dm
Labels: Bug-Fix, Balance

#3495 More Mech Weapons: The Balance Edition
  code/game/mecha/equipment/weapons/melee.dm
  code/game/mecha/equipment/weapons/ranged/bullet_weapons.dm
Labels: Balance

#3201 bows and arrows, or How I Learnt To Stop Worrying And Love The Lodge
  code/__DEFINES/projectile_defines.dm
  code/__HELPERS/_lists.dm
  code/datums/craft/recipes/guild.dm
  code/datums/craft/recipes/guns.dm
  code/datums/craft/recipes/lodge.dm
  code/game/objects/items/animal_parts.dm
  code/game/objects/items/weapons/tools/mods/_defines.dm
  code/modules/hydroponics/grown.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/charge.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/projectile/other/bow.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullettypes.dm
  icons/obj/ammo.dmi
  icons/obj/guns/bow.dmi
  icons/obj/guns/bow_old.dmi
  icons/obj/guns/mods.dmi
  icons/obj/projectiles.dmi
  sojourn-station.dme
Labels: Enhancement, New Content, Balance, Sprite Work

#3479 Gives roaches and many swarmer types AP
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/spider_armor.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach_armor.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/emp.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
  code/modules/mob/living/living_defines.dm
Labels: Enhancement, Balance

#3469 Makes death alarms now talk on medical coms
  code/game/objects/items/weapons/implant/implants/death_alarm.dm
Labels: Balance

#3493 Adds a var to shield generators that controls if it will report it's damage or not.
  code/modules/shield_generators/shield_generator.dm
Labels: Enhancement

#3498 Marshal Disks & Small Fixes
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/specop.dm
  icons/obj/discs.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Bug-Fix, Balance, Sprite Work

#3500 Nightmare stalkers now drop chitin
  code/modules/mob/living/simple_animal/hostile/big.dm
Labels: Bug-Fix

#3502 Adds a use of comfy_distance where I should've put it before, damn it.
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Balance

#3503 Adding the Mime mask to the loadout. That's it.
  code/modules/client/preference_setup/loadout/lists/clothing.dm
Labels: Good-To-Merge

#3504 fixes bow loading ammo weirdness
  code/modules/projectiles/guns/projectile/other/bow.dm
Labels: Bug-Fix

#3505 Fixes forman armor
  code/modules/clothing/suits/armor.dm
Labels: Balance

#3506 Recoil tested hard-numbers fix
  code/modules/projectiles/gun.dm
Labels: Bug-Fix

#3507 Guncase changes
  code/datums/autolathe/security.dm
  code/datums/perks/job.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/back/mob.dmi
  icons/inventory/on_suit/mob.dmi
  icons/obj/storage/backpack.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance

#3508 Bags of Chaos!
  code/game/turfs/flooring/flooring.dm
Labels: Balance

#3510 Fixes mops for real
  code/__HELPERS/turfs.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
Labels: Bug-Fix

#3513 Revert "sawn off cogs"
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/_projectile.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/cog.dm
  icons/obj/guns/energy/obrez_retro.dmi
Labels: Skill-Issue | Salt PR

#3516 Remove not improve
  code/game/mecha/equipment/tools/ai_holder.dm
  code/game/mecha/mecha.dm
  code/game/objects/random/mecha.dm
  code/modules/research/designs/mecha_equipment.dm
  code/modules/research/nodes/robotics.dm
  sojourn-station.dme
Labels: Wont fix

#3515 Loadout guns! pew pew
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  sojourn-station.dme
Labels: Balance

#3517 Allow mechs to punch & interact with shit.
  code/game/mecha/combat/combat.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/equipment/weapons/melee.dm
  code/game/mecha/mecha.dm
  code/game/mecha/working/working.dm
  code/modules/research/designs/mecha_equipment.dm
Labels: Enhancement, Balance

#3446 Printers run dry
  code/controllers/subsystems/economy.dm
  code/game/jobs/department.dm
Labels: Documentation, Balance

#3524 WO Primary & Sky Movement
  code/datums/autolathe/guns.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/projectiles/guns/projectile/pistol/judiciary.dm
  icons/obj/guns/projectile/judiciary.dmi
  sojourn-station.dme
Labels: Balance

#3523 Blackshield Lore Errors
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
Labels: Documentation, Bug-Fix, Good-To-Merge

#3526 Better departmental accounts
  code/game/jobs/department.dm
Labels: Balance

#3525 Jumpsuit rolling
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/inventory/overlays.dmi
Labels: Enhancement

#3531 New sheep ears
  code/modules/sprite_accessories/_accessory_ears.dm
  icons/mob/sprite_accessory/ears.dmi
Labels: Sprite Work

#3533 Trade update: Papers, Please
  code/controllers/subsystems/trade.dm
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/modular_computers/file_system/programs/generic/trade_log.dm
  nano/templates/trade.tmpl
  nano/templates/trade_log.tmpl
  sojourn-station.dme
Labels: Documentation, Enhancement, New Content, Balance, Good-To-Merge

#3537 basic anti-cheat
  code/modules/core_implant/cruciform/rituals/path.dm
Labels: Bug-Fix

#3535 GOATMed Deluxe: Bigger and Baaaader
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/living.dm
Labels: Balance

#3528 Health through Stats
  code/__DEFINES/mob_stats.dm
  code/controllers/subsystems/jobs.dm
  code/controllers/subsystems/staverbs.dm
  code/datums/mob_stats.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/offcolony.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/oddities_faction.dm
  code/modules/client/preference_setup/general/07_stats.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/mob/mob.dm
  code/modules/reagents/metabolism.dm
  code/modules/sanity/inspiration_component.dm
  code/modules/sanity/sanity_mob.dm
Labels: Balance

#3538 Python Fix
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
Labels: Bug-Fix

#3539 More misc absure things
  code/__DEFINES/perks.dm
  code/__DEFINES/tools_and_qualities.dm
  code/datums/craft/recipes/alchemy.dm
  code/datums/perks/job.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/items/weapons/weldbackpack.dm
  code/modules/hydroponics/grown.dm
  code/modules/mob/mob_helpers.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagents/alchemy.dm
  code/modules/reagents/recipes/alchemy.dm
  icons/obj/hydroponics_products.dmi
  icons/obj/storage.dmi
  icons/obj/tools.dmi
  sojourn-station.dme
Labels: Enhancement

#3536 Story Teller enabled
  code/game/gamemodes/events/carp_migration.dm
  code/game/gamemodes/events/hidden_events/bluespace_rift.dm
  code/game/gamemodes/events/ion_storm.dm
  code/game/gamemodes/events/meteors.dm
  code/game/gamemodes/events/radiation_storm.dm
  code/game/gamemodes/events/rogue_drones.dm
  code/game/gamemodes/events/supply_pod.dm
  code/game/gamemodes/events/wormholes.dm
  code/game/gamemodes/storyteller.dm
Labels: Bug-Fix, Game Breaking

#3540 Fixes 10x77 Mislabel
  code/game/machinery/autolathe/fabricators.dm
Labels: Bug-Fix

#3542 Storyteller tweaks
  code/controllers/subsystems/voting/poll_types.dm
  code/game/gamemodes/events/electrical_storm.dm
  code/game/gamemodes/storyteller.dm
Labels: Balance

#3545 If a mob is dead, it will now clarify that
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug-Fix

#3543 spider tweaks and rng
  code/game/objects/effects/spiders.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/spider_armor.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
Labels: Balance

#3549 Non-contrivserah eris ports
  code/game/machinery/kitchen/gibber.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/cyberplants.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/projectiles/guns/energy.dm
  icons/obj/food.dmi
Labels: Bug-Fix, Content, Balance

#3546 more anticheat and icon fix
  code/modules/core_implant/cruciform/rituals/path.dm
  icons/obj/tools.dmi
Labels: Bug-Fix

#3551 exl mech fixes
  code/game/objects/effects/mines.dm
  code/game/objects/items/weapons/emp_mine.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  icons/obj/lighting.dmi
Labels: Bug-Fix, Balance, Sprite Work

#3550 Hivemind additons
  code/game/gamemodes/events/hivemind_controller.dm
  code/modules/admin/admin_verbs.dm
  code/modules/hivemind/core.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/mobs.dm
  code/modules/hivemind/self_defense.dm
  code/modules/hivemind/wires.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
  sojourn-station.dme
Labels: Documentation, Enhancement, New Content

#3548 Blackshield Armory Rework
  code/game/machinery/excelsior/blackshield_teleporter.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Good Issue Report, Balance, Map

#3547 Makes mobs wander a little if they can't see you.
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug-Fix, Balance

#3552 Slightly slower but more danger
  code/game/objects/effects/spiders.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/spider_armor.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach_armor.dm
Labels: Bug-Fix, Balance

#3553 Fixes numerical garb
  code/modules/clothing/suits/miscellaneous.dm
Labels: Bug-Fix, Sprite Work

#3555 church buff
  code/controllers/subsystems/jobs.dm
  code/game/gamemodes/events/hivemind_controller.dm
  code/modules/core_implant/core_implant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
Labels: Bug-Fix

#3556 Its no longer 2020
  code/game/gamemodes/events/viral_infection.dm
Labels: Skill-Issue | Salt PR

#3558 Mobs lose sight and stop trying to follow you if you break LOS. They instead follow your position. Also a few bugfixes and code improvements.
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/life.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug-Fix, Balance

#3559 Makes mobs randomly retarget, adds framework for custom mob targetting, moves superior mob vars into their own file, among other changes.
  code/__DEFINES/mobs.dm
  code/__HELPERS/_lists.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/drone/ai.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/ai.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
  code/modules/mob/living/carbon/superior_animal/roach/ai.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/friendly.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/carbon/superior_animal/vox/ai.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/ai.dm
  sojourn-station.dme
Labels: Balance

#3562 Proper Termite names
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
Labels: Bug-Fix

#3560 Hopefully Fixes Runtime
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Bug-Fix

#3564 Better balance Of story Tellers
  code/game/gamemodes/events/blob.dm
  code/game/gamemodes/events/carp_migration.dm
  code/game/gamemodes/events/electrical_storm.dm
  code/game/gamemodes/events/infestation.dm
  code/game/gamemodes/storytellers/chronicler.dm
  code/game/gamemodes/storytellers/healer.dm
  code/game/gamemodes/storytellers/jester.dm
  code/game/gamemodes/storytellers/mime.dm
  code/game/gamemodes/storytellers/sleeper.dm
  code/game/gamemodes/storytellers/warrior.dm
Labels: Balance

#3568 Ana fixes
  code/__DEFINES/mob_stats.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/oddities_faction.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/reagents/metabolism.dm
  code/modules/sanity/breakdowns.dm
Labels: Bug-Fix

#3567 THE REMAPPENING
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, New Content, Map

#3566 Potentially fixes the bug where dead mobs follow you
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
Labels: Bug-Fix

#3561 Makes pepper spiders spray pepper at enemies, and shock rock spiders shock carbons.
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/pepper.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/shocker.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/living_defines.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagents/food-Drinks.dm
  sojourn-station.dme
Labels: New Content, Balance

#3569 wires, apcs, and air
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix

#3570 Airmapfix
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3571 Map stuff by lich and catt
  code/__DEFINES/machinery.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
  maps/CEVEris/_Eris_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3574 Camaer rework
  code/__DEFINES/machinery.dm
  code/game/machinery/camera/presets.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance, Map

#3573 Brute & Burn Modifiers Rework
  code/datums/perks/job.dm
  code/datums/perks/nanogate.dm
  code/datums/perks/psionic.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/security.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/reagents/race.dm
Labels: Balance

#3572 Fixes name of the val and vin
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
Labels: Bug-Fix

#3575 lights
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3576 small tweaks
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3577 Tweaks map
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3578 patches holes
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Map

#3587 [APPROVED] Xenobio buffs & Misc map fixes
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/xenobio.dm
  code/game/objects/items/weapons/manuals.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: New Content, Bug-Fix, Good-To-Merge, Map

#3580 Return of some Health to Psionics
  code/datums/perks/psionic.dm
Labels: Balance

#3583 LightPink Slime Reactions
  code/game/objects/items/weapons/manuals.dm
  code/modules/reagents/recipes/recipes_slime.dm
  icons/obj/guns/projectile/slaught_o_matic.dmi
Labels: Enhancement, New Content, Sprite Work

#3557 [DONE and TESTED] Add Workvisa/Passports/Passcards to the game and makes all accessories point free.
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
Labels: Enhancement, New Content, Sprite Work

#3581 Removes negative health modifiers
  code/game/jobs/job/captain.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
Labels: Balance

#3589 Fixes substations and APCs in maintenance, adds Church wall obelisks to cryo
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Good-To-Merge, Map

#3591 hivemind balances
  code/game/gamemodes/events/hivemind_controller.dm
  code/modules/hivemind/mobs.dm
  code/modules/hivemind/wires.dm
Labels: Balance

#3590 death alarm medical check
  code/game/objects/items/weapons/implant/implants/death_alarm.dm
Labels: Enhancement, Balance

#3595 Kaizer rebalance
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
Labels: Balance

#3596 less-wall obelisks
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#3593 Code Framework for Customization, Progression and Experience System
  .gitignore
  code/__DEFINES/jobs.dm
  code/controllers/subsystems/jobs.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/perks/job.dm
  code/game/jobs/department.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/modules/client/preference_setup/occupation/occupation.dm
Labels: Enhancement, New Content, Good-To-Merge

#3597 New Borg Icons
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_dogborgs.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/silicon.dm
  icons/mob/robot_tall/cargo.dmi
  icons/mob/robot_tall/janitor.dmi
  icons/mob/robot_tall/medical.dmi
  icons/mob/robot_tall/mining.dmi
  icons/mob/robot_tall/readme.md
  icons/mob/robot_tall/science.dmi
  icons/mob/robot_tall/server.dmi
  icons/mob/robot_tall/unused.dmi
  icons/mob/robots.dmi
  icons/mob/robots_tall.dmi
  icons/mob/robots_wide.dmi
  icons/mob/screen1_robot.dmi
Labels: Bug-Fix, Sprite Work

#3598 Admin and Mimery
  code/_global_vars/misc.dm
  code/game/gamemodes/storytellers/mime.dm
  code/modules/admin/admin_verbs.dm
Labels: Enhancement, Bug-Fix

#3599 Major fixes and qol
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_hud.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/power/cell.dm
  code/modules/surgery/internal.dm
Labels: Bug-Fix, Balance, Skill-Issue | Salt PR

#3600 Sadly less lethal biomatter
  code/modules/biomatter_manipulation/toxic_biomass.dm
Labels: Balance

#3604 Small fixes
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/storage/pouches.dm
Labels: Bug-Fix

#3605 Bee Sanity
  code/modules/hydroponics/beekeeping/beehive.dm
Labels: Balance

#3606 death to sleep procs MK I
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/structures/burrows.dm
  code/game/objects/structures/satellite.dm
  code/modules/client/edge_sliding/move_loop.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/scrap/scrap_beacon.dm
Labels: Enhancement

#3607 dogborg icon hotfix
  code/modules/mob/living/silicon/robot/robot_dogborgs.dm
Labels: Bug-Fix

#3608 replaces gate network (unused) with LSS network
  code/game/machinery/camera/presets.dm
Labels: Bug-Fix

#3601 Gives Salvagers back their cognition bonus
  code/game/jobs/job/prospector.dm
Labels: Balance

#3609 Worst trade deal
  code/modules/modular_computers/file_system/programs/generic/trade.dm
Labels: Bug-Fix

#3612 Trade tree
  code/controllers/subsystems/trade.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/modular_computers/file_system/programs/generic/trade_catalog.dm
  code/modules/modular_computers/file_system/programs/generic/trade_log.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advtechno.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
  nano/css/shared.css
  nano/images/overmap.png
  nano/templates/trade.tmpl
  nano/templates/trade_catalog.tmpl
  nano/templates/trade_log.tmpl
Labels: Enhancement, Bug-Fix, Balance, Sprite Work, Good-To-Merge

#3611 Reintegrates the gibber with genetics
  code/game/machinery/kitchen/gibber.dm
Labels: Bug-Fix, Balance

#3610 more skinsuits
  code/modules/clothing/under/casual.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work

#3613 Nosfernium effect change
  code/modules/organs/blood.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/other.dm
Labels: Bug-Fix, Balance

#3615 Small optimizations
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/crayon.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/custodian.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug-Fix, Balance

#3618 a godawful dirty fix for mobs following you while dead
  code/__HELPERS/game.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/living_powers.dm
  code/modules/mob/mob_helpers.dm
Labels: Bug-Fix

#3620 Minor Blackshield and Marshal additions
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Balance

#3619 Tweaks For Cat
  code/game/jobs/job/job.dm
Labels: Balance, Good-To-Merge

#3617 Cleaner code and more optiomation
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/emp.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/plasmaroach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/church/church.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/roomba.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/mining/mining_drone.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/carbon/superior_animal/vox/ai.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/ai.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/attack.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoMega.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoRobust.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  sojourn-station.dme
Labels: Documentation, Balance
