Repository sojourn-13/sojourn-station, pull requests merged in 2023-06, with the labels that each got.

#4679 Add three towels to the athletic wardrobe
  code/game/objects/structures/crates_lockers/closets/fitness.dm
Labels: Content

#4676 baby's first salt PR
  code/game/objects/random/mob/misc.dm
Labels: Balance

#4678 typo in opifex mask
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
Labels: Bug-Fix
