Repository sojourn-13/sojourn-station, pull requests merged in 2023-09, with the labels that each got.

#4758 small bugfixes
  code/datums/contract.dm
  code/modules/clothing/suits/armor.dm
Labels: Bug-Fix

#4759 PROBABLY fixes certain deferred boxes being an obnoxious meme.
  code/game/objects/items/weapons/storage/deferred.dm
Labels: Bug-Fix, Balance, Good-To-Merge

#4757 Drip or Drown; Premier style update. And some other clothing related stuff.
  code/datums/outfits/jobs/command.dm
  code/game/objects/random/cloth.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/security.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
Labels: Content, Sprite Work, Good-To-Merge, Removal, Test Merged, Port

#4762 Small map fixes
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
Labels: Bug-Fix, Map

#4765 Add option to disable the farmbot speaker
  code/modules/mob/living/bot/farmbot.dm
Labels: Content

#4770 Make janitorial cart destructible
  code/game/objects/structures/janicart.dm
Labels: Bug-Fix, Good-To-Merge

#4753 Hivemind - per emojiocracy vote.
  code/game/gamemodes/events/blob.dm
  code/game/gamemodes/events/hivemind_invasion.dm
Labels: Balance, Test Merged

#4750 removing roaches from maint lockers
  code/game/objects/structures/crates_lockers/closets/maint_loot.dm
Labels: Removal, Test Merged

#4720 TALLY HO EEPY TIME TO GO
  code/modules/projectiles/guns/energy/projectile/sst.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/research/designs/greyson.dm
  code/modules/research/nodes/combat.dm
Labels: Content, Balance, Test Merged

#4772 Revamping Lodge Power + Colony Map Fix
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Good-To-Merge, Map

#4754 Bullet balance
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance, Discussion Needed, Test Merged

#4755 Events 'n Objectives.
  code/controllers/subsystems/migration.dm
  code/datums/objective/individual_objective/church.dm
  code/datums/objective/individual_objective/command.dm
  code/datums/objective/individual_objective/common.dm
  code/datums/objective/individual_objective/guild.dm
  code/datums/objective/individual_objective/moebius.dm
  code/datums/objective/individual_objective/technomancers.dm
  code/game/gamemodes/events/spacevine.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
Labels: Bug-Fix, Balance, Test Merged

#4761 Visitor update.
  code/__DEFINES/jobs.dm
  code/datums/outfits/jobs/civilian.dm
  code/game/jobs/department.dm
  code/game/jobs/job/avisitor.dm
  code/game/jobs/jobs.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/multiz/map_data.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  sojourn-station.dme
Labels: Content, Test Merged

#4774 fixes BS headsets
  code/game/objects/items/devices/radio/headset.dm
Labels: Bug-Fix, Balance, Good-To-Merge
