Repository sojourn-13/sojourn-station, pull requests merged in 2023-05, with the labels that each got.

#4659 Cash register: fix custom orders, make price changeable
  code/modules/economy/cash_register.dm
Labels: Bug-Fix

#4661 Excel armor stat change and mob tweaks
  code/modules/clothing/spacesuits/void/excelsior.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
Labels: Balance

#4575 Lonestar Pricing Overhaul (Testing)
  code/controllers/subsystems/trade.dm
  code/game/objects/items/devices/scanners/price.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advtechno.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
Labels: Balance, Test Merged

#4673 fix typo
  code/game/objects/structures/watercloset.dm
Labels: Bug-Fix

#4670 Minor map fixes
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Map

#4668 Error in calculation of station time, fix #4666
  code/__HELPERS/time.dm
Labels: Bug-Fix

#4669 Enable removing other's underwear, comparable to other clothing items.
  code/modules/clothing/underwear/base.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/stripping.dm
Labels: Enhancement, Balance

#4655 Sanity
  code/datums/perks/backgrounds.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/sanity/breakdowns.dm
Labels: Balance, Test Merged

#4662 Merc space base update
  maps/Centcom/map/centcom.dmm
Labels: Balance, Map
