Repository sojourn-13/sojourn-station, pull requests merged in 2023-03, with the labels that each got.

#4508 Exalt Nerve Fix
  code/modules/organs/internal/nerves.dm
Labels: Bug-Fix

#4507 Less Dump-Stat FBP Backgrounds & Welderproof Eyes
  code/datums/setup_option/backgrounds/origin_synthetic.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/organs/internal/eyes.dm
Labels: Balance

#4509 FBP markings
  code/modules/sprite_accessories/_accessory_marking.dm
  icons/mob/human_races/markings.dmi
Labels: Sprite Work

#4495 Adds multi-z transmission to radios
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Balance

#4511 Imprinters
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
Labels: Balance

#4512 rad collectors are now viable
  code/modules/power/supermatter/supermatter.dm
Labels: Bug-Fix

#4513 fixes sprites
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  icons/inventory/head/mob.dmi
  icons/obj/ammo.dmi
  icons/obj/ammo_mags.dmi
  icons/obj/guns/projectile/copperhead.dmi
Labels: Bug-Fix

#4514 tool breaking buffs
  code/game/objects/items/weapons/tools/_tools.dm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/tasks.dm
Labels: Bug-Fix, Content, Balance

#4515 add tape recorder to loadout
  code/modules/client/preference_setup/loadout/lists/general.dm
Labels: Balance

#4516 tool break fix
  code/game/objects/items/weapons/tools/_tools.dm
Labels: Bug-Fix

#4519 Erisportsss
  code/controllers/subsystems/migration.dm
  code/game/antagonist/antagonist_create.dm
  code/modules/aberrants/organs/_defines.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/reagents/medicine.dm
Labels: Bug-Fix, Balance

#4518 more stuff into TGUI and a small cryo buff? (somewhat of a Guild nerf)
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/game/machinery/cryo.dm
Labels: Enhancement

#4517 Update belt.dm
  code/game/objects/items/weapons/storage/belt.dm
Labels: Balance

#4520 TGUI solars computer
  code/modules/power/solar.dm
Labels: Enhancement

#4522 Pain and Melee
  code/game/mecha/combat/phazon.dm
  code/game/mecha/mecha.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/lighting/flare.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/objs.dm
  code/modules/clothing/head/costume.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
Labels: Bug-Fix, Content, Balance

#4523 Abandoned Safehouse
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
Labels: Balance, Map

#4470 Map Overhaul
  code/datums/outfits/outfit.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/structures/burrows.dm
  code/modules/unit_tests/map_tests.dm
  icons/obj/contraband_large.dmi
  maps/Centcom/map/centcom.dmm
  maps/SpaceFortress/map/space_dungeons.dmm
  maps/SpaceFortress/spacefortress.dm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  maps/__Nadezhda/nadezhda.dm
Labels: Balance, Map

#4510 event npcs
  code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm
  icons/mob/mobs-humanoid.dmi
  sojourn-station.dme
Labels: Content, Sprite Work

#4490 Sanity PR Attempt
  code/__DEFINES/perks.dm
  code/__DEFINES/sanity.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/controllers/subsystems/sanity.dm
  code/datums/components/clothing_sanity_protection.dm
  code/datums/perks/backgrounds.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/datums/setup_option/backgrounds/origin_career.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/datums/topic/admin.dm
  code/game/objects/items.dm
  code/game/objects/items/_inventory.dm
  code/modules/admin/admin.dm
  code/modules/clothing/head/mindreader.dm
  code/modules/clothing/masks/balaclava.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/monkey.dm
  code/modules/mob/living/carbon/human/species/station/skeleton.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/sanity/breakdown.dm
  code/modules/sanity/breakdowns.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/scrap/scrap.dm
  code/modules/tips_and_tricks/gameplay.dm
  nano/images/desire.png
  nano/images/gangnam_style.png
  nano/images/insight.png
  nano/images/sanity.png
  nano/templates/sanity.tmpl
  sojourn-station.dme
Labels: Enhancement, New Content, Content, Balance, Sprite Work, Sound Addition, Skill-Issue | Salt PR

#4530 fixes many things
  code/game/machinery/sorter.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/organs/internal/bones.dm
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#4533 Sanity Loss Fixes
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/sanity/breakdowns.dm
  code/modules/scrap/scrap.dm
Labels: Bug-Fix, Balance

#4534 Update spreading_growth.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: Bug-Fix

#4535 more sanity and map fixes
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/structures/flora/flora.dm
  code/game/turfs/simulated/footsteps.dm
  code/modules/clothing/clothing.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/sanity/sanity_mob.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Content

#4536 fixes up some npcs
  code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm
Labels: Bug-Fix

#4537 Crayon Pouch
  code/game/objects/effects/decals/crayon.dm
Labels: Enhancement, Balance

#4538 some fixes some new
  code/modules/library/lib_items.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm
  icons/obj/library.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Content, Balance, Sprite Work

#4540 Serene Serenity
  code/datums/autolathe/guns.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/oddities.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/modules/cargo/packs_security.dm
  code/modules/projectiles/guns/energy/laser/egun.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
Labels: Balance

#4541 S4N1TY
  code/modules/projectiles/guns/energy/misc/mindflayer.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  sojourn-station.dme
Labels: Balance

#4542 helpful mobs
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/friendly/exotic_animals.dm
  code/modules/mob/living/simple_animal/friendly/light_geist.dm
  code/modules/mob/living/simple_animal/friendly/possum.dm
  code/modules/mob/living/simple_animal/friendly/roomba.dm
  code/modules/mob/living/simple_animal/friendly/slime.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/dino.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/mob/living/simple_animal/hostile/jelly.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/misc.dm
  code/modules/mob/living/simple_animal/hostile/tomato.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Balance

#4543 last fixes, that i know about
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#4547 Marshal hat and balaclava
  code/datums/outfits/jobs/security.dm
  code/modules/clothing/masks/balaclava.dm
Labels: Bug-Fix

#4546 Makes the marqua perk not lie
  code/datums/perks/racial.dm
Labels: Bug-Fix

#4548 POW ah
  icons/obj/power.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  modular_sojourn/power_puncher.dm
  sojourn-station.dme
Labels: Bug-Fix, Content, Balance, Sprite Work

#4549 Misc fixessss
  code/modules/clothing/under/jobs/militia.dm
  icons/inventory/head/icon.dmi
  icons/obj/ammo_mags.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance

#4545 9 to 5 experience
  code/__DEFINES/economy.dm
  code/game/jobs/department.dm
Labels: Balance

#4551 pow changes and some wire fixes
  code/modules/psionics/psionic_items/psi_catalysts.dm
  code/modules/psionics/psionic_items/psi_misc.dm
  icons/obj/device.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  modular_sojourn/power_puncher.dm
Labels: Content, Balance

#4552 Guild heavy barrel, jumpsuits and round 2 of plasma weapons balance
  code/datums/craft/recipes/guild.dm
  code/modules/client/preference_setup/loadout/lists/factionartificer.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/projectiles/guns/energy/plasma/cassad.dm
  code/modules/projectiles/guns/energy/plasma/centurio_auretian.dm
  code/modules/projectiles/guns/energy/plasma/excubitor.dm
  code/modules/projectiles/guns/energy/plasma/plasma.dm
  code/modules/psionics/psionic_items/psi_weptools.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Bug-Fix, Balance

#4553 Converts legacy-formatted signals to legacy
  code/modules/organs/internal/internal_wounds/_internal_wound.dm
  code/modules/reagents/reagents/medicine.dm
Labels: Bug-Fix

#4555 Frontier Psychiatrist - Two new psionic abilities to help with sanity
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
Labels: Content, Balance

#4556 Incendiary Ammo
  code/game/machinery/autolathe/fabricators.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/projectile/automatic/luger.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
Labels: Balance

#4558 No More Sanity Whispering
  code/modules/sanity/sanity_lists.dm
  code/modules/sanity/sanity_mob.dm
Labels: Bug-Fix, Balance

#4557 Fixes internal organs nulling damages
  code/modules/organs/internal/internal_organ_processes.dm
Labels: Bug-Fix

#4554 Alchemy and Crayon Meowgic stuff
  code/datums/craft/recipes/alchemy.dm
  code/game/jobs/job/offcolony.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/random/oddities.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/genetics/genetics.dm
  code/modules/genetics/machinery/genetics_items.dm
  code/modules/library/lib_items.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/organs/internal/bones.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  code/modules/reagents/machinery/alchemy.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/glass/bottled_chemicals.dm
  code/modules/reagents/reagents/alchemy.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/recipes/alchemy.dm
  icons/inventory/back/mob.dmi
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/chemical.dmi
  icons/obj/drinks.dmi
  icons/obj/oddities.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/scroll_bandange.dmi
  icons/obj/watercloset.dmi
  icons/obj/wizard.dmi
  maps/Centcom/map/centcom.dmm
  maps/SpaceFortress/map/blackstone_temple.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  maps/submaps/map_clearers/coras_map.dmm
  modular_sojourn/cardgame_2/cardpacks_and_spawner.dm
Labels: Documentation, Enhancement, New Content, Bug-Fix, Content, Balance, Sprite Work, Sound Addition

#4566 fixes some insighter
  code/modules/sanity/sanity_mob.dm
  modular_sojourn/task_master/tasks.dm
Labels: Bug-Fix

#4563 smoking nerfs?
  code/modules/sanity/sanity_mob.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/tasks.dm
Labels: Content, Balance

#4567 code clean up and small fixes
  code/__DEFINES/perks.dm
  code/datums/craft/crafting_items.dm
  code/datums/perks/backgrounds.dm
  code/datums/perks/imprinter_perks.dm
  code/datums/perks/job.dm
  code/datums/perks/racial.dm
  code/datums/setup_option/backgrounds/origin_akula.dm
  code/datums/setup_option/backgrounds/origin_career.dm
  code/datums/setup_option/backgrounds/origin_chtmant.dm
  code/datums/setup_option/backgrounds/origin_homeworld.dm
  code/datums/setup_option/backgrounds/origin_opifex.dm
  code/datums/setup_option/backgrounds/origin_sablekyne.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/game/antagonist/station/marshal.dm
  code/game/atoms.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/offcolony.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/implant/implants/carrion/holo_spider.dm
  code/game/turfs/simulated/cleaning.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/hydroponics/seed.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/captive_brain.dm
  code/modules/mob/living/carbon/brain/say.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/slime/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/friendly/slime.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/sanity/sanity_mob.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  modular_sojourn/Borers/say.dm
  modular_sojourn/annomlies/stalker_annomlies.dm
Labels: Bug-Fix

#4568 small mapfix + church rebalance round 3
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  code/modules/projectiles/guns/energy/laser/carpediem.dm
  code/modules/projectiles/projectile/beams.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix

#4574 more sanity interactions
  code/game/objects/items/weapons/candle.dm
  code/game/objects/structures/bluespace_crystal_structure.dm
  code/game/objects/structures/diamond_gem.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/fireaxe_cabinet.dm
  code/game/objects/structures/flora/flora.dm
  code/game/objects/structures/flora/flora_potted.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/sanity/sanity_mob.dm
Labels: Balance

#4573 adds a message cooldown to nonsmoking areas
  code/modules/sanity/sanity_mob.dm
Labels: Documentation

#4571 dynamic xenoarch anomalies
  code/controllers/subsystems/xenoarch.dm
Labels: Enhancement, Balance

#4580 anomaly research additions
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
Labels: Bug-Fix

#4581 forge rebalance
  code/game/machinery/autolathe/matterforge.dm
Labels: Balance

#4583 HUD helmets
  code/game/objects/random/cloth.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/clothing/head/helmet.dm
  icons/inventory/eyes/icon.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  maps/_DeepForest/map/_Prepper_Bunker.dmm
Labels: Enhancement, Bug-Fix, Balance

#4572 Stop Making Me Hurt You
  code/game/jobs/department.dm
  code/game/jobs/job/prospector.dm
Labels: Balance

#4578 Marshal Armory QoL
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix

#4577 Erismed ports
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/scanners/health.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach_spits.dm
  code/modules/mob/living/living.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/internal/carrion.dm
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/organs/internal/internal_wounds/_internal_wound.dm
  code/modules/organs/internal/internal_wounds/organic.dm
  code/modules/organs/organ.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/toxins.dm
  modular_sojourn/Borers/borer_powers.dm
Labels: Bug-Fix, Balance

#4587 Reduces crossbow bolt crafting cost
  code/datums/craft/recipes/lodge.dm
Labels: Balance

#4589 plants and flash fix
  code/modules/dungeons/teleporter.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/living.dm
  code/modules/organs/internal/eyes.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/organs/internal/liver.dm
  icons/obj/surgery.dmi
Labels: Bug-Fix

#4588 Adds Initial Starting Funds to Prospectors
  code/game/jobs/job/prospector.dm
Labels: Balance

#4590 Unbreaks Gun Case Physics
  code/game/objects/items/weapons/storage/backpack.dm
  icons/obj/storage/backpack.dmi
Labels: Balance, Sprite Work

#4594 Psionic Harvester Sprite
  code/modules/research/xenoarchaeology/machinery/psionic_harvester.dm
  icons/obj/xenoarchaeology.dmi
Labels: Balance, Sprite Work

#4592 Excelsior Map Fix
  maps/SpaceFortress/map/space_dungeons.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance

#4595 pyrokinetic spark
  code/modules/clothing/clothing.dm
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
  icons/obj/psionic/occpyrospark.dmi
Labels: Content, Sprite Work

#4597 two new gloves
  code/datums/craft/recipes/clothing.dm
  code/datums/craft/recipes/guild.dm
  code/modules/clothing/gloves/knuckledusters.dm
  code/modules/clothing/gloves/miscellaneous.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
Labels: Content, Balance, Sprite Work

#4596 Shield Balances
  code/game/objects/items/weapons/shields.dm
Labels: Balance

#4598 Engineer gaming drip
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/client/preference_setup/loadout/lists/factionartificer.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/under/jobs/engineering.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Balance, Sprite Work

#4599 area and some map fixes
  maps/SpaceFortress/map/space_dungeons.dmm
Labels: Bug-Fix

#4593 The Anti-Blackshield Struggle
  code/controllers/subsystems/ticker.dm
  code/datums/contract.dm
  code/datums/outfits/jobs/security.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/random/cloth.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/cargo/packs_clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  maps/_DeepForest/map/_Prepper_Bunker.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Content, Balance, Sprite Work

#4586 Reference moment
  code/datums/uplink/void_wolf.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/disc.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/random/medicine.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  code/modules/projectiles/guns/energy/laser/carpediem.dm
  code/modules/projectiles/guns/energy/laser/cog.dm
  code/modules/projectiles/guns/energy/laser/laser.dm
  code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/sandwich.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagents/stims.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/research/designs/greyson.dm
  code/modules/research/nodes/greyson.dm
  maps/__Nadezhda/map/Underground_Old.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Underground.dmm
  modular_sojourn/Borers/borer.dm
Labels: Documentation

#4601 Map Compression
  maps/_DeepForest/deepforest.dm
  maps/_DeepForest/map/_River_To_Colony.dmm
  maps/_DeepForest/map/_River_To_Swamp_old.dmm
Labels: Enhancement, Balance, Map

#4602 Unfucks a few sprites, buffs marshals
  code/datums/autolathe/gun_frames.dm
  code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/clothing/head/helmet.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  icons/obj/guns/projectile/rivet_gun.dmi
  icons/obj/guns/projectile/scaffold.dmi
  icons/obj/guns/projectile/spring.dmi
Labels: Bug-Fix, Balance, Sprite Work

#4603 Helmet and Armor compression
  code/datums/craft/recipes/clothing.dm
  code/datums/outfits/antagonist/mercenary.dm
  code/datums/outfits/jobs/ghostroles.dm
  code/datums/outfits/jobs/medical.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/costume.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/random/cloth.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/cargo/packs_clothing.dm
  code/modules/cargo/packs_security.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/__Nadezhda/map/Surface_Old.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Surface.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Underground.dmm
Labels: Enhancement, Balance

#4605 Rebreathers! Finally (hopefully)
  code/modules/client/preference_setup/loadout/lists/clothing.dm
  code/modules/clothing/masks/gasmask.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
Labels: Content, Sprite Work

#4606 fixes some spelling and bad slot_w_uniforms
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/security.dm
Labels: Bug-Fix

#4607 Trys again to fix thins
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/security.dm
Labels: Bug-Fix

#4610 AAAAAAAAH
  code/modules/clothing/head/helmet.dm
Labels: Bug-Fix

#4609 condences down more maps
  maps/_DeepForest/deepforest.dm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
  maps/_DeepForest/map/_Greyson_Field_Office_old.dmm
Labels: Enhancement, Balance, Map

#4608 Altmode item adjustments
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
Labels: Bug-Fix, Balance

#4612 Adds trays to Beacon (Tray revolution)
  code/modules/hydroponics/trays/tray.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
Labels: Balance

#4616 Fixes accessories on spawn
  code/modules/clothing/clothing.dm
Labels: Bug-Fix

#4591 ATMOSPHERIS! This time with more emotion
  code/ATMOSPHERICS/_atmos_setup.dm
  code/ATMOSPHERICS/_atmospherics_helpers.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/ATMOSPHERICS/datum_pipeline.dm
  code/ATMOSPHERICS/mainspipe.dm
  code/ATMOSPHERICS/pipes.dm
  code/__DEFINES/atmos.dm
  code/game/machinery/alarm.dm
  code/game/machinery/atmoalter/meter.dm
Labels: Enhancement, Bug-Fix

#4619 Stat cap
  code/__DEFINES/mob_stats.dm
  code/datums/mob_stats.dm
  code/modules/sanity/sanity_mob.dm
Labels: Balance

#4617 Power to the guild
  code/game/objects/items/weapons/autolathe_disk/guild_disks.dm
  maps/_DeepForest/map/_Prepper_Bunker.dmm
  maps/_DeepForest/map/_River_To_Colony.dmm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#4625 Slide shotgun new sprite + Marshal buff
  code/modules/projectiles/guns/projectile/automatic/freedom.dm
  code/modules/projectiles/guns/projectile/shotgun/handmade.dm
  icons/obj/crafts.dmi
  icons/obj/guns/projectile/slideshotgun.dmi
Labels: Balance, Sprite Work

#4624 Fixes a typo in alt-modes
  code/game/objects/items.dm
Labels: Bug-Fix

#4622 church sprite round + moves mapping stuff to code
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/mining/mine_items.dm
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  icons/obj/guns/energy/antebellum.dmi
  icons/obj/guns/energy/carpediem.dmi
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Sprite Work

#4621 Marketing Phone
  code/game/objects/items/oddities_faction.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  icons/obj/items.dmi
Labels: Balance, Sprite Work

#4576 Church armour
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/storage/church_kits.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  sojourn-station.dme
Labels: Content, Balance

#4627 fixes armor doups and compresses
  code/game/objects/items/weapons/storage/church_kits.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
Labels: Documentation, Balance

#4628 fixes the marshal shuttle now having a transition area
  maps/Centcom/map/centcom.dmm
Labels: Bug-Fix

#4629 Event Shit
  code/modules/mob/living/carbon/superior_animal/human/subtype/prisoners/prisoners.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/solgov/marines.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/xiang jiang/xiang.dm
  icons/mob/mobs-humanoid.dmi
  maps/SpaceFortress/map/space_dungeons.dmm
  maps/SpaceFortress/spacefortress.dm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
  sojourn-station.dme
  sound/death_gasps/marine1.ogg
  sound/death_gasps/marine2.ogg
  sound/death_gasps/xiang.ogg
Labels: Bug-Fix, Content, Balance

#4631 event over
  maps/SpaceFortress/spacefortress.dm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
Labels: Removal

#4633 fixes a douped navpoint
  maps/Centcom/map/centcom.dmm
Labels: Bug-Fix
