Repository sojourn-13/sojourn-station, pull requests merged in 2023-07, with the labels that each got.

#4685 Bugfixes.
  code/__DEFINES/projectile_defines.dm
  code/game/machinery/tesla_turret.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/mop_bucket.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/organs/body_modifications.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
  icons/inventory/head/mob.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/guns/energy/gauss.dmi
  icons/obj/guns/projectile/duty.dmi
  maps/__Nadezhda/data/shuttles-nadezhda.dm
Labels: Bug-Fix, Good-To-Merge

#4682 HexCookFixAdd
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  icons/obj/food.dmi
  icons/obj/food_ingredients.dmi
Labels: Enhancement, Content, Good-To-Merge

#4698 fixes the bluespace scanner oddity
  code/game/objects/items/oddities.dm
Labels: Bug-Fix, Good-To-Merge

#4708 Fixed lemni hat turning into tesselate veil visually
  code/modules/clothing/head/helmet.dm
Labels: Bug-Fix

#4703 Small lil bandaid.
  code/game/objects/items/weapons/tools/_tools.dm
  code/modules/power/cable.dm
Labels: Bug-Fix

#4714 Direct line exploits fix
  code/game/objects/items/oddities_faction.dm
Labels: Good Issue Report, Bug-Fix, Good-To-Merge

#4684 Psion Regen Increase
  code/modules/psionics/psion.dm
Labels: Balance, Test Merged

#4696 Gunsmithing fixes n tweaks.
  code/datums/craft/recipes/armor.dm
  code/datums/craft/recipes/clothing.dm
  code/datums/craft/recipes/repairs.dm
  code/datums/craft/recipes/weapon.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/boltgun/novakovic.dm
  code/modules/projectiles/guns/projectile/boltgun/roe_sika.dm
  code/modules/projectiles/guns/projectile/boltgun/scout.dm
  code/modules/projectiles/guns/projectile/revolver/sixshot.dm
  code/modules/projectiles/guns/projectile/shotgun/combatsg.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/psionics/psionic_items/psi_weptools.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Test Merged

#4707 Carpediem buff, recommended by Rain Chule
  code/modules/projectiles/guns/energy/laser/carpediem.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Balance, Good-To-Merge

#4711 Ports
  code/__DEFINES/perks.dm
  code/datums/mob_stats.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/game/machinery/gym.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/traps.dm
  code/modules/mob/mob.dm
  icons/effects/perks.dmi
  icons/obj/machines/gym.dmi
Labels: Content, Good-To-Merge, Port

#4722 Fixes caustic bullets
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Bug-Fix, Balance

#4721 Fixes dress selection.
  code/game/machinery/vendor/cloathing.dm
  code/game/objects/items/weapons/storage/costume.dm
  code/game/objects/landmarks/costume.dm
  code/game/objects/random/cloth.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/under/dress.dm
  code/modules/clothing/under/miscellaneous.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix

#4730 fixes #4690: update icon of mop bucket in cart when it goes empty
  code/game/objects/structures/janicart.dm
Labels: Bug-Fix
