Repository sojourn-13/sojourn-station, pull requests merged in 2023-10, with the labels that each got.

#4775 Disables reload admin/mentor
  code/modules/admin/verbs/diagnostics.dm
Labels: Removal

#4786 postpen for abdicator/Peacekeeper
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#4768 Buffs marshals for Pneumo. Nerfs marshals for Meeeeeee also some bugfixes i guess
  code/datums/autolathe/gun_frames.dm
  code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
  code/modules/mob/living/say.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/ostwind.dm
  code/modules/reagents/metabolism.dm
Labels: Bug-Fix, Balance, Test Merged

#4788 some energy shotgun changes.
  code/modules/projectiles/guns/energy/laser/abdicator.dm
  code/modules/projectiles/guns/energy/laser/peacekeeper.dm
Labels: Balance

#4789 should've tested the last bugfix, oh well.
  code/modules/projectiles/guns/energy/laser/abdicator.dm
Labels: Bug-Fix

#4780 Creating ERT Ready Room
  maps/Centcom/map/centcom.dmm
Labels: Balance, Map, Test Merged

#4777 This was supposed to be a small PR.
  code/datums/outfits/jobs/ghostroles.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/simple_animal/friendly/roomba.dm
  code/modules/projectiles/ammunition/magazines.dm
  icons/mob/battle_roomba.dmi
  icons/obj/ammo_mags.dmi
Labels: Enhancement, Content, Balance, Sprite Work, Test Merged

#4776 CBO buffs
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Content, Balance, Test Merged

#4781 re-adds some guns that were requested
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/projectiles/guns/projectile/automatic/bulldog.dm
  code/modules/projectiles/guns/projectile/automatic/mac.dm
  code/modules/projectiles/guns/projectile/automatic/pitbull.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/random_map/drop/drop_types.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  icons/obj/guns/projectile/pitbull.dmi
  icons/obj/guns/projectile/sts40.dmi
  sojourn-station.dme
Labels: Content, Balance, Test Merged

#4794 Reverts the DB shotgun sprite to it's pre-fallout glory days.
  icons/obj/guns/projectile/dshotgun.dmi
  icons/obj/guns/projectile/sawnoff/sawnshotgun.dmi
Labels: Sprite Work

#4793 Im having trouble holding all these borg icons
  code/modules/mob/living/silicon/Cyborg_AI/custom_cyborg.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  icons/mob/robot_tall/engi.dmi
  icons/mob/robot_tall/janitor.dmi
  icons/mob/robot_tall/medical.dmi
  icons/mob/robot_tall/mining.dmi
  icons/mob/robot_tall/misc.dmi
  icons/mob/robot_tall/science.dmi
  icons/mob/robot_tall/sec.dmi
  icons/mob/robot_tall/server.dmi
  icons/mob/robot_tall/unused.dmi
  icons/mob/robots.dmi
Labels: Sprite Work, Test Merged

#4790 So much for that small PR i was working on.
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/spawners/corpsespawner.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/random/cloth.dm
  code/game/objects/random/mob/misc.dm
  code/modules/biomatter_manipulation/toxic_biomass.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/void/excelsior.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/casual.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_behemoth.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_runtling.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach_spits.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/laser/sunrise.dm
  code/modules/projectiles/guns/energy/misc/robotguns.dm
  code/modules/projectiles/guns/projectile/automatic/ostwind.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/tips_and_tricks/gameplay.dm
  code/modules/tips_and_tricks/jobs.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/guns/projectile/sawnoff/sts40.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Content, Balance, Sprite Work, Skill-Issue | Salt PR, Map, Test Merged

#4797 Just a small PR this time, i promise.
  code/game/objects/items/weapons/manuals.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Content

#4799 Gladstone
  code/datums/autolathe/guns.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  sojourn-station.dme
Labels: Content, Balance, Good-To-Merge

#4802 Fixes janitor borg icons
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Bug-Fix

#4804 Update noticeboard.dm
  code/game/objects/structures/noticeboard.dm
Labels: Content

#4805 sprite fix
  icons/obj/guns/energy/excubitor.dmi
Labels: Sprite Work

#4792 Addon - Excel Fortress (Fixed maybe)
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Content, Map, Test Merged

#4795 yet another outsider buff
  code/datums/setup_option/core_implants.dm
Labels: Bug-Fix, Balance, Skill-Issue | Salt PR, Test Merged

#4800 Janibuffs
  code/game/jobs/job/civilian.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
Labels: Balance, Test Merged

#4806 Removes background restrictions for synthetic outsiders
  code/datums/setup_option/backgrounds/origin_synthetic.dm
Labels: Balance, Test Merged

#4817 Excelsior Space Program
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Bug-Fix, Good-To-Merge, Map

#4818 Update - Loot & Mines
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Balance, Map

#4819 No message regarding contents on empty bottles
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Labels: Bug-Fix, Balance

#4820 When putting a bedsheet on a bed, remove pixel shift
  code/game/objects/structures/bedsheet_bin.dm
Labels: Bug-Fix

#4824 Better descriptions for ''non-lethal'' ballistics
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
Labels: Enhancement

#4826 Joseph atton found the ids!
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix

#4709 Ports some erismed tweaks
  code/__DEFINES/damage_organs.dm
  code/controllers/hooks-defs.dm
  code/datums/autolathe/organ.dm
  code/datums/repositories/crew/binary.dm
  code/datums/repositories/crew/vital.dm
  code/game/machinery/bioprinter.dm
  code/game/objects/items/devices/defib.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
  code/modules/food/recipes_microwave.dm
  code/modules/genetics/machinery/genetics_items.dm
  code/modules/genetics/mutations/item_makers.dm
  code/modules/integrated_electronics/subtpes/input.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/mob/living/carbon/brain/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/golem.dm
  code/modules/mob/living/carbon/human/species/station/hivelord.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/organs/blood.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/internal/appendix.dm
  code/modules/organs/internal/blood_vessels.dm
  code/modules/organs/internal/bones.dm
  code/modules/organs/internal/carrion.dm
  code/modules/organs/internal/eyes.dm
  code/modules/organs/internal/heart.dm
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/organs/internal/internal_wounds/organic.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/organs/internal/lungs.dm
  code/modules/organs/internal/muscles.dm
  code/modules/organs/internal/nerves.dm
  code/modules/reagents/metabolism.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/stims.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/scrap/scrap.dm
  code/modules/surgery/surgery_ui.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  code/modules/virus2/effect.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  tools/Runtime Condenser/Input.txt
  tools/Runtime Condenser/Output.txt
Labels: Balance, Test Merged, Port

#4808 balances self surgery + fixes farmbots
  code/modules/mob/living/bot/farmbot.dm
  code/modules/surgery/surgery.dm
Labels: Balance, Test Merged

#4809 Guild borg buffs mostly (so they can do their job)
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
Labels: Balance, Test Merged
