Repository sojourn-13/sojourn-station, pull requests merged in 2023-01, with the labels that each got.

#4261 Banana Republic
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/mods/_defines.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/multitool.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/modules/projectiles/guns/ameridian.dm
  code/modules/projectiles/guns/energy/laser/cog.dm
  code/modules/projectiles/guns/energy/laser/laser.dm
  code/modules/projectiles/guns/energy/plasma/plasma.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/nail_gun.dm
  code/modules/projectiles/guns/projectile/automatic/scaffold.dm
  code/modules/projectiles/guns/projectile/automatic/trouble_shooter.dm
  code/modules/projectiles/guns/projectile/pistol/rebar.dm
  code/modules/projectiles/guns/projectile/pistol/rivet.dm
  code/modules/projectiles/guns/projectile/pistol/spring.dm
  code/modules/research/xenoarchaeology/finds/finds_eguns.dm
Labels: Enhancement, Balance

#4262 Gun Lootpile Changes & Beacon Changes
  code/game/objects/random/guns.dm
  code/game/objects/random/packs.dm
  code/modules/projectiles/guns/projectile/revolver/breakaction.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
Labels: Balance, Removal

#4263 Ammo crafting changes
  code/game/machinery/crafting_station.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/bullets.dm
Labels: Balance

#4264 bug Additional slash makes URL invalid
  code/game/objects/items/weapons/manuals.dm
Labels: Bug-Fix

#4265 fix some drink bottles having invalid empty sprites
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Labels: Bug-Fix, Sprite Work

#4266 goated robes and sashes
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
Labels: Sprite Work

#4267 slots balance
  code/modules/gambling/slot_machine.dm
  icons/obj/vending.dmi
Labels: Balance, Sprite Work

#4271 cargo nerfs and ammo crafting buff
  code/controllers/subsystems/trade.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
Labels: Balance

#4270 Ghetto Chem Revamp (And minor typo fix)
  code/game/objects/items/bodybag.dm
  code/game/objects/items/devices/radio/beacon.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/scanners/gas.dm
  code/game/objects/items/devices/scanners/health.dm
  code/game/objects/items/devices/scanners/plant.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/phone.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/pen.dm
  code/modules/psionics/psion.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
Labels: Balance

#4272 ports deconning church stuff
  code/modules/core_implant/cruciform/rituals/construction.dm
Labels: Content, Balance

#4273 Colourable accessories!
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
Labels: Sprite Work

#4268 removes three pixels
  icons/inventory/head/mob.dmi
Labels: Sprite Work

#4274 ameridian buffs
  code/game/objects/items/weapons/circuitboards/machinery/ameridian.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/ameridian/ameridian_core.dm
  code/modules/ameridian/ameridian_refinery.dm
  code/modules/ameridian/liquid_ameridian_processor.dm
Labels: Balance

#4277 some sorting and name fixes
  code/game/machinery/vendor/tool_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/boltgun/zatvor_ak.dm
Labels: Bug-Fix

#4278 Xenoarch Types and QOL
  code/controllers/subsystems/xenoarch.dm
  code/modules/multiz/map_data.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  maps/_DeepForest/deepforest.dm
  maps/__DeepTunnels/deeptunnels.dm
  maps/__Nadezhda/nadezhda.dm
Labels: Enhancement, Bug-Fix, Balance

#4279 [MINOR] Hotfix for tincture bottle
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/machinery/grinder.dm
  icons/obj/chemical.dmi
Labels: Bug-Fix

#4280 Gun Bloat Finals (For Now)
  code/datums/autolathe/guns.dm
  code/datums/craft/recipes/guns.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Balance, Removal

#4282 womp womp
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  sojourn-station.dme
Labels: Wont fix, Skill-Issue | Salt PR

#4281 Blackshield Drip
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/head/jobs.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/obj/guns/projectile/blackguard.dmi
  icons/obj/guns/projectile/colt.dmi
Labels: Sprite Work

#4284 Ports onmob examine from Polaris
  code/modules/mob/living/carbon/human/examine.dm
Labels: Enhancement, Balance, Good-To-Merge

#4283 lots of small stuff
  code/__DEFINES/weapons.dm
  code/datums/craft/recipes/guild.dm
  code/datums/craft/recipes/guns.dm
  code/game/machinery/vendor/medical_vendors.dm
  code/game/machinery/vendor/tool_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/library/lib_items.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/projectiles/guns/energy/projectile/sst.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/revolver/lemant.dm
  code/modules/research/designs/greyson.dm
  code/modules/research/nodes/combat.dm
  icons/obj/machines/one_star/vending.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Bug-Fix, Balance, Map, Removal

#4287 Radiohat Fix
  icons/inventory/head/mob.dmi
Labels: Sprite Work

#4286 Readds casio ship
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/casino.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  sojourn-station.dme
Labels: Content

#4288 Blackshield Drip V2
  code/datums/craft/recipes/storage.dm
  code/datums/outfits/jobs/security.dm
  code/game/machinery/vendor/cloathing.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/random/cloth.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/clothing/under/jobs/security.dm
  icons/inventory/back/mob.dmi
  icons/obj/storage/backpack.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Content, Sprite Work

#4289 Onmob-examine fixes
  code/modules/clothing/accessories/holster.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Bug-Fix

#4290 Small icon fixes
  code/modules/clothing/under/jobs/militia.dm
  icons/obj/guns/projectile/blackguard.dmi
Labels: Sprite Work

#4292 Exploit fix and typo fixes
  code/__DEFINES/weapons.dm
  code/datums/autolathe/security.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/modules/ameridian/ameridian_core.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/_projectile.dm
  code/modules/projectiles/guns/energy/laser/tetra.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/mac.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  icons/mob/screen/gun_actions.dmi
Labels: Bug-Fix, Balance

#4294 germ tweaks and shower changes
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/surgery/organic.dm
  icons/obj/watercloset.dmi
Labels: Balance

#4299 Mapfixess
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Duplicate, Bug-Fix

#4298 BS Backpack Fix
  icons/obj/storage/backpack.dmi
Labels: Sprite Work

#4300 mind fixs
  code/game/gamemodes/events/hivemind_invasion.dm
  code/modules/admin/bluespacetech.dm
Labels: Bug-Fix

#4302 something mini-eventy
  maps/submaps/map_clearers/map_clearers.dm
  maps/submaps/map_clearers/os_reclaimed_spider_post.dmm
Labels: Map

#4301 Letting Some Money Flow (More Station offers , Purchaseable cryptograph)
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
Labels: Balance

#4305 Secondary template for events
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/submaps/map_clearers/burnt_post_voidwolf_reclaimed.dmm
  maps/submaps/map_clearers/map_clearers.dm
  maps/submaps/map_clearers/os_reclaimed_spider_post.dmm
Labels: Content, Map

#4306 Fixes stuff
  code/modules/mob/angel/login.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/login.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/observer/ghost/login.dm
  code/modules/multiz/shadow.dm
  interface/skin.dmf
Labels: Bug-Fix

#4307 Gun balance ports
  code/__DEFINES/weapons.dm
  code/datums/datum_click_handlers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser/centauri.dm
  code/modules/projectiles/guns/energy/projectile/sst.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/armsmg.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/bond.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/freedom.dm
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
  code/modules/projectiles/guns/projectile/automatic/luger.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
  code/modules/projectiles/guns/projectile/automatic/mac.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/nail_gun.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/ostwind.dm
  code/modules/projectiles/guns/projectile/automatic/pulse_rifle.dm
  code/modules/projectiles/guns/projectile/automatic/scaffold.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/automatic/specop.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/automatic/texan.dm
  code/modules/projectiles/guns/projectile/automatic/triage.dm
  code/modules/projectiles/guns/projectile/automatic/trouble_shooter.dm
  code/modules/projectiles/guns/projectile/automatic/vector.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/glock.dm
  code/modules/projectiles/guns/projectile/pistol/judiciary.dm
  code/modules/projectiles/guns/projectile/pistol/rivet.dm
  code/modules/projectiles/guns/projectile/pistol/spring.dm
  code/modules/projectiles/guns/projectile/revolver/lemant.dm
  code/modules/projectiles/guns/projectile/shotgun/pug.dm
  code/modules/projectiles/guns/projectile/shotgun/sbaw.dm
  code/modules/projectiles/guns/projectile/shotgun/swat.dm
  nano/templates/weapon_stats.tmpl
Labels: Bug-Fix, Balance

#4309 Yet another batch of QoL goodies
  code/controllers/subsystems/vote.dm
  code/game/machinery/syndicatebeacon.dm
  code/game/machinery/vendor/medical_vendors.dm
  code/game/machinery/vendor/tool_vendors.dm
  code/game/objects/items/weapons/hydrogen_fuel_cell.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/tools/bonesetters.dm
  code/game/objects/items/weapons/tools/cauterys.dm
  code/game/objects/items/weapons/tools/hemostats.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/retractors.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/stripping.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/kriosan/kriosan.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/power/antimatter/control.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/nail_gun.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/ostwind.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/automatic/trouble_shooter.dm
  code/modules/projectiles/guns/projectile/boltgun/roe_sika.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/deaglebolt.dm
  code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
  code/modules/projectiles/guns/projectile/pistol/ladon.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/spring.dm
  code/modules/projectiles/guns/projectile/revolver/breakaction.dm
  code/modules/research/designs/medical.dm
  code/modules/surgery/surgery.dm
  icons/obj/guns/projectile/blackguard.dmi
  icons/obj/storage.dmi
  icons/obj/tools.dmi
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  modular_sojourn/area_blurbs.dm
  sound/weapons/guns/fire/carbine.ogg
  sound/weapons/guns/fire/heroic_fire.ogg
  sound/weapons/guns/fire/rifle.ogg
Labels: Bug-Fix, Content, Balance, Sprite Work, Map

#4293 Vape and Command Role Age Requirements Salt PR
  code/game/jobs/job/captain.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/science.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
Labels: Balance

#4310 jackpotfix
  code/modules/gambling/slot_machine.dm
Labels: Bug-Fix

#4312 wooh gym
  code/__DEFINES/components.dm
  code/__DEFINES/perks.dm
  code/datums/objective/individual_objective/individual_objective.dm
  code/datums/perks/cooldown.dm
  code/game/machinery/gym.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/gym_ticket.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  code/modules/sanity/sanity_mob.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/drinks.dmi
  icons/obj/gym_ticket.dmi
  icons/obj/machines/gym.dmi
  icons/obj/tools.dmi
  icons/obj/trash.dmi
  icons/obj/vending.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  modular_sojourn/task_master/tasks.dm
  sojourn-station.dme
Labels: Enhancement, Content, Balance, Sprite Work

#4311 Adds Exotic Ammo Disk to Factio
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
Labels: Balance

#4313 Infestation fixes
  maps/__Nadezhda/area/_Nadezhda_areas.dm
Labels: Bug-Fix

#4314 Ruins everything, Again.
  code/__DEFINES/reagents.dm
  code/modules/reagents/reagents/stims.dm
Labels: Balance

#4315 fixes venders not giving tasks and level up sound
  code/game/machinery/vending.dm
  code/modules/sanity/sanity_mob.dm
  modular_sojourn/task_master/task_helpers.dm
  modular_sojourn/task_master/tasks.dm
Labels: Duplicate, Bug-Fix

#4317 QoL - Lodge roles
  code/datums/outfits/jobs/off_colony.dm
Labels: Balance

#4318 Stuff for events
  code/modules/admin/admin_verbs.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/sanity/sanity_lists.dm
  code/modules/sanity/sanity_mob.dm
  icons/mob/64x64.dmi
Labels: Content, Balance, Sprite Work

#4321 Echomic deasters
  code/game/gamemodes/scores.dm
  code/game/jobs/department.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Removal

#4324 Ports a infi loop fix
  code/modules/sanity/sanity_mob.dm
Labels: Bug-Fix

#4323 Infestation fixes re-add
  maps/__Nadezhda/area/_Nadezhda_areas.dm
Labels: Bug-Fix

#4316 Soteria skirts, shared comms, mapfixes and more
  code/controllers/communications.dm
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/curtains.dm
  code/game/objects/structures/flora/flora.dm
  code/game/objects/structures/flora/flora_potted.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/energy/misc/slimegun.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/stylesheet.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/_DeepForest/map/_River_To_Swamp.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  modular_sojourn/task_master/tasks.dm
  nano/templates/radio_basic.tmpl
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
Labels: Enhancement, Bug-Fix, Content, Balance, Sprite Work

#4327 Ports a few things
  code/__DEFINES/perf_test.dm
  code/__DEFINES/subsystems-priority.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/_logging.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/machines.dm
  code/controllers/subsystems/mapping.dm
  code/controllers/subsystems/processing/airflow.dm
  code/controllers/subsystems/processing/objs.dm
  code/controllers/subsystems/processing/processing.dm
  code/datums/craft/menu.dm
  code/datums/craft/step.dm
  code/datums/datum.dm
  code/game/machinery/smelter.dm
  code/game/machinery/sorter.dm
  code/game/world.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/dungeons/procedural/deepmaint.dm
  code/modules/dungeons/procedural/jp_dungeon_gen.dm
  code/modules/flufftext/TextFilters.dm
  code/modules/maps/tg/map_template.dm
  nano/templates/smelter.tmpl
  nano/templates/sorter.tmpl
  sojourn-station.dme
Labels: Documentation, Enhancement, Bug-Fix

#4328 Soteria skirts quickfix
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/jobs/medsci.dm
  icons/obj/guns/projectile/mateba.dmi
Labels: Bug-Fix

#4329 Enclave Bot Salt
  code/modules/hivemind/mobs.dm
Labels: Balance, Skill-Issue | Salt PR

#4330 Smelter fix, ana not with levels and nsa changes
  code/game/machinery/smelter.dm
  code/modules/aberrants/organs/_defines.dm
  code/modules/reagents/metabolism.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/sanity/sanity_mob.dm
Labels: Bug-Fix, Balance

#4335 Changes the absolute's pronouns
  code/datums/perks/oddity.dm
Labels: Documentation

#4334 Makes smelters possible to be 100% efficient
  code/game/machinery/smelter.dm
Labels: Balance

#4333 New marshal coat and some old church sprites
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Content, Sprite Work

#4336 adds a safty check to chems
  code/modules/reagents/reagents.dm
Labels: Balance

#4332 Premier turtlenecks addition (plz review code just incase I goofed)
  code/modules/client/preference_setup/loadout/lists/factioncommand.dm
  code/modules/clothing/under/casual.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Content, Sprite Work

#4337 Trash beacon + fluff + small slots balance
  code/game/objects/items/weapons/storage/wallets.dm
  code/game/objects/random/cigarettes.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/scrap.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/world_building.dm
  code/modules/gambling/slot_machine.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/scrap/scrap.dm
  code/modules/scrap/scrap_beacon.dm
  sojourn-station.dme
Labels: Content, Balance

#4339 Revert "Echomic deasters"
  code/game/gamemodes/scores.dm
  code/game/jobs/department.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance

#4338 Freelancer as alt-title for colonist
  code/game/jobs/job/assistant.dm
Labels: Enhancement

#4340 eris ports and locker changes
  code/datums/outfits/jobs/security.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/random/cloth.dm
  code/game/objects/structures/coathanger.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/admin/verbs/debug.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/accessories/badges.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/projectiles/gun.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/inventory/uniform/spriting.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Balance, Sprite Work

#4331 Rebalances nanogate inspiration
  code/modules/sanity/sanity_mob.dm
Labels: Balance

#4341 Department Account Tweaks
  code/game/jobs/department.dm
Labels: Balance

#4342 bartweaks
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#4343 Small spite updates for misc things
  icons/obj/items.dmi
  icons/obj/janitor.dmi
Labels: Balance, Sprite Work

#4344 map fixes
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/submaps/map_clearers/burnt_post_voidwolf_reclaimed.dmm
Labels: Map

#4346 Guild TEG changes + small bar mapfix
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
  maps/__Nadezhda/nadezhda.dm
Labels: Balance, Map

#4345 Adjusted Robotic Limbs
  code/modules/organs/organ.dm
  code/modules/surgery/surgery.dm
Labels: Balance
