Repository sojourn-13/sojourn-station, pull requests merged in 2023-02, with the labels that each got.

#4349 Oh wow another QoL patch what a surprise
  code/datums/mob_stats.dm
  code/datums/topic/admin.dm
  code/game/gamemodes/events/holidays/Christmas.dm
  code/game/machinery/crafting_station.dm
  code/game/machinery/vendor/cloathing.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/devices/scanners/health.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/under/casual.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/energy/laser/laser.dm
  code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/mob/items/righthand.dmi
  icons/obj/drinks.dmi
  icons/obj/guns/projectile/gyropistol.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Underground.dmm
  sound/effects/creatures/barking.ogg
  sound/effects/creatures/death_whine.ogg
  sound/effects/creatures/ian_beg.ogg
  sound/effects/creatures/puppy_beg.ogg
Labels: Enhancement, Bug-Fix, Balance, Sprite Work

#4350 giving it a shot
  code/modules/library/lib_items.dm
  code/modules/paperwork/filingcabinet.dm
  tgui/packages/tgui/interfaces/BookCase.js
  tgui/packages/tgui/interfaces/FilingCabinet.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Balance

#4351 Tgui basic stuff MK II linter addition
  tgui/packages/tgui/interfaces/BookCase.js
  tgui/packages/tgui/interfaces/FilingCabinet.js
  tools/build/build.js
Labels: Bug-Fix

#4353 New Absolute Wintercoat 2023
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
  code/modules/clothing/suits/greatcoat.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Balance, Sprite Work

#4352 Ammo box and quality of life.
  code/game/machinery/excelsior/blackshield_teleporter.dm
Labels: Balance

#4357 miner news once again
  code/modules/modular_computers/file_system/news_article.dm
  news_articles/Emily_chu.html
Labels: Content

#4356 Fixes mapping issues in solars + colored pipes + pipe painter
  maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
Labels: Bug-Fix

#4360 bulletainboard and folders
  code/game/objects/structures/noticeboard.dm
  code/modules/library/lib_items.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  tgui/packages/tgui/interfaces/FilingCabinet.js
  tgui/packages/tgui/interfaces/Folder.js
  tgui/public/tgui.bundle.js
Labels: Documentation, Enhancement, javascript

#4361 ports over tgui'ed oresmelter
  code/__DEFINES/materials.dm
  code/modules/mining/alloys.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/ore.dm
  code/modules/mining/ore_datum.dm
  icons/obj/mining.dmi
  tgui/packages/tgui/interfaces/Processor.js
  tgui/public/tgui.bundle.js
Labels: Bug-Fix, Balance, javascript

#3837 The cooking rework, PART 1
  code/__DEFINES/cooking_with_jane.dm
  code/__HELPERS/text.dm
  code/__HELPERS/time.dm
  code/_onclick/ai.dm
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/game/world.dm
  code/modules/client/asset_cache.dm
  code/modules/cooking_with_jane/cooking.dm
  code/modules/cooking_with_jane/cooking_appliances/appliance_defines.dm
  code/modules/cooking_with_jane/cooking_appliances/cooking_circuits.dm
  code/modules/cooking_with_jane/cooking_appliances/grill.dm
  code/modules/cooking_with_jane/cooking_appliances/machinery.dm
  code/modules/cooking_with_jane/cooking_appliances/oven.dm
  code/modules/cooking_with_jane/cooking_appliances/stove.dm
  code/modules/cooking_with_jane/cooking_catalog.dm
  code/modules/cooking_with_jane/cooking_init.dm
  code/modules/cooking_with_jane/cooking_items/cooking_containers.dm
  code/modules/cooking_with_jane/cooking_items/dollop.dm
  code/modules/cooking_with_jane/cooking_items/frosting.dm
  code/modules/cooking_with_jane/cooking_items/spatula.dm
  code/modules/cooking_with_jane/cooking_tracker.dm
  code/modules/cooking_with_jane/food_overrides.dm
  code/modules/cooking_with_jane/porting_readme.txt
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/step_defines.dm
  code/modules/cooking_with_jane/step_types/add_item.dm
  code/modules/cooking_with_jane/step_types/add_produce.dm
  code/modules/cooking_with_jane/step_types/add_reagent.dm
  code/modules/cooking_with_jane/step_types/recipe_start.dm
  code/modules/cooking_with_jane/step_types/use_grill.dm
  code/modules/cooking_with_jane/step_types/use_item.dm
  code/modules/cooking_with_jane/step_types/use_oven.dm
  code/modules/cooking_with_jane/step_types/use_stove.dm
  code/modules/cooking_with_jane/step_types/use_tool.dm
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  code/modules/modular_computers/file_system/catalog.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/cooking_with_jane
  icons/obj/cwj_cooking/eris_kitchen.dmi
  icons/obj/cwj_cooking/grill.dmi
  icons/obj/cwj_cooking/kitchen.dmi
  icons/obj/cwj_cooking/oven.dmi
  icons/obj/cwj_cooking/scan.dmi
  icons/obj/cwj_cooking/stove.dmi
  maps/Centcom/map/centcom.dmm
  nano/images/The_B.png
  nano/templates/catalog_entry_cooking.tmpl
  nano/templates/catalog_list_cooking.tmpl
  nano/templates/cooking_catalog.tmpl
  sojourn-station.dme
Labels: Documentation, Enhancement, Help Wanted, New Content, Content, Balance, Sprite Work, Sound Addition

#4364 fixes mining stuff
  code/modules/mining/machine_processing.dm
  icons/obj/mining.dmi
Labels: Bug-Fix

#4363 adds female church robe sprites
  icons/inventory/uniform/mob_fem.dmi
Labels: Bug-Fix

#4365 Guild's redecoration of the workshop + church conveyor starts on
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
Labels: Balance, Map

#4366 The cooking rework
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/cooking_with_jane/cooking_catalog.dm
  code/modules/cooking_with_jane/food_overrides.dm
Labels: Bug-Fix

#4368 Alchemy Addition
  code/game/objects/effects/decals/crayon.dm
  code/modules/reagents/machinery/alchemy.dm
Labels: Enhancement, Content, Balance

#4369 Bugfixes and more stuff trilby pls don't rush me :(
  code/datums/autolathe/guns.dm
  code/game/machinery/kitchen/petrel_maker.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/posters/bs12.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/under/casual.dm
  code/modules/mob/living/simple_animal/hostile/dino.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/contraband.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Bug-Fix, Content, Balance, Sprite Work, Map

#4370 gives lodge roles access to alchemy
  code/game/jobs/job/offcolony.dm
  code/modules/library/lib_items.dm
  code/modules/organs/internal/psionic.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/folders.dm
  code/modules/reagents/machinery/alchemy.dm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Balance

#4372 stuff before stuff
  code/game/machinery/vendor/food_vendors.dm
  code/modules/cooking_with_jane/cooking_items/cooking_containers.dm
  code/modules/cooking_with_jane/recipes/_read_me.dm
  code/modules/cooking_with_jane/recipes/example_recipes.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Documentation, Balance, Map

#4374 Time To Duel!
  code/game/objects/effects/decals/crayon.dm
Labels: Enhancement, Content

#4375 Adds more Gun Frames, Parts, and Items to LSS Beacon & Armory
  code/datums/autolathe/gun_frames.dm
  code/datums/autolathe/parts.dm
  code/datums/craft/gun_parts.dm
  code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/freedom.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/revolver/judge.dm
  code/modules/projectiles/guns/projectile/shotgun/riot.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  icons/obj/crafts.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance

#4377 more gun frame spawns and changed rng
  code/game/machinery/crafting_station.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/hardcases.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/structures/crates_lockers/closets/maint_loot.dm
  code/game/objects/structures/crates_lockers/closets/onestar.dm
  code/modules/scrap/scrap.dm
Labels: Bug-Fix, Balance

#4378 air alarm + scrubbers fixes (this one does not causes lag)
  code/__DEFINES/machinery.dm
  code/game/machinery/alarm.dm
Labels: Bug-Fix

#4379 gun frame fixes
  code/modules/projectiles/guns/projectile/automatic/bastard.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/dp.dm
  code/modules/projectiles/guns/projectile/automatic/freedom.dm
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/pulse_rifle.dm
  code/modules/projectiles/guns/projectile/automatic/specop.dm
  code/modules/projectiles/guns/projectile/automatic/tommygun.dm
  code/modules/projectiles/guns/projectile/automatic/vintorez.dm
  code/modules/projectiles/guns/projectile/boltgun/armstrong.dm
  code/modules/projectiles/guns/projectile/boltgun/roe_sika.dm
  code/modules/projectiles/guns/projectile/pistol/basilisk.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/glock.dm
  code/modules/projectiles/guns/projectile/pistol/judiciary.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
  code/modules/projectiles/guns/projectile/revolver/detective.dm
  code/modules/projectiles/guns/projectile/revolver/hornet.dm
  code/modules/projectiles/guns/projectile/revolver/judge.dm
  code/modules/projectiles/guns/projectile/revolver/mistral.dm
  code/modules/projectiles/guns/projectile/revolver/revolver.dm
  code/modules/projectiles/guns/projectile/revolver/sixshot.dm
  code/modules/projectiles/guns/projectile/revolver/tacticool_revolver.dm
  code/modules/projectiles/guns/projectile/revolver/wayfarer.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/combatsg.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/pug.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
Labels: Bug-Fix

#4380 Hex cooking convering
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  sojourn-station.dme
Labels: Content, Balance

#4381 Update _Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance, Map, Removal

#4384 more gun frame stuff
  code/datums/craft/gun_parts.dm
  code/game/objects/random/guns.dm
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
  code/modules/projectiles/guns/projectile/automatic/texan.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/boltgun/armstrong.dm
  code/modules/projectiles/guns/projectile/boltgun/handmade.dm
  code/modules/projectiles/guns/projectile/boltgun/novakovic.dm
  code/modules/projectiles/guns/projectile/boltgun/roe_sika.dm
  code/modules/projectiles/guns/projectile/boltgun/scout.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/revolver/handmade.dm
  code/modules/projectiles/guns/projectile/revolver/judge.dm
  code/modules/projectiles/guns/projectile/revolver/sixshot.dm
  icons/obj/crafts.dmi
Labels: Bug-Fix, Balance

#4386 Adds RPG to BS Armory
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Balance, Map

#4387 Autolathe Rebalancing
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/autolathe/mechfab.dm
  code/game/machinery/bioprinter_nt.dm
  code/modules/research/rdmachines.dm
Labels: Balance

#4390 Spec Op & Misc
  code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
  code/modules/projectiles/guns/projectile/automatic/specop.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
Labels: Bug-Fix

#4391 The prophesized autolathe buff
  code/game/machinery/bioprinter_nt.dm
Labels: Balance

#4394 Date in Status
  code/modules/mob/mob.dm
Labels: Wont fix, Skill-Issue | Salt PR

#4393 Add Food Qualifiers
  code/modules/cooking_with_jane/cooking.dm
  code/modules/cooking_with_jane/cooking_catalog.dm
  code/modules/cooking_with_jane/food_overrides.dm
  code/modules/cooking_with_jane/porting_readme.txt
  code/modules/cooking_with_jane/recipes/_read_me.dm
  code/modules/cooking_with_jane/recipes/example_recipes.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/modular_computers/computers/subtypes/preset_pda.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  nano/templates/catalog_entry_cooking.tmpl
Labels: Enhancement, Bug-Fix

#4396 Fixes heavy barrel printing
  code/datums/craft/gun_parts.dm
Labels: Bug-Fix

#4395 Equalize ritual
  code/game/objects/effects/decals/crayon.dm
  maps/Centcom/map/centcom.dmm
Labels: Content, Balance

#4398 oil burner fix
  code/datums/craft/recipes/alchemy.dm
Labels: Bug-Fix

#4400 more cooking repices
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
Labels: Content, Balance

#4406 Eris's ATMOSPHERICS folder
  code/ATMOSPHERICS/_atmos_setup.dm
  code/ATMOSPHERICS/_atmospherics_helpers.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/circulator.dm
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/binary_devices/volume_pump.dm
  code/ATMOSPHERICS/components/omni_devices/filter.dm
  code/ATMOSPHERICS/components/omni_devices/mixer.dm
  code/ATMOSPHERICS/components/omni_devices/omni_base.dm
  code/ATMOSPHERICS/components/portables_connector.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/ATMOSPHERICS/components/tvalve.dm
  code/ATMOSPHERICS/components/unary/cold_sink.dm
  code/ATMOSPHERICS/components/unary/generator_input.dm
  code/ATMOSPHERICS/components/unary/heat_exchanger.dm
  code/ATMOSPHERICS/components/unary/heat_source.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/oxygen_generator.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/components/valve.dm
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/ATMOSPHERICS/datum_pipeline.dm
  code/ATMOSPHERICS/mainspipe.dm
  code/ATMOSPHERICS/pipes.dm
  code/__DEFINES/atmos.dm
  code/game/machinery/atmoalter/meter.dm
Labels: Enhancement, Bug-Fix

#4403 New Lantern Sprite from F13
  icons/obj/lighting.dmi
Labels: Sprite Work

#4407 Introduces a new hog mob for the garden to start
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  icons/mob/mobs-domestic.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Enhancement, Content, Balance

#4408 more repices again and fixes
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
Labels: Bug-Fix, Content

#4404 Bees wax to bees
  code/game/objects/effects/decals/crayon.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
Labels: Content

#4410 SM Pipe fix
  maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
Labels: Bug-Fix

#4411 Uses pixel scaling in general to combat blurness in general
  code/__DEFINES/_planes+layers.dm
  code/_onclick/hud/plane_master.dm
  code/_onclick/hud/radial.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/progressbar.dm
  code/game/atoms.dm
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/policetape.dm
  code/game/objects/structures/firepits.dm
  code/modules/mob/animations.dm
  code/modules/mob/living/carbon/human/species/forms/station.dm
  code/modules/mob/living/carbon/human/species/forms/station_unusual.dm
  code/modules/mob/observer/ghost/login.dm
  code/modules/mob/observer/observer.dm
  code/modules/organs/external/organ_icon.dm
  code/modules/scrap/scrap.dm
  code/modules/xgm/xgm_gas_data.dm
Labels: Bug-Fix

#4412 Dormsandbarrework
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#4414 News update
  code/modules/modular_computers/file_system/news_article.dm
  news_articles/An_odd_twist_of_fate.html
  news_articles/Full_stop.html
  news_articles/The_month_in_recap.html
Labels: Documentation

#4418 Being on fire is now bad for everyone's health (buff or nerf?)
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Balance

#4405 I see you quiver with antici...
  code/datums/autolathe/biomatter.dm
  code/datums/craft/gun_parts.dm
  code/datums/craft/recipes/storage.dm
  code/game/machinery/crafting_station.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/random/guns.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/materials/material_sheets.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/luger.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/ppsh.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/automatic/specop.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/automatic/tommygun.dm
  code/modules/projectiles/guns/projectile/boltgun/handmade.dm
  code/modules/projectiles/guns/projectile/boltgun/roe_sika.dm
  code/modules/projectiles/guns/projectile/boltgun/scout.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/revolver/breakaction.dm
  code/modules/projectiles/guns/projectile/revolver/tacticool_revolver.dm
  icons/inventory/belt/mob.dmi
  icons/inventory/pockets/icon.dmi
  icons/obj/crafts.dmi
  icons/obj/guns/bow.dmi
  icons/obj/guns/launcher/crossbow-solid.dmi
Labels: Content, Balance, Sprite Work

#4422 A-Z Seed Vendor + Lil Booze-O-Mat Organization
  code/game/machinery/vendor/food_vendors.dm
Labels: Documentation

#4420 Death optimization
  code/modules/mob/death.dm
Labels: Bug-Fix

#4425 VIKA name fix
  nano/templates/cooking_catalog.tmpl
Labels: Bug-Fix

#4424 Cheap Gun Modularity + Fixes
  code/__DEFINES/projectile_defines.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/nail_gun.dm
  code/modules/projectiles/guns/projectile/automatic/ostwind.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/boltgun/handmade.dm
  code/modules/projectiles/guns/projectile/revolver/handmade.dm
  code/modules/projectiles/guns/projectile/shotgun/handmade.dm
  icons/obj/guns/projectile/ak_homemade.dmi
Labels: Bug-Fix, Balance

#4423 fixes mechs dropping invisable stuff
  code/game/mecha/combat/combat.dm
  code/game/mecha/medical/medical.dm
  code/game/mecha/working/working.dm
  code/modules/holodeck/HolodeckObjects.dm
Labels: Bug-Fix

#4421 Small rebalace of church prayers
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Bug-Fix, Balance

#4426 fixes spicy food gibbing you
  code/modules/mob/living/living_defense.dm
Labels: Balance

#4427 Solmarine Fix Again
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
Labels: Bug-Fix

#4429 firstaidkit refactor
  code/datums/autolathe/biomatter.dm
  code/datums/craft/recipes/lodge.dm
  code/datums/perks/racial.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/vendor/medical_vendors.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/ichor.dm
  code/game/objects/items/stacks/medical_stacks/medical.dm
  code/game/objects/items/stacks/medical_stacks/nanopaste.dm
  code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
  code/game/objects/items/stacks/medical_stacks/splint_stacks.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/vendor_loot_boxes.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/surgery/organic_damage.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/wound_repair.dm
  maps/Centcom/map/centcom.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance

#4434 Drip Infusion
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/head/misc.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: Content, Balance, Sprite Work

#4433 Fixes atk sprites and new goggle
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
  code/game/objects/random/cloth.dm
  code/modules/clothing/glasses/misc.dm
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/obj/stack/items.dmi
Labels: Bug-Fix, Sprite Work

#4436 Drip Infusion hotfix
  code/modules/client/preference_setup/loadout/lists/accessories.dm
Labels: Bug-Fix

#4435 'cowboy' tactical poncho
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
Labels: Sprite Work

#4437 Outsider now spawns in a single location
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_Prepper_Bunker.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/_DeepForest/map/_River_Forest_old.dmm
  maps/_DeepForest/map/_River_To_Swamp.dmm
Labels: Map

#4438 V-day hair pins
  code/datums/craft/recipes/misc.dm
  code/modules/clothing/head/misc.dm
Labels: Content

#4432 People can use now earings
  code/modules/client/preference_setup/loadout/lists/cosmetics.dm
  code/modules/clothing/head/misc.dm
  icons/inventory/head/icon.dmi
Labels: Sprite Work

#4440 Fixes Female Plate Carriers
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#4442 Revert "Outsider now spawns in a single location"
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_DeepForest/map/_Prepper_Bunker.dmm
  maps/_DeepForest/map/_River_Forest.dmm
  maps/_DeepForest/map/_River_Forest_old.dmm
  maps/_DeepForest/map/_River_To_Swamp.dmm
Labels: Skill-Issue | Salt PR, Map, Removal

#4439 Morehex+cooking
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
Labels: Enhancement, Content, Balance

#4445 Object verbs for cooking
  code/modules/cooking_with_jane/cooking_appliances/grill.dm
  code/modules/cooking_with_jane/cooking_appliances/oven.dm
  code/modules/cooking_with_jane/cooking_appliances/stove.dm
Labels: Bug-Fix

#4447 New Mutations
  code/__DEFINES/genetics.dm
  code/modules/genetics/creatures/bioshock.dm
  code/modules/genetics/creatures/golden_roach.dm
  code/modules/genetics/machinery/genetics_items.dm
  code/modules/genetics/mutations/disability.dm
  code/modules/genetics/mutations/friendly.dm
  code/modules/genetics/mutations/phasing.dm
  code/modules/genetics/recipes/abilities.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/misc.dm
  sojourn-station.dme
Labels: Content, Balance

#4448 Scrolls
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/game/objects/effects/decals/crayon.dm
  code/modules/library/lib_items.dm
  code/modules/reagents/machinery/alchemy.dm
  code/modules/reagents/reagents/other.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/scroll_bandange.dmi
  maps/Centcom/map/centcom.dmm
Labels: Enhancement, Content, Sprite Work

#4451 Prospie changes
  code/game/jobs/job/prospector.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Balance

#4347 Title changes
  code/__DEFINES/jobs.dm
  code/datums/outfits/jobs/security.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/vouchers.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Enhancement

#4454 Adds a new Absolutist uniform
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Sprite Work

#4457 scroll spell updoot
  code/game/objects/effects/decals/crayon.dm
Labels: Enhancement, Content

#4455 TGUI atmos_alert.dm
  code/game/machinery/computer/atmos_alert.dm
Labels: Enhancement

#4453 Gp vender enhancement
  code/game/machinery/vendor/one_star_vending.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm
  icons/obj/drinks.dmi
  icons/obj/food.dmi
  icons/obj/machines/one_star/vending.dmi
  icons/obj/trash.dmi
Labels: Enhancement, Bug-Fix, Balance, Sprite Work

#4458 Revert "Title changes"
  code/__DEFINES/jobs.dm
  code/datums/outfits/jobs/security.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/vouchers.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Documentation

#4459 small gun flip on spawns
  code/game/machinery/autolathe/nanite_reconstitution_apparatus.dm
  code/game/objects/random/guns.dm
Labels: Bug-Fix, Balance

#4460 Prospector & Lonestar Coms Change + Sergeant gets Marshal Coms
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
Labels: Balance

#4461 Sergeant Headset Addition
  code/datums/outfits/jobs/security.dm
Labels: Bug-Fix

#4456 tools nerf
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
Labels: Balance

#4452 Drippening II: I Fucking Hate Accessory Code
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/mob/new_player/preferences_setup.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
Labels: Enhancement, Sprite Work

#4450 Piping changes 2: electric bogaloo (Guild buff and nerf)
  code/ATMOSPHERICS/components/binary_devices/circulator.dm
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pipeturbine.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/binary_devices/volume_pump.dm
  code/ATMOSPHERICS/components/omni_devices/filter.dm
  code/ATMOSPHERICS/components/omni_devices/mixer.dm
  code/ATMOSPHERICS/components/omni_devices/omni_base.dm
  code/ATMOSPHERICS/components/portables_connector.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/ATMOSPHERICS/components/tvalve.dm
  code/ATMOSPHERICS/components/unary/cold_sink.dm
  code/ATMOSPHERICS/components/unary/generator_input.dm
  code/ATMOSPHERICS/components/unary/heat_exchanger.dm
  code/ATMOSPHERICS/components/unary/heat_source.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/oxygen_generator.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/components/valve.dm
Labels: Enhancement

#4462 Fixes negative power draw on scrubbers/vents (again)
  code/ATMOSPHERICS/_atmospherics_helpers.dm
Labels: Bug-Fix

#4463 APC -> TGUI (another Guild buff...really)
  code/modules/power/apc.dm
Labels: Enhancement

#4465 two new tasks and borrow sealing refractor-ish
  code/game/objects/structures/burrows.dm
  code/modules/reagents/reagent_containers/pill.dm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/tasks.dm
Labels: Content, Balance

#4468 Re-allows admins to use APCs
  code/_onclick/ghost.dm
  code/_onclick/other_mobs.dm
  code/modules/power/apc.dm
  code/modules/tgui/states/admin.dm
Labels: Bug-Fix

#4464 SMES -> TGUI (yet another guild buff, trust me)
  code/modules/power/power.dm
  code/modules/power/smes.dm
Labels: Enhancement

#4466 Fixes the grammar skill issue of catto
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/superior_animal/robots/robot.dm
Labels: Bug-Fix

#4471 Nullifer fix
  code/modules/core_implant/cruciform/machinery/onlooker.dm
Labels: Bug-Fix

#4473 fixes a bunch of repices
  code/modules/cooking_with_jane/recipes/recipe.dm
Labels: Bug-Fix

#4467 Funny title about yet another QoL patch of mine
  code/datums/craft/gun_parts.dm
  code/datums/craft/recipes/clothing.dm
  code/datums/craft/recipes/furniture.dm
  code/datums/craft/recipes/weapon.dm
  code/game/machinery/crafting_station.dm
  code/game/machinery/vendor/cloathing.dm
  code/game/objects/items/paintkit.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/structures/curtains.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/gloves/knuckledusters.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/pulse_rifle.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  code/modules/projectiles/guns/projectile/pistol/judiciary.dm
  code/modules/projectiles/guns/projectile/revolver/hornet.dm
  code/modules/projectiles/guns/projectile/revolver/judge.dm
  code/modules/projectiles/guns/projectile/revolver/mistral.dm
  code/modules/projectiles/guns/projectile/revolver/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/handmade.dm
  code/modules/sprite_accessories/_accessory_facial.dm
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/inventory/back/mob.dmi
  icons/inventory/belt/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/mecha/mecha.dmi
  icons/mob/hair.dmi
  icons/mob/hair_facial.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/lefthand_uniforms.dmi
  icons/mob/items/righthand.dmi
  icons/mob/items/righthand_uniforms.dmi
  icons/obj/weapons.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  sound/weapons/renderslash.ogg
Labels: Enhancement, Bug-Fix, Content, Balance, Sprite Work, Skill-Issue | Salt PR, Map, Removal

#4475 Adds Outsider Slots
  code/game/jobs/job/offcolony.dm
Labels: Balance

#4472 Synthetic racial language + AI language adjustments.
  code/__DEFINES/species_languages.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/synthetic.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Bug-Fix, Content

#4476 Streward is no longer head position
  code/game/jobs/job/captain.dm
Labels: Bug-Fix

#4479 Venting in 2023
  code/defines/procs/announce.dm
  sound/misc/Alarm_Emergency_Meeting.ogg
Labels: Sound Addition

#4481 tea party removed and apc fix
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
Labels: Map

#4477 Deepmaintsbuff
  code/game/objects/structures/salvageable.dm
  code/modules/dungeons/procedural/deepmaint.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/attack.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiMega.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiTrash.dm
  maps/submaps/deepmaint_rooms/core/Lab.dmm
  maps/submaps/deepmaint_rooms/core/Lab2.dmm
  maps/submaps/deepmaint_rooms/core/ai_core.dmm
  maps/submaps/deepmaint_rooms/core/lab5.dmm
  maps/submaps/deepmaint_rooms/core/maint_asteroid.dmm
  maps/submaps/deepmaint_rooms/core/medbay.dmm
  maps/submaps/deepmaint_rooms/normal/anomalysci.dmm
  maps/submaps/deepmaint_rooms/normal/barricades.dmm
  maps/submaps/deepmaint_rooms/normal/catwalks.dmm
  maps/submaps/deepmaint_rooms/normal/cryo.dmm
  maps/submaps/deepmaint_rooms/normal/freezer.dmm
  maps/submaps/deepmaint_rooms/normal/garbage.dmm
  maps/submaps/deepmaint_rooms/normal/hydro.dmm
  maps/submaps/deepmaint_rooms/normal/library.dmm
  maps/submaps/deepmaint_rooms/normal/mechbay.dmm
  maps/submaps/deepmaint_rooms/normal/medical.dmm
  maps/submaps/deepmaint_rooms/normal/morgue.dmm
  maps/submaps/deepmaint_rooms/normal/office.dmm
  maps/submaps/deepmaint_rooms/normal/roach.dmm
  maps/submaps/deepmaint_rooms/normal/sm_core.dmm
  maps/submaps/deepmaint_rooms/normal/storage.dmm
  maps/submaps/deepmaint_rooms/normal/toilet.dmm
Labels: Bug-Fix, Content, Balance, Test Merged

#4482 Bloodroot - new plant seed
  code/game/machinery/vendor/food_vendors.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
  icons/obj/hydroponics_growing.dmi
  icons/obj/hydroponics_products.dmi
  icons/obj/seeds.dmi
Labels: Content, Sprite Work

#4483 food fixes
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
  code/modules/reagents/reagent_containers/food/snacks/cakes_pies.dm
  code/modules/reagents/reagent_containers/food/snacks/donut.dm
  code/modules/reagents/reagent_containers/food/snacks/pizza.dm
  code/modules/reagents/reagent_containers/food/snacks/soup.dm
Labels: Bug-Fix

#4485 Fixes the Psions' balls
  code/modules/psionics/psionic_items/psi_temp_items.dm
Labels: Bug-Fix

#4489 three new nanogate perks
  code/__DEFINES/perks.dm
  code/datums/perks/nanogate.dm
  code/modules/nanogate/powers/user.dm
  code/modules/organs/internal/nanogate.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/other.dm
Labels: Bug-Fix, Content, Balance

#4488 Massively buffs bltizshell
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Bug-Fix, Balance

#4487 Naramad Language
  code/__DEFINES/chemistry.dm
  code/__DEFINES/species_languages.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Content

#4493 Records Requirement
  code/modules/mob/new_player/new_player.dm
Labels: Documentation

#4494 fixes
  code/__DEFINES/species_languages.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/synthetic.dm
Labels: Bug-Fix

#4496 Fixes gunmod names
  code/datums/autolathe/parts.dm
  code/datums/craft/recipes/guild.dm
  code/modules/research/designs/weapon.dm
Labels: Bug-Fix

#4492 Eris Med 3.0 & It's Additions Port
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/mobs.dm
  code/game/objects/items/weapons/implant/implants/carrion/infection_spider.dm
  code/modules/assembly/mousetrap.dm
  code/modules/core_implant/cruciform/rituals/inquisitor.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/forms/form.dm
  code/modules/mob/living/carbon/human/species/forms/station.dm
  code/modules/mob/living/carbon/human/unarmed_attack.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/external/dismemberment.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/internal/blood_vessels.dm
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/organs/internal/muscles.dm
  code/modules/organs/internal/nanogate.dm
  code/modules/organs/internal/nerves.dm
  code/modules/organs/pain.dm
  code/modules/organs/surgery_helpers.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/race.dm
  code/modules/reagents/reagents/toxins.dm
Labels: Balance

#4491 Truly a Marshal Buff (Rubber round changes + Pepperballs)
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  icons/obj/ammo.dmi
Labels: Balance, Sprite Work

#4486 I don't have an addiciton to mech games totally
  code/__DEFINES/projectile_defines.dm
  code/datums/craft/recipes/guns.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/equipment/weapons/ranged/bullet_weapons.dm
  code/game/mecha/equipment/weapons/ranged/explosive_weapons.dm
  code/game/mecha/equipment/weapons/ranged/laser_weapons.dm
  code/game/mecha/equipment/weapons/ranged/mech_ammunition.dm
  code/game/objects/random/mecha.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/special.dm
  icons/mecha/mecha_equipment.dmi
  icons/obj/grenade.dmi
  sound/mecha/weapons/autocannon.ogg
  sound/mecha/weapons/burstautocannon.ogg
  sound/mecha/weapons/coilgun.ogg
  sound/mecha/weapons/flakcannon.ogg
  sound/mecha/weapons/laser.ogg
  sound/mecha/weapons/laser_military.ogg
  sound/mecha/weapons/laser_multi.ogg
  sound/mecha/weapons/lbx.ogg
  sound/mecha/weapons/ppc.ogg
  sound/mecha/weapons/scatterautocannon.ogg
  sound/mecha/weapons/ultracannon.ogg
Labels: Content, Balance, Sprite Work

#4500 Decreases Overall Pain by 10%, Decreases Oxy Pain by 40%, & Some other changes
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/shock.dm
Labels: Balance

#4499 Crayon bugfix and balance
  code/game/objects/effects/decals/crayon.dm
Labels: Bug-Fix, Balance

#4504 painkiller changes
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Balance

#4506 sharpened crayons
  code/game/objects/effects/decals/crayon.dm
Labels: Bug-Fix, Content, Balance
