Repository sojourn-13/sojourn-station, pull requests merged in 2023-08, with the labels that each got.

#4686 Re-adding the baroque rifle (test merge recommended)
  code/__DEFINES/projectile_defines.dm
  code/datums/craft/recipes/lodge.dm
  code/datums/perks/nanogate.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  sojourn-station.dme
Labels: Balance, Good-To-Merge

#4739 Im so sick of bugs.
  code/modules/client/preference_setup/loadout/lists/belt.dm
  code/modules/clothing/suits/armor.dm
  code/modules/psionics/psionic_items/psi_Larmor.dm
  code/modules/reagents/reagents/drugs.dm
Labels: Bug-Fix, Balance

#4719 Makes low blood more lethal.
  code/modules/organs/internal/internal_organ_processes.dm
Labels: Balance, Good-To-Merge, Test Merged

#4736 Gives salvagers combat gloves in their locker
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Labels: Balance, Good-To-Merge

#4746 Security buff from cdb? gasp.
  code/game/jobs/job/security.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/triage.dm
  icons/obj/guns/projectile/Osprey.dmi
Labels: Bug-Fix, Balance

#4745 Makes the bar and exterior more stylish
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Map, Test Merged

#4749 Fixing the previous mapping PR. (spaceport)
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Map

#4733 Minor Lodge map edit
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Map
