Repository sojourn-13/sojourn-station, pull requests merged in 2023-11, with the labels that each got.

#4821 Greyson Offices changes
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
Labels: Balance, Map, Test Merged

#4834 Makes non-antag TaxQuickly available on all devices
  code/modules/modular_computers/file_system/programs/generic/taxes.dm
Labels: Bug-Fix, Good-To-Merge

#4798 Adds new mini-room at the lowest maints
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map, Test Merged

#4813 Organ vender spawn rate buff.
  code/modules/aberrants/organs/design_disks/disks.dm
  code/modules/aberrants/organs/spawners.dm
Labels: Balance, Test Merged

#4843 French Toast
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Content

#4844 Bugfix + wanted issue.
  code/game/mecha/equipment/weapons/ranged/laser_weapons.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/modular_computers/file_system/news_article.dm
  code/modules/research/designs/mecha_equipment.dm
  news_articles/wanted_issue_terran.html
Labels: Bug-Fix, Content

#4850 Adds ossi tape to the 3 advanced surgery kits
  code/game/objects/items/weapons/storage/firstaid.dm
Labels: Bug-Fix, Good-To-Merge

#4852 Makes psionic gloves actually insulated as intended
  code/modules/psionics/psionic_items/psi_armor.dm
Labels: Bug-Fix, Good-To-Merge

#4837 more consistent overwear
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
Labels: Balance, Removal, Test Merged

#4833 More! borg buffing/qol and gifts for prospecting.
  code/game/objects/random/cloth.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Good Issue Report, Bug-Fix, Balance, Good-To-Merge

#4846 Tweaks to job restrictions (mostly for synths)
  code/datums/setup_option/backgrounds/origin_chtmant.dm
  code/datums/setup_option/backgrounds/origin_synthetic.dm
  code/datums/setup_option/core_implants.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Balance, Test Merged

#4856 crayon fluff
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/oddities.dm
Labels: Enhancement, Good-To-Merge

#4858 Fixing the croon's firerate (using burst delay instead of fire_delay).dm
  code/modules/projectiles/guns/projectile/automatic/mac.dm
Labels: Balance

#4854 Liberty drill port.
  code/modules/mining/drilling/drill.dm
  code/modules/mining/drilling/termite_burrow.dm
  code/modules/mining/drilling/termite_wave.dm
Labels: Balance, Port

#4862 robot limbs bio protection bugfix
  code/modules/organs/external/subtypes/robotic_types.dm
Labels: Bug-Fix

#4865 armor fixes!
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/psionics/psionic_items/psi_Harmor.dm
  code/modules/psionics/psionic_items/psi_Larmor.dm
Labels: Bug-Fix, Balance

#4859 Eris plasma port and balance
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  code/modules/projectiles/guns/energy/laser/carpediem.dm
  code/modules/projectiles/guns/energy/laser/concilium.dm
  code/modules/projectiles/guns/energy/plasma/cassad.dm
  code/modules/projectiles/guns/energy/plasma/centurio_auretian.dm
  code/modules/projectiles/guns/energy/plasma/excubitor.dm
  code/modules/projectiles/guns/energy/plasma/plasma.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/projectiles/guns/energy/projectile/slab.dm
  code/modules/psionics/psionic_items/psi_weptools.dm
  sound/weapons/energy/burn.ogg
  sound/weapons/energy/incinerate.ogg
  sound/weapons/energy/melt.ogg
  sound/weapons/energy/vaporize.ogg
Labels: Balance, Test Merged

#4860 Adds the disk storage fridge
  code/datums/autolathe/circuits.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/objects/items/weapons/autolathe_disk/guild_disks.dm
  code/game/objects/items/weapons/circuitboards/machinery/smartfridge.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  sojourn-station.dme
Labels: Content, Map, Test Merged

#4849 Greyson Star Traders First PR of a greyson ally of the colony based of a event.
  code/game/machinery/vendor/one_star_vending.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/obj/machines/one_star/vending.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance

#4867 finalized disk storage
  code/game/machinery/kitchen/smartfridge.dm
  icons/obj/vending.dmi
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Enhancement, Bug-Fix, Map

#4864 Fixes/cleans up Urah emote code
  code/modules/mob/living/carbon/human/emote.dm
Labels: Enhancement, Bug-Fix

#4871 disk storage fix
  code/game/machinery/kitchen/smartfridge.dm
Labels: Bug-Fix, Good-To-Merge

#4875 New Wings: Dragon Fold
  code/modules/sprite_accessories/_accessory_wings.dm
  icons/mob/sprite_accessory/wings.dmi
Labels: Enhancement
