Repository sojourn-13/sojourn-station, pull requests merged in 2023-12, with the labels that each got.

#4877 Buffs biojuice tanks
  code/modules/biomatter_manipulation/bioreactor/bioreactor.dm
Labels: Balance, Good-To-Merge

#4876 updates non-records warning
  code/modules/mob/new_player/new_player.dm
Labels: Documentation

#4878 fixes armblade sound
  code/game/objects/items/devices/organ_module/active/armblades.dm
Labels: Bug-Fix

#4880 marshi gun tweaks
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
Labels: Balance, Good-To-Merge

#4887 Recycling vendor: consider stacks of materials in payout and storage
  code/game/machinery/vendor/recycle_vendor.dm
Labels: Balance

#4885 cat tribute
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/modules/mob/living/damage_procs.dm
Labels: Bug-Fix, Balance

#4890 Of Cards and Crayonsolot
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/random/cloth.dm
  modular_sojourn/cardgame_2/cardgame_2.dm
  modular_sojourn/cardgame_2/cardpacks_and_spawner.dm
Labels: Bug-Fix, Balance

#4892 fix own bug that prevented the recycling vendor from accepting items
  code/game/machinery/vendor/recycle_vendor.dm
Labels: Bug-Fix

#4886 Sensible greyson suit
  code/game/machinery/vendor/one_star_vending.dm
  code/game/objects/effects/spawners/corpsespawner.dm
  code/game/objects/random/cloth.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship.dm
Labels: Balance

#4888 Ports a few updated icons from Eris + New Medhud
  icons/mob/hud.dmi
  icons/obj/power.dmi
  icons/obj/stack/items.dmi
  icons/obj/stationobjs.dmi
Labels: Question, Sprite Work, Port, changes requested

#4883 misc map fixes
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Map, Test Merged

#4881 useful mech chargers
  code/game/mecha/mech_bay.dm
Labels: Balance, Test Merged

#4873 Ports KARL from eris
  code/game/objects/items/weapons/tools/karl.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/karl_mining.dmi
  maps/CEVEris/_CEV_Eris.dmm
  sojourn-station.dme
Labels: Balance, Sprite Work, Test Merged, Port

#4891 Defib revert
  code/datums/outfits/jobs/medical.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/projectiles/guns/energy/projectile/sst.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
Labels: Balance, Test Merged

#4894 med map changes
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map, Test Merged

#4898 Removes duplicate APC from forest excel bunker
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Bug-Fix, Map

#4897 Ports
  code/game/objects/items/contraband.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/scrap/oldificator.dm
  icons/obj/chemical.dmi
  icons/obj/doors/rapid_pdoor.dmi
Labels: Enhancement, Sprite Work, Test Merged, Port

#4896 guns and bullets
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance, Test Merged

#4900 psion sleepy time powers return
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
Labels: Balance, Skill-Issue | Salt PR

#4904 Elite Armor
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
Labels: Bug-Fix, Balance
