Repository sojourn-13/sojourn-station, pull requests merged in 2024-06, with the labels that each got.

#5391 fixes missing/mislabled borg icons
  icons/mob/robot_tall/janitor.dmi
  icons/mob/robot_tall/mining.dmi
  icons/mob/robot_tall/misc.dmi
  icons/mob/robot_tall/server.dmi
Labels: Bug-Fix, Sprite Work

#5353 [balance] New burn-wound medicine
  code/__DEFINES/chemistry.dm
  code/modules/organs/internal/internal_wounds/organic.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Content, Balance

#5328 saving xenobotany from itself
  code/game/machinery/vendor/food_vendors.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Nuclear Option, Test Merged

#5331 Remaps the engine chamber to allow for larger engines
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5335 [Removal] Removes partial understanding on monkey for common and for common on monkey
  code/modules/mob/language/monkey.dm
  code/modules/mob/language/station.dm
Labels: Removal

#5338 [balance] Removes the Laser-Core from the Trooper starting options.
  code/game/machinery/vendor/weapon_kit_vendors.dm
Labels: Balance

#5396 [balance] Contaminiated items respect bio_armor now
  code/modules/mob/living/carbon/human/life.dm
Labels: Balance

#5398 Ditch abiotic checks in scanner/cryo cell, make cryo eject dropped items
  code/game/machinery/adv_med.dm
  code/game/machinery/cryo.dm
Labels: Bug-Fix, Balance

#5397 note boards for bulk selling
  code/game/objects/structures/noticeboard.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Enhancement, Bug-Fix, Map

#5394 TEFs changes to xenobio/slimegun
  code/modules/projectiles/guns/energy/misc/slimegun.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5406 Fix Computer Subtype Sprites being wrong
  code/modules/modular_computers/computers/subtypes/dev_tablet.dm
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  code/modules/modular_computers/computers/subtypes/preset_pda.dm
  code/modules/nanogate/nanogate_vm.dm
Labels: Bug-Fix

#5402 Make people spawn directly at appropriate locations
  code/controllers/subsystems/ticker.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/transform_procs.dm
Labels: Bug-Fix, Balance

#5388 More QOL for borgs and minor AI bugfix
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance, Test Merged

#5370 Xenohydro relayed out!
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map, Removal, Test Merged

#5373 Market Exspert fix + surplus tag fix
  code/controllers/subsystems/trade.dm
  code/game/objects/items.dm
Labels: Bug-Fix, Balance

#5392 Adds area to SLT helmet alerts, suit sensor changes
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
Labels: Enhancement, Test Merged

#5390 Ports various cold assets
  code/game/machinery/atmoalter/scrubber.dm
  code/game/objects/structures/flora/flora.dm
  code/game/objects/structures/flora/flora_tree.dm
  code/game/sound.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  icons/obj/flora/snowflora.dmi
  icons/obj/flora/snowrocks.dmi
  icons/obj/flora/snowtree.dmi
  icons/turf/flooring/icewater.dmi
  icons/turf/flooring/newsnow.dmi
  icons/turf/flooring/snows.dmi
  sound/effects/footstep/ice1.ogg
  sound/effects/footstep/ice2.ogg
  sound/effects/footstep/ice3.ogg
  sound/effects/footstep/ice4.ogg
  sound/effects/footstep/ice5.ogg
  sound/effects/footstep/snow1.ogg
  sound/effects/footstep/snow2.ogg
  sound/effects/footstep/snow3.ogg
  sound/effects/footstep/snow4.ogg
Labels: Bug-Fix, Balance, Sprite Work, Sound Addition, Port

#5389 Church biomatter rounding
  code/modules/biomatter_manipulation/bioreactor/platform.dm
Labels: Bug-Fix, Balance

#5384 Pouch "rebalance"
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/modules/mob/inventory/slots.dm
Labels: Enhancement, Balance, Skill-Issue | Salt PR, Test Merged

#5376 TGUI Guild Part 3
  code/ATMOSPHERICS/components/omni_devices/filter.dm
  code/ATMOSPHERICS/components/omni_devices/mixer.dm
  code/ATMOSPHERICS/components/unary/cold_sink.dm
  code/ATMOSPHERICS/components/unary/heat_source.dm
  code/_onclick/ai.dm
  code/game/machinery/atmo_control.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/atmoalter/pump.dm
  code/game/machinery/atmoalter/scrubber.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/circuitboards/computer/air_management.dm
  code/modules/power/generator.dm
  html/font-awesome/css/all.min.css
  html/font-awesome/css/v4-shims.min.css
  html/font-awesome/webfonts/fa-regular-400.eot
  html/font-awesome/webfonts/fa-regular-400.woff
  html/font-awesome/webfonts/fa-solid-900.eot
  html/font-awesome/webfonts/fa-solid-900.woff
  maps/__Nadezhda/map/Underground_Old.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Underground.dmm
  sound/machines/synth_buttonpress.ogg
  tgui/packages/tgui/components/LabeledControls.tsx
  tgui/packages/tgui/format.ts
  tgui/packages/tgui/interfaces/AiAirlock.tsx
  tgui/packages/tgui/interfaces/AtmosOmniFilter.tsx
  tgui/packages/tgui/interfaces/AtmosOmniMixer.tsx
  tgui/packages/tgui/interfaces/AtmosPumpPortable.tsx
  tgui/packages/tgui/interfaces/AtmosScrubberPortable.tsx
  tgui/packages/tgui/interfaces/Canister.tsx
  tgui/packages/tgui/interfaces/GasTemperatureControl.tsx
  tgui/packages/tgui/interfaces/GeneralAirControl.tsx
  tgui/packages/tgui/interfaces/GeneralAirControlFuelInjection.tsx
  tgui/packages/tgui/interfaces/GeneralAirControlInputOutput.tsx
  tgui/packages/tgui/interfaces/IDCard.tsx
  tgui/packages/tgui/interfaces/Matterforge.tsx
  tgui/packages/tgui/interfaces/SuitStorageUnit.tsx
  tgui/packages/tgui/interfaces/ThermoelectricGenerator.tsx
  tgui/packages/tgui/interfaces/common/AtmosComponents.tsx
  tgui/packages/tgui/styles/interfaces/Canister.scss
  tgui/packages/tgui/styles/interfaces/IDCard.scss
  tgui/packages/tgui/styles/interfaces/SuitStorageUnit.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Documentation, Enhancement, Balance, Test Merged

#5408 Add a bunch of log_debugs to the new spawning code to try and nail down a problem
  code/modules/mob/new_player/new_player.dm
Labels: Documentation

#5418 KILL EM
  code/__DEFINES/perks.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/effects/perks.dmi
Labels: Balance, Sprite Work

#5410 Fix some miscellaneous startup errors
  code/controllers/subsystems/garbage.dm
  code/datums/transformation_types/transform_types.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/flooring/flooring_effects.dm
Labels: Bug-Fix

#5424 disallows SI synth to be GM
  code/game/jobs/job/engineering.dm
Labels: Balance

#5425 [Hotfix] Hydrogen Sword EMP effect wont crash the server
  code/game/objects/items/weapons/hydrogen_melee.dm
Labels: Bug-Fix, Balance

#5419 Fixes SI outpost atmos setup
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
Labels: Bug-Fix, Map

#5423 [Removal, Hotfix] Hydrogen Sword EMP interaction removal
  code/game/objects/items/weapons/hydrogen_melee.dm
Labels: Bug-Fix, Balance

#5426 Small mob size audit, kitchen spike mob size limit
  code/game/objects/structures/kitchen_spike.dm
  code/modules/genetics/creatures/wasonce.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/mob/living/simple_animal/hostile/misc.dm
Labels: Balance

#5430 Fixes TEF's fluff item, ckeys are always lower case
  code/modules/client/preference_setup/loadout/lists/fluff.dm
Labels: Bug-Fix

#5417 Adds White Absolutist Greatcloak, removes laurel loadout cost
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Balance, Sprite Work

#5414 Nanite Rigsuit can now be removed, also refactored
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/clothing/spacesuits/rig/rig_modules.dm
  code/modules/nanogate/nanogate_items.dm
Labels: Enhancement, Balance

#5409 Bolt Lance Quickpump
  code/modules/projectiles/guns/projectile/shotgun/hunter_crossbow.dm
Labels: Balance

#5400 Mobs targeting turrets
  code/game/machinery/os_portable_turret.dm
  code/game/machinery/portable_turret.dm
  code/game/machinery/tesla_turret.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
Labels: Enhancement, Balance, Test Merged

#5369 deepmaint mobs uniquic attacks
  code/game/objects/random/mob/misc.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/hivemind/objects.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/attack.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/psionics/psionic_items/psi_armor.dm
Labels: Enhancement, Content, Balance

#5434 Pulper auto lable and flesh sac fix
  code/modules/genetics/machinery/genetics_extractor.dm
  code/modules/genetics/machinery/genetics_items.dm
Labels: Bug-Fix

#5403 Trashed Telesci Room™ (An all-you-can-repair-yourself toy)
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5436 Mech fixes
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/equipment/weapons/melee.dm
  code/game/mecha/mecha.dm
Labels: Bug-Fix, Balance

#5437 [READY] [TESTED] Adds a sheath to loadout.
  code/game/objects/items/weapons/storage.dm
  code/modules/client/preference_setup/loadout/lists/belt.dm
  code/modules/client/preference_setup/loadout/lists/clothing.dm
  code/modules/client/preference_setup/loadout/lists/general.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  icons/inventory/belt/mob.dmi
  icons/inventory/on_suit/mob.dmi
  icons/obj/sheath.dmi
Labels: Balance, Sprite Work

#5442 Let mechs compact scrap again
  code/game/mecha/mecha.dm
Labels: Bug-Fix

#5431 fixes some missing perk icons and blood lust maybe
  code/datums/perks/job.dm
  code/datums/perks/perk.dm
  icons/effects/perks.dmi
Labels: Sprite Work

#5427 Adds solar panel upgrade
  code/modules/power/solar.dm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Enhancement, Balance, Nuclear Option

#5428 515 compiling issues + bedsheet bin bug fix
  code/_compile_options.dm
  code/controllers/subsystems/jobs.dm
  code/game/objects/items/oddities.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Bug-Fix, Test Merged

#5404 The Great Cellening, prices for thee AND me
  code/game/objects/items/weapons/power_cells.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
Labels: Balance

#5441 Fix a bunch of runtimes
  code/controllers/subsystems/movement/movement_types.dm
  code/datums/components/clothing_sanity_protection.dm
  code/datums/perks/backgrounds.dm
  code/datums/perks/imprinter_perks.dm
  code/datums/perks/job.dm
  code/datums/perks/nanite_powers.dm
  code/datums/perks/nanogate.dm
  code/datums/perks/nepotism.dm
  code/datums/perks/oddity.dm
  code/datums/perks/perk.dm
  code/datums/perks/psionic.dm
  code/datums/perks/racial.dm
  code/datums/perks/special.dm
  code/game/machinery/bioprinter.dm
  code/modules/cooking_with_jane/cooking_items/cooking_containers.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/modular_computers/hardware/scanners/scanner_price.dm
  code/modules/nano/nanoui.dm
  code/modules/organs/blood.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/core.dm
  code/modules/virus2/isolator.dm
Labels: Bug-Fix, Test Merged

#5433 Rig suit QoL
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
Labels: Balance

#5393 Armor surgery difficulty tweaks
  code/modules/surgery/surgery.dm
Labels: Balance, Test Merged

#5446 tanker helmet path fix
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/lists/factionblackshield.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
Labels: Bug-Fix, Balance

#5448 flesh sacs no longer dump their stuff into the area's loc
  code/modules/genetics/machinery/genetics_items.dm
Labels: Bug-Fix

#5429 Adds Paradise's Click Catcher & Misc. Fixes
  code/__DEFINES/_planes+layers.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/wires/wires.dm
  code/game/mecha/combat/marauder.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/mob/login.dm
  icons/mob/screen_gen.dmi
Labels: Bug-Fix, Balance, Nuclear Option

#5440 fixing map troubles (copypasting)
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Enhancement, Balance, Map

#5444 examination room to upper soteria medical
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5452 Deadsay chat color fixes
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
Labels: Enhancement, Balance, Good-To-Merge

#5457 Fix nanoui throwing errors when moving away
  code/modules/nano/nanoui.dm
Labels: Bug-Fix

#5454 Gun scope toggle hotkey
  code/modules/projectiles/gun.dm
  interface/skin.dmf
Labels: Content

#5453 [Spellcheck] Fixes various typos and grammar on diving messages
  code/modules/mob/living/living.dm
Labels: Documentation

#5432 fixes some omni tool intractions
  code/modules/aberrants/organs/machinery/organ_fabricator.dm
  code/modules/power/hydrogen_generator.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Bug-Fix, Balance

#5461 Fix incorrect spawner name
  code/game/objects/random/mob/misc.dm
Labels: Bug-Fix

#5465 Data star collectors addition
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm
Labels: Balance

#5468 Make faxes log to a place we can actually see as admins
  code/modules/paperwork/faxmachine.dm
Labels: Documentation

#5464 Remove a handful of native BYOND procs we redefine for no reason
  code/__DEFINES/is_helpers.dm
Labels: Enhancement

#5456 robotic aberrants
  code/modules/aberrants/_modification.dm
Labels: Bug-Fix, Balance, Test Merged

#5455 swaps tree spiders with wasps
  code/game/objects/structures/flora/flora_tree.dm
  code/modules/hydroponics/beekeeping/beehive.dm
Labels: Balance

#5450 more gameifed hud
  code/modules/mob/living/carbon/human/life.dm
  icons/mob/hud.dmi
Labels: Balance, Sprite Work

#5472 Add Guidesa's fluff item, the Runed Sheath
  code/game/objects/items/weapons/storage.dm
  code/modules/client/preference_setup/loadout/lists/fluff.dm
  icons/fluff/clothing_mob.dmi
  icons/fluff/fluff_items.dmi
Labels: Content, Balance, Sprite Work

#5473 Added the Uni-Horn to the Markings section under the name "Unicorn Horn"
  code/modules/sprite_accessories/_accessory_marking.dm
  icons/mob/human_races/markings.dmi
Labels: Balance, Sprite Work

#5475 Misc. Fixes
  code/game/machinery/autolathe/matterforge.dm
  code/game/objects/structures/watercloset.dm
  code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
  tgui/packages/tgui/interfaces/Matterforge.tsx
  tgui/packages/tgui/interfaces/Ntos/NtosRcon.tsx
  tgui/packages/tgui/interfaces/Ntos/NtosWord.tsx
  tgui/packages/tgui/styles/interfaces/Vending.scss
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Bug-Fix, Balance

#5462 Supermatter now tied to radiationSS
  code/controllers/subsystems/radiation.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Enhancement, Balance

#5460 Soteria+ Cosmetic Upgrade (Not limited)
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5476 treefix
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Map

#5421 Keg based brewing system
  code/datums/craft/recipes/misc.dm
  code/datums/craft/recipes/storage.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown_predefined.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  icons/obj/drinks.dmi
  icons/obj/objects.dmi
  modular_sojourn/bottler.dm
  modular_sojourn/brewing.dm
  modular_sojourn/brewing_datums.dm
  modular_sojourn/fencer.dmi
  modular_sojourn/guild_rep.dmi
  sojourn-station.dme
Labels: Enhancement, New Content, Balance, Sprite Work

#5471 Make nano wait till the UI loads to send updates
  code/modules/nano/nanoui.dm
  nano/js/nano_utility.js
Labels: Enhancement, Test Merged

#5480 Refactor Disposals and remove Atmos Interactions
  code/modules/genetics/machinery/genetics_cloner.dm
  code/modules/recycling/disposal-construction.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  tgui/packages/tgui/interfaces/DisposalUnit.tsx
  tgui/public/tgui.bundle.js
Labels: Bug-Fix, Balance, Makes-Trilby-Sad

#5466 Revert white mode dsay change
  code/modules/goonchat/browserassets/css/browserOutput_white.css
Labels: Balance

#5458 Psion Verb Swapping
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion.dm
  code/modules/psionics/psion_powers/armour_powers.dm
  code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
  code/modules/psionics/psion_powers/faction_powers.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/locator_powers.dm
  code/modules/psionics/psion_powers/mob_affecting_powers.dm
  code/modules/psionics/psion_powers/oddity_powers.dm
  code/modules/psionics/psion_powers/oldification_powers.dm
  code/modules/psionics/psion_powers/psion_starter_powers.dm
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
  code/modules/psionics/psion_powers/telekinetsis_powers.dm
  code/modules/psionics/psion_powers/teleporation_powers.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
Labels: Enhancement, Balance, Test Merged

#5484 missed a few HEV things. Woops!
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Bug-Fix, Balance

#5481 Adds comb attackverbs
  code/game/objects/items/weapons/cosmetics.dm
Labels: Enhancement

#5487 adds a new maid dress
  code/game/machinery/vendor/cloathing.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/under/costume.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Balance, Sprite Work

#5490 Adds utility Ivan paintjob
  code/game/machinery/vendor/tool_vendors.dm
  code/game/objects/items/paintkit.dm
  icons/mecha/mecha.dmi
Labels: Balance, Sprite Work

#5474 untested fixes to misc things
  code/game/objects/effects/mines.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/traps.dm
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/scrap/scrap_pileripper.dm
Labels: Bug-Fix, Balance

#5469 Wingbat HE Ego
  code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
Labels: Balance, Test Merged

#5488 Adding oddities
  code/game/objects/items/oddities.dm
  code/game/objects/random/oddities.dm
  code/modules/library/lib_items.dm
  code/modules/paperwork/filingcabinet.dm
Labels: Balance

#5478 Colony atmos pass + more maintenance
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#5399 Hardsuit storage module tweaks
  code/modules/clothing/spacesuits/rig/modules/storage.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/research/designs/rigmodules.dm
  code/modules/research/nodes/engineering.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
Labels: Content, Balance

#5479 tile affection
  code/game/objects/structures/turf_spawner.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/turf.dm
  code/modules/mob/mob.dm
  icons/obj/structures.dmi
  modular_sojourn/cement_bag.dm
  modular_sojourn/misc_stuff.dmi
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#5491 Moved foreman disks to prep
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5492 Prospector disks movement PR.2
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Labels: Balance

#5493 nanite RIG resprite
  code/modules/nanogate/nanogate_items.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
Labels: Balance, Sprite Work
