Repository sojourn-13/sojourn-station, pull requests merged in 2024-04, with the labels that each got.

#5136 data_star buff and fixes
  code/game/objects/random/mob/greyson.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm
Labels: Bug-Fix, Balance, Good-To-Merge

#5137 armor and message fixes
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm
Labels: Bug-Fix, Balance

#5135 Adds a verb that lets you toggle verb visibility
  code/game/verbs/toggle_verbs.dm
  sojourn-station.dme
Labels: Balance, Good-To-Merge

#5116 regal sickness
  code/__DEFINES/genetics.dm
  code/modules/genetics/genetics.dm
  code/modules/genetics/machinery/genetics_items.dm
  code/modules/genetics/mutations/vampire.dm
  code/modules/genetics/recipes/blood_based.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/organs/blood.dm
  code/modules/reagents/reagents/core.dm
  code/modules/reagents/reagents/food-Drinks.dm
  sojourn-station.dme
Labels: Balance

#5140 z level check and QoL for toxins
  code/game/objects/explosion.dm
  code/game/objects/explosion_recursive.dm
  code/modules/research/experiment.dm
Labels: Bug-Fix

#5115 having a bad time: Buffing Ossisine while making bone wounds worse.
  code/game/objects/items/weapons/tools/tape.dm
  code/modules/organs/internal/internal_wounds/bone.dm
Labels: Balance

#5050 Readd guns and balance laser bullets
  code/datums/perks/nanogate.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/buckler.dm
  code/modules/projectiles/guns/projectile/boltgun/star_striker.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  sojourn-station.dme
Labels: Documentation, Enhancement, Content, Balance

#5148 the Deboxening: biogen materials made slightly easier
  code/game/machinery/biogenerator.dm
  code/modules/materials/material_sheets.dm
Labels: Balance

#5147 No more meth sandwich
  code/modules/reagents/reagent_containers/food/snacks/sandwich.dm
Labels: Balance, Good-To-Merge

#5146 SWAT
  code/game/objects/items/weapons/storage/hardcases.dm
Labels: Balance

#5138 Update economy.dm
  code/controllers/subsystems/economy.dm
Labels: Balance, Test Merged

#5094 cap pain multiplier from nerves
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/pain.dm
Labels: Balance

#5108 Remaps the Vassily (by Lamasmaster)
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map, Test Merged

#5154 spaghettifix big bushes to be cuttable.
  code/game/objects/structures/flora/flora.dm
Labels: Bug-Fix, Balance

#5139 Fix aberrant infinit reagent
  code/modules/aberrants/organs/mods/component/output.dm
Labels: Balance

#5151 IFF for allied mobs and unique turrets
  code/game/machinery/excelsior/ex_turret.dm
  code/game/machinery/os_portable_turret.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/items/weapons/implant/implants/excelsior.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/drone/types/roomba.dm
  code/modules/projectiles/projectile.dm
Labels: Enhancement, Balance, Test Merged

#5150 Misc psion armor fixes/tweaks
  code/modules/psionics/psion_powers/armour_powers.dm
  code/modules/psionics/psionic_items/psi_Harmor.dm
  code/modules/psionics/psionic_items/psi_Larmor.dm
  code/modules/psionics/psionic_items/psi_armor.dm
  icons/mob/light_overlays.dmi
  icons/obj/psionic/occLmob.dmi
Labels: Bug-Fix, Balance

#5166 fixes borg intractions and misc
  code/modules/cooking_with_jane/cooking_items/cooking_containers.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/subsystems.dm
Labels: Bug-Fix, Balance

#5157 psionic messages
  code/modules/client/preference_setup/global/preferences.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/psionics/psion_powers/psion_starter_powers.dm
Labels: Balance

#5159 Name numbers
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
Labels: Balance, Good-To-Merge

#5130 Squishy heads of staff
  code/game/jobs/job/captain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/security.dm
Labels: Balance

#5096 Career Tweak: Intelligensia Cannot be Hunters + Buff
  code/datums/setup_option/backgrounds/origin_marqua.dm
Labels: Balance

#5168 More cyborg cooking fixes
  code/modules/cooking_with_jane/cooking_appliances/grill.dm
  code/modules/cooking_with_jane/cooking_appliances/oven.dm
  code/modules/cooking_with_jane/cooking_appliances/stove.dm
  code/modules/mob/living/silicon/robot/gripper.dm
Labels: Bug-Fix, Balance

#5158 LC personal shields tweak.
  code/game/mecha/equipment/tools/shields.dm
Labels: Balance, Skill-Issue | Salt PR

#5165 Slimelight restored: QOL changes and re-added recipes
  code/game/machinery/xenobio.dm
  code/game/objects/items/weapons/manuals.dm
  code/modules/reagents/recipes/recipes_slime.dm
Labels: Content, Balance

#5170 panacea fixes and adjustment
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/reagents/medicine.dm
Labels: Balance

#5169 Le gun in my le colony
  code/datums/autolathe/gun_frames.dm
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/blackshield_disks.dm
  code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/bulldog.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/pitbull.dm
  code/modules/projectiles/guns/projectile/automatic/ppsh.dm
  code/modules/projectiles/guns/projectile/pistol/ladon.dm
  code/modules/projectiles/guns/projectile/revolver/breakaction.dm
Labels: Bug-Fix, Balance

#5161 Psionic Swarm + Psionic Spark Fix
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion_powers/mob_affecting_powers.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
  icons/mob/mobs-monster.dmi
Labels: Enhancement, Bug-Fix, Balance, Test Merged

#5163 AP base and PDM base tweaks
  code/game/objects/items/weapons/tools/mods/_defines.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/projectiles/guns/mods/mods.dm
Labels: Enhancement, Balance, Skill-Issue | Salt PR, Nuclear Option

#5156 Adds Pain Infliction Psionic Power
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion_powers/healing_powers.dm
Labels: Balance

#5178 Recolors the Police Hats (now with 99.9999% less screw-ups and merge conflicts!)
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Balance, Sprite Work

#5181 Marshal borgs (part 1 ?)
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robot_tall/sec.dmi
  icons/mob/robots.dmi
Labels: Balance, Sprite Work

#5182 Fruit volume fix
  code/modules/hydroponics/grown.dm
  code/modules/reagents/reagents/medicine.dm
Labels: Bug-Fix, Balance

#5164 Greyson Offices Map Rework
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
Labels: Balance, Map

#5155 Guild burn engine and extra mapping
  code/ATMOSPHERICS/components/unary/map_sink.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  maps/__Nadezhda/map/_Nadezhda_Solar_Area.dmm
  sojourn-station.dme
Labels: Content, Balance

#5179 stranger doom shooting
  code/modules/mob/living/carbon/superior_animal/human/stranger.dm
  icons/mob/mobs-humanoid.dmi
Labels: Sprite Work

#5192 CE_BLOODCLOT no longer lethal
  code/modules/organs/internal/internal_organ_processes.dm
Labels: Balance

#5189 Fix shield geni not blocking air
  code/modules/shield_generators/shield.dm
Labels: Bug-Fix

#5128 Crimson Cross Arsenal
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/oddity_items.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: Balance, Sprite Work

#5152 Nanogate Overhaul Part 1: The Powercreepining
  code/__DEFINES/dcs/signals/signals_nanogate/signals_nanogate_main.dm
  code/__DEFINES/perks.dm
  code/datums/perks/nanite_powers.dm
  code/datums/perks/nanogate.dm
  code/datums/perks/racial.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/modular_computers/file_system/programs/research/cyborg_remote.dm
  code/modules/nanogate/nanogate.dm
  code/modules/nanogate/nanogate_items.dm
  code/modules/nanogate/nanogate_vm.dm
  code/modules/nanogate/powers/user.dm
  code/modules/organs/internal/nanogate.dm
  sojourn-station.dme
Labels: Enhancement, New Content, Bug-Fix, Content, Balance, Nuclear Option, Test Merged

#5196 New Hair Styles
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/mob/hair.dmi
Labels: Balance, Sprite Work

#5197 Fixes New Hair Styles #5196
  icons/mob/human_races/species/human/hair.dmi
Labels: Bug-Fix

#5191 Fixes humans being unable to upgrade borgs
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
Labels: Bug-Fix, Balance

#5190 lockpick o matic rework
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/oddity_items.dm
Labels: Enhancement, Balance, Test Merged

#5198 Last Hair fix
  icons/mob/human_races/species/human/hair.dmi
Labels: Bug-Fix, Balance

#5199 Lodge SMES Fix
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Bug-Fix, Balance, Map

#5200 Fenceline camera fix
  code/modules/modular_computers/file_system/programs/generic/camera.dm
Labels: Bug-Fix, Balance

#5202 Fixes the fence cameras
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#5195 GP optimization
  code/game/objects/random/mob/greyson.dm
  code/game/objects/random/random.dm
  code/modules/dungeons/crawler/areas.dm
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
  maps/submaps/dungeon_rooms/rooms/commanderoffice.dmm
  maps/submaps/dungeon_rooms/rooms/corner_energy_NE.dmm
  maps/submaps/dungeon_rooms/rooms/corner_energy_NW.dmm
  maps/submaps/dungeon_rooms/rooms/corner_energy_SE.dmm
Labels: Enhancement, Balance

#5210 Nerfs Plasma Firestacks
  code/modules/projectiles/projectile/plasma.dm
Labels: Balance

#5208 Sci shuttle Access
  maps/__Nadezhda/data/shuttles-nadezhda.dm
Labels: Documentation, Balance

#5206 [Balancing] Lowers cooldown of Aulvaes limb regen
  code/datums/perks/racial.dm
Labels: Balance

#5194 GP turret fixes
  code/game/machinery/os_portable_turret.dm
  code/game/objects/items/weapons/circuitboards/machinery/tesla_turret.dm
Labels: Bug-Fix, Balance

#5201 Allow Hand Labelers to label a wide variety of things onto equipment.
  code/modules/paperwork/handlabeler.dm
Labels: Bug-Fix, Balance

#5187 Surplus Disk
  code/datums/autolathe/gun_frames.dm
  code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Balance

#5204 [QOL] Frequency Transfer for Signallers
  code/modules/assembly/signaler.dm
Labels: Balance, Port

#5205 [QOL] Transferring timing parameters (timing and time) from one timer to another timer
  code/modules/assembly/timer.dm
Labels: Balance

#5203 [Lore Compliance PR] Lore compliance PR on Posibrains
  code/game/objects/items/trash_material.dm
  code/modules/research/designs/medical.dm
  code/modules/research/nodes/robotics.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Documentation, Balance

#5212 Fixes fence prefabs
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Map

#5214 [FIX] Assorted TeleSci Icon Fixes
  code/modules/telesci/relay.dm
  code/modules/telesci/telepads.dm
  code/modules/telesci/teleporter_blocker.dm
Labels: Bug-Fix, Balance

#5215 Outsider shuttle med nerf
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Balance, Map

#5216 [FIX] [BALANCE] Dartrifle now functioning again + lower capacity fired with darts
  code/modules/projectiles/guns/projectile/dartgun.dm
Labels: Bug-Fix, Balance

#5219 Robot resting on reset fix
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Bug-Fix, Balance

#5149 Removes Dylovenes table salt byproduct
  code/modules/reagents/recipes/recipes.dm
Labels: Skill-Issue | Salt PR, Removal

#5222 Re-adding Umi's Snow Tiles
  code/game/turfs/flooring/flooring_premade.dm
  icons/turf/flooring/newsnow.dmi
Labels: Balance, Sprite Work, Port

#5176 4x records size increase
  code/__DEFINES/misc.dm
  code/modules/client/preference_setup/general/03_flavor.dm
Labels: Balance

#5207 [Content] Psionic Pain Transference Spell
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion_powers/healing_powers.dm
Labels: Content, Balance, Test Merged

#5209 bluecross Lockpick o matic anti lag measures
  code/modules/projectiles/guns/oddity_items.dm
Labels: Balance, Test Merged

#5184 K5 request
  code/modules/core_implant/core_implant.dm
Labels: Balance, Test Merged

#5173 new caseless and 17mm firearm (making use of the unused)
  code/modules/projectiles/guns/projectile/automatic/mercurian.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  icons/obj/guns/projectile/mercurian.dmi
  sojourn-station.dme
Labels: Content, Balance, Sprite Work

#4831 Adds risky CHECK_TICKs to human rendering code
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preference_setup/preview.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Test Merged

#5224 Imprinter psion check
  code/game/objects/items/devices/hardware_imprinter.dm
Labels: Balance

#5229 [Fix] Actually fixes Unbidden/Stranger Plasma sound effects.
  sound/weapons/guns/unknown_spacegun_burn.ogg
  sound/weapons/guns/unknown_spacegun_incinerate.ogg
  sound/weapons/guns/unknown_spacegun_melt.ogg
  sound/weapons/guns/unknown_spacegun_vaporize.ogg
Labels: Bug-Fix, Sound Addition

#5237 [Fix] Fixes Inner Peace Church Litany
  code/modules/core_implant/cruciform/rituals/path.dm
Labels: Bug-Fix, Balance

#5236 [Balance, Fix, Spritefix] Corestopper inconsistency fix
  code/modules/projectiles/projectile/special.dm
Labels: Bug-Fix, Balance

#5235 [Spellcheck] Spellchecks disk storage
  code/game/machinery/kitchen/smartfridge.dm
Labels: Bug-Fix

#5233 Cessation
  code/game/objects/effects/decals/crayon.dm
Labels: Content

#5232 [Fix] Icons now update again when an APC is rebooted during the best event in the game
  code/modules/power/apc.dm
Labels: Bug-Fix, Balance

#5231 Standardizes gun interactions
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/_projectile.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/plasma/plasma.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/projectiles/guns/energy/projectile/shrapnel.dm
  code/modules/projectiles/guns/energy/projectile/slab.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance

#5230 Fixes some tool upgrade intractions
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/clothing/spacesuits/breaches.dm
  code/modules/clothing/spacesuits/void/void.dm
Labels: Bug-Fix, Balance

#5240 surface transport access patch
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance

#5244 [Spellcheck] Mini Stunbaton --> Defence to defense.
  code/game/objects/items/weapons/tools/stunbatons.dm
Labels: Bug-Fix

#5220 [Fix] Fixes broken thermodynamics resulting in critical thermal runaway reactions with plants
  code/modules/hydroponics/seed.dm
Labels: Bug-Fix, Balance

#5228 Updates Matterforge/Autolathe to use TGUI
  code/game/machinery/autolathe/artist_bench.dm
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/autolathe/matterforge.dm
  code/game/machinery/autolathe/mechfab.dm
  code/game/objects/objs.dm
  code/modules/aberrants/organs/machinery/organ_fabricator.dm
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/ArtistBench.tsx
  tgui/packages/tgui/interfaces/Autolathe.tsx
  tgui/packages/tgui/interfaces/Matterforge.tsx
  tgui/public/tgui.bundle.js
Labels: Documentation, Enhancement, Balance, Test Merged

#5243 Lables and tweaks
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig_verbs.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
Labels: Bug-Fix, Balance

#5241 Hivemind ""buffs"" (fixes)
  code/game/gamemodes/events/hivemind_controller.dm
  code/game/objects/random/hivemind.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/mobs.dm
  code/modules/hivemind/objects.dm
  code/modules/hivemind/wires.dm
  icons/obj/hivemind_machines.dmi
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#5246 Xenopit Steward Headset and Misc Brig Changes
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5252 Excelsior psi_block
  code/modules/clothing/spacesuits/void/excelsior.dm
Labels: Balance

#5251 spin fix
  code/modules/mob/animations.dm
Labels: Bug-Fix
