Repository sojourn-13/sojourn-station, pull requests merged in 2024-11, with the labels that each got.

#5810 Gun Fixes & Misc Stuff (Second Attempt)
  code/datums/craft/recipes/guild.dm
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/energy/laser/abdicator.dm
  code/modules/projectiles/guns/energy/laser/sunrise.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/projectiles/guns/projectile/automatic/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/dp.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Bug-Fix, Balance

#5808 Fixes a nsa bug
  code/modules/reagents/metabolism.dm
Labels: Bug-Fix, Balance

#5805 oldification things
  code/game/objects/items/weapons/tools/mods/trash_mods.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/mods/mods_for_old.dm
  code/modules/scrap/oldificator.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Test Merged

#5811 robot restart fixes
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
Labels: Bug-Fix, Balance

#5793 Ports from downstream + Gun Correction
  code/controllers/subsystems/migration.dm
  code/game/machinery/autolathe/fabricators.dm
  code/modules/client/preference_setup/preview.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/organ_icon.dm
  code/modules/organs/external/subtypes/robotic.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/plasma/excubitor.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/sprite_accessories/_accessory_marking.dm
Labels: Enhancement, Bug-Fix, Balance, Test Merged, Port

#5776 return of appendicitis and spacevines
  code/game/gamemodes/events/rogue_drones.dm
  code/game/gamemodes/events/spacevine.dm
  code/game/gamemodes/events/spontaneous_appendicitis.dm
  code/game/machinery/adv_med.dm
Labels: Bug-Fix, Balance

#5812 Recipe Timer updates
  code/modules/cooking_with_jane/recipes/recipe.dm
Labels: Balance

#5813 fix more spelling errors
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/research/nodes/greyson.dm
Labels: Bug-Fix

#5818 Minor spelling fixes
  code/__DEFINES/jobs.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/jobs/department.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/paintkit.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/cards_ids_syndicate.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/modules/biomatter_manipulation/solidifier.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/spacesuits/void/neotheology.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  maps/_HunterLodge/map/_Hunting_Lodge_old.dmm
  maps/__Nadezhda/data/_Nadezhda_factions.dm
Labels: Bug-Fix

#5817 Grammar and spelling fixes - Gunslinger's Edition Part 2 -Energy Weapons
  code/modules/projectiles/guns/energy/laser/abdicator.dm
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  code/modules/projectiles/guns/energy/laser/carpediem.dm
  code/modules/projectiles/guns/energy/laser/centauri.dm
  code/modules/projectiles/guns/energy/laser/cog.dm
  code/modules/projectiles/guns/energy/laser/concilium.dm
  code/modules/projectiles/guns/energy/laser/disco_vazer.dm
  code/modules/projectiles/guns/energy/laser/egun.dm
  code/modules/projectiles/guns/energy/laser/firestorm.dm
  code/modules/projectiles/guns/energy/laser/laser.dm
  code/modules/projectiles/guns/energy/laser/laser_cannon.dm
  code/modules/projectiles/guns/energy/laser/lasercore.dm
  code/modules/projectiles/guns/energy/laser/makeshift_carbine.dm
  code/modules/projectiles/guns/energy/laser/nuclear.dm
  code/modules/projectiles/guns/energy/laser/peacekeeper.dm
  code/modules/projectiles/guns/energy/laser/sunrise.dm
  code/modules/projectiles/guns/energy/laser/xray.dm
  code/modules/projectiles/guns/energy/misc/floragun.dm
  code/modules/projectiles/guns/energy/misc/lasertag.dm
  code/modules/projectiles/guns/energy/misc/mindflayer.dm
  code/modules/projectiles/guns/energy/misc/robotguns.dm
  code/modules/projectiles/guns/energy/plasma/cassad.dm
  code/modules/projectiles/guns/energy/plasma/centurio_auretian.dm
  code/modules/projectiles/guns/energy/plasma/excubitor.dm
  code/modules/projectiles/guns/energy/plasma/hydrogen.dm
  code/modules/projectiles/guns/energy/plasma/variant.dm
  code/modules/projectiles/guns/energy/pulse/glock.dm
  code/modules/projectiles/guns/energy/tesla/tesla_gun.dm
Labels: Bug-Fix

#5816 cuff math tweaks
  code/modules/mob/living/carbon/resist.dm
Labels: Balance

#5822 Hair Addition: Dreads 2
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/mob/human_races/species/human/hair.dmi
Labels: Sprite Work

#5824 sheild - shield spelling fix
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/research/designs/mecha_equipment.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
Labels: Bug-Fix, Balance

#5820 Bayonet Gun Attachments
  code/__DEFINES/items.dm
  code/__DEFINES/projectile_defines.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/luger.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/boltgun/armstrong.dm
  code/modules/projectiles/guns/projectile/boltgun/mares_leg.dm
  code/modules/projectiles/guns/projectile/boltgun/roe_sika.dm
  code/modules/projectiles/guns/projectile/shotgun/combatsg.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/shotgun/riot.dm
  code/modules/projectiles/guns/projectile/shotgun/swat.dm
  icons/obj/guns/projectile/ak_homemade.dmi
  icons/obj/guns/projectile/custer.dmi
  icons/obj/guns/projectile/dshotgun.dmi
  icons/obj/guns/projectile/lever.dmi
  icons/obj/guns/projectile/lightboltgun.dmi
  icons/obj/guns/projectile/lightboltgun_wood.dmi
  icons/obj/guns/projectile/luger.dmi
  icons/obj/guns/projectile/mamba.dmi
  icons/obj/guns/projectile/mares.dmi
  icons/obj/guns/projectile/martian.dmi
  icons/obj/guns/projectile/operator.dmi
  icons/obj/guns/projectile/sawnoff/sawnshotgun.dmi
  icons/obj/guns/projectile/sawnoff/sts25.dmi
  icons/obj/guns/projectile/sawnoff/sts30.dmi
  icons/obj/guns/projectile/sawnoff/sts35.dmi
  icons/obj/guns/projectile/sawnoff/sts40.dmi
  icons/obj/guns/projectile/shotgun.dmi
  icons/obj/guns/projectile/strelki.dmi
  icons/obj/guns/projectile/sts25.dmi
  icons/obj/guns/projectile/sts30.dmi
  icons/obj/guns/projectile/sts35.dmi
  icons/obj/guns/projectile/sts40.dmi
  sojourn-station.dme
Labels: Enhancement, Content, Balance, Sprite Work

#5826 New Prime Royal Armor
  code/modules/clothing/head/helmet.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#5827 Hair Addition: Gloom
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/mob/hair.dmi
  icons/mob/human_races/species/human/hair.dmi
Labels: Balance, Sprite Work

#5829 SRI -> SI
  code/datums/outfits/jobs/ghostroles.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/game/objects/items/weapons/cards_ids_syndicate.dm
  code/game/objects/items/weapons/storage/hardcases.dm
Labels: Balance

#5831 Embed Chance Fix
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bug-Fix, Balance

#5833 Greasegun/Texan/Giant Snake Fix
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
Labels: Bug-Fix, Balance

#5834 Soda Dispenser: Strawberry Juice
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Balance

#5839 Lets mods dragdrop ghosts into control of a mob.
  code/modules/admin/admin.dm
Labels: Bug-Fix

#5836 carth now is a proper anti-toxin
  code/modules/reagents/reagents/medicine.dm
Labels: Bug-Fix, Balance

#5814 Map making perk
  code/__DEFINES/perks.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  icons/effects/perks.dmi
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/tasks.dm
Labels: Content, Balance, Sprite Work, Test Merged

#5806 Running shoes
  code/game/objects/random/oddities.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/projectiles/guns/oddity_items.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
Labels: Content, Balance, Sprite Work

#5828 Nerfs cargo and some anti-lag mapping
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/bluespace_tech.dm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Balance, Map

#5838 Cooking tweaks + fixes
  code/game/objects/structures/watercloset.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/food/recipes_microwave.dm
Labels: Bug-Fix, Balance

#5825 Marshal Gun Changes (w/ New Gun!) & Marshal Disk Changes
  code/datums/autolathe/guns.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/marshal_kits.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/modules/projectiles/guns/energy/laser/peacekeeper.dm
  code/modules/projectiles/guns/energy/pulse/glock.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/shotgun/riot.dm
  icons/obj/guns/projectile/mamba.dmi
  icons/obj/guns/projectile/python.dmi
  icons/obj/guns/projectile/viper.dmi
  maps/Centcom/map/centcom.dmm
Labels: Content, Balance, Sprite Work

#5832 Optimized hud
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/datum_hud_alt.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/modules/client/client_procs.dm
  code/modules/client/ui_style.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/human_hud.dm
  code/modules/mob/living/living_hud.dm
  code/modules/projectiles/gun_hud_actions.dm
  icons/mob/ErisStyleHolo.dmi
  icons/mob/screen/ErisStyleHolo.dmi
  sojourn-station.dme
Labels: Bug-Fix, Content, Balance, Sprite Work

#5842 duct tape rig fix
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_ui.dm
  code/modules/clothing/spacesuits/rig/rig_verbs.dm
Labels: Bug-Fix

#5844 Labcoat overwrites own armor stats
  code/modules/clothing/suits/labcoat.dm
Labels: Bug-Fix

#5847 Janetics Embryo PR
  code/modules/genetics/machinery/genetics_cloner.dm
Labels: Documentation

#5846 Map fixes misc
  maps/__DeepTunnels/deeptunnels.dm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Bug-Fix, Balance, Map

#5848 records record
  code/modules/modular_computers/file_system/programs/generic/records.dm
Labels: Documentation

#5850 Cosmetic check fix
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Bug-Fix, Balance

#5853 dummy targets no longer are ignored by simples
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug-Fix, Balance

#5843 Edits audio for Trajectory and PARA STS
  sound/weapons/guns/fire/NM_PARA.ogg
  sound/weapons/guns/interact/vector_cock.ogg
  sound/weapons/vector_empty_alarm.ogg
Labels: Sound Addition, Test Merged

#5835 Simplified and fixed atmos for bugs [Exclusive for Superior Animal]
  code/modules/mob/living/carbon/superior_animal/sa_breath.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance

#5830 cheap rapier and cheap spear buff
  code/game/objects/items/weapons/tools/simple_weapons.dm
  icons/obj/weapons.dmi
Labels: Bug-Fix, Balance

#5863 Soteria Branded First Aid Kit
  code/game/machinery/vendor/medical_vendors.dm
  code/game/objects/items/weapons/storage/firstaid.dm
Labels: Balance

#5862 Adds in an alt gorka [Requested]
  code/modules/clothing/under/miscellaneous.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#5851 factorio magnetism
  code/game/objects/items/devices/organ_module/active/armblades.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/modules/core_implant/cruciform/rituals/path.dm
Labels: Content, Balance

#5871 Firstaid
  code/game/machinery/vendor/medical_vendors.dm
Labels: Bug-Fix, Balance

#5869 Removes DA mater doup
  code/modules/research/destructive_analyzer.dm
Labels: Balance

#5840 Add RPD + Clean up LMG sprite code
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic/dp.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  icons/obj/guns/projectile/heroic.dmi
  icons/obj/guns/projectile/l6.dmi
  icons/obj/guns/projectile/pk.dmi
  icons/obj/guns/projectile/rpd.dmi
  icons/obj/guns/projectile/tk.dmi
Labels: Balance, Sprite Work

#5875 fixes gorka suit
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Bug-Fix, Sprite Work

#5876 Fixes missing upgrade stats
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
Labels: Bug-Fix, Balance

#5859 Revert "junk field nerf, sorry ya'll."
  code/modules/dungeons/junk_tractor_beam.dm
Labels: Content, Balance, Test Merged

#5868 Duty retool and WP fix
  code/game/objects/effects/effect_system.dm
  code/game/objects/objs.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/projectile.dm
Labels: Bug-Fix, Balance

#5883 Task typo corrections
  modular_sojourn/task_master/tasks.dm
Labels: Bug-Fix

#5882 Speech flavour
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/whisper.dm
Labels: Enhancement

#5881 Adds a church robe
  code/modules/clothing/under/jobs/civilian.dm
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Sprite Work

#5880 [TGS] DMAPI update to 7.3.0 + discord config
  code/controllers/configuration.dm
  code/controllers/master.dm
  code/game/world.dm
  config/example/discord.txt
  tgs_dmapi/tgs.dm
  tgs_dmapi/tgs/README.md
  tgs_dmapi/tgs/core/README.md
  tgs_dmapi/tgs/core/byond_world_export.dm
  tgs_dmapi/tgs/core/core.dm
  tgs_dmapi/tgs/core/datum.dm
  tgs_dmapi/tgs/includes.dm
  tgs_dmapi/tgs/v5/__interop_version.dm
  tgs_dmapi/tgs/v5/_defines.dm
  tgs_dmapi/tgs/v5/api.dm
  tgs_dmapi/tgs/v5/bridge.dm
  tgs_dmapi/tgs/v5/topic.dm
  tgs_dmapi/tgs/v5/undefs.dm
Labels: Documentation, Bug-Fix, Port

#5861 Meeting room and north east maints
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Balance, Map

#5866 Tessellate Omnitool Litany (For real this time)
  code/game/objects/items/weapons/tools/misc.dm
  code/modules/core_implant/cruciform/rituals/path.dm
Labels: Content, Balance

#5878 Hammer pole thing
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/nt_melee.dmi
Labels: Balance, Sprite Work

#5872 Better sounds for automatics
  code/game/sound.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/reaver.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/_projectile.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/dp.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/mamba.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/ostwind.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/boltgun/handmade.dm
  code/modules/projectiles/guns/projectile/boltgun/zatvor_ak.dm
  code/modules/projectiles/guns/projectile/other/lenar.dm
  code/modules/projectiles/guns/projectile/other/protector.dm
  code/modules/projectiles/guns/projectile/other/underslung.dm
  code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
  sound/weapons/Gunshot_silenced.wav
  sound/weapons/guns/fire/ak.ogg
  sound/weapons/guns/fire/ak_fire.ogg
  sound/weapons/guns/fire/automatic_silenced.ogg
  sound/weapons/guns/fire/carbine.ogg
  sound/weapons/guns/fire/carbine_fire.ogg
  sound/weapons/guns/fire/dmr_fire.ogg
  sound/weapons/guns/fire/grease_fire.ogg
  sound/weapons/guns/fire/lmg_fire.ogg
  sound/weapons/guns/fire/mg_silenced.ogg
  sound/weapons/guns/fire/mosin_fire.ogg
  sound/weapons/guns/fire/ostwind_fire.ogg
  sound/weapons/guns/fire/rifle.ogg
  sound/weapons/guns/fire/rifle_silenced.ogg
  sound/weapons/guns/fire/silenced_mg.ogg
  sound/weapons/guns/fire/smg_fire.ogg
  sound/weapons/guns/fire/tk_fire.ogg
  sound/weapons/guns/fire/ubgl.ogg
  sound/weapons/guns/fire/ubgl_fire.ogg
  sound/weapons/guns/interact/batrifle_cock.ogg
  sound/weapons/guns/interact/batrifle_magin.ogg
  sound/weapons/guns/interact/batrifle_magout.ogg
  sound/weapons/guns/interact/gun_drop.ogg
  sound/weapons/guns/interact/gun_pickup.ogg
  sound/weapons/guns/interact/gun_wield.ogg
  sound/weapons/guns/interact/lmg_close.ogg
  sound/weapons/guns/interact/lmg_cock.ogg
  sound/weapons/guns/interact/lmg_magin.ogg
  sound/weapons/guns/interact/lmg_magout.ogg
  sound/weapons/guns/interact/lmg_open.ogg
  sound/weapons/guns/interact/ltrifle_cock.ogg
  sound/weapons/guns/interact/ltrifle_magin.ogg
  sound/weapons/guns/interact/ltrifle_magout.ogg
  sound/weapons/guns/interact/pan_magout.ogg
  sound/weapons/guns/interact/sfrifle_cock.ogg
  sound/weapons/guns/interact/sfrifle_magin.ogg
  sound/weapons/guns/interact/sfrifle_magout.ogg
  sound/weapons/guns/interact/smg_cock.ogg
Labels: Balance, Sound Addition
