Repository sojourn-13/sojourn-station, pull requests merged in 2024-01, with the labels that each got.

#4905 Psion sleepy time spellcheck
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
Labels: Bug-Fix

#4906 Moves wallet to general loadout to stop runtimes
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/general.dm
Labels: Bug-Fix

#4863 (Ready for Merge) Church code rework
  .gitignore
  code/__DEFINES/misc.dm
  code/__DEFINES/perks.dm
  code/__HELPERS/mobs.dm
  code/controllers/subsystems/migration.dm
  code/datums/autolathe/biomatter.dm
  code/datums/outfits/jobs/ghostroles.dm
  code/datums/perks/job.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/jobs/job/church.dm
  code/game/machinery/bioprinter_nt.dm
  code/game/machinery/doors/holy_door.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/medical_stacks/medical.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/cards_ids_syndicate.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/vacuum.dm
  code/game/objects/random/lathe_disks/guns.dm
  code/game/objects/structures/burrows.dm
  code/modules/biomatter_manipulation/bioreactor/bioreactor.dm
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/core_implant/cruciform/bible.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/altar.dm
  code/modules/core_implant/cruciform/machinery/armaments.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/core_implant/cruciform/machinery/onlooker.dm
  code/modules/core_implant/cruciform/machinery/wall_obelisk.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/cloning.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/core_implant/cruciform/rituals/crusader.dm
  code/modules/core_implant/cruciform/rituals/group.dm
  code/modules/core_implant/cruciform/rituals/inquisitor.dm
  code/modules/core_implant/cruciform/rituals/machinery.dm
  code/modules/core_implant/cruciform/rituals/omni.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/core_implant/ritual.dm
  code/modules/core_implant/ritual_book.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/sandwich.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/race.dm
  code/modules/reagents/reagents/toxins.dm
  icons/obj/doors/Door_holy_public.dmi
  icons/obj/neotheology_machinery.dmi
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Enhancement, Content, Balance, Map

#4908 Heirloom weapon fix and balance
  code/datums/perks/backgrounds.dm
  code/modules/sanity/inspiration_component.dm
Labels: Bug-Fix, Balance

#4909 fixes showers/soap
  code/game/machinery/shower.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/structures/watercloset.dm
Labels: Bug-Fix

#4910 Gives the Command panic bunker an exit to Security
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Good-To-Merge, Map

#4911 Removing Possum's Shit Code
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/fancy.dm
Labels: Balance, Good-To-Merge, Skill-Issue | Salt PR

#4912 Fixes a couple security map issues
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Good-To-Merge, Map

#4899 Crayolo Antaginism
  code/__DEFINES/perks.dm
  code/controllers/subsystems/migration.dm
  code/datums/perks/job.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
  code/modules/psionics/psion.dm
  code/modules/psionics/psionic_items/psi_misc.dm
  code/modules/reagents/reagents/other.dm
  code/modules/sanity/inspiration_component.dm
  code/modules/sanity/sanity_mob.dm
  modular_sojourn/cardgame_2/cardgame_2.dm
Labels: Enhancement, Bug-Fix, Content, Balance, Good-To-Merge, Test Merged

#4913 Fixes Perk UI
  code/modules/mob/mob.dm
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui-say.bundle.js
  tgui/public/tgui.bundle.js
Labels: Bug-Fix, Balance

#4914 Plumbing
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer3.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral1.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral3.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian2.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral10.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral7.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral8.dmm
Labels: Bug-Fix, Good-To-Merge, Map, Removal

#4917 fixes cap guns
  code/modules/projectiles/guns/projectile/revolver/capgun.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Bug-Fix, Balance

#4926 Makes the IC start time the server time, rounded to the nearest hour
  code/__HELPERS/time.dm
Labels: Enhancement

#4927 Marshal buffs. Gasp.
  code/modules/clothing/head/helmet.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/mob/light_overlays.dmi
  icons/obj/light_overlays.dmi
Labels: Balance, Test Merged

#4922 Creates the Eventwolf
  code/modules/mob/living/carbon/superior_animal/human/subtype/eventwolf/eventwolf.dm
Labels: Invalid

#4928 prevents harmless guns from harming you. + lodge fix
  code/modules/projectiles/gun.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
Labels: Bug-Fix, Balance, Skill-Issue | Salt PR, Removal

#4925 Adds the remnant of the ex-solfed base to the deep forest (almost no loot)
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Balance, Map, Test Merged

#4932 Another liberty port for trilby
  code/__DEFINES/perks.dm
  code/datums/perks/cooldown.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/datums/perks/special.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/eventwolf/eventwolf.dm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/tasks.dm
  sojourn-station.dme
Labels: Content, Port

#4921 Removes the restricted tag from several languages.
  code/datums/perks/backgrounds.dm
  code/datums/perks/racial.dm
  code/modules/mob/language/outsider.dm
Labels: Balance, Test Merged

#4923 Taser changes.
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/energy.dm
Labels: Balance, Test Merged

#4916 more event stuff.
  code/datums/lobbyscreen.dm
  code/datums/outfits/jobs/ghostroles.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/cards_ids_syndicate.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/spacesuits/rig/modules/ninja.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/rig_back.dmi
  icons/obj/card.dmi
  icons/obj/rig_modules.dmi
  icons/title_screens/garden.png
Labels: Content, Test Merged

#4919 Sanity tweaks.
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/decals/remains.dm
  code/modules/sanity/sanity_mob.dm
Labels: Balance, Test Merged

#4948 Psionic food power now burns rather than takes blood, also reflavored
  code/modules/psionics/psion_powers/healing_powers.dm
Labels: Balance

#4951 RIG weirdness, star trader and objective bug fixs
  code/game/machinery/vendor/one_star_vending.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/nanogate/nanogate_items.dm
  code/modules/power/apc.dm
Labels: Bug-Fix, Balance

#4952 Mapping in what the colonists build (event reward)
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Map

#4935 Erisports
  code/__DEFINES/chemistry.dm
  code/__HELPERS/global_lists.dm
  code/game/machinery/bioprinter.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/organs/internal/bones.dm
  code/modules/organs/internal/eyes.dm
  code/modules/organs/internal/internal_wounds/_internal_wound.dm
  code/modules/organs/internal/internal_wounds/brain.dm
  code/modules/organs/internal/internal_wounds/eyes.dm
  code/modules/organs/internal/nerves.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/nanites.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/reagents/recipes.dm
  code/modules/surgery/internal.dm
  code/modules/surgery/mods.dm
  code/modules/surgery/organic.dm
  maps/__Nadezhda/map/Underground_Old.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_Underground.dmm
  sojourn-station.dme
  sound/weapons/lightstab.ogg
Labels: Balance, Port

#4950 Third Try
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/suits/storage.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Balance, Sprite Work

#4960 Exchanges bicar pill in IFAKs for splints
  code/game/objects/items/weapons/storage/firstaid.dm
Labels: Balance

#4959 Breakable splints, brought 2 u by kegdo ft. "CDB ruins the game".
  code/modules/mob/living/living_defense.dm
Labels: Balance

#4967 machete exploit/handtele fix
  code/__HELPERS/bluespace_entropy.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
Labels: Bug-Fix, Balance

#4966 church melee balance
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/storage/belt.dm
Labels: Balance

#4964 Changes the Hymn of the Engineer description
  code/modules/core_implant/cruciform/rituals/path.dm
Labels: Enhancement

#4940 telesci fixes/buffs
  code/modules/reagents/reagents/toxins.dm
  code/modules/telesci/circuits.dm
  code/modules/telesci/teleporter_blocker.dm
  code/modules/telesci/telesci_computer.dm
  icons/obj/telescience.dmi
Labels: Bug-Fix, Balance, Sprite Work, Test Merged

#4947 Head Office upgrades and other things
  code/game/machinery/requests_console.dm
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/computers/subtypes/preset_tablet.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Question, Balance, Map, Removal, Test Merged

#4957 Fractals are invited
  code/game/machinery/doors/holy_door.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/modules/clothing/accessories/accessory.dm
Labels: Enhancement, Balance

#4970 Adds generic implant and known_cybernetics to adv medscanner
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/organ_module/active/armblades.dm
  code/game/objects/items/weapons/implant/implanter.dm
  code/game/objects/items/weapons/implant/implants/generic.dm
  code/game/objects/items/weapons/implant/implants/tracking.dm
  code/modules/client/preference_setup/loadout/lists/general.dm
  code/modules/psionics/psion.dm
  sojourn-station.dme
Labels: Enhancement, New Content, Bug-Fix, Balance

#4971 maps in my mini-inhibitors (AKA nerfing myself)
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#4972 Buffs download speeds
  code/__DEFINES/misc.dm
Labels: Balance

#4973 Makes maintenance areas make sense
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Enhancement, Balance, Map

#4974 Powercrovel
  code/datums/craft/recipes/guild.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/shovel.dm
  icons/inventory/back/mob.dmi
  icons/inventory/on_suit/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/powercrovel.dmi
  icons/obj/tools.dmi
Labels: Enhancement, Content, Balance, Sprite Work

#4976 genes and blood fussion
  code/__DEFINES/genetics.dm
  code/modules/genetics/machinery/genetics_items.dm
  code/modules/genetics/mutations/blood_bank.dm
  code/modules/genetics/mutations/seasoned_mind.dm
  code/modules/genetics/mutations/shock_loss.dm
  code/modules/genetics/recipes/blood_based.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/pepper.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/shocker.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
  sojourn-station.dme
Labels: Enhancement, Content, Balance

#4977 Makes the WO's window tinter work
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Skill-Issue | Salt PR, Map, Nuclear Option

#4978 Update _internal_wound.dm
  code/modules/organs/internal/internal_wounds/_internal_wound.dm
Labels: Bug-Fix

#4968 Rapiers
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/tools/stunbatons.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/experiment.dm
  icons/obj/weapons-blades.dmi
Labels: Enhancement, New Content, Bug-Fix, Balance, Sprite Work, Good-To-Merge

#4975 More church gun balance and small fixes.
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/projectiles/guns/energy/laser/concilium.dm
  code/modules/projectiles/guns/energy/laser/laser.dm
  code/modules/projectiles/guns/energy/plasma/plasma.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/psionics/psionic_items/psi_weptools.dm
Labels: Documentation, Bug-Fix, Balance, Test Merged

#4987 Sensible Benzin roaches
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/random/mob/roach.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/fragment.dm
  code/modules/projectiles/projectile/plasma.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagent_containers/food/cubes.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Documentation, Balance, Port

#4986 more_layered_shielding
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
Labels: Enhancement, Content, Balance

#4988 Tisane description fix
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug-Fix
