Repository sojourn-13/sojourn-station, pull requests merged in 2024-12, with the labels that each got.

#5879 Allows marshals and blackshield TWO Secondaries
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/storage/hardcases.dm
Labels: Balance

#5894 Lonestar-ering 2
  code/game/objects/items/toys.dm
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
  code/modules/trade/datums/trade_stations_presets/1-common/factio.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
Labels: Enhancement, Balance

#5892 Lonestar-ering
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/projectile/revolver/capgun.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
Labels: Enhancement, Balance

#5886 hydro additions
  code/datums/craft/recipes/misc.dm
  code/modules/hydroponics/trays/tray.dm
  modular_sojourn/cement_bag.dm
  modular_sojourn/misc_stuff.dmi
Labels: Balance, Sprite Work

#5897 5th Absolutist Spelling TrilBee Contest
  code/datums/craft/gun_parts.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/random/mob/termite.dm
  code/modules/hydroponics/seed.dm
  code/modules/mob/living/living.dm
  code/modules/organs/internal/lungs.dm
  modular_sojourn/churn.dm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/tasks.dm
Labels: Bug-Fix, Makes-Trilby-Sad

#5884 way more random and more items
  code/game/objects/random/booze.dm
  code/game/objects/random/cloth.dm
  code/game/objects/random/food.dm
  code/game/objects/random/junk.dm
  code/game/objects/random/packs.dm
  code/game/objects/random/prosthesis.dm
  code/game/objects/random/purerandom.dm
  code/modules/scrap/scrap.dm
  sojourn-station.dme
Labels: Balance

#5893 Makes TTS device 'Tiny' instead of small
  code/game/objects/items/devices/text_to_speech.dm
  code/game/objects/items/weapons/storage/wallets.dm
Labels: Balance

#5887 [TGS] Enhance TGS Integration and Admin Tools.
  code/__HELPERS/chat.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/_global_vars/_regexes.dm
  code/controllers/configuration.dm
  code/controllers/evacuation/evacuation.dm
  code/controllers/master.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/tickets/tickets.dm
  code/datums/helper_datums/getrev.dm
  code/datums/topic/world.dm
  code/game/verbs/who.dm
  code/game/world.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/chat_commands.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/webhook/webhook.dm
  config/example/discord.txt
  sojourn-station.dme
  tgs_dmapi/code/tgs_event_handler.dm
  tgs_dmapi/code/world.dm
Labels: Documentation, Enhancement, dependencies

#5890 removes a doup, CRO stuff and cleaning, Centcom RnD
  code/game/objects/items/weapons/grenades/hydrogen.dm
  code/game/objects/items/weapons/tools/hyrogen_melee.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/projectiles/guns/energy/plasma/hydrogen.dm
  code/modules/projectiles/guns/energy/plasma/variant.dm
  code/modules/projectiles/guns/energy/plasma/welder.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  maps/Centcom/map/centcom.dmm
  sojourn-station.dme
Labels: Documentation, Enhancement, Bug-Fix, Balance, Map

#5895 shrapnel tweaks
  code/__DEFINES/weapons.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#5902 Boots and Gloves
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
Labels: Bug-Fix, Balance

#5905 fixes grinders matter doup and vital monitor
  code/datums/repositories/crew/vital.dm
  code/modules/genetics/machinery/advanced_grinder.dm
  code/modules/reagents/machinery/grinder.dm
Labels: Bug-Fix, Balance

#5904 allows players to disable the antimatter annoucer
  code/modules/power/antimatter/control.dm
Labels: Balance

#5900 Xenobio batong
  code/game/objects/items/weapons/tools/stunbatons.dm
Labels: Bug-Fix

#5896 Title AD tweaks and Golem/Termite tweaks
  code/__DEFINES/mobs.dm
  code/datums/stat_modifiers/modifiers/mob/superior/roach_modifiers.dm
  code/datums/stat_modifiers/modifiers/mob/superior/spider_modifiers.dm
  code/datums/stat_modifiers/modifiers/mob/superior/superior_modifiers.dm
  code/datums/stat_modifiers/modifiers/mob/superior/xeno_modifers.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_behemoth.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_runtling.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_shooter.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
Labels: Bug-Fix, Balance

#5903 Mac and Texan buffs
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic/mac.dm
  code/modules/projectiles/guns/projectile/automatic/texan.dm
  nano/templates/weapon_stats.tmpl
Labels: Documentation, Balance

#5910 size fix for hydrogen sword
  code/game/objects/items/weapons/tools/hyrogen_melee.dm
Labels: Bug-Fix

#5911 Replace spaces with tab
  code/modules/reagents/recipes/recipes.dm
Labels: Bug-Fix

#5912 typo Forecful -> Forceful
  code/datums/perks/special.dm
Labels: Bug-Fix

#5916 Fabricator conistanty
  code/game/machinery/autolathe/fabricators.dm
Labels: Enhancement, Bug-Fix

#5917 Typo; requested by Trilby
  code/modules/psionics/psion_powers/healing_powers.dm
Labels: Bug-Fix

#5919 EGO EAR machine thingy fix.dm
  code/modules/psionics/ear.dm
Labels: Bug-Fix

#5921 Fixes rig pieces randomly losing temp/shock protection
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Bug-Fix, Balance

#5909 hydrotweaks: more regnant interactions + borg qol + balance tweaks
  code/__DEFINES/_hydro_setup.dm
  code/datums/craft/recipes/misc.dm
  code/game/objects/items/devices/scanners/plant.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_gene_presets.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/hydroponics/trays/tray_process.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/research/experiment.dm
  code/modules/trade/datums/trade_stations_presets/1-common/botany.dm
  modular_sojourn/brewing_datums.dm
Labels: Bug-Fix, Balance

#5907 ablative mobs + blocking buff
  code/__DEFINES/items_clothing.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_behemoth.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_runtling.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_shooter.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
Labels: Balance

#5898 Requested balance changes
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#5913 Requested by k5: Lobby death
  code/controllers/configuration.dm
  code/controllers/subsystems/ticker.dm
  sound/AI/annoucement_dings.ogg
Labels: Documentation, Bug-Fix
