Repository sojourn-13/sojourn-station, pull requests merged in 2024-05, with the labels that each got.

#5255 Pistol firing sounds
  code/modules/projectiles/guns/projectile/automatic/freedom.dm
  code/modules/projectiles/guns/projectile/pistol/basilisk.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/deaglebolt.dm
  code/modules/projectiles/guns/projectile/pistol/glock.dm
  code/modules/projectiles/guns/projectile/pistol/judiciary.dm
  sound/weapons/guns/fire/1911_fire.ogg
  sound/weapons/guns/fire/9mm_marshal_pistol.ogg
  sound/weapons/guns/fire/9mm_pistol.ogg
  sound/weapons/guns/fire/deagle_fire.ogg
  sound/weapons/guns/fire/glock_fire.ogg
Labels: Balance, Good-To-Merge, Sound Addition

#5250 SLT sidearm options
  code/game/objects/items/weapons/storage/hardcases.dm
  code/modules/projectiles/guns/energy/projectile/stun.dm
Labels: Balance, Good-To-Merge

#5254 Fixes Ewallets tasks
  code/game/machinery/vending.dm
Labels: Bug-Fix, Balance

#5249 Folding typo fix
  code/modules/projectiles/gun.dm
Labels: Bug-Fix, Good-To-Merge

#5242 Dusk Saber
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/oddity_items.dm
  icons/obj/weapons-blades.dmi
Labels: Balance, Sprite Work

#5260 ADMS requires solid work space
  code/modules/maint_expeditions/adms.dm
Labels: Balance

#5258 Card game rules and such
  code/game/machinery/vendor/misc_vendors.dm
  modular_sojourn/cardgame_2/cardgame_2.dm
  modular_sojourn/cardgame_2/cardgame_sprites.dmi
  modular_sojourn/cardgame_2/cardpacks_and_spawner.dm
Labels: Balance, Sprite Work

#5217 [Balance, Buff] Polytrinic Acid lethality
  code/modules/reagents/reagents/toxins.dm
Labels: Balance, Test Merged

#5239 [Balance] Table salt radiation intraction
  code/modules/reagents/reagents/food-Drinks.dm
Labels: Balance, Skill-Issue | Salt PR, Test Merged

#5257 Changes LSS ERT to an IAA
  code/datums/outfits/jobs/ghostroles.dm
  code/game/objects/effects/spawners/ghostroles.dm
Labels: Balance, Good-To-Merge

#5261 Update floor_damage
  code/game/turfs/simulated/floor_damage.dm
Labels: Bug-Fix, Balance

#5160 Blockshield 2.0
  code/__DEFINES/jobs.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/manifest.dm
  code/datums/objective/individual_objective/ironhammer.dm
  code/datums/outfits/jobs/_defines.dm
  code/datums/outfits/jobs/blackshield.dm
  code/datums/outfits/jobs/security.dm
  code/datums/setup_option/core_implants.dm
  code/game/antagonist/station/changeling.dm
  code/game/antagonist/station/contractor.dm
  code/game/jobs/department.dm
  code/game/jobs/job/blackshield.dm
  code/game/jobs/job/security.dm
  code/game/jobs/jobs.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/client/preference_setup/loadout/lists/factionblackshield.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/mob/living/simple_animal/hostile/dino.dm
  code/modules/multiz/map_data.dm
  code/modules/organs/body_modifications.dm
  icons/inventory/back/mob.dmi
  icons/obj/storage/backpack.dmi
  sojourn-station.dme
Labels: Documentation, Enhancement, Balance, Test Merged

#5145 Ammo stuff
  code/datums/autolathe/ammo.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/research/designs/mecha_equipment.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
  icons/obj/guns/projectile/Hustler.dmi
  icons/obj/guns/projectile/saiga12.dmi
  icons/obj/guns/projectile/sbaw.dmi
Labels: Bug-Fix, Balance, Test Merged

#5248 EMP scaling
  code/modules/organs/external/_external.dm
  code/modules/organs/internal/_internal.dm
Labels: Balance, Test Merged

#5218 Borg fixes and balance pass
  code/datums/craft/recipes/guild.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/genetics/creatures/golden_roach.dm
  code/modules/mob/living/silicon/robot/admin_only_modules.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/syndicate.dm
  code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm
  code/modules/research/designs/robot_parts.dm
  code/modules/research/nodes/robotics.dm
  interface/skin.dmf
  sojourn-station.dme
Labels: Bug-Fix, Balance

#5221 [Feature] Cindarite Voc, a Cindarite language PR
  code/__DEFINES/chemistry.dm
  code/__DEFINES/species_languages.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/mob/language/outsider.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Balance

#5266 Add a warning to 515+ clients that stuff is likely to break
  code/modules/client/client_procs.dm
Labels: Documentation

#5265 powercreep round 2 (gives salvager med expert)
  code/game/jobs/job/prospector.dm
Labels: Balance

#5269 fix genetics console deconstruction
  code/modules/genetics/machinery/genetics_cloner.dm
Labels: Bug-Fix, Balance

#5268 rapier_fix
  icons/mob/items/righthand.dmi
Labels: Sprite Work

#5271 tool repair change
  code/game/objects/items/weapons/tools/_tools.dm
Labels: Bug-Fix, Balance

#5273 Let Guildees and Ghosts see Machine Parts
  code/game/machinery/machinery.dm
Labels: Balance

#5267 Adds SI Field Scientist armored labcoat
  code/modules/clothing/suits/labcoat.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
Labels: Balance, Sprite Work

#5259 Chaos intrigration
  code/game/objects/random/mob/greyson.dm
  code/game/objects/random/mob/misc.dm
  code/game/objects/random/mob/roach.dm
  code/game/objects/random/mob/spider.dm
  code/game/objects/random/mob/termite.dm
  code/game/objects/random/random.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/synthetic.dm
Labels: Content, Balance

#5226 [Balance, Fix(?), Math, Sanity Check] Rebalances firestacks to use a logistic function
  code/__DEFINES/items_clothing.dm
  code/modules/mob/living/living_defense.dm
Labels: Bug-Fix, Balance

#5281 Update construction.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
Labels: Bug-Fix

#5272 Add byond-tracy and cut 2 minutes and 2 seconds off init
  code/__DEFINES/_init.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/mapping.dm
  code/game/atoms.dm
  code/game/objects/structures/low_wall.dm
  code/game/turfs/simulated/floor.dm
  code/modules/multiz/basic.dm
  code/modules/random_map/_random_map_setup.dm
  code/modules/random_map/automata/automata.dm
  code/modules/random_map/automata/caves.dm
  code/modules/random_map/noise/noise.dm
  code/modules/random_map/noise/ore.dm
  code/modules/random_map/random_map.dm
  prof.dll
  sojourn-station.dme
  tools/ci/check_grep.sh
Labels: Documentation, Enhancement, Test Merged

#5274 the best new bluecross ever
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/projectile/special.dm
  icons/obj/guns/energy/flaregun_bluecross.dmi
Labels: Balance, Sprite Work, Test Merged

#5276 fixes tools for reals
  code/game/objects/items/weapons/tools/_tools.dm
Labels: Bug-Fix, Balance, Test Merged

#5275 more exl tools and mobs
  code/datums/autolathe/security.dm
  code/datums/autolathe/tools.dm
  code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/random/mob/misc.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/mob/mobs-humanoid.dmi
  icons/obj/weapons.dmi
Labels: Balance, Sprite Work, Test Merged

#5270 Borg posibrains
  code/game/jobs/job/silicon.dm
  code/game/machinery/computer/ai_core.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/transform_procs.dm
Labels: Balance

#5286 Borg inventory patch
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
Labels: Bug-Fix, Balance

#5290 Makes the excel spawner set the person as excel faction
  code/game/objects/effects/spawners/ghostroles.dm
Labels: Bug-Fix

#5285 Shield SMASHING targets
  code/game/objects/items/weapons/shields.dm
Labels: Bug-Fix, Balance, Test Merged

#5282 proof of conspect
  modular_sojourn/fencer.dm
  modular_sojourn/fencer.dmi
  sojourn-station.dme
Labels: Balance, Sprite Work, Test Merged

#5279 Crusades can now end
  code/game/antagonist/station/inquisitor.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/rituals/crusader.dm
Labels: Balance

#5292 xenoarch loop fix
  code/controllers/subsystems/xenoarch.dm
Labels: Bug-Fix

#5263 [lore] Cruciforms for Councilors
  code/datums/setup_option/core_implants.dm
Labels: Content, Balance

#5278 Gives Prospectors some Church weapons
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Labels: Balance

#5295 Give preacher hat bioprotection
  code/modules/clothing/head/jobs.dm
Labels: Bug-Fix, Balance

#5299 Fixes Bulwark of Harmony
  code/modules/core_implant/cruciform/rituals/path.dm
Labels: Bug-Fix, Balance

#5300 Make bioreactor goo anchored to the ground
  code/modules/biomatter_manipulation/bioreactor/bioreactor.dm
Labels: Bug-Fix, Balance

#5291 Skylight: Adding Suit and Overcoat
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/suits.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Balance, Sprite Work, Port

#5301 Make subsystems report self-init time
  code/controllers/master.dm
Labels: Bug-Fix

#5305 Add 8.6 packets for the bullet fab
  code/game/machinery/autolathe/fabricators.dm
Labels: Balance

#5304 Perk pathing fix for prospector and blackshield conditioning
  code/datums/perks/job.dm
Labels: Bug-Fix, Balance

#5302 Adds a colorable robes to roundstart loadout.
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Balance, Sprite Work

#5306 marshal break room fix
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5308 readds skylights suits
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#5312 Merge ASAP / Tested: Fixes the spriting mistake i did when byond decided to delete the sprites.
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#5310 Greyson turret emp and death fix
  code/game/machinery/os_portable_turret.dm
Labels: Bug-Fix, Balance

#5289 Port new Icons and PRs from ERIS.
  code/game/objects/structures/flora/flora_potted.dm
  icons/obj/curtain.dmi
  icons/obj/cyberplants.dmi
  icons/obj/items.dmi
  icons/obj/janitor.dmi
  icons/obj/plants.dmi
Labels: Sprite Work, Port

#5256 [Content] Ported Omni Translators (from Polaris), Adds NO_TRANSLATE to Opifex and Cultcommon
  code/__DEFINES/species_languages.dm
  code/game/objects/items/devices/translators.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
  code/modules/client/preference_setup/loadout/lists/tools.dm
  code/modules/mob/language/outsider.dm
  code/modules/research/designs/devices.dm
  code/modules/research/nodes/bluespace.dm
  icons/obj/items.dmi
  sojourn-station.dme
Labels: Content, Balance, Test Merged, Port

#5298 less chemicals around (rigs)
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/stashes/stash_types/ninja.dm
Labels: Balance

#5307 buffs, tweaks and differences in spawning for oddities weapon
  code/__HELPERS/global_lists.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/oddity_items.dm
Labels: Enhancement, Balance

#5316 Refactors warrant projectors and makes them able to print
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/devices/holowarrant.dm
  code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
  nano/templates/digitalwarrant.tmpl
Labels: Balance

#5303 more advanced mob attacks
  code/_onclick/other_mobs.dm
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/traps.dm
  code/game/objects/structures.dm
  code/game/objects/structures/alien/alien.dm
  code/game/objects/structures/burrows.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/fireaxe_cabinet.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/railing.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_spawner.dm
  code/game/supplyshuttle.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/clothing/clothing.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/human/stranger.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/kriosan/kriosan.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/prisoners/prisoners.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/multiz/structures.dm
  code/modules/power/lighting.dm
  code/modules/random_map/drop/droppod_doors.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/scrap/scrap.dm
  code/modules/shield_generators/shield.dm
  code/modules/tables/tables.dm
  code/modules/turbolift/turbolift_console.dm
  code/modules/vehicles/vehicle.dm
  modular_sojourn/power_puncher.dm
  modular_sojourn/shields.dm
Labels: Enhancement, Bug-Fix, Balance, Test Merged

#5297 TGUI Guild (Part 2)
  .gitignore
  code/__DEFINES/misc.dm
  code/__HELPERS/icons.dm
  code/datums/craft/menu.dm
  code/datums/wires/airlock.dm
  code/datums/wires/alarm.dm
  code/datums/wires/apc.dm
  code/datums/wires/autolathe.dm
  code/datums/wires/camera.dm
  code/datums/wires/jukebox.dm
  code/datums/wires/mulebot.dm
  code/datums/wires/nuclearbomb.dm
  code/datums/wires/recycle_vendor.dm
  code/datums/wires/robot.dm
  code/datums/wires/smartfridge.dm
  code/datums/wires/smes.dm
  code/datums/wires/suit_storage_unit.dm
  code/datums/wires/vending.dm
  code/datums/wires/wires.dm
  code/game/machinery/alarm.dm
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/autolathe/matterforge.dm
  code/game/machinery/crafting_station.dm
  code/game/machinery/crafting_station_recipes.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/smelter.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/structures/tank_dispenser.dm
  code/modules/aberrants/organs/machinery/organfridge.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/client/preference_setup/global/preferences.dm
  code/modules/materials/materials.dm
  code/modules/power/hydroelectric.dm
  code/modules/power/port_gen.dm
  code/modules/tgui/tgui.dm
  nano/templates/smartfridge.tmpl
  sojourn-station.dme
  tgui/.gitignore
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/interfaces/CraftMenu.tsx
  tgui/packages/tgui/interfaces/CraftingStation.tsx
  tgui/packages/tgui/interfaces/Fabrication/MaterialAccessBar.tsx
  tgui/packages/tgui/interfaces/Fabrication/MaterialIcon.tsx
  tgui/packages/tgui/interfaces/Fabrication/Types.ts
  tgui/packages/tgui/interfaces/FireAlarm.tsx
  tgui/packages/tgui/interfaces/HydroelectricControl.tsx
  tgui/packages/tgui/interfaces/Matterforge.tsx
  tgui/packages/tgui/interfaces/PortableGenerator.tsx
  tgui/packages/tgui/interfaces/Smartfridge.tsx
  tgui/packages/tgui/interfaces/Smelter.tsx
  tgui/packages/tgui/interfaces/Vending.tsx
  tgui/packages/tgui/interfaces/Wires.tsx
  tgui/packages/tgui/interfaces/common/ColoredSecurityLevel.tsx
  tgui/public/tgui.bundle.js
Labels: Enhancement, Balance, Test Merged

#5318 sprites and alt mode tweak
  code/modules/projectiles/guns/oddity_items.dm
  icons/inventory/accessory/icon.dmi
  icons/obj/guns/projectile/rafale_bluecross.dmi
Labels: Bug-Fix, Balance, Sprite Work

#5317 Gun safety verb no longer brings up a dialogue box
  code/modules/projectiles/gun.dm
Labels: Enhancement, Balance

#5314 Vexilar Forceblade Rework
  code/game/objects/items/weapons/nt_melee.dm
Labels: Enhancement, Balance

#5294 Councilors are no longer required for game start
  code/game/gamemodes/storyteller.dm
Labels: Balance

#5309 Make sure client FPS is always set to preference value
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/client/preferences.dm
Labels: Bug-Fix, Balance

#5325 Make crafting station work better for ghosts
  code/game/machinery/crafting_station.dm
  tgui/packages/tgui/interfaces/CraftingStation.tsx
  tgui/public/tgui.bundle.js
Labels: Bug-Fix, Balance

#5323 [Fix] Makes some non-languages non-translatable.
  code/modules/mob/language/generic.dm
  code/modules/mob/language/monkey.dm
Labels: Bug-Fix

#5326 Fix blood volume adjustments and subdermal armor
  code/game/objects/items/devices/organ_module/passive/armor.dm
  code/game/objects/items/devices/scanners/health.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/organs/blood.dm
Labels: Bug-Fix, Balance

#5322 reverts mop, bucket and light replacer sprites
  icons/obj/janitor.dmi
Labels: Sprite Work

#5329 Fix the animals translate bug properly
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/devices/translators.dm
  code/modules/mob/language/generic.dm
Labels: Bug-Fix

#5334 Change welcome sound to chimes
  sound/AI/welcome.ogg
Labels: Sound Addition

#5319 Hydro nerfs*
  code/__DEFINES/_hydro_setup.dm
  code/game/objects/items/devices/scanners/plant.dm
  code/game/objects/items/devices/scanners/scanners.dm
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_gene_presets.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/trade/datums/trade_stations_presets/1-common/botany.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Enhancement, Balance, Map, Port

#5321 Robot self diagnostic
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Enhancement, Bug-Fix, Balance, Removal

#5337 Update _Nadezhda_Colony_New.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Map

#5238 [Content, Spritework] Adds the TRR-2 Dissolver Beam, a Guild craftable gun based on the EBR-4
  code/datums/craft/recipes/guild.dm
  code/modules/projectiles/guns/energy/laser/xray.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/special.dm
  icons/obj/guns/energy/nucgun2.dmi
  sound/weapons/energy/SuperHeavyLaser.ogg
Labels: Content, Balance, Sprite Work, Test Merged

#4654 Tgs tweaks
  code/_global_vars/misc.dm
  code/controllers/master.dm
  code/game/world.dm
  code/modules/client/client_procs.dm
  tgs_dmapi/tgs.dm
  tgs_dmapi/tgs/core/datum.dm
  tgs_dmapi/tgs/includes.dm
  tgs_dmapi/tgs/v3210/api.dm
  tgs_dmapi/tgs/v3210/commands.dm
  tgs_dmapi/tgs/v4/api.dm
  tgs_dmapi/tgs/v4/commands.dm
  tgs_dmapi/tgs/v5/README.md
  tgs_dmapi/tgs/v5/__interop_version.dm
  tgs_dmapi/tgs/v5/_defines.dm
  tgs_dmapi/tgs/v5/api.dm
  tgs_dmapi/tgs/v5/bridge.dm
  tgs_dmapi/tgs/v5/chunking.dm
  tgs_dmapi/tgs/v5/commands.dm
  tgs_dmapi/tgs/v5/serializers.dm
  tgs_dmapi/tgs/v5/topic.dm
  tgs_dmapi/tgs/v5/undefs.dm
Labels: DO NOT MERGE, Test Merged

#5349 Fix Href exploit for the ameridian processor
  code/modules/ameridian/liquid_ameridian_processor.dm
Labels: Bug-Fix

#5185 Marshal vendor actually marshal
  code/game/machinery/vendor/weapon_vendors.dm
Labels: Balance, Removal, Test Merged

#5280 Modernising Mech Code
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/tools/_tools.dm
Labels: Enhancement, Bug-Fix, Balance

#5287 Rebalances Hivemind Special Options
  code/game/gamemodes/events/hivemind_controller.dm
  code/game/objects/structures/burrows.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/wires.dm
Labels: Balance

#5320 cargo export tweaks
  code/controllers/subsystems/trade.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
Labels: Bug-Fix, Balance, Test Merged

#5296 Surgery Tweaks + Cloathing balance
  code/modules/surgery/robotic_damage.dm
  code/modules/surgery/surgery.dm
Labels: Bug-Fix, Balance

#5324 Renames the Chief Executive Officer to Surface Operations Manager
  code/__DEFINES/jobs.dm
  code/datums/outfits/jobs/guild.dm
  code/datums/perks/job.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/department.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/guild.dm
  code/game/machinery/requests_console.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/toys.dm
  code/game/objects/landmarks/join.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/client/preference_setup/loadout/lists/factionlonestar.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/paperwork/stamps.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/data/reports.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Documentation, Test Merged

#5351 Fullauto runtime
  code/datums/datum_click_handlers.dm
Labels: Bug-Fix

#5350 NSA icon is now percentage based
  code/_onclick/hud/screen_objects/base_screen_objects.dm
Labels: Bug-Fix

#5354 New tasks + diving tweak
  code/game/turfs/flooring/flooring.dm
  code/modules/mob/living/living.dm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/task_helpers.dm
  modular_sojourn/task_master/tasks.dm
Labels: Enhancement, Balance

#5348 fixes wire exsam for drones (and everyone)
  code/datums/wires/wires.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Bug-Fix, Balance

#5356 Fixes hypospray delay stacking
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Bug-Fix, Balance

#5357 fixes nanobot healing + buffs
  code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
Labels: Bug-Fix, Balance

#5355 injector sword fix + robo tool fixes
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Bug-Fix, Balance

#5359 Make roomba un-buckle-able
  code/modules/mob/living/carbon/superior_animal/drone/types/roomba.dm
Labels: Bug-Fix, Balance

#5358 skipjack and merc event shuttles fixes
  maps/Centcom/map/centcom.dmm
Labels: Bug-Fix, Map

#5365 Change missleading setting
  code/game/machinery/tesla_turret.dm
Labels: Balance

#5367 Fix organ fab not removing categories on eject and tabs not wrapping
  code/modules/aberrants/organs/machinery/organ_fabricator.dm
  tgui/packages/tgui/interfaces/Autolathe.tsx
  tgui/public/tgui.bundle.js
Labels: Bug-Fix, Balance

#5340 Rebalance recluse to be 2 hit instant death
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/reagents/reagents/toxins.dm
Labels: Balance

#5366 Turns the Delay admin verbs into separate start and resume verbs
  code/modules/admin/admin.dm
Labels: Enhancement

#5368 slight shieldie camo overhaul
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/lists/factionblackshield.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/under/jobs/militia.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Balance, Sprite Work

#5372 fix markdown calc and rebalance direct sales
  code/controllers/subsystems/trade.dm
  code/modules/trade/datums/_trade_station.dm
Labels: Bug-Fix, Balance

#5381 Scrap Beacon cooldown timer visibility
  code/modules/scrap/scrap_beacon.dm
Labels: Enhancement

#5380 Oversight on Guild Adept's locker
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Balance

#5379 mechivers no longer eat mechs
  code/modules/hivemind/mobs.dm
Labels: Balance

#5378 MegaSeed Servitor for Lodge
  code/game/machinery/vendor/food_vendors.dm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
Labels: Balance, Map

#5375 [Removal, Fix] Removes otherwise unobtainable 7.62 mm and 6.4 mm incendiary ammo from scrap ammo kits. Removes 8.6 mm incendiary from scrap ammo kits.
  code/modules/projectiles/ammunition/ammo_kits.dm
Labels: Wont fix, Balance

#5374 Removes the spare Church vendor
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map, Removal, Makes-Trilby-Sad

#5344 Projectiles go over disposal bins
  code/modules/recycling/disposal.dm
Labels: Bug-Fix

#5339 [bugfix] NO_PAIN flag now actually properly confers pain immunity.
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Bug-Fix, Balance

#5327 rework of damage mods
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/datums/perks/racial.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/genetics/mutations/cow_skin.dm
  code/modules/genetics/mutations/dwarfism.dm
  code/modules/genetics/mutations/gigantism.dm
  code/modules/genetics/mutations/thick_fur.dm
  code/modules/mob/living/living_defines.dm
  code/modules/reagents/reagents/alchemy.dm
Labels: Nuclear Option, Test Merged

#5360 Adds Larkens Laptop fluff item - also adds system to make gear items locked to ckeys
  code/modules/admin/admin_investigate.dm
  code/modules/client/preference_setup/loadout/lists/fluff.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/modular_computers/computers/subtypes/dev_console.dm
  code/modules/modular_computers/computers/subtypes/dev_laptop.dm
  code/modules/modular_computers/computers/subtypes/dev_pda.dm
  code/modules/modular_computers/computers/subtypes/dev_tablet.dm
  code/modules/modular_computers/computers/subtypes/dev_telescreen.dm
  code/modules/modular_computers/computers/subtypes/dev_wristbound.dm
  code/modules/unit_tests/loadout_tests.dm
  icons/fluff/shadow_laptop.dmi
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance, Sprite Work

#5383 Makes the close button on votes actually close the window
  code/controllers/subsystems/vote.dm
Labels: Bug-Fix

#5385 Trivial Favor Title Correction
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
Labels: Bug-Fix
