Repository sojourn-13/sojourn-station, pull requests merged in 2024-03, with the labels that each got.

#5091 Maxhp via leveling cap
  code/modules/mob/mob.dm
Labels: Balance

#5092 Fixes helmets not hiding ears
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bug-Fix

#5082 Xenoarch fix(es) and intractions
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/geosample.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  code/modules/research/xenoarchaeology/tools/tools_coresampler.dm
Labels: Bug-Fix, Balance, Test Merged

#5089 new bluecross weapon - Crimson Arc
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/oddity_items.dm
  icons/obj/weapons.dmi
Labels: Bug-Fix, Balance, Sprite Work, Test Merged

#5087 Fixed Ambrosia Panacea being a freeby
  code/modules/hydroponics/seed_datums.dm
Labels: Balance

#5101 New Perk Icons ( Set 1 - 42 Icons )
  code/datums/perks/job.dm
  code/datums/perks/nanogate.dm
  code/datums/perks/nepotism.dm
  code/datums/perks/psionic.dm
  code/datums/perks/racial.dm
  icons/effects/perks.dmi
Labels: Sprite Work

#5099 Tames Some Exploits
  code/datums/perks/backgrounds.dm
  code/modules/sanity/sanity_mob.dm
Labels: Bug-Fix, Balance

#5098 crayon basin anti spam
  code/game/objects/effects/decals/crayon.dm
Labels: Bug-Fix, Balance

#5103 *incoherent fox noises*
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/geck.ogg
  sound/voice/slime_squish.ogg
Labels: Balance, Sound Addition

#5106 Quick xenobio fix
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/recipes/recipes_slime.dm
Labels: Removal

#5102 tesla turret fix(?)
  code/game/machinery/tesla_turret.dm
Labels: Bug-Fix, Balance

#5070 Fixes perk-based damage mods, adds ablative subdermal armor
  code/game/objects/items/devices/organ_module/passive/armor.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/organs/external/damage.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/research/nodes/biotech.dm
Labels: Bug-Fix, Balance

#5095 Language Adjustment: Opifexee
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/mob/language/outsider.dm
  code/stylesheet.dm
Labels: Balance

#5080 Faction Addition: Lodge Manifest
  code/__DEFINES/jobs.dm
  code/__HELPERS/manifest.dm
  code/datums/datacore.dm
  code/datums/setup_option/core_implants.dm
  code/datums/topic/admin.dm
  code/datums/topic/world.dm
  code/game/jobs/department.dm
  code/game/jobs/job/offcolony.dm
  code/game/jobs/jobs.dm
Labels: Balance

#5097 Buffs the heavy pulse rifle
  code/modules/projectiles/guns/energy/pulse/heavypulserifle.dm
Labels: Balance

#5100 psi monsters pannel + blueprint exploit fixes
  code/game/gamemodes/events/hivemind_controller.dm
  code/game/objects/items/blueprints.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/ai.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/deepmaints_psionic_controler.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/life.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/psionics/psion.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Test Merged

#5107 Spectral Harvester
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/random/oddities.dm
  code/modules/projectiles/guns/oddity_items.dm
  icons/obj/weapons.dmi
Labels: Bug-Fix, Balance, Sprite Work

#5104 Paper Encurgement
  code/game/objects/effects/decals/crayon.dm
  code/modules/paperwork/paper.dm
Labels: Bug-Fix, Balance

#5093 Change the me verb to be a message box rather than a small text input
  code/modules/mob/say.dm
Labels: Balance

#5112 New Perk Icons ( 38 Icons ) Set 2
  code/datums/perks/backgrounds.dm
  code/datums/perks/job.dm
  code/datums/perks/nanogate.dm
  code/datums/perks/nepotism.dm
  code/datums/perks/oddity.dm
  code/datums/perks/psionic.dm
  code/datums/perks/racial.dm
  icons/effects/perks.dmi
Labels: Enhancement, Sprite Work, Good-To-Merge

#5111 misc helmet fixes
  code/game/objects/random/cloth.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/void/station.dm
  icons/inventory/head/mob.dmi
Labels: Bug-Fix, Balance, Sprite Work

#5113 Buffs foreman
  code/game/jobs/job/prospector.dm
Labels: Balance, Skill-Issue | Salt PR

#5119 Regal Outfit
  code/modules/clothing/suits/greatcoat.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#5110 Blue Carpet cane gun
  code/game/objects/random/oddities.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/projectiles/guns/oddity_items.dm
  icons/obj/weapons.dmi
Labels: Balance, Sprite Work

#5121 By Lamasmaster - Fixes Tenacity and reduces Will to Survive's cooldown
  code/datums/perks/racial.dm
  code/modules/mob/living/carbon/shock.dm
Labels: Balance

#5126 Recipe calculation fix
  code/modules/cooking_with_jane/step_types/use_grill.dm
  code/modules/cooking_with_jane/step_types/use_oven.dm
  code/modules/cooking_with_jane/step_types/use_stove.dm
Labels: Bug-Fix

#5127 Pray for eventmins
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/pray.dm
Labels: Balance

#5122 Better logging + regal outfit
  code/game/machinery/os_portable_turret.dm
  code/game/objects/random/oddities.dm
  code/modules/admin/admin_attack_log.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/projectile.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Bug-Fix, Content, Balance, Sprite Work
