Repository sojourn-13/sojourn-station, pull requests merged in 2024-02, with the labels that each got.

#4999 adds unnecessary mess to medical and also fixes welding for good this…
  code/game/objects/items/weapons/tools/_tools.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#5001 Mod supremisy
  code/modules/admin/verbs/adminsay.dm
Labels: Balance

#5003 Antitoxin + hunger fix
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Bug-Fix, Balance, Skill-Issue | Salt PR, Removal

#5002 Lowers cost of armament summoning litanies, ensures litanies consume power, couple other minor Church fixes
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/core_implant/cruciform/rituals/crusader.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Balance

#5011 Fixes some hunger issues
  code/modules/genetics/mutations/bottomless_belly.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Bug-Fix, Balance

#5010 Adds Mardinat-Yunan specific items
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/head/helmet.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/obj/storage/deferred.dmi
Labels: Content, Balance, Sprite Work

#5015 tubulkar pouch buff
  code/game/objects/items/weapons/storage/pouches.dm
Labels: Balance

#5000 Replaces the Spider Outpost with an underground Spider Cave
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Map, Test Merged

#4981 Stingers and bouncing bullets.
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/turfs/simulated/walls.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/fragment.dm
Labels: Bug-Fix, Balance, Test Merged

#4985 Bullits 'n woundiing mods.
  code/__DEFINES/weapons.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/external/subtypes/standard.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullettypes.dm
  nano/templates/weapon_stats.tmpl
Labels: Bug-Fix, Balance

#5004 Hard case storage buffing
  code/game/objects/items/weapons/storage/hardcases.dm
Labels: Balance

#5005 new toys for the shield.
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/machinery/vendor/weapon_kit_vendors.dm
  code/game/objects/items/weapons/storage/blackshield_kits.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/energy/laser/lasercore.dm
  icons/obj/guns/energy/gleam.dmi
  icons/obj/guns/energy/lasercore_bs.dmi
Labels: Wont fix, Balance, Sprite Work

#5012 gatehouse tweaks + glass buffs
  code/game/machinery/doors/showcase.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/window.dm
  icons/obj/closet.dmi
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map, Test Merged

#5027 Makes carbons no longer spill their organs during bioreactor procesing and give too much biomatter
  code/modules/biomatter_manipulation/bioreactor/platform.dm
Labels: Wont fix, Removal

#5009 Fence position
  code/__DEFINES/jobs.dm
  code/datums/outfits/jobs/prospector.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/department.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/jobs.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/multiz/map_data.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Content, Balance, Sprite Work, Test Merged, changes requested

#5032 Soteria_Sheaths
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/clothing/accessories/holster.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/obj/weapons-blades.dmi
Labels: Enhancement, Content, Balance, Sprite Work, Good-To-Merge

#5031 Defib rebalance
  code/__DEFINES/mob_stats.dm
  code/game/objects/items/devices/defib.dm
Labels: Documentation, Balance

#5034 Foreshadowing the end of an era: removes the Guild bullet fab and adds a board to GM locker
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance

#5035 no more ghost-crew
  code/game/gamemodes/storyteller.dm
Labels: Skill-Issue | Salt PR

#5023 updates the spider hgole this time properly.
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map, Test Merged

#5021 No more connecting bioreactor to solidifier, but buffs transfer rate to canisters
  code/modules/biomatter_manipulation/bioreactor/biotank.dm
  code/modules/biomatter_manipulation/solidifier.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance

#5020 junk field nerf, sorry ya'll.
  code/modules/dungeons/junk_tractor_beam.dm
Labels: Bug-Fix, Balance, Skill-Issue | Salt PR

#5037 Colour difference
  code/game/gamemodes/storyteller.dm
Labels: Balance

#5039 Many map tweaks
  maps/Centcom/map/centcom.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#5041 Misc bug fixes and corrections
  code/__DEFINES/research.dm
  code/datums/autolathe/autolathe_datums.dm
  code/datums/autolathe/organ.dm
  code/datums/craft/recipes/guild.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/autolathe/mechfab.dm
  code/game/machinery/bioprinter_nt.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/aberrants/organs/machinery/organ_fabricator.dm
  code/modules/clothing/spacesuits/void/neotheology.dm
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  code/modules/projectiles/guns/energy/laser/carpediem.dm
  code/modules/projectiles/guns/energy/laser/concilium.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/nordwind.dm
  code/modules/projectiles/guns/projectile/automatic/solmarine.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
  code/modules/projectiles/guns/projectile/pistol/basilisk.dm
  code/modules/projectiles/guns/projectile/revolver/detective.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/hunter_crossbow.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/projectile/plasma_aoe.dm
  code/modules/research/designs.dm
  code/modules/research/designs/mecha_equipment.dm
  code/modules/research/designs/robot_parts.dm
  code/modules/research/rdmachines.dm
  icons/obj/aberrant_organs.dmi
Labels: Bug-Fix, Balance, Nuclear Option

#5045 Passcard adding and tiny AI fix
  code/modules/clothing/accessories/accessory.dm
  code/modules/mob/living/say.dm
Labels: Bug-Fix, Balance

#5044 radiation mod fix
  code/modules/mob/living/damage_procs.dm
Labels: Bug-Fix, Balance

#5046 Fixes some bad layering code issues with defibs
  code/game/objects/items/devices/defib.dm
Labels: Bug-Fix, Balance

#5051 Data Star
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm
  code/modules/projectiles/projectile/special.dm
  icons/mob/battle_roomba.dmi
  sojourn-station.dme
Labels: Bug-Fix, Good-To-Merge

#5052 Fixes an indentation error that causes an error message
  code/modules/client/preference_setup/options_popup.dm
Labels: Bug-Fix

#5047 Accessory Addition: Thick Poncho
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/suit/mob.dmi
Labels: Sprite Work

#5026 CO armor tweaks.
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Bug-Fix, Balance, Sprite Work, Test Merged

#5025 mob armor nukiing.
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/human/stranger.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
Labels: Balance

#5055 Adds Journalist alt title
  code/game/jobs/job/assistant.dm
Labels: Content

#5058 Laser tag vendor
  code/game/machinery/vendor/cloathing.dm
Labels: Content

#5067 Fixes AK frame grips
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
Labels: Bug-Fix, Balance

#5066 Rig slowdown fix
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Bug-Fix, Balance

#5060 Adds neko vending machine
  code/game/machinery/vendor/misc_vendors.dm
  icons/obj/vending.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Enhancement, New Content, Sprite Work, Good-To-Merge

#5071 Adding Winter Cape
  code/game/machinery/vendor/cloathing.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Content, Sprite Work, Good-To-Merge

#5072 Map Bugfix: Prospector Blast Doors
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Map

#5065 Bioreactor eris update.
  code/game/atoms_movable.dm
  code/modules/biomatter_manipulation/biogenerator.dm
  code/modules/biomatter_manipulation/bioreactor/biotank.dm
  code/modules/biomatter_manipulation/bioreactor/loader.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/biomatter_manipulation/bioreactor/unloader.dm
  code/modules/biomatter_manipulation/solidifier.dm
  code/modules/materials/material_sheets.dm
Labels: Enhancement, Balance, Port

#5040 Bioprinter changes
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/autolathe_datums.dm
  code/datums/autolathe/biomatter.dm
  code/game/machinery/bioprinter_nt.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/items/weapons/grenades/heatwave.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/clothing/spacesuits/void/neotheology.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  code/modules/projectiles/guns/energy/laser/carpediem.dm
  code/modules/projectiles/guns/energy/laser/laser.dm
  code/modules/projectiles/guns/energy/laser/sniperrifle.dm
  code/modules/projectiles/guns/energy/plasma/excubitor.dm
  code/modules/projectiles/guns/energy/plasma/plasma.dm
Labels: Balance, Nuclear Option, Removal, Test Merged

#5049 Scrap Haven Rework
  maps/_DeepForest/map/_River_To_Colony.dmm
Labels: Enhancement, New Content, Balance, Map, Nuclear Option

#5068 Hair Addition: Tri Bun + Jill Bugfix
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/mob/hair.dmi
  icons/mob/human_races/species/human/hair.dmi
Labels: Sprite Work, Good-To-Merge

#5077 more data star buffs
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm
Labels: Balance

#5084 Mapping fixes
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#5083 Laser penetration fix
  code/modules/projectiles/projectile/beams.dm
Labels: Bug-Fix

#5081 Bioballistic fix
  code/modules/hydroponics/seed_machines.dm
Labels: Bug-Fix

#5069 Title Addition: Lodge Hunt Master
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance

#5062 Renames and readds numerical clothes
  code/game/machinery/vendor/weapon_vendors.dm
  code/modules/client/preference_setup/loadout/lists/factionabsolute.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Enhancement

#5056 Lowers the Shuttle Flight time
  maps/__Nadezhda/data/shuttles-nadezhda.dm
Labels: Balance

#5053 Refactors psionic powers, plus misc. improvements
  code/modules/psionics/psion.dm
  code/modules/psionics/psion_powers/armour_powers.dm
  code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
  code/modules/psionics/psion_powers/faction_powers.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/locator_powers.dm
  code/modules/psionics/psion_powers/mob_affecting_powers.dm
  code/modules/psionics/psion_powers/oddity_powers.dm
  code/modules/psionics/psion_powers/oldification_powers.dm
  code/modules/psionics/psion_powers/psion_starter_powers.dm
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
  code/modules/psionics/psion_powers/telekinetsis_powers.dm
  code/modules/psionics/psion_powers/teleporation_powers.dm
Labels: Enhancement, Bug-Fix, Balance

#5057 Update eyes.dm
  code/modules/organs/internal/internal_wounds/eyes.dm
Labels: Balance

#5054 revert auretian nerf
  code/modules/projectiles/guns/energy/plasma/centurio_auretian.dm
Labels: Balance

#5086 a better fix for greatermutant not working! :D
  code/modules/hydroponics/seed.dm
Labels: Bug-Fix

#5088 Title Tweak: Huntmaster not Hunt Master
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug-Fix

#5078 Stat balance 9.0c
  code/__DEFINES/mob_stats.dm
  code/__DEFINES/perks.dm
  code/datums/mob_stats.dm
  code/datums/perks/special.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/oddities.dm
  code/game/objects/random/oddities.dm
  code/modules/hivemind/machines.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/sanity/inspiration_component.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/surgery/surgery.dm
  icons/effects/perks.dmi
  icons/obj/oddities.dmi
Labels: Content, Balance, Sprite Work

#5090 drain max hp softcap
  code/game/objects/effects/decals/crayon.dm
Labels: Bug-Fix, Balance
