Repository sojourn-13/sojourn-station, pull requests merged in 2024-07, with the labels that each got.

#5496 removes broken folder
  code/modules/paperwork/folders.dm
Labels: Removal

#5497 Fixes lack of firedoors in medical
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5501 CBO rigsuit fix
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
Labels: Bug-Fix, Balance

#5494 Gives hud-style rig helmets no face covering
  code/modules/clothing/spacesuits/rig/suits/light.dm
Labels: Bug-Fix, Balance

#5495 Ballistic Mask
  code/datums/autolathe/clothing.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/modules/clothing/head/helmet.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Balance, Sprite Work

#5503 SLRaptor fluff item
  code/modules/client/preference_setup/loadout/lists/fluff.dm
  icons/fluff/clothing_mob.dmi
  icons/fluff/fluff_items.dmi
Labels: Sprite Work

#5505 fixes ballistic mask
  code/datums/autolathe/clothing.dm
  code/modules/clothing/head/helmet.dm
Labels: Bug-Fix

#5512 package issue
  code/controllers/subsystems/trade.dm
Labels: Bug-Fix, Balance

#5509 more robust logging
  code/modules/projectiles/projectile.dm
Labels: Bug-Fix

#5511 Artist bench fixes
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/structures/artwork_statue.dm
  code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
Labels: Bug-Fix, Balance

#5517 Corrects artst mods stats
  code/game/objects/items/weapons/tools/mods/mod_types.dm
Labels: Bug-Fix, Balance

#5519 rigs to be storged in the human verbs
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/clothing/spacesuits/rig/rig_modules.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/rig_verbs.dm
  code/modules/clothing/spacesuits/rig/rig_wiring.dm
Labels: Documentation, Enhancement, Bug-Fix, Balance

#5513 proper jr roles
  code/__DEFINES/economy.dm
  code/__DEFINES/jobs.dm
  code/datums/outfits/jobs/blackshield.dm
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/security.dm
  code/datums/setup_option/backgrounds/origin_chtmant.dm
  code/datums/setup_option/core_implants.dm
  code/game/jobs/department.dm
  code/game/jobs/job/blackshield.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/jobs.dm
  code/game/objects/landmarks/join.dm
  code/modules/client/preference_setup/loadout/lists/factionartificer.dm
  code/modules/client/preference_setup/loadout/lists/factionblackshield.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/multiz/map_data.dm
  icons/misc/landmarks.dmi
  icons/mob/hud.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Enhancement, Balance, Sprite Work, Skill-Issue | Salt PR, Map, Test Merged

#5516 Update c20r.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
Labels: Bug-Fix, Balance

#5514 Disposal rework and mailing room
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map, Removal

#5518 Handmade Guild Cells
  code/datums/craft/recipes/guild.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/projectiles/guns/energy/projectile/slab.dm
  icons/obj/power_cells.dmi
Labels: Enhancement, Balance, Sprite Work

#5522 Creates a barefoot shoes that does not have a mob icon so people can walk around "barefoot"
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/shoes/jobs.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
Labels: Balance, Sprite Work

#5523 Slabteehee
  code/modules/projectiles/guns/energy/projectile/slab.dm
Labels: Balance

#5524 Startup optimization - 218 seconds -> 154.7
  code/__DEFINES/misc.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/areas.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystems/mapping.dm
  code/datums/transformation_types/transform_types.dm
  code/datums/transformation_types/types.dm
  code/game/turfs/simulated/wall_icon.dm
  code/modules/projectiles/gun_firemode.dm
  prof.dll
Labels: Documentation, Enhancement

#5507 Adds Security/Defence borg sprite
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots.dmi
Labels: Balance, Sprite Work

#5515 CWJ Oven overhaul
  code/__DEFINES/cooking_with_jane.dm
  code/modules/cooking_with_jane/cooking.dm
  code/modules/cooking_with_jane/cooking_appliances/grill.dm
  code/modules/cooking_with_jane/cooking_appliances/oven.dm
  code/modules/cooking_with_jane/cooking_appliances/stove.dm
  code/modules/cooking_with_jane/cooking_items/cooking_containers.dm
  code/modules/cooking_with_jane/cooking_tracker.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_dough.dm
  code/modules/cooking_with_jane/step_types/add_reagent.dm
  code/modules/cooking_with_jane/step_types/use_tool.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/recipes.dm
  sojourn-station.dme
Labels: Documentation, Enhancement, Bug-Fix, Balance

#5387 Makes the Church vendor no longer custom
  code/game/machinery/vendor/weapon_vendors.dm
Labels: Wont fix, Balance, Test Merged

#5510 opfiex buffs
  code/datums/perks/racial.dm
  code/datums/setup_option/backgrounds/origin_opifex.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/organ_module/_module.dm
  code/game/objects/items/devices/organ_module/active/pouch.dm
  code/game/objects/items/devices/organ_module/passive/muscle.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/firstaid.dm
Labels: Enhancement, Bug-Fix, Balance

#5529 Fixes the Guild part of the disposal line
  code/game/objects/structures.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance

#5533 med students now spawn with labcoats & not armored vests
  code/datums/outfits/jobs/medical.dm
Labels: Balance

#5534 Adds homewrecker backsprites and fixes power crovel backsprites
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/shovel.dm
  icons/inventory/back/mob.dmi
Labels: Balance, Sprite Work

#5531 SMC MEHA
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/structures/burrows.dm
  code/game/objects/structures/flora/flora.dm
  code/game/objects/structures/turf_spawner.dm
  code/game/turfs/flooring/flooring.dm
  code/modules/mining/drilling/slab_mining.dm
  code/modules/mining/mine_turfs.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/sanity/sanity_mob.dm
  icons/obj/mining.dmi
  icons/obj/structures.dmi
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/human_helper.dm
  modular_sojourn/task_master/tasks.dm
  sojourn-station.dme
Labels: Content, Balance, Sprite Work, Test Merged

#5536 Something about tripping
  code/game/turfs/flooring/flooring.dm
Labels: Bug-Fix

#5386 Fluff Items [Alpha Branch]
  code/game/objects/items/weapons/storage.dm
  code/modules/admin/admin_investigate.dm
  code/modules/client/preference_setup/loadout/lists/fluff.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/modular_computers/computers/subtypes/dev_console.dm
  code/modules/modular_computers/computers/subtypes/dev_laptop.dm
  code/modules/modular_computers/computers/subtypes/dev_pda.dm
  code/modules/modular_computers/computers/subtypes/dev_tablet.dm
  code/modules/modular_computers/computers/subtypes/dev_telescreen.dm
  code/modules/modular_computers/computers/subtypes/dev_wristbound.dm
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  code/modules/modular_computers/computers/subtypes/preset_pda.dm
  code/modules/nanogate/nanogate_vm.dm
  code/modules/unit_tests/loadout_tests.dm
  icons/fluff/clothing_mob.dmi
  icons/fluff/fluff_items.dmi
  sojourn-station.dme
Labels: Documentation, Enhancement, Sprite Work

#5540 removes some debug things
  modular_sojourn/task_master/human_helper.dm
Labels: Bug-Fix

#5530 Remove overlay stat logging at round end
  code/controllers/subsystems/overlays.dm
Labels: Balance

#5535 Switch all_wall_states to be less sus and initialize lazily
  code/game/turfs/simulated/wall_icon.dm
Labels: Enhancement

#5544 Misc fixes
  .github/workflows/ci_suite.yml
  code/__DEFINES/misc.dm
  code/__HELPERS/_logging.dm
  code/_onclick/hud/action.dm
  code/datums/datum_hud.dm
  code/game/world.dm
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/global/preferences.dm
  code/modules/mob/living/carbon/human/human_hud.dm
  code/modules/mob/living/default_language.dm
  code/modules/unit_tests/_unit_tests.dm
  sojourn-station.dme
  tools/ticked_file_enforcement/schemas/sojourn_dme.json
  tools/ticked_file_enforcement/schemas/unit_tests.json
  tools/ticked_file_enforcement/ticked_file_enforcement.py
  tools/validate_dme.py
Labels: Bug-Fix, Balance

#5545 Emergency Fix: Actually apply the skin.dmf changes
  interface/skin.dmf
Labels: Bug-Fix, Balance

#5542 mining less affect + less cheesy ore smelting
  code/game/machinery/autolathe/autolathe.dm
  code/modules/mining/mine_point_vendor.dm
  code/modules/mining/mine_turfs.dm
Labels: Bug-Fix, Balance, Skill-Issue | Salt PR

#5543 converts the HEV suit to new armor system
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Bug-Fix, Balance

#5541 Cargo + maints + pipeing
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Skill-Issue | Salt PR, Map

#5506 Adds 6 new psionic powers
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/random/scrap.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/trash_powers.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
  icons/obj/stack/items.dmi
  sojourn-station.dme
Labels: Enhancement, Balance

#5551 CBO Helmet Fix
  icons/inventory/head/mob.dmi
Labels: Balance, Sprite Work

#5552 Update psi_catalysts.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
Labels: Bug-Fix, Balance

#5554 Research Face Lift
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5553 Colorable harpy wings
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/sprite_accessories/_accessory_wings.dm
  icons/mob/sprite_accessory/wings.dmi
Labels: Balance, Sprite Work

#5556 fixes weird verbiage in new soteria alt titles
  code/game/jobs/job/science.dm
Labels: Documentation

#5555 For surgery, shift it all down one tile
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5561 Update _Nadezhda_Colony_New.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#5560 Hopefully fixes lodge bolt lance and minor smelter fixes.
  code/game/machinery/smelter.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#5549 Psionic clothing
  code/__DEFINES/research.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/materials/materials.dm
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion.dm
  code/modules/psionics/psion_powers/trash_powers.dm
  code/modules/psionics/psionic_items/psi_armor.dm
  code/modules/psionics/psionic_items/psi_misc.dm
  code/modules/research/designs/psionic.dm
  code/modules/research/nodes/psionic.dm
  code/modules/research/research.dm
  icons/inventory/ears/icon.dmi
  icons/inventory/ears/mob.dmi
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/pockets/icon.dmi
  icons/obj/psionic/occ_armor.dmi
  icons/obj/psionic/occicon.dmi
  icons/obj/psionic/occmob.dmi
  nano/css/shared.css
  nano/images/science.png
  sojourn-station.dme
Labels: Enhancement, Bug-Fix, Balance, Sprite Work, Test Merged

#5565 new rig sprites for hazmat RIG, Hazard RIG and EVA RIG
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
Labels: Sprite Work

#5559 Art cooldown + better values
  code/__DEFINES/perks.dm
  code/datums/perks/cooldown.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/structures/artwork_statue.dm
  icons/effects/perks.dmi
Labels: Bug-Fix, Balance, Sprite Work, Skill-Issue | Salt PR, Test Merged

#5567 Prosthetic markings
  code/modules/sprite_accessories/_accessory_marking.dm
  icons/mob/human_races/markings.dmi
Labels: Balance, Sprite Work

#5574 Gibber fixs
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/scrap/scrap_pileripper.dm
Labels: Bug-Fix, Balance

#5575 Fixes endless plasma
  code/modules/mob/living/carbon/human/life.dm
Labels: Bug-Fix, Balance

#5576 Nanoforgestuff + toolmod fix
  code/game/machinery/autolathe/matterforge.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
Labels: Bug-Fix, Balance

#5539 Better reaching attacks
  code/__DEFINES/perks.dm
  code/_onclick/item_attack.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/storage.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/judgement_sheath.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/wielding.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
  code/modules/research/xenoarchaeology/finds/finds_eguns.dm
  modular_sojourn/task_master/_task_master_defines.dm
  modular_sojourn/task_master/human_helper.dm
  modular_sojourn/task_master/tasks.dm
Labels: Enhancement, Bug-Fix, Content, Balance

#5570 Cloth psych ward walls
  code/game/turfs/simulated/wall_types.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5581 more fixes
  code/modules/clothing/head/helmet.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
Labels: Bug-Fix, Balance

#5584 fixes artist gun names (again) and TK for trays + misc
  code/game/machinery/autolathe/artist_bench.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  icons/obj/food.dmi
Labels: Bug-Fix, Balance, Sprite Work, Port

#5582 Fixes armor values for the ballistic mask
  code/modules/clothing/head/helmet.dm
Labels: Bug-Fix, Balance

#5580 Fixes rig armor maybe
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
Labels: Bug-Fix, Balance, Test Merged

#5579 new tiles from fallout servers
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/turf_spawner.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/flooring/flooring_premade.dm
  icons/obj/stack/tile.dmi
  icons/turf/flooring/decals.dmi
  icons/turf/flooring/tiles_industeral.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Sprite Work, Map, Test Merged, Port

#5569 Tweaks spawn rates of ore in slab + psion fix
  code/modules/mining/drilling/slab_mining.dm
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion.dm
Labels: Balance, Test Merged

#5585 Fixes for Alchemy
  code/modules/reagents/machinery/alchemy.dm
  code/modules/reagents/recipes/alchemy.dm
Labels: Bug-Fix, Balance

#5588 Returns to pile ripper
  code/modules/scrap/scrap_pileripper.dm
Labels: Wont fix

#5563 Handheld explosives nerf, or; The saltiest of the salt nerfs yet.
  code/datums/autolathe/ammo.dm
  code/datums/perks/nanogate.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/crafting_station_recipes.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/random/ammo.dm
  code/modules/cargo/packs_security.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm
  code/modules/projectiles/guns/projectile/other/lenar.dm
  code/modules/projectiles/guns/projectile/other/protector.dm
  code/modules/projectiles/guns/projectile/other/underslung.dm
  code/modules/projectiles/guns/projectile/pistol/gyropistol.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  maps/SpaceFortress/map/exc_fort.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Skill-Issue | Salt PR, Map, Nuclear Option, Removal

#5577 Painmaker fixers
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/projectile/revolver/hornet.dm
  code/modules/projectiles/projectile.dm
Labels: Bug-Fix, Balance

#5564 some combat PR balance tweaks
  code/game/objects/random/rig.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/guns/projectile/shotgun/buffalo.dm
  code/modules/projectiles/guns/projectile/shotgun/swat.dm
Labels: Balance

#5573 Fixes RIG ablative armor readout, nerfs AMI rig.
  code/game/objects/random/science.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
Labels: Bug-Fix, Balance

#5590 Fixes another issue with harvesting
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug-Fix

#5592 splint fix and fpb mercy
  code/game/objects/items/stacks/medical_stacks/medical.dm
  code/game/objects/items/stacks/medical_stacks/splint_stacks.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/external/_external.dm
Labels: Bug-Fix, Balance

#5586 print-o-matter
  code/game/machinery/vendor/tool_vendors.dm
  code/modules/materials/material_sheets.dm
Labels: Balance, Test Merged

#5596 Sprite crediting + artwork revolver name fix
  code/game/machinery/kitchen/smartfridge.dm
  code/modules/mob/living/carbon/superior_animal/drone/handmade_drone.dm
  code/modules/projectiles/guns/projectile/automatic/vector.dm
  code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
  code/modules/psionics/credits.dm
  code/modules/telesci/telepads.dm
  icons/mob/custom_bot.dmi
  icons/obj/telescience.dmi
  sojourn-station.dme
Labels: Documentation

#5595 Autodoc Bugfix / Church Jobs Tweak
  code/game/jobs/job/church.dm
  code/modules/surgery/autodoc.dm
Labels: Bug-Fix, Balance

#5587 Return of Sudtle (Not antighost)
  code/modules/mob/say.dm
Labels: Balance, Skill-Issue | Salt PR

#5562 New forest ruin!
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
Labels: Bug-Fix, Balance, Map, Test Merged

#5572 Merge-conflict resolution of PR 5538
  code/datums/craft/recipes/armor.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/storage.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
Labels: Content, Sprite Work

#5601 Quick botch fix for JTB portals
  code/game/objects/effects/portals.dm
Labels: Bug-Fix
