Repository sojourn-13/sojourn-station, pull requests merged in 2024-08, with the labels that each got.

#5598 Defib + better floors
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#5599 lowers some armor values
  code/modules/clothing/suits/armor.dm
Labels: Balance

#5604 Fixes tree stumps not spawning anchored
  code/game/objects/structures/flora/flora_tree.dm
Labels: Bug-Fix

#5609 everything for the event and test
  code/ATMOSPHERICS/components/unary/air_blocker.dm
  code/game/turfs/flooring/flooring_premade.dm
  maps/SpaceFortress/map/space_ambush.dmm
  maps/SpaceFortress/spacefortress.dm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
  sojourn-station.dme
Labels: Balance, Map

#5610 fixes some pathing
  code/game/machinery/vendor/tool_vendors.dm
  code/modules/materials/material_sheets.dm
Labels: Bug-Fix

#5611 Fixes an icon error
  code/modules/materials/material_sheets.dm
Labels: Bug-Fix

#5600 New tobacco products (WIP for Trilby review)
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/misc.dm
  icons/inventory/face/icon.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/cigarettes.dmi
Labels: Balance, Sprite Work, Port

#5603 Adds dynamic blinky lights to the intercom.
  code/game/objects/items/devices/radio/intercom.dm
  icons/obj/radio.dmi
Labels: Balance, Sprite Work

#5602 automatic exchange machine
  code/modules/economy/ATM.dm
  icons/obj/terminals.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Sprite Work, Map

#5608 Wrestling ring in the west maintenance
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5613 Small kitchen changes
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
Labels: Balance, Map

#5612 nerfs power sledges
  code/game/objects/items/weapons/tools/hammer.dm
Labels: Balance

#5605 Maybe fixes dropped phatom guns
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_firemode.dm
  code/modules/projectiles/guns/energy/charge.dm
  code/modules/projectiles/guns/projectile/automatic.dm
Labels: Bug-Fix, Balance

#5606 sleeping buff + some small optimizations
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/slime/life.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/life.dm
Labels: Enhancement, Balance

#5591 More Cyberware
  code/game/objects/items/devices/organ_module/active/pouch.dm
  code/game/objects/items/devices/organ_module/passive/blood.dm
  code/game/objects/items/devices/organ_module/passive/food.dm
  code/game/objects/items/devices/organ_module/passive/nsa.dm
  code/game/objects/items/devices/organ_module/passive/sanity.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/research/nodes/biotech.dm
  code/modules/research/nodes/illegal.dm
  code/modules/surgery/internal.dm
  icons/inventory/pockets/icon.dmi
  icons/obj/surgery.dmi
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work, Test Merged

#5621 Moves unused maps into their own folder
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
  maps/__Nadezhda/nadezhda.dm
  maps/__Nadezhda/unused/Surface_Old.dmm
  maps/__Nadezhda/unused/Underground_Old.dmm
  maps/__Nadezhda/unused/_Nadezhda_Colony_Omni_STU.dmm
  maps/__Nadezhda/unused/_Nadezhda_Colony_Surface.dmm
  maps/__Nadezhda/unused/_Nadezhda_Colony_Transition.dmm
  maps/__Nadezhda/unused/_Nadezhda_Colony_Underground.dmm
  maps/__Nadezhda/unused/_Nadezhda_Colony_labercamp.dmm
  maps/__Nadezhda/unused/unused_map_datas.dm
  maps/__Nadezhda/unused_map_datas.dm
Labels: Documentation

#5620 fixes tally issues + fixes some kegs + buffs herme shoes
  code/datums/mob_stats.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
Labels: Bug-Fix, Balance

#5623 Adds More Marshal Clothes
  code/modules/clothing/accessories/badges.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Balance, Sprite Work

#5624 Drop off maths tweaks
  code/modules/projectiles/projectile.dm
Labels: Balance

#5626 runtimes food and fix for ians
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Balance, Map

#5628 fixes to regal suit
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bug-Fix, Balance

#5634 Removes a *BRUH* unexpanded debuff from SI synths
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Balance

#5633 Food descriptor fix
  code/modules/cooking_with_jane/food_overrides.dm
Labels: Bug-Fix

#5619 Opt in lower stat caps
  code/controllers/subsystems/jobs.dm
  code/datums/mob_stats.dm
  code/modules/client/preference_setup/general/07_stats.dm
Labels: Enhancement, Balance

#5618 Fixes skill perks cap things
  code/datums/perks/special.dm
  code/game/machinery/autolathe/matterforge.dm
Labels: Bug-Fix, Balance

#5616 chemicals for sleeping folks
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Balance

#5625 fixes ak sprite + OKB armor
  code/modules/mob/living/simple_animal/hostile/excelsior.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  icons/obj/guns/projectile/ak_homemade.dmi
Labels: Bug-Fix, Balance

#5627 Kaiser fixes and betterment
  code/game/objects/effects/overlays.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach_spits.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
Labels: Bug-Fix, Balance

#5622 antibluecross cheats
  code/game/objects/items/weapons/storage/vendor_loot_boxes.dm
  code/game/objects/random/oddities.dm
Labels: Balance, Skill-Issue | Salt PR, Test Merged

#5635 kaiser dead attack fix
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
Labels: Bug-Fix, Balance

#5637 Fixes certain tasers not tasing
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/plasma.dm
  code/modules/projectiles/projectile/special.dm
Labels: Bug-Fix, Balance

#5638 exploit fix + rnd additions
  code/game/objects/items/weapons/implant/implants/chemical.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/research/nodes/biotech.dm
Labels: Bug-Fix, Balance

#5640 bullet fixes
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/fragment.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  code/modules/projectiles/projectile/special.dm
Labels: Bug-Fix, Balance

#5631 More synth implants
  code/datums/setup_option/backgrounds/origin_synthetic.dm
  code/game/objects/items/devices/organ_module/active/armblades.dm
  code/game/objects/items/devices/organ_module/active/armguns.dm
  code/game/objects/items/devices/organ_module/active/multitool/engineering.dm
  code/game/objects/items/devices/organ_module/active/multitool/farmer.dm
  code/game/objects/items/devices/organ_module/active/multitool/lighting.dm
  code/game/objects/items/devices/organ_module/active/multitool/medical.dm
  code/game/objects/items/devices/organ_module/active/multitool/miner.dm
  code/game/objects/items/devices/organ_module/active/pouch.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
  code/game/objects/items/stacks/medical_stacks/splint_stacks.dm
  code/modules/power/cable.dm
  code/modules/projectiles/guns/energy/laser/laser_cannon.dm
  icons/obj/power.dmi
  icons/obj/surgery.dmi
  sojourn-station.dme
Labels: Content, Balance, Sprite Work, Test Merged

#4969 Generate Discord Link
  code/game/world.dm
Labels: Documentation

#5642 rig and helmt stuff
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Bug-Fix, Balance

#5632 replaces courtroom with arcade + general remapping of the bar/halway
  code/game/turfs/flooring/flooring.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Balance, Map, Test Merged

#5643 removes a bad debug gun
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Bug-Fix, Balance, Map

#5646 leaks no longer break down
  code/modules/sanity/sanity_mob.dm
  modular_sojourn/spaceleak.dm
Labels: Balance

#5644 reavers will no longer be as mocked
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/reaver.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/beams.dm
  sojourn-station.dme
Labels: Documentation, Enhancement, Balance

#5647 armor fixes + gun penetration fix
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
Labels: Bug-Fix, Balance

#5629 Insight womp
  code/datums/perks/job.dm
  code/modules/sanity/sanity_mob.dm
Labels: Documentation, Skill-Issue | Salt PR, Nuclear Option
