Repository sojourn-13/sojourn-station, pull requests merged in 2024-09, with the labels that each got.

#5653 fixes ear slotting in pillar 3
  code/modules/psionics/ear.dm
Labels: Bug-Fix

#5648 MORE BORG ICOSN!!!!!
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robot_tall/cargo_dullahan.dmi
  icons/mob/robot_tall/engi.dmi
  icons/mob/robot_tall/engi_dullahan.dmi
  icons/mob/robot_tall/janitor_dullahan.dmi
  icons/mob/robot_tall/medical.dmi
  icons/mob/robot_tall/medical_dullahan.dmi
  icons/mob/robot_tall/medical_ft.dmi
  icons/mob/robot_tall/mining_dullahan.dmi
  icons/mob/robot_tall/misc_dullahan.dmi
  icons/mob/robot_tall/readme.md
  icons/mob/robot_tall/science_dullahan.dmi
  icons/mob/robot_tall/sec_dullahan.dmi
  icons/mob/robot_tall/server_dullahan.dmi
  icons/mob/robots.dmi
Labels: Documentation, Balance, Sprite Work, Port

#5661 Revert "Bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows"
  .github/workflows/ci_suite.yml
Labels: Removal

#5663 minor Robotics Typo fixes
  code/game/objects/items/devices/organ_module/passive/food.dm
  code/game/objects/items/devices/organ_module/passive/nsa.dm
  code/game/objects/items/devices/organ_module/passive/sanity.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
Labels: Documentation

#5662 Cube+Pouch+Rig
  code/game/objects/items/devices/organ_module/active/pouch.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/reagents/reagent_containers/food/cubes.dm
Labels: Bug-Fix, Balance

#5651 SOM and cargo "qol"
  code/controllers/subsystems/trade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/trade/datums/_trade_station.dm
  nano/templates/trade.tmpl
Labels: Enhancement, Bug-Fix, Balance

#5650 Void wolf captain
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/reaver.dm
  icons/mob/mobs-humanoid.dmi
Labels: Balance, Sprite Work

#5665 More love for borgs.
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance

#5669 G.P. Revolution (Lets wallets holds G.P. Yuan.)
  code/game/objects/items/weapons/storage/wallets.dm
Labels: Bug-Fix

#5664 The greatest NPC revolt as seen on TV
  code/__HELPERS/game.dm
  code/game/machinery/doors/door.dm
  code/game/objects/explosion.dm
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/ameridian/ameridian_spire.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/projectiles/projectile.dm
  code/modules/sanity/sanity_mob.dm
Labels: Enhancement, Bug-Fix, Balance, Test Merged

#5657 Buffs Divisors, changes Lemniscates, gives utility litany to prime
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Enhancement, Bug-Fix, Balance

#5670 fire fighting buff for borgs
  code/game/objects/items/weapons/extinguisher.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance

#5679 Update descriptions of meds
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/toxins.dm
Labels: Enhancement

#5682 Removal of a second chef and bartender slot
  code/game/jobs/job/civilian.dm
Labels: Balance, Skill-Issue | Salt PR

#5681 Add marshal raincloak
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
Labels: Balance, Sprite Work

#5680 Area issues Corrections
  code/game/area/areas.dm
  code/game/area/asteroid_areas.dm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
Labels: Bug-Fix, Balance, Test Merged

#5671 more brewing
  modular_sojourn/brewing.dm
  modular_sojourn/brewing_datums.dm
Labels: Balance

#5659 Bridge Remodel!
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Enhancement, Balance, Map

#5656 churn
  code/datums/craft/recipes/storage.dm
  maps/_HunterLodge/map/_Hunting_Lodge.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
  modular_sojourn/churn.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#5686 Add suit iconstates for the new marshal cloak
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Bug-Fix, Sprite Work

#5685 [Content] Irkalla lives, fixes Dissolver sounds finally
  code/modules/projectiles/guns/energy/laser/xray.dm
  sound/weapons/energy/Dissolve.ogg
Labels: Bug-Fix, Sound Addition

#5689 Accessory Addition: colorable drop straps
  code/modules/client/preference_setup/loadout/lists/accessories.dm
Labels: Balance

#5688 Human layering button
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance

#5684 New job titles, fixing spelling errors and rephrasing some descriptions
  code/game/jobs/job/avisitor.dm
  code/game/jobs/job/blackshield.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/offcolony.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/security.dm
Labels: Documentation, Balance

#5691 Opt in colour filters
  modular_sojourn/client_colour.dm
  sojourn-station.dme
Labels: Content, Balance, Port

#5690 More fonts for papers
  code/modules/paperwork/paper.dm
  code/modules/paperwork/pen.dm
  icons/obj/bureaucracy.dmi
Labels: Balance, Sprite Work, Test Merged

#5687 dispolies cargo
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Balance, Map

#5677 Hivemind buffs(*)
  code/game/gamemodes/events/hivemind_controller.dm
  code/game/objects/structures/burrows.dm
  code/modules/hivemind/mobs.dm
Labels: Documentation, Enhancement, Bug-Fix, Balance

#5673 Recipe coverts + fixes + makeover of food and drink
  code/game/objects/items/oddities_faction.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_burger.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
  code/modules/cooking_with_jane/step_types/add_produce.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/mob/living/carbon/superior_animal/lodge/types/cerberus.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/bread_loafs.dm
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
  code/modules/reagents/reagent_containers/food/snacks/cakes_pies.dm
  code/modules/reagents/reagent_containers/food/snacks/donut.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagent_containers/food/snacks/pizza.dm
  code/modules/reagents/reagent_containers/food/snacks/sandwich.dm
  code/modules/reagents/reagent_containers/food/snacks/soup.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
  sojourn-station.dme
Labels: Documentation, Enhancement, Bug-Fix, Balance

#5696 Removes character direct refences
  code/modules/genetics/machinery/advanced_grinder.dm
  code/modules/genetics/machinery/genetics_analyzer.dm
  code/modules/genetics/machinery/genetics_cloner.dm
  code/modules/genetics/machinery/genetics_designs.dm
  code/modules/genetics/machinery/genetics_items.dm
  maps/Centcom/map/centcom.dmm
  nano/templates/clone_console.tmpl
  nano/templates/genetic_analyzer.tmpl
Labels: Documentation

#5698 chef doggos fluff item
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/client/preference_setup/loadout/lists/fluff.dm
  icons/fluff/fluff_items.dmi
Labels: Balance, Sprite Work

#5699 Make BS-BDU selectable in loadout
  code/modules/client/preference_setup/loadout/lists/factionblackshield.dm
Labels: Balance

#5697 fixes vender exploit
  code/game/machinery/vending.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
Labels: Balance

#5695 Rigsuit shield module health buff
  code/game/objects/items/weapons/shields.dm
Labels: Balance

#5703 Add glass pitchers to dinnerware vendors
  code/game/machinery/vendor/food_vendors.dm
Labels: Balance

#5702 Fix CO coat, add new CO fullbody tan/green
  code/modules/clothing/suits/armor.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Bug-Fix, Balance, Sprite Work

#5701 Sprite Additon: Flower Crown Galore
  code/datums/craft/recipes/clothing.dm
  code/modules/client/preference_setup/loadout/lists/cosmetics.dm
  code/modules/clothing/head/misc.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Content, Sprite Work

#5705 More specific hog desc
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Documentation

#5710 Gun parts fixes
  code/modules/projectiles/guns/projectile/automatic/greasegun.dm
  code/modules/projectiles/guns/projectile/automatic/sts.dm
Labels: Bug-Fix, Balance
