Repository sojourn-13/sojourn-station, pull requests merged in 2024-10, with the labels that each got.

#5716 Removes guild requirement
  code/game/gamemodes/storyteller.dm
Labels: Removal

#5715 Lonestar grammar fixes and additions
  code/game/jobs/job/guild.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
Labels: Enhancement

#5712 Allow items in storage slots to not hassle body cover checks
  code/__HELPERS/mobs.dm
Labels: Bug-Fix, Balance

#5711 wall builders
  code/datums/craft/recipes/wall.dm
  code/datums/craft/step.dm
  code/game/objects/structures/turf_spawner.dm
  code/game/turfs/simulated/wall_types.dm
  icons/obj/structures.dmi
Labels: Balance, Sprite Work

#5708 Medical items death grip
  code/modules/mob/living/carbon/human/human_organs.dm
Labels: Balance

#5704 exspands blackshield dorms and gives back the shower area
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Bug-Fix, Balance, Test Merged

#5683 No pain gene fix
  code/__DEFINES/genetics.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/structures/morgue.dm
  code/modules/genetics/mutations/painless.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/unarmed_attack.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/mob.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/organ.dm
  code/modules/organs/pain.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/scrap/scrap.dm
Labels: Enhancement, Bug-Fix, Balance, Test Merged

#5706 more CWJ recipes and fixes
  code/__HELPERS/global_lists.dm
  code/modules/cooking_with_jane/recipes/cubes.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
  code/modules/cooking_with_jane/step_types/add_produce.dm
  code/modules/hydroponics/grown_predefined.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  modular_sojourn/brewing_datums.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance

#5645 Hunters update (1/?)
  code/datums/craft/recipes/lodge.dm
  code/game/objects/items/stacks/throwing.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/objs.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/mob/light_overlays.dmi
  icons/mob/rig_back.dmi
  icons/obj/cannibal_scythe.dmi
  icons/obj/light_overlays.dmi
  icons/obj/rig_modules.dmi
  icons/obj/stack/items.dmi
  icons/obj/weapons.dmi
  sound/misc/sandjump.ogg
  sound/weapons/flamesword.ogg
  sound/weapons/scabbard.ogg
Labels: Enhancement, Content, Balance, Sprite Work, Sound Addition

#5718 art + ladon fixes
  code/modules/projectiles/guns/projectile/pistol/ladon.dm
  code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
Labels: Bug-Fix, Balance

#5722 Correctly removing Belvoix from things
  code/modules/genetics/machinery/advanced_grinder.dm
  code/modules/genetics/machinery/genetics_analyzer.dm
  code/modules/genetics/machinery/genetics_cloner.dm
  code/modules/genetics/machinery/genetics_items.dm
  maps/Centcom/map/centcom.dmm
Labels: Documentation

#5723 Church changes
  code/game/jobs/job/church.dm
  code/modules/clothing/head/helmet.dm
Labels: Bug-Fix, Balance

#5724 Map Addition: New Vector Room and Chiken Coop Moved
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Balance, Map

#5725 Parse bbcode for admin fax
  code/datums/topic/admin.dm
Labels: Enhancement

#5729 Micro Map Addition: Chikens Crosses
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Balance, Map

#5727 allows artist to make 12mm revolvers
  code/game/machinery/autolathe/artist_bench.dm
  code/modules/projectiles/guns/projectile/revolver/artwork_revolver.dm
Labels: Content, Balance

#5720 Roach Meat Audit + GP station change (And Misc Station tweaks)
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/greyson_ship_alt.dm
Labels: Bug-Fix, Balance

#5714 Gives staff fancy OOC tags.
  code/game/verbs/ooc.dm
  icons/chattags.dmi
Labels: Enhancement

#5707 Fixes fluff item ckey check
  code/modules/client/preference_setup/loadout/lists/fluff.dm
Labels: Bug-Fix

#5693 Add Crinos + Allow for species-specific speak-only languages
  code/__DEFINES/chemistry.dm
  code/__DEFINES/species_languages.dm
  code/datums/perks/backgrounds.dm
  code/datums/perks/racial.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/say.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/tgchat/shared/basic.scss
  tgui/public/tgui-panel.bundle.css
Labels: Content, Balance

#5728 MINOR Psych QOL Map Changes
  code/modules/reagents/reagent_containers/food/drinks.dm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Balance, Map

#5730 Suits and Boots
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/trade/datums/trade_stations_presets/1-common/botany.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
Labels: Balance

#5731 Makes both foreman melee options more equivalent
  code/game/objects/items/weapons/tools/simple_weapons.dm
Labels: Balance

#5737 Wasps
  code/modules/mob/living/simple_animal/hostile/big.dm
  icons/mob/deathclaw.dmi
Labels: Balance, Sprite Work

#5735 Balance rigtele, fix energy nets
  code/game/objects/items/weapons/weaponry.dm
  code/modules/clothing/spacesuits/rig/modules/ninja.dm
  code/modules/mob/mob_defines.dm
Labels: Bug-Fix, Balance

#5738 Statues and Signposts
  code/game/objects/structures/statues.dm
  icons/obj/stationobjs.dmi
  icons/obj/statue_large.dmi
  sojourn-station.dme
Labels: Sprite Work

#5745 Altyn Rebalance
  code/modules/clothing/head/helmet.dm
Labels: Balance

#5744 Mercurian
  code/modules/projectiles/guns/projectile/automatic/mercurian.dm
Labels: Balance

#5743 Change Crinos to ,5
  code/modules/mob/language/outsider.dm
Labels: Bug-Fix

#5742 big stat buffs for synths
  code/datums/setup_option/backgrounds/origin_synthetic.dm
Labels: Balance

#5741 marqua backround tweaks
  code/datums/setup_option/backgrounds/origin_marqua.dm
Labels: Documentation, Balance

#5740 Fixes firefighter slam interactions with dense objects
  code/modules/mob/mob_grab_specials.dm
Labels: Bug-Fix, Balance

#5734 Decrease PARA conversion kit price
  code/game/machinery/excelsior/blackshield_teleporter.dm
Labels: Balance

#5726 churn and witches brew
  code/modules/reagents/reagents/food-Drinks.dm
  icons/obj/drinks.dmi
  modular_sojourn/brewing_datums.dm
  modular_sojourn/churn.dm
Labels: Balance, Sprite Work

#5713 Use role's alt title instead of assigned role when cryoing
  code/game/machinery/cryopod.dm
Labels: Enhancement, Bug-Fix

#5747 fixes gas masks and bridge pipes
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/mob/inventory.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Bug-Fix, Balance, Map

#5748 Let artists name/desc their creation
  code/game/machinery/autolathe/artist_bench.dm
Labels: Enhancement

#5750 fixes disk auto naming incorrectly
  code/modules/hydroponics/seed_gene_presets.dm
Labels: Bug-Fix

#5757 Updates synth buffs.
  code/datums/setup_option/backgrounds/origin_synthetic.dm
Labels: Balance

#5760 We Dig It
  code/modules/trade/datums/trade_stations_presets/2-uncommon/junker.dm
Labels: Balance

#5759 Burgers for VIKA + dumplings fix
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_burger.dm
Labels: Content, Balance

#5758 Crafting Addition: Sofa
  code/datums/craft/recipes/furniture.dm
Labels: Balance

#5756 Solarian armor added helmet and mask for full set no kit bashing
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Balance, Sprite Work

#5763 Sunrise + Firestorm
  code/modules/projectiles/guns/energy/laser/firestorm.dm
  code/modules/projectiles/guns/energy/laser/sunrise.dm
Labels: Bug-Fix, Balance

#5755 Lowers crayon sanity damage
  code/game/objects/effects/decals/crayon.dm
Labels: Balance

#5753 Clean up poison attacks/give wasprender poisonbite
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/attack.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/drone.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Documentation, Enhancement, Bug-Fix, Balance

#5754 better power sink and guilg rig
  code/modules/clothing/spacesuits/rig/modules/computer.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
Labels: Balance

#5751 fixes some materal weapons and xenoarch weapons
  code/game/objects/items/weapons/material/material_weapons.dm
  code/modules/research/xenoarchaeology/finds/finds_eguns.dm
Labels: Bug-Fix, Balance

#5769 Update description of sleep meds
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Bug-Fix

#5767 Drink Addition + Bug Fixs: Strawberry Soda
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  icons/obj/drinks.dmi
Labels: Bug-Fix, Balance

#5766 Actually swap helmet coverage values
  code/modules/clothing/head/helmet.dm
Labels: Bug-Fix, Balance

#5774 Soteria Buff one out of one hundred.
  code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm
  code/modules/research/designs/greyson.dm
  code/modules/research/nodes/greyson.dm
Labels: Balance

#5770 Marshal Vest has LOWER_TORSO tag
  code/modules/clothing/suits/armor.dm
Labels: Balance

#5761 more robotic upgrades
  code/game/objects/items/devices/organ_module/passive/movement.dm
  code/game/objects/items/devices/organ_module/passive/punch_increaser.dm
  code/modules/aberrants/_modification.dm
  code/modules/aberrants/organs/mods/5_upgrades.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/internal/_internal.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/research/nodes/combat.dm
  code/modules/surgery/organic.dm
  code/modules/surgery/robotic.dm
  icons/obj/surgery.dmi
  sojourn-station.dme
Labels: Enhancement, Content, Balance, Sprite Work, Test Merged

#5717 Swamp revamp
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
  maps/__Nadezhda/area/_Nadezhda_areas.dm
Labels: Balance, Map

#5768 Assorted blackshield armour visuals
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/light_overlays.dmi
  icons/obj/light_overlays.dmi
Labels: Balance, Sprite Work

#5775 map reduction and locker post spawning
  code/game/machinery/smelter.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/l3closet.dm
  code/game/objects/structures/crates_lockers/closets/maint_loot.dm
  code/game/objects/structures/crates_lockers/closets/malfunction.dm
  code/game/objects/structures/crates_lockers/closets/onestar.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/militia.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal/subtypes.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/mining/mine_items.dm
  maps/_DeepForest/map/_Beast_Cave.dmm
  maps/_DeepForest/map/_Deep_Forest.dmm
Labels: Bug-Fix, Balance, Map

#5784 update Eurolang and Kriosan with more filler words for more a coherent reading experience
  code/modules/mob/language/euro.dm
  code/modules/mob/language/outsider.dm
Labels: Enhancement

#5783 Add Umami Tags to drinks
  code/modules/reagents/reagents/food-Drinks.dm
Labels: Bug-Fix, Balance

#5782 Church fixes and flavour rephrasing
  code/game/objects/items/weapons/nt_melee.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/suits/jobs.dm
Labels: Bug-Fix, Balance

#5781 Fixes no melee blast doors
  code/game/machinery/doors/blast_door.dm
Labels: Bug-Fix, Balance

#5778 adds empty implant case to loadout
  code/modules/client/preference_setup/loadout/lists/general.dm
Labels: Balance

#5786 Add blacksilk boots to loadout
  code/modules/client/preference_setup/loadout/lists/footwear.dm
Labels: Balance

#5790 update snack description
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug-Fix

#5789 New prime paladin sprite
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Sprite Work

#5794 Costume Box Addition: Live Action Roleplay Roman Gear
  code/game/machinery/vendor/cloathing.dm
  code/game/objects/items/weapons/storage/costume.dm
Labels: Balance

#5792 adds spare marshal uniform to loadout
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
Labels: Balance

#5798 removes blacksilk boots from loadout
  code/modules/client/preference_setup/loadout/lists/footwear.dm
Labels: Removal

#5799 Update item_attack.dm
  code/_onclick/item_attack.dm
Labels: Bug-Fix, Balance

#5800 STS Carbine
  code/modules/projectiles/guns/projectile/automatic/sts.dm
Labels: Balance

#5796 Alt prime helmet laurel
  code/modules/clothing/head/helmet.dm
Labels: Bug-Fix

#5803 Fixes GP lockers not properly stacking spawns
  code/game/objects/structures/crates_lockers/closets/onestar.dm
Labels: Bug-Fix, Balance

#5802 Weapon Addition: Re-add Churchs Javelin
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/nt_melee.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
Labels: Bug-Fix, Balance

#5780 adds shoulderboards & patches to loadout
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/factionblackshield.dm
Labels: Balance

#5801 better shooting for mobs
  code/datums/stat_modifiers/modifiers/mob/superior/ranged/ranged_modifiers.dm
  code/datums/stat_modifiers/stat_modifier.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/turrets.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/projectile.dm
Labels: Enhancement, Balance
