Repository sojourn-13/sojourn-station, pull requests merged in 2025-04, with the labels that each got.

#5987 Fixes two missing/wrong pipes
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Bug-Fix

#5980 Turns on cache_sprites by default
  code/modules/admin/verbs/appearance_testing.dm
Labels: Enhancement, Port

#5979 Ports downstream fixes and some upstream fixes as well
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_burger_roach.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/food/recipes_microwave.dm
  code/modules/hydroponics/grown_predefined.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Bug-Fix, Balance, Port

#5991 Ways to disable traps
  code/game/objects/effects/mines.dm
  code/game/objects/items/weapons/traps.dm
  code/modules/tips_and_tricks/gameplay.dm
Labels: Balance

#5990 closet repair and seeable health
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/tips_and_tricks/gameplay.dm
Labels: Balance

#5988 Runtime squashing
  code/__HELPERS/unsorted.dm
  code/controllers/subsystems/statpanel.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/organs/internal/_internal.dm
  code/modules/paperwork/folders.dm
  code/modules/power/cable.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/tgui/tgui.dm
  code/modules/trade/datums/_trade_station.dm
Labels: Bug-Fix, Balance

#5993 autodoc toxin fix
  code/modules/surgery/autodoc.dm
  nano/templates/autodoc.tmpl
  nano/templates/autodoc_capitalism.tmpl
Labels: Bug-Fix, Balance

#5994 reverts changes to cargo goods list
  code/modules/trade/datums/_trade_station.dm
Labels: Bug-Fix

#5995 Monocaridine and Moonwater cans
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  icons/obj/drinks.dmi
Labels: Balance, Sprite Work

#5996 eye damage tweaks
  code/game/objects/items/weapons/tools/_tools.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
  code/modules/organs/internal/internal_wounds/eyes.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/reagents/recipes/recipes_slime.dm
  modular_sojourn/anomalies/stalker_anomalies.dm
Labels: Bug-Fix, Balance

#5992 Updates ear protection and hivemind nerfs
  code/game/gamemodes/events/hivemind_invasion.dm
  code/game/machinery/jukebox.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/mobs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoRobust.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
Labels: Enhancement, Bug-Fix, Balance

#5984 Appendix tweaks
  code/__HELPERS/global_lists.dm
  code/game/gamemodes/events/spontaneous_appendicitis.dm
  code/modules/client/preference_setup/augmentation/01_modifications.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/internal/appendix.dm
  icons/obj/surgery.dmi
Labels: Enhancement, Balance, Sprite Work

#5989 movement recoil
  code/__DEFINES/items.dm
  code/datums/movement/mob.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_recoil.dm
  code/modules/projectiles/gun.dm
Labels: Balance

#5986 Organic and Robotic internal injuries nerf
  code/modules/organs/internal/internal_wounds/organic.dm
  code/modules/organs/internal/internal_wounds/robotic.dm
Labels: Balance, Test Merged

#5771 Toxins Troubles
  code/game/objects/structures/noticeboard.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/research/experiment.dm
  code/modules/research/experiment_toxins.dm
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  sojourn-station.dme
Labels: Documentation, Enhancement, Content, Balance, Map

#5860 GP medical gear
  code/game/machinery/vendor/one_star_vending.dm
  code/game/objects/items/devices/scanners/health.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/greyson_inhailers.dm
  code/game/objects/items/stacks/medical_stacks/medical.dm
  code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
  code/game/objects/items/weapons/storage/firstaid_os.dm
  icons/obj/device.dmi
  icons/obj/stack/medical_big.dmi
  icons/obj/storage.dmi
  sojourn-station.dme
Labels: Content, Balance, Sprite Work, Test Merged

#5953 relay shot
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile/bullettypes.dm
  icons/obj/ammo.dmi
Labels: New Content, Balance, Sprite Work

#5999 framework for sounds
  code/game/objects/items.dm
  code/game/objects/items/stacks/throwing.dm
  code/modules/mob/living/living_defense.dm
Labels: Bug-Fix

#6000 fire screaming
  code/modules/mob/living/carbon/human/life.dm
Labels: Balance

#6001 fixes a roach runtime on equipment checks
  code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
Labels: Bug-Fix

#6005 Fixes damage overlays
  icons/mob/human_races/masks/dam_mask_human.dmi
  icons/mob/human_races/masks/dam_mask_monkey.dmi
Labels: Bug-Fix

#6003 Adds apple juice and cider
  code/game/machinery/vendor/food_vendors.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  icons/obj/drinks.dmi
  modular_sojourn/brewing_datums.dm
Labels: Balance, Sprite Work

#6004 increases cooldown + less spammy
  code/controllers/subsystems/ticker.dm
Labels: Enhancement

#6009 Remove scribble sound when creating glass bottle
  code/modules/reagents/reagent_containers/glass.dm
Labels: Bug-Fix

#5998 Attack cooldown chem and fixes withdraws
  code/__DEFINES/chemistry.dm
  code/_onclick/click.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/race.dm
  code/modules/reagents/reagents/stims.dm
  code/modules/reagents/reagents/toxins.dm
Labels: Bug-Fix, Balance

#5997 Mecha fixa
  code/game/mecha/equipment/weapons/ranged/bullet_weapons.dm
  code/game/mecha/equipment/weapons/ranged/explosive_weapons.dm
  code/game/mecha/equipment/weapons/ranged/mech_ammunition.dm
  code/game/mecha/mecha.dm
  code/game/verbs/ooc.dm
Labels: Bug-Fix, Balance

#6006 Deepmaints nitpicks
  code/game/area/Space Station 13 areas.dm
  code/game/objects/random/mob/misc.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiMega.dm
  code/modules/mob/living/living_defense.dm
  code/modules/multiz/structures.dm
  code/modules/psionics/psion_powers/teleporation_powers.dm
  icons/obj/structures/ladder_tall.dmi
  maps/submaps/deepmaint_rooms/core/overrun.dmm
  maps/submaps/deepmaint_rooms/core/telecoms.dmm
  maps/submaps/deepmaint_rooms/normal/catwalks.dmm
Labels: Bug-Fix, Balance

#6002 Organ damage delaying
  code/__DEFINES/chemistry.dm
  code/modules/organs/blood.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/internal/internal_wounds/_internal_wound.dm
  code/modules/organs/internal/internal_wounds/eyes.dm
  code/modules/organs/internal/internal_wounds/organic.dm
  code/modules/organs/internal/internal_wounds/sanity.dm
  code/modules/organs/internal/internal_wounds/slime.dm
  code/modules/organs/organ_description.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Content, Balance

#6007 Destroying clothing will drop accessories, items in pockets, on the ground
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/storage.dm
  code/modules/reagents/reagents/dispenser.dm
Labels: Enhancement, Balance
