Repository sojourn-13/sojourn-station, pull requests merged in 2025-03, with the labels that each got.

#5958 Fixes janitor borg trash bags
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Bug-Fix

#5963 Adds crafting recipes for tribal clothing
  code/datums/craft/recipes/clothing.dm
Labels: Balance

#5962 Fixes synth shark marking
  icons/mob/human_races/markings.dmi
Labels: Bug-Fix, Sprite Work

#5957 Make Boris Mildly Unique
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
Labels: Balance

#5956 Close-minded upbringing (No inspiration)
  code/__DEFINES/perks.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/modules/sanity/sanity_mob.dm
Labels: Content, Balance

#5954 Kits and Station Tweaks
  code/datums/craft/recipes/misc.dm
  code/game/objects/items/weapons/stock_parts.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon2.dm
Labels: Bug-Fix, Balance

#5949 Dynamic Hivemind
  code/game/gamemodes/events/hivemind_controller.dm
  code/game/gamemodes/events/hivemind_invasion.dm
  code/modules/hivemind/core.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/wires.dm
Labels: Bug-Fix, Balance, Test Merged

#5955 Account Database Tweak
  code/modules/economy/Accounts_DB.dm
  nano/templates/accounts_terminal.tmpl
Labels: Enhancement, Balance

#5964 Gives Robots OOC notes
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Enhancement, Port

#5966 remove AI, premier and robo from hivemind list
  code/__DEFINES/jobs.dm
Labels: Balance

#5965 Actually adds linebreaks to /me
  code/__HELPERS/text.dm
Labels: Balance

#5969 Adds 'Linen' - a cloth producing plant
  code/game/machinery/vendor/food_vendors.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Balance

#5961 Auto Doc Fix and Ore Box UI
  nano/templates/autodoc_capitalism.tmpl
  tgui/packages/tgui/interfaces/OreBox.tsx
Labels: Bug-Fix, Balance, Port

#5968 Re-enables telekinetic hydroponics harvesting, removes the plant teleportation that it previously caused
  code/game/objects/items/oddities_faction.dm
  code/modules/admin/admin.dm
  code/modules/hydroponics/grown_predefined.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/hydroponics/trays/tray.dm
Labels: Bug-Fix

#5970 The Big Psionic Hubaloo
  code/game/machinery/vending.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/ear.dm
  code/modules/psionics/psion.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/oldification_powers.dm
  code/modules/psionics/psion_powers/trash_powers.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
  code/modules/psionics/psionic_items/psi_misc.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
  icons/obj/power_cells.dmi
Labels: Bug-Fix, Balance, Sprite Work, Test Merged

#5971 Gun fix port + QoL ports + misc fixes
  code/datums/datum_click_handlers.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/computer/Operating.dm
  code/game/objects/items/devices/scanners/health.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/stack.dm
  code/game/verbs/who.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/mob.dm
  code/modules/power/cable.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/research/nodes/psionic.dm
  code/modules/surgery/autodoc.dm
  icons/mob/items/lefthand.dmi
  icons/obj/weapons-blades.dmi
  nano/css/shared.css
Labels: Bug-Fix, Balance, Test Merged

#5977 Corrects a heresy (Makes benches buildable)
  code/datums/craft/recipes/furniture.dm
Labels: Balance

#5981 The Big Builder Hubaloo
  code/datums/craft/recipes/floor.dm
  code/datums/craft/recipes/furniture.dm
  code/datums/craft/recipes/machinery.dm
  code/datums/craft/recipes/misc.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/turfs/flooring/flooring.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/bot/cleanbot.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/tables/presets.dm
  code/modules/tables/tables.dm
  icons/obj/bench.dmi
  icons/obj/sofas.dmi
  icons/obj/stack/tile.dmi
  icons/obj/tables.dmi
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
  modular_sojourn/cement_bag.dm
  modular_sojourn/pixelshift.dm
Labels: Content

#5982 Fixes some sofas in dorms
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Bug-Fix
