Repository sojourn-13/sojourn-station, pull requests merged in 2025-08, with the labels that each got.

#6059 Minor Grammar edit to species language lore blurbs.
  code/modules/mob/language/outsider.dm
Labels: Bug-Fix

#6058 Ports AMcilraith SI decon sword tweaks
  code/game/objects/items/weapons/tools/sword.dm
  code/modules/hivemind/mobs.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/carbon/superior_animal/animals/farwa.dm
  code/modules/mob/living/carbon/superior_animal/fungi/fungi.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/human/human.dm
  code/modules/mob/living/carbon/superior_animal/human/stranger.dm
  code/modules/mob/living/carbon/superior_animal/lodge/types/cerberus.dm
  code/modules/mob/living/carbon/superior_animal/lodge/types/clucker.dm
  code/modules/mob/living/carbon/superior_animal/lodge/types/tatonka.dm
  code/modules/mob/living/carbon/superior_animal/nanobot/nanobot.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/emp.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/plasmaroach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tazntz.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
  code/modules/mob/living/carbon/superior_animal/wurms/types/wurm.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/dino.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/mob/living/simple_animal/hostile/jelly.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/misc.dm
  code/modules/mob/living/simple_animal/hostile/plant.dm
  code/modules/mob/mob_defines.dm
Labels: Port

#6047 Bluespace Ammo
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/bluespace.dm
  code/modules/telesci/bcrystal.dm
  icons/obj/ammo.dmi
  icons/obj/ammo_speed.dmi
  icons/obj/telescience.dmi
Labels: Balance, Sprite Work

#6039 Church perk upgrades
  code/__DEFINES/perks.dm
  code/_onclick/item_attack.dm
  code/datums/autolathe/biomatter.dm
  code/datums/perks/job.dm
  code/datums/perks/rezsickness.dm
  code/game/objects/effects/temporary_text.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/modules/core_implant/cruciform/machinery/altar.dm
  code/modules/core_implant/cruciform/machinery/lazbench.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/upgrades.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  icons/obj/module.dmi
  icons/obj/neotheology_machinery.dmi
  sojourn-station.dme
Labels: Enhancement, Balance, Sprite Work

#6049 Ore crushing tweaks
  code/modules/mining/machine_crusher.dm
  code/modules/mining/ore.dm
  icons/obj/machines/mining_machines.dmi
  icons/obj/mining.dmi
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#6055 Gives every psionic power (that i know of) its own section
  code/modules/psionics/psion_powers/armour_powers.dm
  code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
  code/modules/psionics/psion_powers/enhance_items.dm
  code/modules/psionics/psion_powers/faction_powers.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/locator_powers.dm
  code/modules/psionics/psion_powers/mob_affecting_powers.dm
  code/modules/psionics/psion_powers/oddity_powers.dm
  code/modules/psionics/psion_powers/oldification_powers.dm
  code/modules/psionics/psion_powers/psion_starter_powers.dm
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
  code/modules/psionics/psion_powers/telekinetsis_powers.dm
  code/modules/psionics/psion_powers/teleporation_powers.dm
  code/modules/psionics/psion_powers/trash_powers.dm
Labels: Enhancement, Balance

#6030 Stamped Workshop
  code/__DEFINES/projectile_defines.dm
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/clothing.dm
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disk/exoidic.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol/stamp.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/marqua_travel.dm
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/obj/ammo_mags.dmi
  icons/obj/discs.dmi
  icons/obj/guns/projectile/stamp.dmi
  icons/obj/guns/projectile/stamper.dmi
  sojourn-station.dme
Labels: Balance, Sprite Work, Port

#6063 feedback + bug fix for manual charger
  code/game/objects/items/weapons/power_cells.dm
Labels: Bug-Fix, Balance
