Repository sojourn-13/sojourn-station, pull requests merged in 2025-06, with the labels that each got.

#6021 Update dependencies
  .github/workflows/ci_suite.yml
  dependencies.sh
  tools/ci/download_byond.sh
  tools/ci/install_byond.sh
Labels: Enhancement, Port

#6008 Ciriklo buffs and more Ciriklo mobs
  code/__DEFINES/perks.dm
  code/datums/perks/cooldown.dm
  code/datums/perks/special.dm
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/traps.dm
  code/game/turfs/flooring/flooring.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/carbon/superior_animal/vox/ai.dm
  code/modules/mob/living/carbon/superior_animal/vox/thrown_items.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/living_defense.dm
  code/modules/reagents/reagents/toxins.dm
  icons/effects/perks.dmi
  icons/mob/battle_overlays.dmi
  icons/mob/mobs-voxy.dmi
  icons/obj/cwj_cooking/scan.dmi
  icons/obj/traps.dmi
Labels: Bug-Fix, Balance, Sprite Work

#6024 Ameridian_Titan
  code/game/gamemodes/events/migration_ameridian.dm
  code/game/turfs/initialization/mines.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_titan.dm
  code/modules/modular_computers/file_system/news_article.dm
  icons/obj/ameridian_titan.dmi
  news_articles/Frost_Annoucement.html
  sojourn-station.dme
Labels: Balance, Sprite Work, Test Merged

#6017 Sanity drag
  code/game/objects/items/devices/organ_module/passive/sanity.dm
  code/modules/sanity/breakdowns.dm
  code/modules/sanity/sanity_mob.dm
Labels: Balance

#6015 Ports bubbers coolest borgs by Vanilla1040
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robot_tall/cargo.dmi
  icons/mob/robot_tall/engi.dmi
  icons/mob/robot_tall/medical.dmi
  icons/mob/robot_tall/mining.dmi
  icons/mob/robot_tall/science.dmi
  icons/mob/robot_tall/server.dmi
  icons/mob/robot_tall/standard.dmi
  icons/mob/robots.dmi
Labels: Sprite Work, Port

#6034 After Image Movement
  code/__DEFINES/maths.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/temporary_visual.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
Labels: Enhancement, Balance

#6027 New deepmaints mob + fixes to general psionic issues/mobs
  code/datums/perks/psionic.dm
  code/game/objects/items/weapons/candle.dm
  code/game/objects/random/mob/misc.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/attack.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiDebuffer.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiMega.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiTrash.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/mob/living/simple_animal/hostile/excelsior.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm
  code/modules/psionics/ear.dm
  code/modules/psionics/psion_powers/armour_powers.dm
  code/modules/psionics/psion_powers/enhance_items.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psionic_items/psi_armor.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
  code/modules/psionics/psionic_items/psi_misc.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/mob/psi_monsters.dmi
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work

#6032 Slightly better code for golems
  code/modules/ameridian/ameridian_crystal.dm
  code/modules/mob/living/carbon/superior_animal/ameridian/ameridian_golem.dm
Labels: Bug-Fix

#6041 Fixes oddies hiding away
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_modules.dm
  code/modules/mob/living/living.dm
Labels: Bug-Fix, Balance

#6020 stuff for a rocky event
  code/modules/ameridian/ameridian_spire.dm
  maps/Centcom/centcom.dm
  maps/Centcom/map/mapmaker_assets.dmm
  maps/_PostForest/map/_rocky_caves.dmm
  maps/_PostForest/postforest.dm
  maps/__Nadezhda/data/shuttles-nadezhda.dm
  news_articles/Frost_Annoucement.html
  sojourn-station.dme
Labels: Enhancement, Balance, Map
