Repository sojourn-13/sojourn-station, pull requests merged in 2025-05, with the labels that each got.

#6013 Bonfire-Psion
  code/game/objects/structures/firepits.dm
  code/modules/psionics/psion_powers/mob_affecting_powers.dm
  icons/obj/structures.dmi
Labels: Bug-Fix, Balance

#6010 Cleans up gun code a little and removes feature
  code/game/objects/objs.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/_projectile.dm
  code/modules/projectiles/guns/launcher.dm
  code/modules/projectiles/guns/matter/launcher.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Enhancement, Bug-Fix, Balance, Removal

#6019 fixes bond
  code/modules/projectiles/guns/projectile/automatic/bond.dm
Labels: Bug-Fix

#6016 shields and stat tweaks
  code/game/objects/items/weapons/baton_physical.dm
  code/game/objects/items/weapons/shields.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Test Merged

#6014 Lighting fixes by ryuu-dragon and misc tweaked
  code/modules/lighting/lighting_overlay.dm
  code/modules/lighting/lighting_source.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Bug-Fix, Balance, Map

#6011 Yet Another Cargo Tweaking (I'm tweaking)
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
Labels: Balance

#6018 Shotgun tweak
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance, Test Merged
