Repository sojourn-13/sojourn-station, pull requests merged in 2025-07, with the labels that each got.

#6043 Fixes bad crop data
  modular_sojourn/brewing_datums.dm
Labels: Bug-Fix

#6035 More breakdowns and frameworking
  code/game/objects/effects/temporary_text.dm
  code/modules/sanity/breakdowns.dm
  code/modules/sanity/breakdowns/breakdown.dm
  code/modules/sanity/breakdowns/breakdowns.dm
  code/modules/sanity/breakdowns/common.dm
  code/modules/sanity/breakdowns/negative.dm
  code/modules/sanity/breakdowns/positive.dm
  sojourn-station.dme
Labels: Enhancement, Content, Balance, Test Merged

#6031 BirdsOfWar01
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/projectiles/ammunition/bullets.dm
  icons/mob/mobs-voxy64.dmi
Labels: Balance, Sprite Work

#6048 Makes poison bites from mobs injection scaling better
  code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/attack.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug-Fix, Balance

#6044 Jugement of the prime
  code/__DEFINES/perks.dm
  code/datums/perks/cooldown.dm
  code/game/objects/effects/temporary_text.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/sanity/breakdowns/common.dm
Labels: Bug-Fix, Balance

#6051 Data star fixes as well as buffs
  code/modules/mob/living/carbon/superior_animal/robots/subtype/greyson/types/data_star.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Bug-Fix, Balance

#6050 Removes unneeded feedback about welding
  code/game/objects/items/weapons/tools/_tools.dm
Labels: Removal

#6054 Fixes relay
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Bug-Fix
