Repository sojourn-13/sojourn-station, pull requests merged in 2025-01, with the labels that each got.

#5874 Ports RnG-Room framework
  code/__HELPERS/cmp.dm
  code/_global_vars/mapping.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/mapping.dm
  code/datums/ruins.dm
  code/datums/ruins/hallway.dm
  code/datums/ruins/maints.dm
  code/game/objects/landmarks/maints_ruins.dm
  code/modules/maps/tg/map_template.dm
  maps/MaintsRuins/3x3/3x3_barrels.dmm
  maps/MaintsRuins/3x3/3x3_floor_repair_shop.dmm
  maps/MaintsRuins/3x3/3x3_guntinerk.dmm
  maps/MaintsRuins/3x3/3x3_kcoin.dmm
  maps/MaintsRuins/3x3/3x3_meat.dmm
  maps/MaintsRuins/3x3/3x3_minihydro.dmm
  maps/MaintsRuins/3x3/3x3_posters.dmm
  maps/MaintsRuins/4x4/4x4_guntinker.dmm
  maps/MaintsRuins/4x4/4x4_mini_bar.dmm
  maps/MaintsRuins/4x4/4x4_mixed_storage.dmm
  maps/MaintsRuins/4x4/4x4_trash_dump.dmm
  maps/MaintsRuins/left_side_vacant_office/bookcased.dmm
  maps/MaintsRuins/left_side_vacant_office/cleared_out.dmm
  maps/MaintsRuins/left_side_vacant_office/framed.dmm
  maps/MaintsRuins/left_side_vacant_office/housing.dmm
  maps/MaintsRuins/left_side_vacant_office/tabled.dmm
  maps/MaintsRuins/left_side_vacant_office/trashed.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
  sojourn-station.dme
Labels: Documentation, Balance, Map, Port

#5918 Oni club rebalance
  code/modules/projectiles/guns/oddity_items.dm
  icons/obj/spatial_cut.dmi
  sound/weapons/metal_disk_fick.ogg
Labels: Bug-Fix, Balance

#5927 Tiny name fix
  code/modules/psionics/psion_powers/healing_powers.dm
Labels: Bug-Fix

#5924 Mob-exclusive catalyst drop changes
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
Labels: Balance, Test Merged

#5928 Grammar n' stuff
  code/modules/psionics/ear.dm
  code/modules/psionics/psion_powers/armour_powers.dm
  code/modules/psionics/psion_powers/deepmaints_themed_powers.dm
  code/modules/psionics/psion_powers/faction_powers.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/locator_powers.dm
  code/modules/psionics/psion_powers/mob_affecting_powers.dm
  code/modules/psionics/psion_powers/oddity_powers.dm
  code/modules/psionics/psion_powers/oldification_powers.dm
  code/modules/psionics/psion_powers/psion_starter_powers.dm
  code/modules/psionics/psion_powers/telekinetsis_powers.dm
  code/modules/psionics/psion_powers/teleporation_powers.dm
  code/modules/psionics/psion_powers/trash_powers.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
Labels: Bug-Fix

#5933 No slowdown on surgery on hooved/taloned/callused patients
  code/modules/surgery/surgery.dm
Labels: Bug-Fix, Balance

#5932 fixes a light switch and extra air alarm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Bug-Fix, Balance, Map

#5930 Some mob attack animations
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/reaver.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  modular_sojourn/attacks.dmi
Labels: Balance, Sprite Work

#5929 Log Spam Fix - instrument issues
  code/datums/sound_player.dm
Labels: Bug-Fix

#5922 Three more perks
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/datums/setup_option/backgrounds/origin_career.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  icons/effects/perks.dmi
Labels: Enhancement, Content, Balance

#5925 New Handcuff + Increased time
  code/datums/autolathe/security.dm
  code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm
  code/game/objects/items/weapons/autolathe_disk/marshal.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  icons/obj/items.dmi
Labels: Balance, Sprite Work

#5935 fixes slime gun and makes feeding less exploitable
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/projectiles/guns/energy/misc/slimegun.dm
  code/modules/projectiles/projectile/special.dm
Labels: Bug-Fix, Balance
