Repository sojourn-13/sojourn-station, pull requests merged in 2025-02, with the labels that each got.

#5920 Chef and bartender endless content(*)
  code/game/objects/objs.dm
  code/modules/cooking_with_jane/cooking.dm
  code/modules/cooking_with_jane/cooking_catalog.dm
  code/modules/cooking_with_jane/cooking_tracker.dm
  code/modules/cooking_with_jane/recipes/_read_me.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_burger.dm
  code/modules/cooking_with_jane/recipes/recipe_burger_roach.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
  code/modules/cooking_with_jane/step_defines.dm
  code/modules/cooking_with_jane/step_types/add_item.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/food-Drinks.dm
  icons/obj/drinks.dmi
  maps/_DeepForest/map/_Greyson_Field_Office.dmm
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
  modular_sojourn/chef_food_celler.dm
  sojourn-station.dme
Labels: Bug-Fix, Balance, Sprite Work, Map

#5937 Workflow Update
  .github/workflows/ci_suite.yml
  .github/workflows/generate_documentation.yml
Labels: dependencies

#5936 psyc door fix
  maps/__Nadezhda/map/_Nadezhda_Colony.dmm
Labels: Bug-Fix, Map

#5939 typo: are mind -> our mind
  code/modules/psionics/psionic_items/psi_catalysts.dm
Labels: Bug-Fix

#5940 Fixes GP coins being doup'ed
  code/modules/economy/os_cash.dm
Labels: Bug-Fix, Balance

#5946 Nerve buff
  code/modules/organs/internal/nerves.dm
Labels: Balance

#5947 Imported mech Price Bump
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
Labels: Balance

#5945 Addition of the quickdraw scabbard to loadout
  code/modules/client/preference_setup/loadout/lists/armament.dm
Labels: Balance

#5948 Ports + Tweaks
  code/datums/craft/recipes/medical.dm
  code/game/machinery/autolathe/matterforge.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/splint_stacks.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
Labels: Balance

#5950 Feedback for crayon drain
  code/game/objects/effects/decals/crayon.dm
Labels: Balance

#5952 QoL Handcrank charger now automatically continues to charge
  code/game/objects/items/weapons/power_cells.dm
Labels: Enhancement

#5941 Adds a cooldown for lobby ending notification sound
  code/controllers/subsystems/ticker.dm
Labels: Bug-Fix, Test Merged
